### ISSUE TITLE
TypeScript docgen isn't properly supporting nested namespaces.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/docs#1001]
https://staging.pulumi.io/reference/pkg/nodejs/@pulumi/awsx/apigateway/#API should have a nested module called "metrics".  however, all these child values are being propagated up to the apigateway module itself.

**Comment by CyrusNajmabadi** [comment]
Tagging @lukehoban @joeduffy Are one of you experts on this such that fixing this would be a tiny change?

**Comment by joeduffy** [comment]
The flattening here is admittedly a hack. It's goal was to avoid the confusing design our TypeDoc website previously suffered from, where every file shows up as a module without any top level summary (the way most people want to browse the docs). It's worth talking to @lblackstone as he recently did some work here for Kubernetes and may have an opinion on this area.

**Comment by lblackstone** [comment]
https://github.com/pulumi/docs/pull/962/files?file-filters%5B%5D=.go are the changes I made, but I don't think they're directly applicable. I had to restructure the k8s provider quite a bit to get it working reasonably with tsdocgen.

**Comment by lukehoban** [comment]
> I had to restructure the k8s provider quite a bit to get it working reasonably with tsdocgen.

Right - my assumption is that if were were to properly fix this, it would have avoided the need for @lblackstone to make many of the structural changes he had to make to work around these issues.

**Comment by CyrusNajmabadi** [comment]
I fixed this.  Now we et the nested module:

![image](https://user-images.githubusercontent.com/4564579/56853172-d78bd180-68d8-11e9-9a91-8e0494990b4c.png)

One thing i would personally prefer is that nested modules somehow show up in the UI in more of a structured fashion.  i.e. they are really children that should maybe should show up at the top/bottom in some sort of folder/collapsible manner.  But that's getting way outside anything i know how to do.  If we have any UI experts here, i would love if we could make things a bit nicer here.
