### ISSUE TITLE
Missing step in fundamentals docs

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/docs#10088]
### Problem description

This page tells the user to update some stack config values:

https://www.pulumi.com/learn/building-with-pulumi/stack-outputs/

But does not tell them to run `pulumi up` after modifying those values, so they never actually get set

**Comment by toriancrane** [comment]
@jaxxstorm I do see a statement to run `pulumi up` after the config values are changed here:

![image](https://github.com/pulumi/docs/assets/19211559/7072704e-05ac-4926-859d-c4fb56bfda9f)

If this isn't the correct section, can you point me in the right direction? Thanks!

**Comment by jaxxstorm** [comment]
ah, the original user might have missed that. I certainly did. Maybe we could just add a code section to make that clearer?
