### ISSUE TITLE
`sync-and-test-bucket` script fails unless bundles bucket exists

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#10113]
The `push` workflow runs `sync-and-test-bucket.sh update`, which relies on the existence of a "bundles" bucket -- but this bucket is created and exported by the Pulumi program, which runs after the script:

https://github.com/cnunciato/docs/blob/dadda3729ff3ca98d720e7cac6cf5b5b07f2e655/scripts/sync-and-test-bucket.sh#L72

This means `pulumi up` on a new stack can never succeed. We should fix this.

**Comment by cnunciato** [comment]
@sean1588 Do we actually need this bucket? I'm not sure we do, since we're building everything separately now.

**Comment by sean1588** [comment]
We do still need it for now with the way things are configured. We would need to find a way to host the registry assets somewhere under the /registry route and not under the root (where the bundles bucket is accessed from under `/registry`) in order for the registry pages to resolve the location of those files.

**Comment by cnunciato** [comment]
Fixed via #10137.
