### ISSUE TITLE
PageFeedback /docs/pulumi-cloud/esc/environments/

### ISSUE THREAD

**Issue by desteves** [pulumi/docs#10146]
Submitted On: 10-20-2023
Comment(s): Please add a Typescript example of using config values in a pulumi program.

**Comment by thoward** [comment]
There's a TypeScript example here: https://www.pulumi.com/docs/esc/environments/working-with-environments/#using-environments-with-pulumi-iac ... The pages have moved around and been restructured a bit, so I'm not sure if this satisfies this report or not. Closing it for now. 

@desteves please re-open if the intent was for this example to be different than what's linked above.
