### ISSUE TITLE
PageFeedback /docs/cli/commands/pulumi_policy_publish/

### ISSUE THREAD

**Issue by desteves** [pulumi/docs#10149]
Submitted On: 10-03-2023
Comment(s): flag for versioning are not described

**Comment by desteves** [comment]
Looking at the latest `pulumi policy publish` output, the version flag is not an option.

```bash
pulumi policy publish --help                                        
Publish a Policy Pack to the Pulumi Cloud

If an organization name is not specified, the default org (if set) or the current user account is used.

Usage:
  pulumi policy publish [org-name] [flags]

Flags:
  -h, --help   help for publish
```

**Comment by desteves** [comment]
https://www.pulumi.com/docs/cli/commands/pulumi_policy_publish/

**Comment by desteves** [comment]
Suggestion: close/can't repo

**Comment by cnunciato** [comment]
Looks like `version` doesn't exist for `publish`, but does exist for `disable`, `enable`, `rm`, and `validate-config`. I think what this user is describing is that the usage for `version` could be better described.
