### ISSUE TITLE
PageFeedback /docs/clouds/kubernetes/get-started/review-project/

### ISSUE THREAD

**Issue by desteves** [pulumi/docs#10151]
Submitted On: 08-11-2023
Comment(s): Following the steps and seeing the following error:
# quickstart
 
./main.go:40:42: deployment.Metadata.Elem undefined (type ""github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"".ObjectMetaOutput has no field or method Elem)
 
error: error in compiling Go: unable to run 'go build': exit status 1

**Comment by desteves** [comment]
Duplicate of #3412

**Comment by ericrudder** [comment]
@Diana Esteves ***@***.***> @James Denyer ***@***.***>
3412 is about pagerduty documentation ... is this really the same issue?
(if so, i can't make heads or tails out of these.)

**Comment by interurban** [comment]
Thx @ericrudder it was a simple mistake; @desteves 's tag automatically linked to a /docs issue which is not related. this is the correct one https://github.com/pulumi/pulumi-hugo/pull/3412 (I fixed the link above)
