### ISSUE TITLE
PageFeedback /docs/pulumi-cloud/deployments/

### ISSUE THREAD

**Issue by desteves** [pulumi/docs#10168]
Submitted On: 05-16-2023
Comment(s): these docs are no fun. I just need to find the page on rolling update config settings :(

**Comment by desteves** [comment]
It's unclear what referenced page could be better linked. I suggest we mark as closed/won't fix given the Search functionality feature.

**Comment by thoward** [comment]
Closing as `wont-fix` per author's recommendation.
