### ISSUE TITLE
PageFeedback /docs/intro/concepts/resources/options/transformations/

### ISSUE THREAD

**Issue by desteves** [pulumi/docs#10165]
Submitted On: 03-10-2023
Comment(s): It needs to have some examples of typing the args, or a reason why args.props can't be typed at the top level.

**Comment by thoward** [comment]
Arg typing seems to be covered now, mostly in comparison to the new Transforms systems. Since this old system will be depecreated soon, and the new system doesn't support typed args, this seems like somethign that can be closed as any of: `wont-fix` `no-repo` or `fixed`. Going w/ `wont-fix`.
