### ISSUE TITLE
PageFeedback /docs/tutorials/kubernetes/gke/

### ISSUE THREAD

**Issue by desteves** [pulumi/docs#10171]
Submitted On: 05-29-2023
Comment(s): failed to initialize discovery client: The gcp auth plugin has been removed

**Comment by thoward** [comment]
Thanks for the feedback. Not sure which section of the doc is leading to this error. I checked the examples and everything seems to be working. Perhaps this was a problem a year ago that has been fixed since then. Not sure. Closing as no-repro.
