### ISSUE TITLE
Docs for manually resolving pending operations

### ISSUE THREAD

**Issue by ekrengel** [pulumi/docs#1017]
During the azure hackathon, my token expired causing my checkpoint file to have the AKS cluster in a pending state. The cluster did indeed get created, but I could not figure out where to copy the resource to & get it working again. 

We should document how to do this as a workaround until importers are supported.

**Comment by bermudezmt** [comment]
Additional note from chatting with @ekrengel : When running `pulumi up` and hitting `Ctrl+C` to cancel the operation, your stack can get into an inconsistent state if a resource operation was pending. There is no known good workaround for this. 

@pgavlin does the `import` resource option address this? Is this something we can work together on? 
(Feel free to chime in, Erin, if my notes are inaccurate).

**Comment by pgavlin** [comment]
> When running pulumi up and hitting Ctrl+C to cancel the operation, your stack can get into an inconsistent state if a resource operation was pending.

Note that this is only possible if you hit Ctrl+C twice (or otherwise kill the process without allowing it to terminate gracefully).

> @pgavlin does the import resource option address this?

It can help in cases where a resource fails to create, yes: if the user can find the created resource using e.g. the AWS console, they can set the `import` option to the ID of the created resource, re-run, then remove the `import` option.

**Comment by pgavlin** [comment]
In cases where the pending operation is an `update` or `delete` rather than a `create`, the user should be able to use `pulumi refresh` to bring the stack back into a consistent state.

**Comment by lukehoban** [comment]
We do have docs here that address what I believe the scenario is here: https://www.pulumi.com/docs/reference/troubleshooting/#interrupted-update-recovery.

We should review those for accuracy (and make sure they are up-to-date with what current troubleshooting techniques are), and should consider adding a link to that troubleshooting guide to the CLI error message.

**Comment by lukehoban** [comment]
Docs are "okay" here for now - and to really make things better we need to tackle the underlying issue - as tracked in https://github.com/pulumi/pulumi/issues/4265.
