### ISSUE TITLE
[Task] Write OIDC(?) Vault guide

### ISSUE THREAD

**Issue by toriancrane** [pulumi/docs#10193]
Some [known limitations](https://github.com/pulumi/esc/issues/142).

Will need to make sure to differentiate between Vault OSS and Vault HCP?

**Comment by toriancrane** [comment]
De-prioritizing to work on Pulumi IaC configuration steps for ESC in AWS, Azure, GCP.

**Comment by ejhayes** [comment]
Some docs on getting the vault provider working with esc would be great! I can't seem to get this working yet and am not sure what needs to be setup to get this to work?

**Comment by toriancrane** [comment]
@ejhayes has picked up this task and created a PR with content for OIDC/Vault. (thank you again! this is definitely needed)

**Comment by ejhayes** [comment]
Thanks @toriancrane. I’m not by a computer right now but it looks like the images in the published docs aren’t displaying. My image references might be wrong?

**Comment by toriancrane** [comment]
Hey @ejhayes,

There are a few tweaks that I am [making in a patch](https://github.com/pulumi/pulumi-hugo/pull/3603). As soon as these changes get merged, your images should show properly.
