### ISSUE TITLE
Improvement for https://www.pulumi.com/learn/building-with-pulumi/stack-references/

### ISSUE THREAD

**Issue by eguerlain** [pulumi/docs#10226]
When creating reference to the stack of `my_first_app`, the `stackRef` variable is built with a kebab-cased project name (`my-first-app`):

```ts
const stackRef = new pulumi.StackReference(`${org}/my-first-app/${stack}`)
```

However, this project was created with a snake_cased name in [Creating a Pulumi Project](https://www.pulumi.com/learn/pulumi-fundamentals/create-a-pulumi-project/). (`mkdir my_first_app`)

This leads to the following error when running `pulumi up` for the `my-second-app-staging` stack:

```bash
     Type                             Name                            Plan       Info
 +   pulumi:pulumi:Stack              my-second-app-staging           create     1 error
     └─ pulumi:pulumi:StackReference  etigrln95/my-first-app/staging             1 error

Diagnostics:
  pulumi:pulumi:Stack (my-second-app-staging):
    error: preview failed

  pulumi:pulumi:StackReference (etigrln95/my-first-app/staging):
    error: Preview failed: unknown stack "etigrln95/my-first-app/staging"
```

Using snake_cased project name works correctly:

```ts
const stackRef = new pulumi.StackReference(`${org}/my_first_app/${stack}`)
```

I suggest using kebab-cased name when creating the `my-first-app` directory in [the first tutorial](https://www.pulumi.com/learn/pulumi-fundamentals/create-a-pulumi-project/) to keep a consistant naming.

**Comment by toriancrane** [comment]
Thank you @eguerlain for submitting this issue! We will be taking a look into this. We do have an updated guide available for [Stack Outputs and References](https://www.pulumi.com/docs/using-pulumi/stack-outputs-and-references/) if you'd like to check that out in the meantime.
