### ISSUE TITLE
Crosswalk for AWS Guides needs refresh for AWSX 2.x

### ISSUE THREAD

**Issue by scottslowe** [pulumi/docs#10230]
### Problem description

A community user brought up a product documentation issue on the following URL: https://www.pulumi.com/docs/clouds/aws/guides/

Specifically, the user was tripped up by the ECR example, which references parameters that are no longer supported in AWSX 2.x (like the `path` parameter, which is replaced by `context`).

This carries over into the more detailed ECR guide found at https://www.pulumi.com/docs/clouds/aws/guides/ecr/ as well.

Pretty much every `awsx.ecr.Image` example is wrong; I checked the ECR page, the EKS page, and the ECS page and found incorrect examples.

### Affected product version(s)

The docs reflect AWSX 1.x, but AWSX 2.x is the default/major version now in use.

### Suggestions for a fix

Update all code examples that use `awsx.ecr.Image` to reflect correct usage with AWSX 2.x.

**Comment by cnunciato** [comment]
Some preliminary investigation:

## For `aws.ecs.Image`

12 files contain references to the no-longer-existent `path` parameter of `aws.ecs.Image`:

- themes/default/content/blog/aws-lambda-container-support/index.md
- themes/default/content/blog/building-and-publishing-docker-images-to-a-private-amazon-ecr-repository/index.md
- themes/default/content/blog/crosswalk-for-aws-1-0/index.md
- themes/default/content/blog/crosswalk-for-aws-all-languages/index.md
- themes/default/content/blog/managing-containers-on-aws-with-pulumi/index.md
- themes/default/content/blog/nov-2022-launches/index.md
- themes/default/content/challenge/holiday-shopping.md
- themes/default/content/docs/clouds/aws/guides/_index.md
- themes/default/content/docs/clouds/aws/guides/ecr.md
- themes/default/content/docs/clouds/aws/guides/ecs.md
- themes/default/content/docs/clouds/aws/guides/eks.md
- themes/default/content/docs/clouds/kubernetes/guides/apps.md

## awsx.ecs.FargateService:

21 files contain references to `container` blocks without a `name` property:

- themes/default/content/blog/aws-lambda-efs/index.md
- themes/default/content/blog/building-and-publishing-docker-images-to-a-private-amazon-ecr-repository/index.md
- themes/default/content/blog/crosswalk-for-aws-1-0/index.md
- themes/default/content/blog/crosswalk-for-aws-all-languages/index.md
- themes/default/content/blog/deploying-a-pern-stack-application-to-aws/index.md
- themes/default/content/blog/deploying-the-infrastructure-of-oauth-server-for-cms-app/index.md
- themes/default/content/blog/get-started-with-docker-on-aws-fargate-using-pulumi/index.md
- themes/default/content/blog/introducing-pulumi-crosswalk-for-aws-the-easiest-way-to-aws/index.md
- themes/default/content/blog/managing-containers-on-aws-with-pulumi/index.md
- themes/default/content/blog/nov-2022-launches/index.md
- themes/default/content/blog/pulumi-universal-iac/index.md
- themes/default/content/blog/run-your-own-rss-server/index.md
- themes/default/content/blog/running-containers-in-aws-the-lowdown-ecs-fargate-and-eks/index.md
- themes/default/content/challenge/holiday-shopping.md
- themes/default/content/crosswalk/aws.md
- themes/default/content/docs/clouds/aws/guides/_index.md
- themes/default/content/docs/clouds/aws/guides/ecr.md
- themes/default/content/docs/clouds/aws/guides/ecs.md
- themes/default/content/docs/clouds/aws/guides/elb.md
- themes/default/content/topics/containers.md

**Comment by desteves** [comment]
Related: https://github.com/pulumi/docs/issues/10162

**Comment by cnunciato** [comment]
All right, I think I have a good sense now of what's needed to fix up the issues here. It boils down to this:

* Change `path` to `context`
* Give `container` blocks a `name`
* Make sure there's a `platform: "linux/amd64"` property passed to *all* `awsx.ecr.Image`s, pretty much everywhere (this is important because as of Docker v4, this is no longer the default, so will not work when run on most users' machines)
* Make sure it's clear which ports are involved in the example (also important, as by default, this stuff generally only works when both the load balancer and the service are intended to listen on port `80`

Related updates will need to be made in pulumi/templates and pulumi/examples well.

**Comment by interurban** [comment]
Related to https://github.com/pulumi/pulumi-hugo/issues/3615

**Comment by cnunciato** [comment]
This is now complete, with the exception of the Kubernetes "apps" page, which has deeper issues. I'll file a follow-up for that one.
