### ISSUE TITLE
AWS API Gateway Guide includes inaccurate example reference

### ISSUE THREAD

**Issue by mnlumi** [pulumi/docs#10266]
### Problem description

On https://www.pulumi.com/docs/clouds/aws/guides/api-gateway/#overview, there's a line that says "Full examples can be found in the [AWS API Gateway component](https://www.pulumi.com/registry/packages/aws-apigateway/) in the Pulumi Registry." When actually visiting the registry page, there are no real examples. The API Gateway docs page has more examples. 

### Suggestions for a fix

Either the language on the docs page should be corrected, or helpful examples be added to the registry page.

**Comment by desteves** [comment]
@mnlumi I agree the word "full" is a bit subjective. @pulumi/docs  I suggest we update the wording to omit the word "full". 

I do see examples when following the link to https://www.pulumi.com/registry/packages/aws-apigateway/  so I'm unclear on the "no real examples" part. Could you share a bit more of what you expected to see?

**Comment by mnlumi** [comment]
Well, I could swear I didn't see that example when I looked before. I think I was expecting more under resources or to have the how-to-guides section there.

**Comment by cnunciato** [comment]
Updating the prose in the guide to point to the Registry for "more information" (syntax reference, etc.).
