### ISSUE TITLE
createListener method not available on awsx.ApplicationLoadBalancer resource

### ISSUE THREAD

**Issue by jimjoes** [pulumi/docs#10336]
### What happened?

The following code from the documentation [here](https://www.pulumi.com/docs/guides/crosswalk/aws/elb/) gives me a typescript error:

`const alb = new awsx.lb.ApplicationLoadBalancer(
        "authoring-tool-lb"
    )
  const listener = alb.createListener("authoring-tool-listener", { port: 80 });`

The error is: 
`Property 'createListener' does not exist on type 'ApplicationLoadBalancer'.ts(2339)`

<img width="691" alt="Untitled" src="https://user-images.githubusercontent.com/61049336/214597875-7fde6ebb-7182-422a-b749-dd0770129a2c.png">

### Steps to reproduce

Use code above and see error.

### Expected Behavior

The method should be available

### Actual Behavior

I received the typescript error

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cnunciato** [comment]
Fixed via https://github.com/pulumi/pulumi-hugo/pull/3693.
