### ISSUE TITLE
Mismatched types in example of reading outputs from stack references

### ISSUE THREAD

**Issue by scottslowe** [pulumi/docs#10342]
### Problem description

Reporting on behalf of a community user, who mentioned the issue in Pulumi Community Slack.

The issue is at this URL: https://www.pulumi.com/docs/concepts/stack/#reading-outputs-from-stack-references

The TypeScript code shows the use of `const ip: Output<string> = infra.getOutput("privateIp");`, but you can't assign an `Output<any>` value (which is what `getOutput` returns) to a variable of type `Output<string>`.

Other languages may be affected; I didn't check.

### Affected product version(s)

This does not appear to be specific to a particular version of Pulumi.

### Suggestions for a fix

@phillipedwards suggested using an `apply`, as in `getOutput("privateIp").apply(s => <string>s);`

**Comment by desteves** [comment]
Exact error:

```
Type 'Output<any>' is not assignable to type 'Output<string>'.
  Type 'OutputInstance<any>' is not assignable to type 'Output<string>'.
    Property 'length' is missing in type 'OutputInstance<any>' but required in type 'LiftedObject<String, NonFunctionPropertyNames<String>>'.ts(2322)

```

**Comment by desteves** [comment]
We can keep the IP as `Output<any>`.

I modified the example to work with one of my existing stacks and then exported the value:

```typescript
import * as pulumi from "@pulumi/pulumi";

const infra: pulumi.StackReference = new pulumi.StackReference("diana-pulumi-corp/addsite-cloudflare/end");
const ip: pulumi.Output<any> = infra.getOutput("zoneId");

export const logKey: pulumi.Output<string> = ip.apply(ip => `logs/${ip}.log`);

```
![image](https://github.com/pulumi/docs/assets/2991841/5d1a609b-42e0-492c-9e4e-7a9dcd3e2bc2)

**Comment by desteves** [comment]
https://github.com/pulumi/pulumi-hugo/pull/3796
