### ISSUE TITLE
pulumi.io bug-fixes and general style improvements 

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#1036]
This meta-issue is intended to contain a proposed set of visual fixes and overall improvements to pulumi.io.

* [x] Fix the search-box styling. Round the corners on the input field, and either add a little spacing between the activation button and the input, or remove the spacing and make the button and input look more unified. The activation button probably needn't be blue, either, as that competes with the SIGN UP button beside it.

* [x] In general, button styles look a bit off as well: the single-pixel outline is unique to pulumi.io (so should be removed), paddings, font weights, etc. We should generally apply the same treatments we're using on pulumi.com.

* [ ] Cloud-provider logos on the home and quick-start pages should be converted from PNGs to SVGs, and they should look more interactive as well. (They currently seem more decorative/informative.)

* [x] We should remove the underlines in most normal hrefs/links. The bright-blue coloring is clear enough.

* [x] The gray headings on the home page (Why Pulumi? etc.) seem a bit drab. They should be given equal or greater contrast then the content below them. We should consider styling them similarly to the Any Code, Any Cloud items on the pulumi.com home page, with higher-contrast headings, for example.

* [ ] The edges of the orange images below that section (in Containers, Serverless, etc.) look fuzzy against the gray background. We could probably make these stand out better by introducing some alternative color and/or contrast.

* [x] The bright blue looks pretty dissonant in this palette. I realize we're using it elsewhere, and it works for links, but it _really_ stands out against when used for buttons and headings in page bodies. There might be a better choice for some of these.

* [x] Items in the TOC navigation should get some sort of a hover effect, like a color change similar to the color they'd get when in the active/selected state, or maybe blue, since that's the color of in-page links.

* [x] The text of TOC items aliases poorly on normal-resolution monitors, and we probably don't need the one-pixel separators between the TOC items themselves, as they're distinguished clearly enough by their color/weight, the spacing between them, and the indentation of their children. (Down with visual noise! :smile:)

* [x] Bullets beside bright-blue/linked text should be text-colored rather than link-colored (as they're not linked themselves).

* [x] In-page TOCs should look more like TOCs, i.e., distinguished from the content below them; even a simple one-pixel seam between them and the content they refer to could help make this separation clearer. Also, since they aren't steps in a sequence, we should remove the lines that connect them. And the bullets themselves should line up vertically with the bulleted items in the pages below them.

* [ ] The HubSpot cookie notification (pinned to the lower edge of the viewport) is misaligned vertically and takes up a lot more space than it needs to. If we can fix this, we should.

* [x] Code samples are a bit noisy, visually. We should be able to lighten their backgrounds, remove the pixel borders, and add a bit more border radius and padding to add some visual polish and improve readability.

* [x] In the TOC, closed-state disclosure triangles should probably also be solid, rather than outlined.

* [x] We use red for inline code snippets, but since red isn't part of our brand palette, and in our apps (and in general), red tends to denote wrongness, we might consider a more harmonious alternative for these.

* [ ] The large graphic on the API reference home page should be converted somehow to SVG, assuming we need/want to keep it there.

* [x] The pink used for class headings in the API reference doesn't quite "go" with the rest of the palette on this site. We could probably find something a little more complementary for it.

* [x] We should take a pass to fix whatever syntax-highlighting problems we can. (For example, in some CLI output samples, you'll get one random blue word among a block of otherwise dark-gray text, for some reason.)

* [ ] The screenshot on the State & Backends page is out of date. We should update it.

* [x] Headings in the providers table on the Organizations page look clickable, because they're the same color as in-page links. We should just make them dark-gray or black to match heading treatments elsewhere.

* [ ] Heading casing is sometimes inconsistent (e.g., SEE ALSO in caps, where others are title-cased).

* [ ] We should consider using tables rather than lists for CLI subcommands and the like.

* [x] We should render well across the site on mobile.

* [ ] We could probably use spacing and color variation to create a slightly better visual hierarchy on these pages. For example, using darker-colored headings with slightly lighter-colored (but still appropriately high-contrast) dark-gray text in paragraphs could add some visual clarity and polish, and make things a little easier on the eyes as well. (Heroku does a nice job of this, IMO.) 

* [ ] The search-results page is a wall of links. Its overall presentation could probably be improved.

**Comment by cnunciato** [comment]
This was displaced by the decision to combine our websites, so I'm moving it to M24.

**Comment by lukehoban** [comment]
Is this issue tracking any specific work outside of https://github.com/pulumi/docs/issues/1213?

**Comment by cnunciato** [comment]
Some of these items were addressed with #1213, but not all. I'll review this today and close it after creating whatever concrete follow-up come out of that.

**Comment by cnunciato** [comment]
Closing as completed with #1213. Will move remaining unchecked items to a new issue and add it to M25.
