### ISSUE TITLE
Add "ESC with K8s" OIDC page

### ISSUE THREAD

**Issue by toriancrane** [pulumi/docs#10384]
Blog: https://www.pulumi.com/blog/esc-kubernetes-cluster-and-app/

```[tasklist]
### Tasks
- [ ] Research/test how K8s works with ESC
- [ ] Write "Using K8s with ESC" content
```

**Comment by thoward** [comment]
Seems to be covered by https://www.pulumi.com/docs/esc/integrations/kubernetes/kubernetes/ .. Closing as fixed.
