### ISSUE TITLE
Docs mentioning terraform?

### ISSUE THREAD

**Issue by CodingMadeEasy** [pulumi/docs#1042]
In the docs here: https://pulumi.io/reference/pkg/nodejs/@pulumi/gcp/compute/#InstanceTemplate

you will see terraform mentioned 36 times. Was the text copied straight from the terraform docs?

**Comment by joeduffy** [comment]
> Was the text copied straight from the terraform docs?

For the subset of packages that are code-generated from [the Terraform Bridge](https://github.com/pulumi/pulumi-terraform), the text comes from the respective open source repo for that Terraform Provider. We do rewrite some of the text on the fly, but some things like this slip through. /cc @jen20 in case there's something we can do for these specific ones.

**Comment by jen20** [comment]
Hmm, yes - these references have come from the Terraform bridge so are verbatim. It's not great to be referencing specific commands that won't work, but short or writing a bunch of cleanup code or allowing overriding specific field docs I don't know there's much that can be done. It's likely worth a discussion of what we want to do here.

**Comment by lukehoban** [comment]
The only remaining mentions of "terraform" in these docs are now in the attributions to the `terraform-providers` source from which these docs are derived.
