### ISSUE TITLE
Make direct download link ("Manual Install") more obvious

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1044]
Per feedback from a user, BitDefender on Windows blocks our powershell install script. We should provide instructions and a direct download link for manual installation.

**Comment by pjoe** [comment]
I'm that user :)

FWIW: I think in general windows antivirus SW will frown upon running PowerShell scripts downloaded from the internet.

**Comment by ellismg** [comment]
On the [install](https://pulumi.io/quickstart/install.html) page, you can select the "manual install" value from the drop down box which will provide you with direct download links for all our platforms.

In addition, https://pulumi.io/reference/changelog.html provides download links for every released version.

I suspect we could have made this more discoverable.  @pjoe Just wondering, did you even know about the install page above?  If not, would you have thought to use the "manual install" to find these direct links?

Any feedback on how we could make this more discoverable?

**Comment by clstokes** [comment]
The "Manual Install" value definitely isn't obvious to me. I think it should be "extracted" to each of OS-specific sections.

**Comment by pjoe** [comment]
doh 🤦‍♂ 

I never noticed there was a separate manual install section, was totally focused on the Windows specific part. Guess as a developer I jumped right into debugging the script.

**Comment by justinvp** [comment]
This was addressed in https://github.com/pulumi/docs/commit/58ce6e507aa091684eadeb5cdd00b17a493d7155
