### ISSUE TITLE
Improve K8s landing pages

### ISSUE THREAD

**Issue by ellismg** [pulumi/docs#1045]
We should identify and drive some key improvements into our landing pages for Kubernetes on our docs website.  We have a lot of great collateral split across our docs website and locked inside on our heads, and providing a focused area where we really nail some E2E scenarios and provide great documentation on them. 

- [x] Revamp Quickstart Page (https://pulumi.io/quickstart/kubernetes)
  - Update: being tracked in https://github.com/pulumi/docs/pull/1126 (M24)
- [ ] Revamp Marketing Page (https://www.pulumi.com/kubernetes)
  - Update: being tracked in https://github.com/pulumi/docs/issues/1159

**Comment by metral** [comment]
- Revamp Quickstart Page was completed in https://github.com/pulumi/docs/pull/1126
- Revamp Marketing Page is now tracked in https://github.com/pulumi/docs/issues/1159

Closing this out
