### ISSUE TITLE
Document how to use a bot account for CI/CD

### ISSUE THREAD

**Issue by ericrudder** [pulumi/docs#1053]
A customer asked if we had a  written definition of a user and whether service accounts / bots needed their own user seat/license.

I answered:

A single bot account is indeed counted as a "user" seat and needs its own license; there is a single role/team assignment per unique bot account.  Each bot account may have unlimited service tokens.

However, I couldn't find an "obvious" place to add to docs ... if you have a suggestion, I can make the actual edit.

**Comment by lukehoban** [comment]
If there is anything to document here - I expect https://pulumi.io/reference/cd.html would be the most natural place.  A section on creating bot users as a best practice on that page likely makes sense.

**Comment by chrsmith** [comment]
As part of organizing the set of docs we want to add, let's close this out. It's something we _could_ document, but it really just confuses the issue. And begs the question about a few features we have in the backlog around scoping a specific access token to teams or stacks.

Especially for Q3, this isn't something that meets the bar for docs to add IMHO.
