### ISSUE TITLE
Cross repo doc links are wrong

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/docs#1073]
See https://github.com/pulumi/docs/pull/1072/files#diff-522872636d36fae384193e8fc38285d1

We have the following embedded link:

```html
<a class="pdoc-child-name" href="https://github.com/pulumi/pulumi-aws/blob/a998eb1436459bca87792641e7c9fb49e4a5e61c/sdk/nodejs/node_modules/@pulumi/pulumi/resource.d.ts#L101">method <b>isInstance</b></a>
```

This doesn't work as we don't have `node_modules` comitted to our repo.  We should find a proper want to do these cross repo links.

**Comment by CyrusNajmabadi** [comment]
Note: this isn't that impactful in practice as it only seems to affect the members inherited from Resource/CustomResource/COmponentResource.  This is a very small set.  We should def fix this, but it's not hampering using the rest of the docs.

**Comment by justinvp** [comment]
This no longer happens AFAICT.
