### ISSUE TITLE
Tutorial: EKS - Hello World! gives incompatible version warnings

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#1084]
Root problem appears to be the use of `aws-infra` package - which we should remove from all tutorials since it is deprecated.

**Comment by CyrusNajmabadi** [comment]
@lukehoban I might need some additional details from you how you're hitting this.  Both the example here (https://github.com/pulumi/examples/blob/master/kubernetes-ts-exposed-deployment/package.json) and the 'latest' pulumi-kubernetes (https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/nodejs/package.json) do not seem to be referencing aws-infra at all...

**Comment by CyrusNajmabadi** [comment]
I'm also not reproing this locally.  But i don't have  kuberenetes setup locally, so it might be htat i'm failing out prior to any message you're seeing.

**Comment by lukehoban** [comment]
Sorry - it's the one here: https://github.com/pulumi/docs/blob/master/quickstart/aws/tutorial-eks.md.

(the fact that we have 3+ copies of more or less the same thing is itself an issue - but I think that's a longer term issue to address).

**Comment by CyrusNajmabadi** [comment]
Ah, gotcha.  Thanks.

**Comment by lukehoban** [comment]
Fixed with https://github.com/pulumi/docs/pull/1093
