### ISSUE TITLE
Wrong naming in heading of documentation "Deploy the grafaml helm chart on Kubernetes"

### ISSUE THREAD

**Issue by erNail** [pulumi/docs#10875]
### Problem description

While googling for the [Helm Chart "grafaml"](https://github.com/erNail/grafaml), which i am the author of, i found a [Pulumi documentation with the name "Deploy the grafaml helm chart on Kubernetes"](https://www.pulumi.com/ai/answers/7W68jq71aqF75Ui3BP4ePR/deploying-grafana-helm-chart-on-kubernetes).

After being really confused why Pulumi would know about my Helm Chart and describe how to install it, i quickly realised, after reading the documentation, that a normal Grafana Helm Chart Deployment is being described. So i guess it is just a typo in the Heading of the documentation page? I guess it should actually be "Deploy the Grafana helm chart on Kubernetes"

### Suggestions for a fix

Change the heading to "Deploy the Grafana helm chart on Kubernetes"

**Comment by interurban** [comment]
thanks @erNail !

**Comment by interurban** [comment]
We've removed this answer page in the near term.
