### ISSUE TITLE
Update docs to use an approved 1Password logo

### ISSUE THREAD

**Issue by isaac-pulumi** [pulumi/docs#10990]
### Problem description

Our friends from 1Password reached out to have this page updated to include their official logo (it appears that we grabbed an old logo).  

- I saw a product documentation issue on the following URL: https://www.pulumi.com/docs/esc/

- Other: <DETAILS>

### Affected product version(s)

N/A

### Suggestions for a fix

Updated the infographic with the logo attached.
![1Password_primary logo_light backgrounds_intrepid blue](https://github.com/pulumi/docs/assets/59850911/34066ea0-616e-4d52-8635-8c1760257642)

**Comment by aaronkao** [comment]
Seems redundant with https://github.com/pulumi/pulumi-hugo/issues/3962

**Comment by interurban** [comment]
Closing this one, I have the new esc image back from our designer I'll wrap this one up in https://github.com/pulumi/pulumi-hugo/issues/3962
