### ISSUE TITLE
Define menu entries for CLI commands in front matter

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#1104]
For expedience, I defined the menus for our generated API docs and CLI commands in `config.toml`:

https://github.com/pulumi/docs/blob/867dc68d08fa9db4334e24b26b1f8d7705a05804/config.toml#L20-L279

However, everywhere else we define menu entries in each page's front matter, and there's no reason we can't do that for our generated docs. We should fix the doc generators to automatically include the menus in the generated front matter.

**Comment by justinvp** [comment]
We no longer list the API packages in the TOC so this only applies to the CLI commands.

**Comment by lukehoban** [comment]
I don't see anything like this in the current docs site - so I'm going to assume we addressed this in the last year.
