### ISSUE TITLE
Update cloud branding

### ISSUE THREAD

**Issue by aydrian** [pulumi/docs#1107]
The logos used for AWS and Azure are currently out of date.
[AWS Trademark Guidelines](https://aws.amazon.com/trademark-guidelines/)

**Comment by cnunciato** [comment]
Related to #1036.

**Comment by joeduffy** [comment]
Perhaps a good cleanup task as part of / after we've moved to the new website.

**Comment by cnunciato** [comment]
Let's also update them all to be SVGs as part of this. From https://github.com/pulumi/pulumi-service/issues/3420:

> The logos we use for AWS, Azure, and GCP on the site are raster-based, and look pretty bad on a (beautiful) 4K display. We should definitely upgrade those to be SVG-based.

**Comment by joeduffy** [comment]
We now use the right logos for the Getting Started guide, but still use the wrong ones on the documentation homepage:

![image](https://user-images.githubusercontent.com/3953235/60926038-1e436380-a25a-11e9-87d8-69c840b70c51.png)
