### ISSUE TITLE
Adjust width of text sections

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#1109]
Our text sections are too wide, per offline conversation, which hampers readability particularly for long walls of text. In fact, based on @cnunciato's scientific analysis, which I shall let him share here, we are about 1.5x too wide. Not a huge deal but given that we're reworking styling anyway, we should keep this in mind and try to address it as part of that workstream.

**Comment by cnunciato** [comment]
Closing as completed with #1213. Text sections are now constrained to the center column of a three-column layout, which should generally hover around 90 characters, or 12-16 words, per line at the 16px default.
