### ISSUE TITLE
Document and blog dev channel releases

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#11100]
We should add some docs around dev channel releases and blog about it:

- Dev channel CLI: Add a section to https://www.pulumi.com/docs/install on how to install the dev channel CLI (mention install script and GitHub action)
- Dev channel SDKs: Add a note to each https://www.pulumi.com/docs/languages-sdks/ page on how to install the dev release

**Comment by cnunciato** [comment]
Hi folks! Just noticed this in triage. It looks like both bullets are done with the exception of the Java SDK. Is that coming as well? If not, is it okay to close this as completed with the linked PRs?

**Comment by tgummerer** [comment]
We're not planning on doing any dev releases for the Java SDK right now, so I think we can close this out.
