### ISSUE TITLE
Provide walkthrough for creating a Pulumi webhook handler

### ISSUE THREAD

**Issue by chrsmith** [pulumi/docs#1110]
It would be nice if this included some more hand-holding on getting users to create a functioning WebHook using Pulumi that they could then use to connect with their own systems.

I suggest we do a few things:

1. Create a strong simple tutorial for setting up a simple webhook handler with a Pulumi program (with AWS, Kubernetes, and possibly Azure/GCP)
2. Link that tutorial from this page, either directly or inside the New button dialog
Possibly even make it a "Deploy with Pulumi" thing that we can walk users through without having to write any code at all.
3. Put some tips on interesting use cases for webhooks at the end of this tutorial (slack notifications, triggering operations in 3rd party systems, logging Pulumi history into 3rd party auditing systems, etc.)

**Comment by lukehoban** [comment]
Between https://github.com/pulumi/examples/tree/master/aws-ts-pulumi-webhooks and https://www.pulumi.com/docs/intro/console/extensions/webhooks/ I think we are okay here for now.  More is always good - but likely can tie that into future product plans.
