### ISSUE TITLE
Config concept page engineering review

### ISSUE THREAD

**Issue by toriancrane** [pulumi/docs#11403]
Regarding the [Config concept page](https://www.pulumi.com/docs/concepts/config/):

- [x] Is the doc representative of the facts? Are the topics covered on the page accurate?
- [x] Are there features of this topic not covered in the guide? Is there anything missing?
- [x] Are there features listed in the guide that no longer exist?
- [x] Are we covering the right concepts and providing relevant use cases/ examples?

**Comment by justinvp** [comment]
https://github.com/pulumi/pulumi-hugo/blob/ec2b6fed8fd7c58cc8d397ac1fed3f20ec170f79/themes/default/content/docs/concepts/config.md?plain=1#L617C116-L617C146

Wondering if "Pulumi ESC" should link to some kind of overview page for Pulumi ESC that explains what it is.
