### ISSUE TITLE
Support guest authors without an avatar image

### ISSUE THREAD

**Issue by sean1588** [pulumi/docs#11438]
Support being able to add a guest author with a default avatar image. If guest authors do not have an account or image in their linkedin or GitHub it does not render correctly on blog posts since there is no image for the person. Can we have a default avatar image that gets shown in these scenarios?

**Comment by thoward** [comment]
Per docs in BLOGGING.md this should be possible already. The `socials` section of the the TOML file is optional and the image is drawn from the static/images/team folder. It seems like as long as there's a TOML file for the guest author and an associated image, this should just work. Closing for now unless we encounter this as a problem in the future.
