### ISSUE TITLE
Carousel behaves incorrectly after resizing the viewport 

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/docs#11494]
On a desktop browser, the customer logo carousel will sometimes incorrectly render multiple identical logos (consistently one customer in particular) after resizing.

To reproduce this, navigate to www.pulumi.com and resize or zoom until the carousel is only 3 logos wide. Refresh the page, then resize or zoom out until the breakpoint is hit to render a wider layout. The result will be something like this, with 3 logos next to one another and no other logos rendering:

![image](https://github.com/pulumi/pulumi-hugo/assets/788800/ae6befd9-b0bd-455d-b8a9-6d2c3972479b)

**Comment by shughes26** [comment]
Carousel has been replaced
