### ISSUE TITLE
Pulumi Cloud access tokens: No explanation of who can create stacks

### ISSUE THREAD

**Issue by jkodroff** [pulumi/docs#11584]
The page Pulumi Cloud access tokens has no documentation on who can create stacks, which is a rather important permission I think.

File: [themes/default/content/docs/pulumi-cloud/access-management/access-tokens.md](https://www.pulumi.com/docs/pulumi-cloud/access-management/access-tokens/)

**Comment by thoward** [comment]
Nice catch, @jkodroff . Added recommended note to token docs. This issue will close when that PR merges.
