### ISSUE TITLE
Nav Icon update needed for ESC

### ISSUE THREAD

**Issue by interurban** [pulumi/docs#11583]
In the move Nav launch to Pulumi Hugo, the shied gliph is missing. The css class for the shield seems to be missing from the source code; there's no definition for it.

In the near term I used an existing one on this temp fix https://github.com/pulumi/pulumi-hugo/pull/3454

**Comment by thoward** [comment]
This seems to be fixed now, and we've moved to a key icon for this product:

![Image](https://github.com/user-attachments/assets/6ee6518c-ba0e-4b20-a245-bb82ee54034e)
