### ISSUE TITLE
logo carousel links difficult to use

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#11595]
## overview
@tusharshahrs called out during ux office hours that he was having difficulty following through links in the homepage logo carousel, several of which link to case studies and youtube content. it seems like while the carousel is auto scrolling that clicking behavior is not respected.

## screen recording
takes three clicks to follow the link through
![carousel-click](https://github.com/pulumi/pulumi-hugo/assets/97129308/e610787a-b49c-4ecb-a3ed-3873ec2ccdca)

**Comment by thoward** [comment]
This has changed. Currently the carousel links don't go directly to the case studies, but link to a lower section on the page. TBH i also find that behavior counter-intuitive, but it seems to work consistently, regardless of scroll status. Closing this as fixed.
