### ISSUE TITLE
Notes are sometimes different sizes

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#11591]
On this page, for example, the first note is in a smaller font than the second one:

![image](https://github.com/pulumi/pulumi-hugo/assets/274700/ac2848d6-add1-4d14-8f82-2052985339fb)

These should always be the size, site-wide.

**Comment by thoward** [comment]
Fixed markdown source in https://github.com/pulumi/docs/pull/13468. This issue will close automatically when the PR is merged.
