### ISSUE TITLE
Okta: Configuring the SCIM Connector doc needing update

### ISSUE THREAD

**Issue by kelsey-dirks** [pulumi/docs#11619]
### What happened?

Our docs say, "For HTTP HEADER, you will use a token from the [Pulumi Cloud](https://app.pulumi.com/) as the authorization bearer token. To generate a token, navigate to your org in the Pulumi Cloud, click on the Settings tab, and then click SAML SSO. Scroll down to the SCIM section and generate a new token if you have never generated one for your org, or regenerate it if you have already done so in the past."

However, the Pulumi Cloud doesn't generate a token. It instead tells the user to contact support. The doc will need to be updated to reflect our new process. 

### Expected Behavior

NA

### Steps to reproduce

The doc that needs updating: [https://www.pulumi.com/docs/guides/scim/okta/#configuring-the-scim-connector](https://www.pulumi.com/docs/guides/scim/okta/#configuring-the-scim-connector)

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by yoejigu** [comment]
PR has been created to make updates to the documentation. Waiting for approval and merging
