### ISSUE TITLE
write content for an `Updates` concept page

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#11615]
this page, will be a child of `Concepts` and. be listed after `Resource options`
the update plans page would be a child of this new page

we have docs on updates spread throughout other concepts pages but this would be a page dedicated to users understanding updates

some things to consider including on this page
- what are updates
- what are the different types of updates
- what happens when you run an update
- different available options when running updates
- what to do when you get errors when running an update
- .. etc etc

**Comment by interurban** [comment]
Thanks, we plan to close down this issue as part of grooming. We have pulumi up documented as part of cli docs here: https://www.pulumi.com/docs/iac/cli/commands/pulumi_up/
