### ISSUE TITLE
Warning banner renders oddly in blog overview pages

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#11626]
<img width="962" alt="Screenshot 2023-04-21 at 3 27 13 PM" src="https://user-images.githubusercontent.com/223467/233728833-cf3de1ab-3a70-46f8-beca-2d9251cc59ef.png">

A few instances of this issue on https://www.pulumi.com/blog/author/joe-duffy/page/3/.

**Comment by thoward** [comment]
This was fixed at some point. Not sure when...

![Image](https://github.com/user-attachments/assets/c78e23c7-0334-4eef-8bc4-65fa5d4677f4)
