### ISSUE TITLE
Add guidelines for tag selection

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#11661]
For writers of blog posts, it'd be good to provide them with a few guidelines for choosing the right set of tags -- how to review the list of tags that already exist, how tags factor into SEO and findability, etc.  (cc @SaraDPH)

**Comment by thoward** [comment]
There is some existing guidance for this here: https://github.com/pulumi/docs/blame/180a84d43e9e2e52480818e602e993729149288b/BLOGGING.md#L65

@asafashirov maybe you could update that file for some tips re: SEO. If so, please create a new issue for this on your board. For now, closing this as fixed.
