### ISSUE TITLE
add indentation guides to codeblocks.

### ISSUE THREAD

**Issue by dixler** [pulumi/docs#11662]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
for some languages(python, yaml) it's hard to identify the nesting of different expressions. Indentation guides(the `|` on the left) can clarify these. Can we style codefences to have indentation guides?

![2022-08-15-080045_788x560_scrot](https://user-images.githubusercontent.com/25750473/184703043-d9fabb4a-f83e-47f0-9537-549a87ac2c2b.png)

cc @susanev

**Comment by thoward** [comment]
Thanks for the suggestion @dixler! It's a great idea, but unfortunately this is probably out of scope for our current publishing system.  As always, we welcome contributions so if you find a way to include this in Hugo's code block rendering we'd be very happy to see a PR for it! Closing as wont-fix for now.
