### ISSUE TITLE
Python example for setting a static name 

### ISSUE THREAD

**Issue by kenseii** [pulumi/docs#11668]
File: [themes/default/content/docs/intro/concepts/resources/names.md](https://www.pulumi.com/docs/intro/concepts/resources/names/)

On the python example it suggests setting it as a dictionary but a simple argument name suffices.
example:
```
role = iam.Role('my-role', {
    name='my-role-001'
})
```
suggestion
```
role = iam.Role('my-role', 
    name='my-role-001')
```
i tested it on dynamoDB with python and something like this worked.
```
table = dynamodb.Table(
    "MyTableName",
    name="MyTableName",
    ...)
```
i wonder if setting the docs to use a simple argument wouldn’t be better

**Comment by thoward** [comment]
Nice catch @kenseii ! This was updated at some point and the current docs use the named parameter instead of a dictionary. Thanks for the feedback.
