### ISSUE TITLE
Add a section on `PULUMI_DEBUG_PROVIDERS`

### ISSUE THREAD

**Issue by dixler** [pulumi/docs#11667]
File: [themes/default/content/docs/support/troubleshooting.md](https://www.pulumi.com/docs/support/troubleshooting/)

debugging an issue. was told this flag is helpful. will document how to use it as I figure out how to use it.

**Comment by thoward** [comment]
Thanks for the feedback @dixler! This was fixed at some point in the following doc: https://www.pulumi.com/docs/iac/packages-and-automation/pulumi-packages/debugging-provider-packages/#running-pulumi-with-debug-providers
