### ISSUE TITLE
Smart Preview URLs

### ISSUE THREAD

**Issue by zchase** [pulumi/docs#11678]
Right now when we create a PR preview we just link to the home page of the preview. We should investigate if we can use the data in the diff to be able to populate the PR preview with pages that have changed. This will make it much easier for a reviewer (especially a non-technical reviewer) to easily know what pages to check for accuracy.

We will probably need to enforce a maximum amount of links we would show on a list as well.

**Comment by thoward** [comment]
This is a great idea, but since there has been no motion on this in 2.5 years, I'm closing as `wont-fix` for now. If we want to make some investments into this subsystem we can reopen at that time.
