### ISSUE TITLE
Make it easier to filter blog posts by cloud and/or language

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#11694]
I was just answering a question that made me wish we had an easy way to filter the blog for examples by cloud and language. We do have tags for this, so it might just be a matter of surfacing these particular tags in a slightly more discoverable way, and then ensuring all posts use the right set of cloud and language tags -- although I don't think Hugo supports multi-tag filtering, so maybe not. Worth looking into.

**Comment by thoward** [comment]
This is a great idea, but likely something that will have to wait until we move away from Hugo. Closed as `wont-fix` for now.
