### ISSUE TITLE
make it easier for all pulumi folks to have insights into our website performance

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#11703]
## overview
itd be great if everyone who works on the website could easily access reporting on website performance. this is especially important as folks are integrating with other tools, so we can all understand the performance impact and then make adjustments as needed

## proposed solution
setup a slack integration with lighthouse that shares a report in #frontend, maybe every weekday or once a week.

**Comment by interurban** [comment]
Thanks, planning to close this down as part of grooming. We pull all this into and report via metabase.
