### ISSUE TITLE
Not clear there is a free text feedback form in docs

### ISSUE THREAD

**Issue by meagancojocar** [pulumi/docs#11700]
File: [themes/default/content/docs/get-started/_index.md](https://www.pulumi.com/docs/get-started/)

On the docs pages we have a "Was this page helpful?" question on the right-hand side of the page which opens up to a free text input field for additional feedback. It wasn't clear to me personally that there was a free text option before clicking on the 'Yes' button. 

Mentioned to the UX team and they suggested I open an issue :).

**Comment by thoward** [comment]
We are working on a new star-based CSAT widget this quarter so closing out this issue as `wont-fix` since it relates to the old design.
