### ISSUE TITLE
add return to top functionality 

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#11705]
## overview
we want to make it easy for folks to return to the top of the page on any of our docs or registry pages. we will need a button design and then will need to implement the behaviour.

this was first discussed in https://github.com/pulumi/pulumi-hugo/issues/883

**Comment by thoward** [comment]
Closing as no-repro since the site already has this feature. While I agree it could use a redesign to make it a bit more obvious, this seems like something we're unlikely to address any time soon. Feel free to re-open if we do a design spike on the site theme.
