### ISSUE TITLE
Add a tip-type callout to the notes shortcode

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#11724]
We have info-style notes and warnings, but it'd be nice to have tips, too, like for things like this, which are meant to be read more as "try this" than "bear in mind":

![image](https://user-images.githubusercontent.com/274700/149406465-05f1ec56-2f11-47aa-8e94-e714dd840621.png)

We should probably also rename the shortcode from `notes` to something more generic. [Leanpub uses an expression called `{blurb}`](https://leanpub.com/markua/read#leanpub-auto-blurbs-b-or-blurb) for this that takes a `class`, like `tip` or `info`, and it works pretty well.

**Comment by thoward** [comment]
Implemented in #13335 with a slightly different style than described here.
