### ISSUE TITLE
Add more useful apply examples to docs/intro/concepts/inputs-outputs/#apply

### ISSUE THREAD

**Issue by stack72** [pulumi/docs#11748]
The examples that are there right now are basic usage of apply - it would be good to do something where we can do something like build an IAM Policy in our apply to show a more complex example

This relates back to https://github.com/pulumi/pulumi/issues/5236 and the incorrect use of the apply inside the get_policy_document invoke

**Comment by jkodroff** [comment]
Found an example for this here: https://www.pulumi.com/docs/concepts/inputs-outputs/apply/#outputs-and-json

I believe this issue can be closed.
