### ISSUE TITLE
Multiple problems with S3 Backend documentation and usage

### ISSUE THREAD

**Issue by eproxus** [pulumi/docs#11755]
File: [themes/default/content/docs/intro/concepts/state.md](https://www.pulumi.com/docs/intro/concepts/state/)

I am trying to use DigitalOcean Spaces as an S3-compatible backend. I encountered the following documentation problems:

1. It is not documented that the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` needs to be set.
2. It is not documented that `AWS_REGION` needs to be set **to some bogus value which is apparently not used** (otherwise an error occurs: `MissingRegion: could not find region configuration`)
3. When importing state exported from the Pulumi cloud storage, this error occurs:
    ```
    $ pulumi stack export --show-secrets --file infra.checkpoint.json
    $ pulumi logout
    $ pulumi login 's3://my-space?endpoint=fra1.digitaloceanspaces.com'
    $ pulumi stack import --file infra.checkpoint.json
    error: could not deserialize deployment: constructing secrets manager of type "service": could not find access token for https://api.pulumi.com, have you logged in?
    ```
3. After the stack import fails, Pulumi keeps asking for a passphares for _every_ operation (even though the passphrase was empty):
    ```
    $ pulumi up
    Enter your passphrase to unlock config/secrets
        (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
    ```

I realize some of these problems might be bugs in Pulumi itself. Please let me know how to handle that (report new issues etc.).

**Comment by thoward** [comment]
These issues have been addressed since this was originally filed.
