### ISSUE TITLE
Linux instructions claim pulumi is added to PATH

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#1176]
Our installation instructions for Linux say

> This will install the pulumi CLI to ~/.pulumi/bin and add it to your path.

This doesn't seem to be correct -- it needs to be added manually

```
root@d5aaa2bfd9eb:/# curl -fsSL https://get.pulumi.com | sh
=== Installing Pulumi v0.17.16 ===
+ Downloading https://get.pulumi.com/releases/sdk/pulumi-v0.17.16-linux-x64.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 43.9M  100 43.9M    0     0  1843k      0  0:00:24  0:00:24 --:--:-- 2101k
+ Extracting to /root/.pulumi/bin

=== Pulumi is now installed! 🍹 ===
+ Please add /root/.pulumi/bin to your $PATH
+ If you're new to Pulumi, here are some resources for getting started:
      - Getting Started Guide: https://pulumi.io/quickstart
      - Examples Repo: https://github.com/pulumi/examples
      - Create a New Project: Run 'pulumi new' to create a new project using a template
root@d5aaa2bfd9eb:/# pulumi
bash: pulumi: command not found
```

This is a minor point, but worth fixing.

**Comment by bermudezmt** [comment]
This seemed to work automatically for me installing Pulumi on Ubuntu 19.04.

**Comment by justinvp** [comment]
The install script will attempt to add it to the path automatically.

https://github.com/pulumi/get.pulumi.com/blob/06a83e9f35f4fa1dcf6f5bf352b8b875fdf7eb3c/dist/install.sh#L158-L162

If it can't it will include the extra "Please add to your path" step.

**Comment by bermudezmt** [comment]
Oops, didn't mean to commit directly to `master`, but I added a note to that effect via https://github.com/pulumi/docs/commit/19a88fc34d33d35328bd58637f7f705e7f1f3fa1.
