### ISSUE TITLE
Suggestion: Change Modify step in Getting Started to truly Modify

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#1177]
Right now in our Getting Started flow, we go from [one example (an S3 bucket)](https://pulumi.io/quickstart/aws/review-project/) to [something entirely different (an EC2 instance running a Python web server)](https://pulumi.io/quickstart/aws/modify-program/). I personally found this confusing to label as "modifying" my program, since I'm actually replacing it altogether. Not only is the EC2 instance example bigger and harder to follow than the nicely simple S3 one we started with, this seems like a missed opportunity to give me a sense of truly updating resources. I would encourage thinking about something else instead, like enabling encryption at rest on our S3 bucket, which is simpler and will give the end user a quicker, more relevant feel for what a typical update entails.

**Comment by joeduffy** [comment]
Another reason to go with the S3 example, rather than EC2. I think if you have an old AWS account created prior to 2013 -- like I do -- it still tries to use EC2-Classic by default when deploying into `us-east-1`, which fails with the default steps specified in our tutorial:

```
    error: Plan apply failed: Error launching source instance: VPCResourceNotSpecified: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.
```

I might be mistaken, but I _think_ that's what's going on.

**Comment by joeduffy** [comment]
For instance, this is a nice modification to the base Python example that creates a KMS key and enables encryption on our S3 bucket:

```
import pulumi
from pulumi_aws import kms, s3

# Create a KMS Key for S3 server-side encryption;
key = kms.Key('my-key')

# Create an AWS resource (S3 Bucket)
bucket = s3.Bucket('my-bucket',
    server_side_encryption_configuration={
        'rule': {
            'apply_server_side_encryption_by_default': {
                'sse_algorithm': 'aws:kms',
                'kms_master_key_id': key.id
            }
        }
    })

# Export the name of the bucket
pulumi.export('bucket_name',  bucket.id)
```

It can be done with an in place update, and is pretty easy to follow:

```
Updating (dev):

     Type                 Name            Status      Info
     pulumi:pulumi:Stack  quickstart-dev
 +   ├─ aws:kms:Key       my-key          created
 ~   └─ aws:s3:Bucket     my-bucket       updated     [diff: ~serverSideEncryptionConfiguration]

Outputs:
    bucket_name: "my-bucket-127bd18"

Resources:
    + 1 created
    ~ 1 updated
    2 changes. 1 unchanged

Duration: 11s
```

**Comment by justinvp** [comment]
PR for AWS: #1253

I look into doing something similar for Azure and GCP.

**Comment by justinvp** [comment]
- [ ] AWS (#1253)
- [ ] Azure
- [ ] GCP

**Comment by justinvp** [comment]
Fix is available for AWS, but still need to update Azure and GCP. Moving to next milestone.
