### ISSUE TITLE
Provider a powershell command to install/update

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/docs#11795]
I installed a new Pulumi CLI version several dozens of times, but I still don't know how to do so *easily*. I basically google "pulumi install windows", then copy-paste the long unreadable command.

The command wouldn't work in Powershell that I already have open, so I have to open a `cmd` window which will run another Powershell window. If I want to run in Powershell directly, I need to cut out the `iex ((New-Object System.Net.WebClient).DownloadString('https://get.pulumi.com/install.ps1'))` command correctly and exactly.

Ideas:
1. Provide a Powershell command to copy-paste.
2. If I already have a CLI installed, there could be a command to upgrade it without google.
3. Chocolatey (and/or other package managers) support as in pulumi/pulumi#1536

**Comment by thoward** [comment]
This seems like something that would be a quick fix, and I'd be happy to act on it right now. If someone can provide the correct Powershell commandline (@mikhailshilkov ?), I could add to the existing documentation, however, I don't have a testing environment for Windows/Powershell to verify it. That said, we already have many methods for installation on Windows, and it feels a little unnecessary to have one more.

The ticket was originally filed 5 years ago, and listed three concerns. Two of those have been addressed (instructions on how to upgrade, and Chocolatey support). So, unless we can address in the next day or two, I will close this as `resolution/fixed`.

**Comment by thoward** [comment]
Chatted w/ @mikhailshilkov and decided to close this as fixed. Happy to reopen at a later date.
