### ISSUE TITLE
4 hours and i still cant get the name of a resource group into a stack output!

### ISSUE THREAD

**Issue by RDavis3000** [pulumi/docs#11840]
File: [themes/default/content/docs/concepts/inputs-outputs/apply.md](https://www.pulumi.com/docs/concepts/inputs-outputs/apply/)

All I want to do is get the name of a created Azure Resource Group to be somehow output by the stack so it can be used by the next step of a GitHub Action. Is that really so much to ask?

1) Why does this page show me all the wrong ways to do it first? Just show me the right way! 
2) I cannot find a straightforward description of the difference between Ouput.Apply and Output.Create in C#
3) I cannot find a straightforward description of the differences between the 

`Public Class MyStack() `

approach and the

```
return await Deployment.RunAsync(() =>
{
```

some examples use one, some the other. I get that it's just a C# thing, but it would be good if the examples were consistent. It makes a difference when you are trying to return/expose values as Outputs.

**Comment by thoward** [comment]
I added a paragraph to disambiguate between stack outputs and Output<T> in #13332 ... This should prevent this kind of (very understandable) confusion in the future.
