### ISSUE TITLE
AWS tutorial and example doesn't work without a Default VPC

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1185]
The AWS quickstart example doesn't work for AWS accounts that do not have a default VPC (as t2 instances require a VPC). The example should be updated to include an awsx VPC.

https://pulumi.io/quickstart/aws/modify-program/

**Comment by joeduffy** [comment]
If we do this https://github.com/pulumi/docs/issues/1177, we won't need to modify the quickstart, fwiw, since it will no longer encounter this problem. We may want to fix up some of our examples, however (e.g. https://github.com/pulumi/examples/tree/master/aws-js-webserver).

**Comment by justinvp** [comment]
I'm updating the AWS Get Started guide to use the approach suggested in #1177.

Keeping this open to track updating:

- https://pulumi.io/reference/tutorials/aws/tutorial-ec2-webserver/
- https://github.com/pulumi/examples/tree/master/aws-js-webserver
- etc.

**Comment by lukehoban** [comment]
> https://pulumi.io/reference/tutorials/aws/tutorial-ec2-webserver/

This now has a mention of the VPC requirement and a suggestion to use `t1` is needed.
