### ISSUE TITLE
Clarify documentation for `pulumi org set-default` to indicate it only affects local users

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/docs#11869]
File: [content/docs/cli/commands/pulumi_org_set-default.md](https://www.pulumi.com/docs/cli/commands/pulumi_org_set-default/)

Currently, this documentation for users with their own self-managed backend is confusing. The wording states, "Set the default organization for the current backend," which can mislead users into thinking that this command will change the default organization for all users sharing the same backend. In reality, it only changes this setting locally for the user via config.json in the Pulumi home directory.

Could we add a note to call out this only affects the local user?

**Comment by interurban** [comment]
in the pulumi cli; update the command help option as well
