### ISSUE TITLE
Component Resources docs should show how to accept arguments

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#11915]
File: [content//docs/concepts/resources/components](https://www.pulumi.com/docs/concepts/resources/components/)

The current example doesn't show how to define a component that accepts a set of inputs. It should.

**Comment by jkodroff** [comment]
@interurban This is a high value page to fix since it explains a core Pulumi concept and is lacking critical information for a pretty basic use case. (I am covering this concept in training.)

**Comment by jkodroff** [comment]
@cnunciato I believe that `CustomResourceOptions` should also default to `{}`.
