### ISSUE TITLE
Minor fixes for Case studies page

### ISSUE THREAD

**Issue by aaronkao** [pulumi/docs#12460]
Here are some minor changes that need to be done to enhance the new case studies page

- [x] Make homepage logos all clickable to redirect it to the case studies homepage 
- [x] Add stats for all the case studies
- [x] Make big logo wall scrolling like https://www.honeycomb.io/customers

**Comment by aaronkao** [comment]
A few things that need to be fixed

- [ ] The logos should already be present on the page but just scrolling. The way I see it is its coming in with blank space from the edge
- [ ] There are some logos that are rendering in a giant way. Can you fix them?

![Image](https://github.com/user-attachments/assets/3af40a56-f76f-45c3-bdbe-5364339a9d96)

![Image](https://github.com/user-attachments/assets/df00b0ec-c53a-4bd9-bfb1-636c2b25692d)

**Comment by joeduffy** [comment]
Note -- My feedback was to ditch the scroll entirely on the /case-studies page (leave it on homepage). To me, it's quite dizzying. I loved how it looked yesterday.

**Comment by joeduffy** [comment]
Also, the logos on the homepage have gone missing on mobile for me entirely.

**Comment by shughes26** [comment]
> Also, the logos on the homepage have gone missing on mobile for me entirely.

@joeduffy I am working on a mobile-friendly carousel to deliver this morning. I'll slow the scroll as well. For the /case-studies page we could slow the logo scroll way down to a crawl if we want, but for now I'll stop it entirely.
