### ISSUE TITLE
Better callout of required and optional resource arguments.

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1246]
From our API documentation (both Node and Python), it's not entirely obvious which resource arguments are required and which are optional. The Node API documentation indicate optional arguments with a `?` (e.g. `ebsOptimized?: pulumi.Input<boolean>;`) but this is subtle and not immediately obvious to users without a strong Node background. In our Python API documentation some of the resource arguments indicate _optional_ but most optional ones do not.

The API docs should indicate clearly which resource arguments are required or not; with an _optional_ label that is not a language-specific indicator (i.e. `?`).

**Comment by lukehoban** [comment]
Another related thing which I would really like to see added in docs - whether the property causes replacement or not.  This is not currently available at all in the docs, and is generally very important for understanding what will happen when you make a change. 

Both of these are aspects of moving away from being strictly language API docs and toward being logically Pulumi resource docs.

**Comment by lukehoban** [comment]
The original issue is handled well in the new resource-based docs.  

The second piece is tracked in https://github.com/pulumi/docs/issues/3602.

Closing this one out now.
