### ISSUE TITLE
TypeScript docgen not working for classes imported from other files

### ISSUE THREAD

**Issue by lblackstone** [pulumi/docs#1251]
This link refers to a class defined in a different file, which isn't showing up in the docs generated with the `tsdocgen` utility:
https://pulumi.io/reference/pkg/nodejs/pulumi/aws/ec2/#InstanceState-iamInstanceProfile

https://github.com/pulumi/pulumi-aws/blob/55bd0390160d27350b297834026fee52114a2d41/sdk/nodejs/ec2/instance.ts#L7

**Comment by justinvp** [comment]
This has been fixed.
