### ISSUE TITLE
[Fusion] Scrollbars always visible, even when unnecessary

### ISSUE THREAD

**Issue by chrsmith** [pulumi/docs#1255]
This doesn't repro consistently, e.g. on my MacBook they aren't visible but on a different machine they are.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/4029847/60391309-53a0c200-9aa0-11e9-94cc-0ef3a963aae2.png">

**Comment by cnunciato** [comment]
@chrsmith Can we close this via #1256?

**Comment by chrsmith** [comment]
Yeah, thanks.
