### ISSUE TITLE
Misleading docs

### ISSUE THREAD

**Issue by Meai1** [pulumi/docs#1258]
This page says: https://pulumi.io/quickstart/kubernetes/configure/

> "Configure Kubernetes so the Pulumi CLI can connect to a Kubernetes cluster."

Yet the homepage says:

> "Kubernetes
> Deploy and orchestrate cloud native Kubernetes services in real code, no YAML needed."

So how can there be no YAML needed when I first need to set up the entire kubernetes platform and run it by myself outside of Pulumi? That doesnt make any sense.

**Comment by lukehoban** [comment]
We do this now in https://www.pulumi.com/docs/get-started/kubernetes/ (and to a lesser extent https://www.pulumi.com/docs/intro/cloud-providers/kubernetes/).
