### ISSUE TITLE
The hero background has a little purple bump at the bottom

### ISSUE THREAD

**Issue by iwahbe** [pulumi/docs#12655]
### Problem description

The [hero image background](https://github.com/pulumi/docs/blob/master/static/images/home/hero-background.svg) has a little purple bump at the bottom, which is visible at certain screen resolutions.

![Image](https://github.com/user-attachments/assets/abbd4130-8c1d-419d-b348-a336a0f780e6)

It looks like the hero image background was cropped from another photo, and the crop wasn't quite clean. 

### Suggestions for a fix

As an initial fix, we could tighten the crop by a couple of pixels.

**Comment by iwahbe** [comment]
CC @dwahbe

**Comment by shughes26** [comment]
The recent homepage updates removed this header
