### ISSUE TITLE
UI Browser Sizing Issue

### ISSUE THREAD

**Issue by toriancrane** [pulumi/docs#12666]
### Problem description

When I navigate to the [Tutorials landing page](https://www.pulumi.com/tutorials/), the separator for the left navigation menu seems to bleed over into the main content area of the page.

Environment Details:

- Browser: Chrome and Firefox
- Dimensions
  - Chrome: 1307 x 582
  - Firefox: 1312 x 620

![Image](https://github.com/user-attachments/assets/e771960d-283d-46ae-8528-ca77ff6ee8c3)

**Comment by thoward** [comment]
This was fixed. Thanks @cnunciato.
