### ISSUE TITLE
Website tweaks

### ISSUE THREAD

**Issue by chrsmith** [pulumi/docs#1277]
Collection of issues post GREAT WEBSITE MIGRATION OF 2019

- [x] We serve a few `.webp` images for blog posts, but it looks like the image format isn't supported on Safari. Example: see the "Running Containers in AWS..." feature image on https://www.pulumi.com/blog/tag/containers/.
- [x] Author avatar images get stretched in odd ways on mobile. Navigate to https://www.pulumi.com/blog/author/chris-smith/ and make the window super-duper teeny-tiny. We should set a min-size of the image and/or constrain how it shrinks?
- [x] Do we still have the short links for `/help/...`? We still have some URLs baked into the `pulumi/pulumi` code that reference things like https://pulumi.io/help/stack-reference. Is there an updated version of that?
- [ ] `h6` seems to be formatter as ALLCAPS, even when styling an inner `code` element?  (see https://www.pulumi.com/docs/reference/programming-model/#dependson)

  <img width="808" alt="Screen Shot 2019-07-10 at 10 20 48 PM" src="https://user-images.githubusercontent.com/710598/61023999-07d3ff80-a361-11e9-9dc8-ac3835fd1a8c.png">

  These are `<h6><code>dependsOn</code></h6>`

- [x] The highlighting of currently selected section in the nav is barely noticeable

- [x] We seem to be generating an rss.xml file for all sections; is there a way to make it only generate for /blog/rss.xml? (#1420)

**Comment by justinvp** [comment]
> * Do we still have the short links for `/help/...`?

We should discuss what we want to do with these. See https://github.com/pulumi/pulumi-service/pull/3716#discussion_r300465434

**Comment by justinvp** [comment]
I checked off the "short links" bullet above per https://github.com/pulumi/pulumi-service/pull/3716#issuecomment-509262571

**Comment by justinvp** [comment]
I also added a couple bullets from #1213 (I'm going to close #1213)
