### ISSUE TITLE
Document AWS S3, Azure Blob, Google Object Store backends

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#1279]
We currently document the `file://` option for local backends, but do not do so for the various cloud provider remote backends (AWS S3, Azure Blob Store, Google Object Store, etc): https://www.pulumi.com/docs/reference/state/#to-the-filesystem-backend. We should also do a great job of documenting the other backends so we can easily reference them.

**Comment by ChristianEder** [comment]
+1 for this. I am currently struggling to use Azure Blob Storage for state handling, and still failings as of now.

- First step was documented in the [changelog](https://github.com/pulumi/pulumi/blob/master/CHANGELOG.md#0179-2019-04-30): `pulumi login azblob://containerName`
- The readme only mentioned `Credentials for accessing the bucket operate in the normal manner for each cloud provider`, I found out how to do that here: https://godoc.org/gocloud.dev/blob/azureblob 
- Now, after creating the required container with the name specified in the first step, `pulumi up` still fails with `The specified blob does not exist`, but doesnt tell which blob it expects and what content that should have.

**Comment by ChristianEder** [comment]
And worse - when I run `pulumi login` now, it won't let me login back to the usual app.pulumi.com account, it just states that I am still logged in to the Azure blob, while the available docs and --help say otherwise.

**Comment by ChristianEder** [comment]
Deleting the `.pulumi/credentials.json` file in my user profile let me login back to the "normal" backend
