### ISSUE TITLE
AWSX VPC Guide has "EIP per private" instead of public subnet

### ISSUE THREAD

**Issue by pomali** [pulumi/docs#12911]
File: [content/docs/iac/clouds/aws/guides/vpc.md](https://www.pulumi.com/docs/iac/clouds/aws/guides/vpc/)

> A NAT Gateway and EIP per private subnet.

This is probably wrong and it's per **public** subnet

**Comment by thoward** [comment]
Nice catch! This kind of feedback is really appreciated.

Fixed when #12934 lands.
