### ISSUE TITLE
Enhance author section on blog post template

### ISSUE THREAD

**Issue by aydrian** [pulumi/docs#1294]
Currently when you click into a blog post, you only see the author name and profile pic with a link the author page. It would be nice to add the following:

- Any defined author social links
- The guest tag if they are a guest
- Title
- Possibly a short description

**Comment by leezen** [comment]
Sorry for the lengthy delay in reply -- getting around to a backlog of items and saw this without any comments. When you say "Possibly a short description" do you mean a quick 1-2 sentence summary of the post itself?

**Comment by lukehoban** [comment]
We do now have title and social links - which I think is okay for now.  

https://www.pulumi.com/blog/author/sophia-parafina/
