### ISSUE TITLE
Incorrect link to autonaming documentation

### ISSUE THREAD

**Issue by BeeDeeBePope** [pulumi/docs#12993]
File: [content/docs/iac/concepts/options/import.md](https://www.pulumi.com/docs/iac/concepts/options/import/)

The link at the bottom of the document does not direct to anything related to autonaming as the sentence suggests

> To fix this problem, explicitly specify the resource’s name [as described here](https://www.pulumi.com/docs/iac/concepts/options/#autonaming).

Should be 

> To fix this problem, explicitly specify the resource’s name [as described here](https://www.pulumi.com/docs/iac/concepts/resources/names/#autonaming).

https://www.pulumi.com/docs/iac/concepts/resources/names/#autonaming

**Comment by thoward** [comment]
Thanks for reporting this! You are 100% correct and I filed a PR to resolve here: https://github.com/pulumi/docs/pull/13143
