### ISSUE TITLE
Duplicate press release displayed.

### ISSUE THREAD

**Issue by aydrian** [pulumi/docs#1305]
It appears there are 2 entries for the same press release. One for June 11, 2019 and the other for October 22, 2019. Perhaps the June one should be Crosswalk.
![image](https://user-images.githubusercontent.com/981130/60912198-b2e99980-a239-11e9-803e-6c6571e62cc5.png)

**Comment by cnunciato** [comment]
Closing as fixed with https://github.com/pulumi/docs/commit/98960e161a872c96b9554d5ef2e6617406ca432b.
