### ISSUE TITLE
Replace all references of pulumi.io to www.pulumi.com

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/docs#1311]
After TGWMO2019, many older links (both emitted from the CLI and within the docs) would benefit from being updated.

---

Page: https://www.pulumi.com/docs/quickstart/aws/install-pulumi/

```
=== Pulumi is now installed! 🍹 ===
+ If you're new to Pulumi, here are some resources for getting started:
      - Getting Started Guide: https://pulumi.io/quickstart
```

The link redirects to https://www.pulumi.com/docs/quickstart/ but this should probably be updated to reflect the new URL.

**Comment by chrsmith** [comment]
Retitled, as this is a more general thing we need to fix up. We made changes in the `pulumi-service` repo, but we need to make similar changes in `pulumi/pulumi` and finally in this one, too.

**Comment by justinvp** [comment]
We also need to update the description of the `pulumi/docs` repo. I'd do it, but I don't think I have the necessary GH permissions.

<img width="507" alt="Screen Shot 2019-07-15 at 7 30 41 AM" src="https://user-images.githubusercontent.com/710598/61223980-92ef2580-a6d2-11e9-9bdb-4bf212823b29.png">

**Comment by ericrudder** [comment]
I updated the URL ... if you meant for something more, please feel free to
file an issue my way.

**Comment by justinvp** [comment]
Need to update all our repos.

Note: There are a handful of `pulum.io` "short links" that we want to continue using for now:

- https://pulumi.io/help/outputs
- https://pulumi.io/help/stack-reference
- https://pulumi.io/oa5g1o
- https://pulumi.io/ws0cq2
- https://pulumi.io/xdv72s

**Comment by stack72** [comment]
https://github.com/pulumi/pulumi-terraform/pull/425

**Comment by chrsmith** [comment]
Should be fixed from the linked PRs, though there are still old references in the library repos. We'll let those slide for the time being.
