### ISSUE TITLE
Mistake in OIDC setup instructions

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#13124]
File: [content/docs/pulumi-cloud/access-management/oidc/provider/aws.md](https://www.pulumi.com/docs/pulumi-cloud/access-management/oidc/provider/aws/)

Running though the setup instructions on this page, Step 4 says to click "Get Thumbprint", but there's no  "Get Thumbprint" button on this page:

![Image](https://github.com/user-attachments/assets/c19ba724-4375-4e92-81ef-8942ff140ddd)

**Comment by thoward** [comment]
Note: Looked into this briefly during triage, and it seems that maybe AWS has changed the UI here. Other users are reporting this issue with AWS https://repost.aws/questions/QUSWNRGttqRvSUWUcMSnAs0w/why-can-t-see-get-thubmprint-when-create-oidc-in-free-account-tier ... seems like maybe the thumbprint function are available in the next screen?

**Comment by smithrobs** [comment]
Just had to do this with a client and can confirm the thumbprint is now auto-gen'd for you; no add'l step needed
