### ISSUE TITLE
Blog tag cloud rendered incorrect on tag overview pages

### ISSUE THREAD

**Issue by ringods** [pulumi/docs#13123]
### Problem description

I saw an issue on the following blog pages:

* https://www.pulumi.com/blog/
* https://www.pulumi.com/blog/tag/policy-as-code/

On the overall blog page and on individual blog posts, the blog tag cloud renders with the (typical) border around each tag:

![Image](https://github.com/user-attachments/assets/1da0ebf6-006c-4e06-9e8c-1d0e1f40cdb0)

But on an overview page for a specific tag, the tag cloud renders as the words without the borders around them:

![Image](https://github.com/user-attachments/assets/32974b3b-e87a-462b-ac27-0389392f0661)

**Comment by thoward** [comment]
Good eye! I don't think i would have ever noticed that, especially with it being beneathe the fold. Fixed in https://github.com/pulumi/docs/pull/13144
