### ISSUE TITLE
kubernetes.helm.sh/v3.Chart note points to wrong blog post

### ISSUE THREAD

**Issue by stooj** [pulumi/docs#13136]
The `Note` on [kubernetes.helm.sh/v3.Chart](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/chart/) points to a blog post about [kubernetes-yaml-v2](https://www.pulumi.com/blog/kubernetes-yaml-v2/).

I believe it should point to [Helm Chart v4 resource with new features and languages](https://www.pulumi.com/blog/kubernetes-chart-v4/).

**Comment by thoward** [comment]
Good catch! @EronWright can you confirm that the wrong post is linked here?
