### ISSUE TITLE
AWS installation documentation contains reference to removed option.

### ISSUE THREAD

**Issue by stooj** [pulumi/docs#13137]
### Problem description

[AWS Installation & Configuration](https://www.pulumi.com/registry/packages/aws/installation-configuration/)
includes the `skipGetEc2Platforms` option, which was removed as part of [Upgrade terraform-provider-aws to v5.27.0 (https://github.com/pulumi/pulumi-aws/pull/3056)](https://github.com/pulumi/pulumi-aws/commit/140767c757410447e8d7d919c6ac347f833c948b#diff-34c57e622183cb0d8dd0d3f9e[%E2%80%A6]40120e9b2ad811bac7ac7be4cea4b1)

If you include this option, pulumi errors with the following message:

```
##[error]error: pulumi:providers:aws resource 'my-provider has a problem: could not validate provider configuration: Invalid or unknown key. Examine values at 'my-provider.skipGetEc2Platforms'.
```

### Affected product version(s)

- pulumi-aws >= v5.27.0

**Comment by thoward** [comment]
Thanks for the tip, @stooj! I updated the doc in this PR https://github.com/pulumi/registry/pull/5733 .

**Comment by stooj** [comment]
Thanks @thoward 😁
