### ISSUE TITLE
Post-migration website tweaks

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#1325]
Some follow-ups:

- [ ] (justinvp) Hook up Purgecss to remove unused CSS classes (#1291)
- [ ] Fix styles used on AWS Crosswalk images to use Tailwind
- [x] Looks like we have both `/image/pulumi.png` and `/social/pulumi.png` used as meta images. We should standardize on `/image/pulumi.png` and update any redirects as appropriate. (#1374)
- [ ] Implement a two-column layout for the docs landing page. Consider implications on search.
- [ ] Follow-up improvements to "On this Page": generate for "Download and Install", add `sticky` positioning

**Comment by lukehoban** [comment]
@cnunciato Anything pressing here?  I'm going to move out of any milestone for now - as we've punted this a lot and nothing seems critical.  But if you want to pull back in or split into specific work feel free.

**Comment by lukehoban** [comment]
Closing as this is quite old.  Will assume we'll reopen specific issue on anything critical here.
