### ISSUE TITLE
Provide in-language examples for Resource Options

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1326]
Our resource options are really powerful features, but not well documented. Just like our other programming model examples (e.g. [.apply](https://www.pulumi.com/docs/reference/programming-model/#apply)) we should provide language-specific examples of their usage. https://www.pulumi.com/docs/reference/programming-model/#resourceoptions

**Comment by bermudezmt** [comment]
@lukehoban can you please provide a bullet list of use cases and code samples? Thank you.
