### ISSUE TITLE
pulumi-stacks provider documentation not referenced from the main Pulumi IaC integration page for ESC

### ISSUE THREAD

**Issue by kallayj** [pulumi/docs#13268]
File: [content/docs/esc/integrations/infrastructure/pulumi-iac/_index.md](https://www.pulumi.com/docs/esc/integrations/infrastructure/pulumi-iac/)

The pulumi-stacks page is in the left sidebar, but this is often collapsed and so would be easy to miss.

**Comment by thoward** [comment]
Thanks for the report @kallayj ! This is a great idea. I added a segment into the page in PR #13291
