### ISSUE TITLE
output must be public

### ISSUE THREAD

**Issue by trondhindenes** [pulumi/docs#13348]
File: [content/docs/iac/concepts/stacks.md](https://www.pulumi.com/docs/iac/concepts/stacks/)

This code:
```
public class MyStack : Stack
{
    public MyStack()
    {
        ...
        this.Url = resource.Url;
    }

    // 'url' is the output name. By default, it would take the property name 'Url'.
    [Output("url")] Output<string> Url { get; set; }
}
```
doesn't produce an output. The output must be made public.

**Comment by thoward** [comment]
Thanks for the report @trondhindenes! We really appreciate the feedback. Fixing that now.
