### ISSUE TITLE
Add note on google_storage_bucket_iam_binding

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/docs#1336]
Actually, `allUsers` is a [special identifier](https://cloud.google.com/storage/docs/json_api/v1/buckets/setIamPolicy) and does not need any prefix like `group:`.
 ```
const binding = new gcp.storage.BucketIAMBinding("member", {
  bucket: config.bucketName,
  members: ["allUsers"],
  role: "roles/storage.objectViewer",
});
```

Maybe you could consider adding it to the documentation, just [here](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/storage/#BucketIAMBinding).

I'm closing this issue myself

_Originally posted by @sebght in https://github.com/pulumi/pulumi-gcp/issues/177#issuecomment-510928342_

**Comment by justinvp** [comment]
Details on the `members` property of `BucketIAMBindingArgs` is missing from https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/storage/#BucketIAMBindingArgs

See https://www.terraform.io/docs/providers/google/r/storage_bucket_iam.html

The docs should include the following:

<img width="843" alt="Screen Shot 2019-07-18 at 9 24 51 AM" src="https://user-images.githubusercontent.com/710598/61474633-e6b17700-a93d-11e9-8ec8-2aa0a5a10216.png">

**Comment by lukehoban** [comment]
Fixed in https://github.com/pulumi/terraform-provider-google-beta/commit/54c1f8e3a8f517ccf08b35a931ae68d0b8d6593f.
