### ISSUE TITLE
Write in-depth guide for securely using Pulumi in CI/CD (credential handling)

### ISSUE THREAD

**Issue by chrsmith** [pulumi/docs#1338]
The topic of how to securely use Pulumi within a CI/CD environment comes up fairly often, as it is actually much more complicated than you'd think. Since to do so securely involves understanding your organization's policies regarding key access and rotation, Pulumi's support for RBAC, and the capabilities of your underlying CI/CD provider.

Here are some rough notes for using AWS and CircleCI, but definitely more a broad and comprehensive guide is needed.

---

## AWS IAM Credentials and AssumeRole

[AWS Best Practices](https://docs.aws.amazon.com/general/latest/gr/aws-access-keys-best-practices.html) recommends the use of short-lived security credentials, “IAM Roles” instead of long-lived IAM User credentials. In essence, you exchange one set of AWS credentials for another. Except the second set of credentials have a built-in expiration date, and may also have a different set of permissions than the first. ([Documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html))

You would configure CircleCI with the credentials of an IAM User that only has permission to “assume role” into an IAM Role, which has the actual permissions necessary to deploy your Pulumi stack. The advantage here is that if the credentials stored on CircleCI are disclosed, they can only grant temporary access to the much more privileged AWS account.

This can be done via the AWS command-line tool, via the [assume-role command](https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html). You’d need to add that to just before you launch `pulumi`, so that the current environment has the IAM Role’s credentials. ([Example](https://github.com/pulumi/pulumi/blob/master/scripts/build-sdk.ps1#L66))

However, even using assume role, you would still need to rotate the initial IAM User credentials. Even though you get better auditing and “blast radius” mitigations using IAM Roles, any compromise would still provide unauthorized access.

## Key Rotation using CircleCI APIs

To facilitate rotating your IAM User credentials stored in CircleCI, you could use the [CircleCI API](https://circleci.com/docs/api/v1-reference/).

Here’s an example Bash script that could be used as part of automating the key rotation: [https://gist.github.com/chrsmith/circleci-envvar-manager.sh](https://gist.github.com/chrsmith/circleci-envvar-manager.sh.).

You could just run that as part of some regular cron job which could use the AWS APIs to create a new IAM credential, update CircleCI projects, and then invalidate the older credentials. ([AWS docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_RotateAccessKey))

Note that while CircleCI’s UI doesn’t differentiate “secret” vs. “non-secret” environment variables like other CI/CD systems, their [Security Features](https://circleci.com/docs/2.0/security/#encryption) documentation states that “All environment variables are encrypted using Hashicorp Vault. Environment variables are encrypted using AES256-GCM96 and are unavailable to CircleCI employees.” So while you would need to trust CircleCI with some of your credentials, it seems like they are taking the appropriate safeguards for your data.

Another way to mitigate accidental disclosure from the build/test process on your CI/CD system is to use immutable, and version-locked build scripts. That’s one of the advantages of moving the complex operations into [CircleCI Orbs](https://circleci.com/docs/2.0/orb-intro/#section=configuration), with the specific versions used being independently reviewed and audited.

**Comment by chrsmith** [comment]
The WIP doc can be found [here](https://docs.google.com/document/d/1mZGzY8U5kNKKpI2nu6jBi5ncvLWS0KphdBRpFOkdsJ4/edit#heading=h.5e1ipv13xlx3), though the current holdup is writing a Pulumi app to automate rotating the AWS IAM credentials. (Since otherwise the doc really just says "you really shouldn't do this, as providing long-lived AWS crews to a 3rd party is very frowned upon".)

**Comment by chrsmith** [comment]
:'(

**Comment by lukehoban** [comment]
We wrote a 3-part blog series - I think that is good for now:
* https://www.pulumi.com/blog/managing-aws-credentials-on-cicd-part-1/
* https://www.pulumi.com/blog/managing-aws-credentials-on-cicd-part-2/
* https://www.pulumi.com/blog/managing-aws-credentials-on-cicd-part-3/
