### ISSUE TITLE
Using Azure CLI

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/docs#1357]
I would probably like to see a page which looks at the whole IaC landscape for Azure users and gives reasonable particularities, pros and cons of each tool. Might be a big chunk, so we need to think how to structure it.

**Comment by lukehoban** [comment]
Not sure by itself this is something we want to tackle directly - and if we did something here - we'd likely need to step back and do something quite significant in re-presenting each cloud platform from first-principles.  For now, I'm going to close this as I'm not sure it's something we would tackle in the current form.
