### ISSUE TITLE
Improve searchability of example services 

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/docs#1358]
It's essential to give users enough examples and make them discoverable. The goal would be more or less so that they pick Azure services that they want, and they finish a Pulumi program that runs those as as quickly as possible.

Examples repo is useful for this. However, it's not always easy to find the right example. The more examples, the better the search we need. One big GitHub repo might not cut it.

**Suggestions/Feedback:**

- Maybe we should make a bootstrapping tool? A user asks - give me Service A, B, and C, - boom - you have a skeleton. Not sure how feasible that is, but sounds like it could get people started more quickly. Alternatively, just a search of examples by service?

- Small things like using constants instead of magic strings are helpful at this stage. People discover the types and see how they are beneficial over textual templates. 
- Focus on good inline docs and error messages.
- Inputs and Outputs are tricky concepts at the stage of discovery, so there should be a decent introduction to the topic with all basic usage scenarios.
- Finding out all the required options is sometimes non-obvious.

**Comment by joeduffy** [comment]
One thing we can consider doing here is creating a "gallery" of sample code coming from our API docs in one place, that's easier to permalink to. The alternative is that we think about this when we create our API docs and just make sure that the result is more easily discoverable, searchable, and linkable.

**Comment by justinvp** [comment]
This is largely covered by the resource oriented docs work (https://github.com/pulumi/docs/issues/2264), so I am going to close this issue. cc @praneetloke
