### ISSUE TITLE
Add an Events listing

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#1364]
To help raise the visibility of Pulumi-related events, we should create an Events listing on the website. Entries would be similar to blog posts, but be located at a different path (e.g, `/events`, or `/blog/events`), and with some additional properties, such as

* `event_date` and time, so announcements can be published in advance
* `registration_url`, for linking to outside websites, like Meetup
* `location`, e.g., "Seattle, WA", and maybe with an address and/or maps link

... and probably some others as well. (cc @aydrian.)

We might also consider publishing these events in a separate RSS feed, since it's easy and offers one more way to subscribe to them.

**Comment by aydrian** [comment]
I vote for not under blog. We should have a start and end date with logic smart enough to know if it's a single day. It would be nice to tag them as sponsorship or presenting, and categorize them as conference, meetup, hackathon, webinar, etc. Maybe have a short description as well. Have location and some kind of url for linking is also good.

**Comment by joeduffy** [comment]
@cnunciato Adding this to M31 for consideration. As part of figuring out our overall 2020 roadmap of conferences and workshops (first 2 weeks of Q1), this would be a good thing to have.

**Comment by joeduffy** [comment]
As part of this, it would also be good to have a place to aggregate webinars, past talks (with transcriptions), etc.

**Comment by zchase** [comment]
Work being done in this PR: https://github.com/pulumi/docs/pull/2318

**Comment by lukehoban** [comment]
Is this done now that #2318 has landed?  If not, what is remaining - and should we open a new issue to track any follow ups?

**Comment by zchase** [comment]
Yup this is done -- Created another issue for follow up items: https://github.com/pulumi/docs/issues/2416
