### ISSUE TITLE
Typo on import documentation, bucketv2

### ISSUE THREAD

**Issue by aaronlidman** [pulumi/docs#13655]
Just letting you know there's a typo on this doc https://www.pulumi.com/docs/iac/adopting-pulumi/import/#how-import-works

`aws:s3/bucketv2:BucketV2` should be `aws:s3/bucketV2:BucketV2` capital V on the first bucketV2

![Image](https://github.com/user-attachments/assets/b7b68672-b029-45b4-9d13-f622e758932f)

**Comment by ericrudder** [comment]
Thanks for reporting [aaronlidman](https://github.com/aaronlidman)
