### ISSUE TITLE
ComponentResource docs need to be updated to explain how to properly use registerOutputs.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/docs#1367]
The docs at https://www.pulumi.com/docs/reference/component-tutorial/ and https://www.pulumi.com/docs/reference/programming-model/#components are incorrect in how they explain how registerOutputs should be used.  It's really only intended to indicate when the component is considered 'finished' by the UI.  There is no need to actually pass any actual values along (except for the main Stack resource).

**Comment by lukehoban** [comment]
We're actually going a bit the other direction with multi-language components work - so I'm inclined not to make any doc change here now - and to instead wait to clean this all up ahead of 3.0 as part of multi-language component documentation push.
