### ISSUE TITLE
Anchor links under "On This Page" don't work

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/docs#1372]
File: [docs/reference/_index.md](https://www.pulumi.com/docs/reference/)

Only "Learning Pulumi" jumps to the right section. This relates to https://github.com/pulumi/docs/issues/927.

**Comment by cnunciato** [comment]
It could be that your viewport is taller than the distance between the anchor target and the bottom of the page, so the browser is attempting to anchor to the right place, but can't get the anchor to the top of the viewport, there isn't enough room:

![](https://cl.ly/d91d56b27e9c/Screen%252520Recording%2525202019-07-16%252520at%25252010.41%252520AM.gif)

**Comment by bermudezmt** [comment]
Very educational -- thank you, @cnunciato . Is this something we should address for atypical viewports or should I close this issue for now?

**Comment by cnunciato** [comment]
I wouldn't -- it's basically expected behavior and not unique to us, so I'd close if you're okay with doing so.
