### ISSUE TITLE
Don't hide the install instructions for alternative platforms

### ISSUE THREAD

**Issue by jestrjk** [pulumi/docs#1394]
File: [docs/quickstart/aws/install-pulumi.md](https://www.pulumi.com/docs/quickstart/aws/install-pulumi/)

When you hide linux instructions for people running Windows Subsystem for Linux (WSL) or WSL2 you are hiding the correct instructions for our platform. 

Your page appears to only display the detected OS instructions, and applies display:none to the rest. Please dont.

**Comment by justinvp** [comment]
Thanks for the issue, @jestrjk! We've heard similar feedback and are planning to add platform selection tabs to the Get Started guide (similar to the language tabs) to allow you to select your platform of choice.

In the meantime, if you click the link to the [detailed installation documentation](https://www.pulumi.com/docs/reference/install/) on [docs/quickstart/aws/install-pulumi.md](https://www.pulumi.com/docs/quickstart/aws/install-pulumi/), you can choose your platform from the drop down:

<img width="803" alt="Screen Shot 2019-07-23 at 9 48 09 AM" src="https://user-images.githubusercontent.com/710598/61730899-32459580-ad2f-11e9-9fd6-076be840ff08.png">

**Comment by joeduffy** [comment]
@justinvp Do you want me to take this one?

**Comment by justinvp** [comment]
@joeduffy, sure! Thanks!
