### ISSUE TITLE
docgen leading to broken links

### ISSUE THREAD

**Issue by chrsmith** [pulumi/docs#1404]
Looking through the Moz's page insights, we are serving broken links from our generated documentation.

TWO BUGS FOR THE PRICE OF ONE!

## Issue 1

Class references in the TypeScript docs like to source code, which will always fail.

For example, on page: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/postgresql/#Database

Clicking “class Database” takes you to https://www.pulumi.com/database.ts#L30. In an ideal world we'd link to https://github.com/pulumi/pulumi-postgresql/branch/master/database.ts or something. But at the very least we shouldn't render the broken link.

## Issue 2

Probably WAI, but hopefully we can fix.

Take a look at the output for this page:
`/content/docs/reference/pkg/nodejs/pulumi/gcp/container/_index.md`

```
The IP address range of the Kubernetes services in this
cluster, in [CIDR](http:en.wikipedia.org/wiki/Classless_Inter-Domain_Routing)
notation (e.g. `1.2.3.4/29`). Service addresses are typically put in the last
`/16` from the container CIDR.
```

Notice that `http:en.wikipedia.org/wiki/Classless_Inter-Domain_Routing` should probably be `http://` and probably even `https://`.

Is this a problem with the underlying docs? Even if so, perhaps its worth adding a quick check to auto fix this on the docgen side? Perhaps there are other instances of `http[s]?:[^/]`?

Part of https://github.com/pulumi/home/issues/514

**Comment by justinvp** [comment]
RE: Issue 2:

This is an issue in `terraform-provider-google`. I've submitted a fix at https://github.com/terraform-providers/terraform-provider-google/pull/4103

**Comment by justinvp** [comment]
Going to close this as Issue 1 is addressed and Issue 2 will be fixed upstream with https://github.com/terraform-providers/terraform-provider-google-beta/pull/977
