### ISSUE TITLE
Browser-specific bugs on the 404 page

### ISSUE THREAD

**Issue by chrsmith** [pulumi/docs#1417]
Our long-standing 404 page with the animated clouds has a couple of problems with it these days. (https://www.pulumi.com/404)

- On Safari, for some reason the top-left cloud flashes for a moment and then disappears. Leading to an odd light ray coming from nowhere.

<img width="1735" alt="image" src="https://user-images.githubusercontent.com/4029847/61574950-0601ee80-aa7b-11e9-9f59-ff51a6dbfb2e.png">

- On Chrome, that "light ray" seems to expand the page document's size. So EPIC scroll bars appear, which definitely doesn't work right.

<img width="190" alt="image" src="https://user-images.githubusercontent.com/4029847/61575012-6c870c80-aa7b-11e9-9f13-9ab660c1bff5.png">

- Finally, while the simple text on the page is nice, we might want to spruce it up ever so slightly if we can think of something that would be an improvement.

**Comment by justinvp** [comment]
We'd also tweaked the colors a bit on https://app.pulumi.com/404, but failed to do the same on the docs site. Would be good if both sites were consistent.
