### ISSUE TITLE
Is Cloud Firestore supported ?

### ISSUE THREAD

**Issue by sebght** [pulumi/docs#1419]
What is the current offer concerning Cloud Firestore integration ?
[Here](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp) _firestore_ stands out as a supported module. However, the [doc](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/firestore/) is clearly empty.

As [TF's doc](https://www.terraform.io/docs/providers/google/r/firestore_index.html) does exist, I suppose that Pulumi also uses this module. Then, it might be good to update the documentation associated 😁

**Comment by stack72** [comment]
Hi @sebght 	

Apologies for this not being in the documentation - on Friday we discovered there was an issue with the Firestore SDK. This has been rectified and we are able to regenerate the SDK for it - which means the documentation will also be available

This new release and it's documentation will be available later today (US time)

If there are any problems then please let me know

Thanks

Paul

**Comment by stack72** [comment]
@sebght https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/firestore/ :)
