### ISSUE TITLE
Instead of single page for module, split into multiple pages

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#1421]
Right now, the module page is a huge dumping ground for all APIs in a module.

Instead, we should consider making the module page more of a landing page that lists all the Resources at the top, followed by Data Sources, and Helpers at the bottom.

Come up with some heuristic and include the ~3-4 types for a resource on the page for each resource, e.g. resources are types that derive from `Resource` (and by extension `CustomResource`), and include their associated `Args` and `State` types on that page.

The nice thing about this is that the examples for a resource will be shown at the top of the page. And this should better help with long tail SEO.

**Comment by lukehoban** [comment]
We may want to hold off on this a little longer and focus on "finishing" the current wave of other overhauls to the API docs before diving into another layer of reorganization.

**Comment by justinvp** [comment]
Going to hold off on this a little longer. We've already made some improvements to the organization/styling on the existing pages (Node.js) and will make some additional refinements on the Python side this milestone. We'll align any additional restructuring with our multi-lang plans, which may help facilitate this.

**Comment by justinvp** [comment]
Replaced by #2263
