### ISSUE TITLE
paul's dig ocean blog preview renders incorrectly

### ISSUE THREAD

**Issue by ericrudder** [pulumi/docs#1422]
![image](https://user-images.githubusercontent.com/8387010/61652988-1928e000-ac6e-11e9-9381-516b3de099b0.png)

the code is shown inline as text on windows/chrome

**Comment by stack72** [comment]
https://github.com/pulumi/docs/pull/1398

Just hasn't been merged yet @ericrudder

**Comment by justinvp** [comment]
This is https://github.com/pulumi/docs/pull/1398 and just needs to be merged.

**Comment by justinvp** [comment]
Fixed by #1398 (will take a few minutes to deploy).
