### ISSUE TITLE
User Guide: Adopting Pulumi

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/docs#1454]
### Problem description

We need a more conceptual doc which can cover the workflows for getting, importing, RemoteStateReference, etc. from a more "workflow" based perspective than raw facts. 

### Suggestions for a fix

YT video and notes

**Comment by lukehoban** [comment]
Blog at https://github.com/pulumi/docs/pull/1556.

Video at https://www.youtube.com/embed/kX_3Wdft0Ms.

These should provide the foundation for a workflow guide in the docs.

**Comment by joeduffy** [comment]
I propose we change this to start with a User Guide, much like the others we have. For instance:

![image](https://user-images.githubusercontent.com/3953235/72192911-37b99980-33bc-11ea-9a09-a32d61d3dd57.png)
