### ISSUE TITLE
Strange wrapping of API text 

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1457]
### Problem description

The API docs seem to have a _hard_ wrap for property descriptive text. This makes it hard to read.

Example from https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/sqs/#Queue-receiveWaitTimeSeconds:

![image](https://user-images.githubusercontent.com/293763/61970751-44733e00-af92-11e9-8f6f-bf6470cd3bdc.png)

**Comment by ericrudder** [comment]
another example at https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/cloudfunctions
