### ISSUE TITLE
Document PULUMI_SKIP_UPDATE_CHECK on install page.

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1473]
### Problem description

Pulumi supports `PULUMI_SKIP_UPDATE_CHECK` to skip checking for new versions but this doesn't appear to be documented anywhere except in the original PR (https://github.com/pulumi/pulumi/pull/2680).

We should document usage of `PULUMI_SKIP_UPDATE_CHECK` at https://pulumi.com/docs/reference/install/ since this is the URL that's referenced in the upgrade message.

```
$ pulumi help
warning: A new version of Pulumi is available. To upgrade from version '0.17.25' to '0.17.26', run
   $ brew upgrade pulumi
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
Pulumi - Cloud Native Infrastructure as Code

To begin working with Pulumi, run the 'pulumi new' command:

    $ pulumi new
...
```

**Comment by bermudezmt** [comment]
Thanks for reporting this, @clstokes . I've addressed via #1489
