### ISSUE TITLE
Pulumi Newsroom is missing coverage

### ISSUE THREAD

**Issue by ericrudder** [pulumi/docs#1474]
### Problem description

Pulumi Newsroom is missing coverage as the last update was in October 2018. For easy upload, a coverage scan from October 2018-July 2019 is in the Google Doc here.

https://docs.google.com/spreadsheets/d/1CtZdFU2I30PF3_e4-snoaLbKPK8TsplQObkaDjSwQdo/edit#gid=0

**Comment by justinvp** [comment]
@bermudezmt is updating this content something you could help with? It would involve adding new `[[coverage]]` items in https://github.com/pulumi/docs/blob/master/data/newsroom.toml
