### ISSUE TITLE
Improve our meta descriptions

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#1475]
At the moment, we rely on Hugo's Content Summaries for most of our `<meta name="description">` tags. These can be quite lengthy and poor (and indeed, Moz flags many/most of them). We could probably make an improvement by reducing `summaryLength` to something more like `30`, rather than its default of `70` -- but even better would be to hand edit these, even if just using `<!--more-->`.

See https://github.com/pulumi/docs/pull/1472#pullrequestreview-268478451 and https://github.com/pulumi/docs/pull/1472#issuecomment-516473456 fore more background.

**Comment by erinhyperplane** [comment]
beat me to it ;) Mark as WIP as i'll come up with a proposal this week for our meta descriptions.

**Comment by erinhyperplane** [comment]
see #1487

**Comment by lukehoban** [comment]
Is this a dupe of #1487?

**Comment by erinhyperplane** [comment]
@lukehoban Yes.
