### ISSUE TITLE
Site doesn't work well on mobile

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#148]
At least on my phone (iPhone 6s), the recent CSS overhaul has made the docs site hard to view on mobile.

It appears the site attempts to adjust for smaller displays below 1290px, but then below 490px, the nav header flows onto two lines, and pushes large portions of content off the screen without any horizontal scroll.  My iPhone has a logical screen width of 375px, so sees the third result below.

**>1290px width**:
<img width="1373" alt="screen shot 2018-03-25 at 10 57 17 am" src="https://user-images.githubusercontent.com/223467/37878287-68a4f608-301b-11e8-933b-bacc91e954df.png">

**<1290px >490px width**:
<img width="930" alt="screen shot 2018-03-25 at 10 57 32 am" src="https://user-images.githubusercontent.com/223467/37878290-6c7a87a2-301b-11e8-855a-c482cc4ddc46.png">

**<490px width**:
<img width="482" alt="screen shot 2018-03-25 at 10 57 50 am" src="https://user-images.githubusercontent.com/223467/37878291-6f5b98e4-301b-11e8-8e36-67a87a569c69.png">

**Comment by joeduffy** [comment]
Reactivating, since we took a few steps back here with the new content and styling updates in the furious march up to launch.  It's actually not terrible, but let's do a quick pass over things.

**Comment by joeduffy** [comment]
For instance, see this tweet

https://twitter.com/komu_wairagu/status/1008752916868620288

![image](https://user-images.githubusercontent.com/3953235/41550529-e35bd088-72dd-11e8-87b7-f46ab3e23ae4.png)

**Comment by justinvp** [comment]
A few other issues remaining:
 - [ ] The search box has a border radius on mobile safari that doesn't look great with the button next to it
 - [ ] The search box width doesn't fit right on small screens
 - [ ] The nav links have a 16px padding on the right in the hamburger menu that should be removed

**Comment by lukehoban** [comment]
Would love to make incremental progress here.  This site is going to be commonly linked to from social media and other places where users are likely to be coming via mobile.

**Comment by joeduffy** [comment]
I am going to close this out. All of the recent work we've done added up to a remarkably good experience IMHO. @lukehoban @justinvp if you know of specific things, please reopen with details.
