### ISSUE TITLE
Add new pages for displaying all press releases and news articles

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/docs#1481]
### Problem description

Consider adding new `/about/press-releases` and `/about/news` pages showing all press releases and news links, that we'd link to underneath the most recent items.

**Comment by justinvp** [comment]
Note: The Linux Journal has shut its doors, so it's very likely any links to this publisher will become broken in the near future. For such broken links, we could keep the content and simply remove the link. Alternatively, if the article is cached in https://archive.org/web/, we could consider linking to it there.

**Comment by lukehoban** [comment]
We do have these at https://www.pulumi.com/about/.  I think that is okay for now and we can revisit this more strategically later if needed.
