### ISSUE TITLE
Getting started script pulumi install script not working

### ISSUE THREAD

**Issue by pixelicous** [pulumi/docs#1484]
### Problem description

I just started with Pulumi, used the following code to install crashes, on 3 different windows machines.
`@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://get.pulumi.com/install.ps1'))" && SET "PATH=%PATH%;%USERPROFILE%\.pulumi\bin"`

Then the last part of the command "SET PATH" doesn't run, as it crashed before.

### Affected product version(s)

Latest (whichever the script downloads)

### Error message

> C:\Users\myuser>@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://get.pulumi.com/install.ps1'))" && SET "PATH=%PATH%;%USERPROFILE%\.pulumi\bin"
> Downloading https://get.pulumi.com/releases/sdk/pulumi-v0.17.27-windows-x64.zip
> Copying Pulumi to C:\Users\myuser\.pulumi\bin
> Pulumi is now installed!
> 
> iex : The variable '$PATH' cannot be retrieved because it has not been set.
> At line:1 char:82
> + ... pe]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('ht ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (PATH:String) [Invoke-Expression], RuntimeException
>     + FullyQualifiedErrorId : VariableIsUndefined,Microsoft.PowerShell.Commands.InvokeExpressionCommand
>

**Comment by ellismg** [comment]
Just to check, @pixelicous are you running this command from a powershell prompt of from cmd.exe prompt?

**Comment by lukehoban** [comment]
Closing as we haven't heard back in some time - definitely interested to hear feedback if others are having problems here.

**Comment by pixelicous** [comment]
@ellismg Running powershell.exe with arguments, so yes i am running it from cmd :)
