### ISSUE TITLE
Stop Using Hugo's `.summary` and replace with `meta_desc` for all pulumi web properties

### ISSUE THREAD

**Issue by erinhyperplane** [pulumi/docs#1487]
### The problem
Currently we are using Hugo to auto generate meta descriptions for our web page, if no `meta_desc` is specified at the time. 
```
{{ if .Params.meta_desc }}
        <meta name="description" content="{{ .Params.meta_desc }}">
        <meta property="og:description" content="{{ .Params.meta_desc }}">
    {{ else if and .IsHome .Site.Params.meta_desc }}
        <meta name="description" content="{{ .Site.Params.meta_desc }}">
        <meta property="og:description" content="{{ .Site.Params.meta_desc }}">
    {{ else if .Summary }}
        <meta name="description" content="{{ .Summary }}">
        <meta property="og:description" content="{{ .Summary }}">
```

This is great way to make sure we always have _some_ meta descriptions, however, i've noticed a few problems: 

- For our blog, because we don't _require_ a `meta_desc` area any more, all blog pages are using Hugo auto-generated meta description, which picks the first 70 words above `<!--more-->`. As a result, most blogs' meta description failed to serve the purpose, and instead become a preview of the article. This is harmful to our SEO, because google largely relies on meta descriptions to judge a site's relevance to a specific search queries, and sometimes even use the `<meta>` tag to create results snippet. 

- For other sub sites, Hugo summary can be very strange sometimes, e.g. 

```
        <meta name="description" content="This page contains detailed instructions on installing Pulumi.

For a streamlined walkthrough of getting started with Pulumi, including installing Pulumi and prerequisites, see the Get Started guide.
 var oses = [ &#34;unknown&#34;, &#34;linux&#34;, &#34;macos&#34;, &#34;windows&#34; ]; function showInstall(os) { // Show the div and select it in the dropdown. var e = document.getElementById(os &#43; &#34;_installation&#34;); if (e) { e.style.display = &#34;block&#34;; var s = document.getElementById(&#34;os&#34;); if (s) { for (var i = 0; i Operating system: (choose one) Linux macOS Windows">
```

- According to Moz, 878 out of 1.5k metadata issues came from "description too long"

![image](https://user-images.githubusercontent.com/38261258/62235937-dc9e6800-b382-11e9-914c-28304ac6a66d.png)

### The Proposal
As part of the effort to improve overall SEO and make the most of out of our great website migration, i suggest us doing the following: 

1. Stop using Hugo's `.summary` across all web properties
2. make `meta_desc` a hard requirement before publishing a blog to ensure blog author will write one meta description. According to Moz, the recommended length for meta description is 55-300 words. 
3. For all the non-blog sites, i'm doing a pass to make sure they all have relevant meta descriptions this week. Once this is done, i don't think we need to change those descriptions unless for SEO testing purposes or other scenarios when we want to make another edit. 

Any feedback for this? 
cc/ @justinvp @joeduffy @chrsmith @cnunciato

**Comment by justinvp** [comment]
+1. Sounds good to me.

**Comment by ericrudder** [comment]
sounds sane ... can we roll these out (in pri order) rather than batching?

**Comment by erinhyperplane** [comment]
@ericrudder I think once we get rid of 
```
   {{ else if .Summary }}
        <meta name="description" content="{{ .Summary }}">
        <meta property="og:description" content="{{ .Summary }}">
```
We'll have to do it in one batch? Not sure but i'll defer this to @justinvp 😛

**Comment by justinvp** [comment]
We can start rolling out custom `meta_desc` on pages now (`meta_desc` takes precedence over `.Summary`) before we get rid of the `{{ else if .Summary }}` block, if we want to start making incremental progress over batching everything into a single PR. Erin, if you'd like to get started with the highest priority pages, go ahead and open a PR (or PRs).

Once all pages have a `meta_desc`, we can remove the `.Summary` block, and add the check to enforce `meta_desc` being set.

**Comment by joeduffy** [comment]
Do we plan to still permit  as a shorthand way of generating the description? It sounds like "no" but I just wanted to explicitly ask.

**Comment by erinhyperplane** [comment]
@joeduffy I would prefer not to - but would like to hear if you have concerns?

**Comment by cnunciato** [comment]
I'll chime in as the contrarian 😇 and say that this strikes me as a little aggressive, at least the bit about failing the build when these descriptions aren't provided. There are plenty of examples both within Pulumi and in the wild of pages with handcrafted `meta description`s that perform "less well" than those whose descriptions were generated algorithmically, and we can easily ratchet back the length of those summaries in a way that'd make Moz (and presumably? Google) happier, to the extent that's part of the problem.  

So I'd personally suggest we begin by considering these descriptions an editorial or marketing best-practice rather than an error case that'd fail a build. I see we're planning to fold them in gradually, but at the same time, I'm also not sure the relevance of these descriptions quite warrants considering them hard requirements across the board. (This itself feels like a hypothesis worth testing, as there are plenty of examples that would seem to disprove it.)

But all that said, I'm happy to "disagree and commit", too. 😄

**Comment by lukehoban** [comment]
Is this "done"? If not, what's remaining?

**Comment by cnunciato** [comment]
I'd like to push one little addition to the blog-post generator for this (to add a placeholder for `meta_desc`), and that ought to do it.
