### ISSUE TITLE
Improved landing pages

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/docs#1492]
### Problem description

- Add nicer intros and/or images (e.g. language and cloud provider icons)
- More visually appealing lists/tables
- Link to relevant content / next steps

- [X] Tutorials
- [X] Pulumi Console
- [X] Guides
- [X] Intro

**Comment by lukehoban** [comment]
@bermudezmt What exactly is this issue tracking?  Which pages does it involve replacing/improving exactly?  

> Add a table with languages as the column headings, and package list as the rows

This is now https://github.com/pulumi/docs/issues/1580.

**Comment by lukehoban** [comment]
This is tracking improving the top level nav pages like:
* https://www.pulumi.com/docs/reference/tutorials/

**Comment by lukehoban** [comment]
@bermudezmt Anything more we're targeting here for "1.0" release?  Should we close this out and open new issues on specific things that we want to do next for landing pages?

**Comment by bermudezmt** [comment]
Working on getting #1644 merged and then we can close this out.

**Comment by lukehoban** [comment]
#1644 was merged, so I'll close this one out.  We still have opportunity for more landing page improvements, but at this point we can open issues for more specific improvements we want to make.
