### ISSUE TITLE
Continue investigation into sitemap coverage

### ISSUE THREAD

**Issue by chrsmith** [pulumi/docs#1508]
There seem to be some missing URLs from the generated sitemap, though I'd need to spend more time understanding the classes of links that are or are not present.

## Repro

Build production website.

```bash
make ensure
HUGO_ENVIRONMENT=production make build
```

Now determine "all links" two ways, by seeing what is referenced in `sitemap.xml` and also by just looking at every `.html` file in the `./public` directory.

**sorted-sitemap-urls.txt**
```bash
cd public

brew install python-yq
cat sitemap.xml \
    | xq --xml-output '.urlset.url[]' \
    | sed 's/<loc>//' \
    | sed 's/<\/loc>.*$//' \
    | sort > sorted-sitemap-urls.txt
```

**sorted-html-file-urls.txt**
```bash
cd public

find . -name "*.html" > all-html-files.txt

cat all-html-files.txt \
    | sed 's/\.//' \
    | sed 's/\/index.html/\//' \
    | sed 's/^/https:\/\/www\.pulumi\.com/' \
    | sort > sorted-html-files.txt
```

Line counts are different.

```
$ cat sorted-html-files.txt | wc -l
    1189
$ cat sorted-sitemap-urls.txt | wc -l
    1089
```

Sample diff output:

```
$ diff sorted-sitemap-urls.txt sorted-html-files.txt
...
1054d1148
< https://www.pulumi.com/docs/search-data/index.json
1073a1168
> https://www.pulumi.com/googlee2ea797459d856b7.html
1074a1170,1172
> https://www.pulumi.com/legal/
> https://www.pulumi.com/migrate/
> https://www.pulumi.com/partner/
```

From the output, files in the diff prefixed with `> ` correspond to an HTML file on disk, but not a URL found in the sitemap.
  - /partner/index.html exists, but isn't referenced in the sitemap.
  - /docs/reference/service/saml-overview/index.html exists, but isn't in the sitemap. (But that is expected, because it is just a redirect to the new page, using a Hugo `alias`.)

I haven't spent much time analyzing the results, but there are some things I'd expect to be in the SiteMap that aren't. (Or perhaps that is by design?)

For example  https://www.pulumi.com/blog/page/2/ has an HTML file on disk, but isn't in the sitemap.

**Comment by ericrudder** [comment]
i think for m26, we really do want to know if this is a "thing" or not ...

**Comment by chrsmith** [comment]
Here's the full diff, with some sorting. Everything seems kosher. Every .html file we render is included in the rendered `sitemap.xml` except:

- paginated list pages. e.g. /blog/page/2. This is unnecessary since all of the specific blog posts are already in the sitemap.
- pages where the front matter has marked them as `private: true`, meaning they were intentionally omitted from the sitemap. (Which appears to be some templates that we aren't using, e.g. `/webinar`.)
- Pages that were generated as part of an alias/redirect. For example `/crosswalk` isn't in the sitemap, since it redirects to `/crosswalk/aws` (which _is_ in the sitemap).

So despite some concerns that our sitemap was leading to some content not being picked up by search engines, everything looks to be working as intended.
