### ISSUE TITLE
Document secrets

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/docs#1509]
### Problem description
- I had trouble finding the information that I needed: Export unencrypted checkpoint, id support, StackReference, stack outputs

### Affected product version(s)
1.0

**Comment by lukehoban** [comment]
@ellismg Could you provide the bullet list of key things we need to cover for fully documenting secrets?

**Comment by joeduffy** [comment]
I plan to document the basics in https://github.com/pulumi/docs/issues/1603. But I just realized that this covers a more complete set of topics (unencrypting checkpoints, StackReference, etc).

**Comment by ellismg** [comment]
Fixed by #1619
