### ISSUE TITLE
API docs: README header IDs conflict with API header IDs

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#1519]
Now that we're emitting `README.md` content above API docs, some docs now have conflicting header IDs.

For example:

https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/cloudwatch/

The cloudwatch [`README.md`](https://github.com/pulumi/pulumi-awsx/blob/5ac4a8c74a3e6b48f7ca0e5e48c85217fb0b88ab/nodejs/awsx/cloudwatch/README.md) has a "Metrics" `h2` which gets an auto id of "metrics", but lower in the page there is a header for the `metrics` module (aside: "module" should be "namespace"), which also has an id of "metrics". Both offer anchor links, but clicking either will always go to the first id in the page, which is the "Metrics" heading from the README.

**Comment by susanev** [comment]
@justinvp is this still an issue? im not seeing a repeated metrics header

**Comment by susanev** [comment]
im going to close this, pls reopened if its still an issue.
