### ISSUE TITLE
Link from the blog to Get Started

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#1521]
Our blog could use a clear call to action inviting readers to try Pulumi. 

A new button in the sidebar, and/or a change to the sign-up button in the header (e.g., to GET STARTED), might work well for this purpose.

**Comment by lukehoban** [comment]
Looks like we already did this?

![Screen Shot 2019-08-19 at 3 53 40 PM](https://user-images.githubusercontent.com/223467/63304873-8cd40200-c299-11e9-9dcb-d23ff4ad030b.png)
