### ISSUE TITLE
Document our security vulnerability and announcement process

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#1523]
We should have a page much like https://aws.amazon.com/security/vulnerability-reporting/, including a link to our security bulletins like https://aws.amazon.com/security/security-bulletins/.

For now, we just use our blog for this but should at least have a dedicated tag -- and may want to revisit this and use a separate page in the docs website (with a distinct RSS feed).

We also post to our Community Slack #announcements channel, which should be documented as an official procedure.

**Comment by joeduffy** [comment]
@clstokes, @ericrudder suggested you pick this one up.

**Comment by lukehoban** [comment]
This was addressed in https://github.com/pulumi/docs/pull/1730.
