### ISSUE TITLE
Listing all function overloads is unusable when there are many

### ISSUE THREAD

**Issue by redbaron** [pulumi/docs#1525]
File: [docs/reference/pkg/nodejs/pulumi/kubernetes/yaml/_index.md](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/kubernetes/yaml/)

**Comment by lukehoban** [comment]
We should consider for docs generation purposes limiting the number of overloads to 10 or something like that - and showing `...` with a link to sources.
