### ISSUE TITLE
Improve Docker Hub READMEs

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#1529]
The docs we expose on Docker Hub for [pulumi/actions](https://hub.docker.com/r/pulumi/actions) and [pulumi/pulumi](https://hub.docker.com/r/pulumi/pulumi) are just duplications of the pulumi/pulumi README. Instead, we should present container-specific usage documentation (and appropriate links to related Pulumi resources) for each of these.

**Comment by lukehoban** [comment]
I believe this is https://github.com/pulumi/pulumi/issues/2432.

**Comment by cnunciato** [comment]
Updated docs here: https://hub.docker.com/r/pulumi/pulumi

**Comment by lukehoban** [comment]
These are good now.
