### ISSUE TITLE
Update GitHub Actions docs and examples

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#1533]
With the [deprecation of GitHub Action's support for HCL](https://developer.github.com/actions/), we'll need to update our examples to use YAML rather than HCL:

* [x] [GitHub Actions docs](https://www.pulumi.com/docs/console/continuous-delivery/github-actions/)
* [x] [GitHub Actions blog post](https://www.pulumi.com/blog/continuous-delivery-to-any-cloud-using-github-actions-and-pulumi/)
* [x] [pulumi/actions workflow examples](https://github.com/pulumi/actions/tree/master/examples) and [README](https://github.com/pulumi/actions/tree/master/README.md)
* [x] [pulumi/actions repo](https://hub.docker.com/r/pulumi/actions) on Docker Hub

Looks like support for HCL will be dropped Sept. 30.

**Comment by cnunciato** [comment]
Looks like before we can use the new syntax in the `pulumi` org, we'll need to [wait for GitHub enable](https://help.github.com/en/articles/about-github-actions#migrating-github-actions-from-hcl-to-yaml-syntax) the new syntax on our account:

> If you participated in the limited public beta and created workflows with the HCL syntax GitHub Actions, you will need to upgrade to the new limited public beta that uses YAML syntax. When your repository is eligible to upgrade, you'll see an invitation in your repository. You must accept the invitation before you can use the new limited public beta.

**Comment by joeduffy** [comment]
> we'll need to wait for GitHub enable the new syntax on our account

I just did this for my own repo. It was nearly instantaneous, fwiw.
