### ISSUE TITLE
Necessary information gets stripped from API documentation

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1534]
The docs for `core.v1.Service.get(...)` are unclear because information from the code documentation is being stripped as a part of the docs generation. Given the nature of the issue it's likely affecting many other functions too.

See the original docs at https://github.com/pulumi/pulumi-kubernetes/blob/1853784b6b4235553c18872d6e11c3026870356e/sdk/nodejs/core/v1/Service.ts#L49-L53

At https://pulumi.io/reference/pkg/nodejs/pulumi/kubernetes/core/v1/#Service-get this becomes the below description (with wrapping added):
```
Get the state of an existing Service resource, as identified by id. 
Typically this ID is of the form /; if is omitted, then (per 
Kubernetes convention) the ID becomes default/.
```

Note specifically that `<namespace>/<name>` becomes `/` in the formatted docs. The full value should be preserved in the docs.

**Comment by praneetloke** [comment]
Reopened because while the original fix worked for the Kubernetes package and that's all that was regenerated with the fix, it caused issues in other TF-based packages.
