### ISSUE TITLE
Update Programming Model 

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/docs#1540]
### Problem description

- [x] StackReference
- [x] Update `invoke` to use `sync`
- [x] Check for anything not covered 
### Affected product version(s)
1.0

**Comment by lukehoban** [comment]
Let's add these to https://www.pulumi.com/docs/reference/programming-model/.

**Comment by lukehoban** [comment]
Closing this out as there is no known gaps remaining.  We can open targetted new issue for specific things.
