### ISSUE TITLE
More/better troubleshooting docs

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#1554]
We should document what to do to try and debug/diagnose issues with the `pulumi` CLI:
1. `--logtostderr -v=9 2> out.txt`
2. `--debug`
3. `TF_LOG=DEBUG`
4. Others?

Ideally we add these to https://www.pulumi.com/docs/reference/troubleshooting/.

**Comment by clstokes** [comment]
Ideas for other values/data to gather at https://github.com/pulumi/pulumi/issues/2715.

**Comment by lukehoban** [comment]
These are all now on https://www.pulumi.com/docs/troubleshooting/.
