### ISSUE TITLE
Make search great

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#1558]
Search could be soo *much* better!

**Comment by justinvp** [comment]
Before proceeding with any work here, I'll check to see how much search is used currently. We may want to consider simply removing search from the docs site (for now) or only working on a small number of targeted improvements than a larger investment for the time being.

**Comment by justinvp** [comment]
The plan of record is to setup an Elasticsearch cluster which will also serve as a good example and blog post (as opposed to using something like Algolia).

**Comment by ringods** [comment]
My $.02:

- search only within the documentation of a single provider. E.g, if I have the API reference of `pulumi-kubernetes` already open, entering `Ingress` should only search within the `pulumi-kubernetes` docs.
- search only within the documentation of the selected language. I'm mainly a TypeScript user in combination with Pulumi. Search for a concept should not return all the results for every language, e.g. `Ingress` links to the TypeScript page, the Python page, ...

**Comment by mikhailshilkov** [comment]
Now when we have better resource docs, I think it's time to give search some love.

I remember basically giving up on search a few times.


It worked now, but I clicked away to the email while it was running. Now when I search for the second time, it takes ~10 seconds before I hear back. Also, this result is totally useless:

![image](https://user-images.githubusercontent.com/1454008/79841472-c4aac080-83b7-11ea-9a7f-cccef464fb93.png)

Ideally, I would see:
- A resource page
- An example

CosmosDB is better but still lots of noise:

![image](https://user-images.githubusercontent.com/1454008/79841511-d724fa00-83b7-11ea-8926-dceb0318b3d2.png)

I'd say we must invest in a great search capability to match our resource docs.

**Comment by justinvp** [comment]
Totally agree. When we originally added search before public launch, we had a small amount of content in our Jekyll-based docs site. Since then, the amount of content has increased considerably: we've added Python API docs, added API docs for lots of other providers, merged the www/docs/blog sites together, generated tutorials, added a bunch more content, and added resource docs, among other things. All the while search has languished, and has not kept up with these changes.

**Comment by susanev** [comment]
closing in favor of #4642
