### ISSUE TITLE
NodePoolArgs["nodeConfig"] optional properties are shown as required

### ISSUE THREAD

**Issue by redbaron** [pulumi/docs#1578]
Properties of NodePoolArgs["nodeConfig"]   are documented as required (
https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/container/#NodePoolArgs-nodeConfig) , but actually they are optional in the code.

File: [docs/reference/pkg/nodejs/pulumi/gcp/container/_index.md](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/container/)

**Comment by lukehoban** [comment]
This was fixed in https://github.com/pulumi/pulumi-gcp/pull/198/files?file-filters%5B%5D=.json&file-filters%5B%5D=.ts#diff-6d54ef2b89d2ddc208fc0a12f1683e0bR1370 (which will be rolled out to docs site along with the next release of the packages).
