### ISSUE TITLE
API docs landing page

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#1580]
Today, we list each package in the TOC under top-level Node.js and Python items, which really bifurcates the APIs between Node.js vs Python:

<img width="226" alt="Screen Shot 2019-08-19 at 9 14 27 AM" src="https://user-images.githubusercontent.com/710598/63281525-bf620880-c261-11e9-9e99-7169ed45ae37.png">

Instead, we'll stop showing these packages in the TOC (#831) and add a single landing page for the API Reference, with lang chooser at the top of the page. This landing page will better present our various packages, e.g. under a AWS heading it will list, aws, awsx, and eks packages.

**Comment by lukehoban** [comment]
Is it the case that both this and the new TOC overall kind of depend on the breadcrumbs as a way to know where you are when you are in these pages that aren’t listed in the TOC?

**Comment by justinvp** [comment]
> Is it the case that both this and the new TOC overall kind of depend on the breadcrumbs as a way to know where you are when you are in these pages that aren’t listed in the TOC?

Yes.
