### ISSUE TITLE
Package overview for pulumi/pulumi needs to be better

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#1584]
The content currently being included here should be replaced with useful and appropriate content for this context:

https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/
https://www.pulumi.com/docs/reference/pkg/python/pulumi/

**Comment by lukehoban** [comment]
We should consider aligning with the style of https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/.

**Comment by joeduffy** [comment]
@lukehoban , this should be tagged `feature/q3`, right?

**Comment by lukehoban** [comment]
Closing out to track as part of #1585.
