### ISSUE TITLE
Missing package overviews for 1.0 APIs

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#1585]
The package overview included in the JavaScript docs for AWS and Azure is missing from the Python docs for AWS/Azure and from both Python and JavaScript docs for GCP/Kubernetes.

**Comment by lukehoban** [comment]
Missing:
* https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/
* https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/kubernetes/
* https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azuread/
* https://www.pulumi.com/docs/reference/pkg/python/pulumi_aws/
* https://www.pulumi.com/docs/reference/pkg/python/pulumi_azure/
* https://www.pulumi.com/docs/reference/pkg/python/pulumi_azuread/
* https://www.pulumi.com/docs/reference/pkg/python/pulumi_gcp/
* https://www.pulumi.com/docs/reference/pkg/python/pulumi_kubernetes/

Present:
* https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/
* https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azure/

**Comment by joeduffy** [comment]
@lukehoban , this should be tagged `feature/q3`, right?

**Comment by geekofalltrades** [comment]
Are #1901 and #1623 duplicates of this?

**Comment by lukehoban** [comment]
> Are #1901 and #1623 duplicates of this

I don’t think so - this is about a README that gets added to the top of the package overview page - that should what API docs are actually included.

**Comment by susanev** [comment]
@lukehoban is this still relevant?

**Comment by stack72** [comment]
This can be closed IMO - it's related to Pulumi 1.0
