### ISSUE TITLE
Add badges and Get Started CTAs to repos

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#1598]
- [x] Add the same badges that `pulumi/pulumi` has
- [x] Add a "NEW USER" CTA button floating to upper-right

**Comment by joeduffy** [comment]
Assigning to @bermudezmt  -- we discussed, but we won't block the release on this.

**Comment by bermudezmt** [comment]
@joeduffy Here's my PR for `pulumi-azure`: https://github.com/pulumi/pulumi-azure/pull/342

If that looks good, I can create similar ones for AWS, GCP, and Kubernetes.

**Comment by joeduffy** [comment]
Looks great!

**Comment by bermudezmt** [comment]
I added the badges to the PRs that are still open: 
- https://github.com/pulumi/pulumi-aws/pull/724
- https://github.com/pulumi/pulumi-kubernetes/pull/773
- https://github.com/pulumi/pulumi-gcp/pull/207/

**Comment by bermudezmt** [comment]
This has been done for AWS, Azure, Kubernetes, and GCP. I haven't done an in-depth review of all the READMEs so I renamed the issue title. We can discuss the follow-up work later.
