### ISSUE TITLE
Cloud Run service documentation is nearly non-existent

### ISSUE THREAD

**Issue by nesl247** [pulumi/docs#1611]
### Problem description
On https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/cloudrun/#Service, the documentation is nearly non-existent. While we have the structure required, no examples are given, no information on what possible values to give are there, etc. For example, what are the possible values for `servingState`?

**Comment by leezen** [comment]
Thanks for the feedback on the documentation. We'll look into how we can surface more data about the fields. Regarding general information about what the structure, you may find the following references helpful: https://github.com/knative/docs/blob/master/docs/serving/spec/knative-api-specification-1.0.md and https://cloud.google.com/run/docs/reference/rest/v1/RevisionTemplate

The specific servingState field is actually a deprecated field at this point.

**Comment by nesl247** [comment]
I'm happy to either leave this open or close it, as we no longer use cloud run ourselves and have no need for this.
