### ISSUE TITLE
Expand organizations page

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1612]
### Problem description

The organizations page at https://www.pulumi.com/docs/console/accounts/organizations/ could use some more detail on the _value_ of using organizations in the Pulumi Console (collaboration, visibility, RBAC, etc). We should also add the Atlassian (and email?) identity options.

**Comment by bermudezmt** [comment]
I believe this has been addressed via #1616, which is a general rework of the Console section in the docs.
