### ISSUE TITLE
Improve instructions on Python installation

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/docs#1622]
Additional notes:

`pip` isn't always installed by default. For example, after `apt-get install python3.6`, I still had to run `apt-get install python3-pip` on Ubuntu.

Also, our instructions assume you've installed `virtualenv`. I don't think that's ever installed by default. You will need to run `pip3 install virtualenv` (we should list in instructions).

_Originally posted by @joeduffy in https://github.com/pulumi/docs/issues/1178#issuecomment-502397282_

**Comment by sepich** [comment]
> pip3 install virtualenv
> virtualenv -p python3 venv

Please do not do this. Correct way to create virtualenv in python3 is:
`python3 -m venv venv`
(last argument is directory name to be created)

**Comment by justinvp** [comment]
No longer relevant
