### ISSUE TITLE
Python APIs that are in the root of the package (not in a module) are missing from the docs

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#1623]
For example, the [`get_ami`](https://github.com/pulumi/pulumi-aws/blob/840379488191484649ae996d75ac884afc1cc9d5/sdk/python/pulumi_aws/get_ami.py#L246) data source function in `pulumi_aws` isn't documented anywhere, because it lives in the root of the package (i.e. isn't in a module).

**Comment by geekofalltrades** [comment]
See also #1901 .

**Comment by leezen** [comment]
This also appears to affect `pulumi/pulumi` itself for things like https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/asset.py

**Comment by komalali** [comment]
This should no longer be an issue once https://github.com/pulumi/docs/issues/4071 is complete.

**Comment by stack72** [comment]
Closing this out as we don't have these python docs anymore
