### ISSUE TITLE
Numbered lists not rendered properly

### ISSUE THREAD

**Issue by lblackstone** [pulumi/docs#1629]
### Problem description

Numbered lists are rendered as normal text, and don't look very good in the API reference docs:
![Screen Shot 2019-08-27 at 9 30 20 AM](https://user-images.githubusercontent.com/9253463/63785466-a2ef4d00-c8ad-11e9-8894-b256ed12ca48.png)

Here are the relevant SDK docs, which render properly in my IDE:

https://github.com/pulumi/pulumi-kubernetes/blob/c0f3522137d7298758794512351c8e946c690cb5/sdk/nodejs/apps/v1/Deployment.ts#L17-L28

![Screen Shot 2019-08-27 at 9 33 40 AM](https://user-images.githubusercontent.com/9253463/63785573-c87c5680-c8ad-11e9-8799-658bf43d09cb.png)

**Comment by justinvp** [comment]
Hugo is finicky about rendering these and requires a blank line before the start of a list. I suspect if a blank line was added in the doc comment, it'd render correctly in the docs. Would need to verify.

**Comment by lblackstone** [comment]
Sweet, that fixed it!
