### ISSUE TITLE
Malformed code fence

### ISSUE THREAD

**Issue by loic-sharma** [pulumi/docs#1636]
File: [docs/tutorials/azure/azure-ts-appservice-springboot.md](https://www.pulumi.com/docs/tutorials/azure/azure-ts-appservice-springboot/)

This section has a malformed code fence: https://www.pulumi.com/docs/tutorials/azure/azure-ts-appservice-springboot/#running-the-app

![image](https://user-images.githubusercontent.com/737941/63884072-60e80900-c98a-11e9-9ce6-08395756e634.png)

**Comment by justinvp** [comment]
I haven't had a chance to verify, but there is a trailing space after the ```, which is likely throwing off Hugo's markdown renderer.
