### ISSUE TITLE
Update the AWS EC2 tutorial to be region and ami agnostic

### ISSUE THREAD

**Issue by danfhernandez** [pulumi/docs#1656]
### Problem description

The AWS EC2 Linux WebServer Instance tutorial is us-east-1 and specific to ami-0ff8a91507f77f867 (https://www.pulumi.com/docs/tutorials/aws/ec2-webserver/)

### Suggestions for a fix

Update the tutorial to be region and ami agnostic using datasources.

**Comment by stack72** [comment]
Closed via #1701
