### ISSUE TITLE
Navigation bar hides headings via anchors

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1709]
Can we offset the anchor links for Resources (and other) headings in our SDK docs?

When I click one of the resource links on our API pages, I'm taken to the resource, but it's heading is hidden underneath the `nav` element and not immediately obvious that I was taken to the resource.

Example for https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/eks/#ServiceRole:
![Screen Recording 2019-09-09 at 16 04 00 2019-09-09 16_05_16](https://user-images.githubusercontent.com/293763/64572314-af4abf80-d31b-11e9-837c-090e6cc61e7b.gif)

**Comment by justinvp** [comment]
The simple fix would be to stop fixing the nav bar at the top. Is that really needed?

**Comment by clstokes** [comment]
In my opinion, no, it's not needed. @joeduffy ?

**Comment by joeduffy** [comment]
I would like to keep it anchored. The primary goal is to keep the CTA visible at all times. A number of other exemplar blogs do this and was an explicit tip from marketing folks we've spoken to.

**Comment by joeduffy** [comment]
Here is an example of a site that handles this gracefully: https://www.confluent.io/blog/kafka-rebalance-protocol-static-membership#opt-into-static-membership.
