### ISSUE TITLE
Last step results in "Connection refused" errors

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/docs#1710]
File: [docs/tutorials/aws/ec2-webserver.md](https://www.pulumi.com/docs/tutorials/aws/ec2-webserver/)

curl $(pulumi stack output publicHostName)
Hello, World!

------

Example Output:
```
curl: (7) Failed to connect to ec2-3-87-190-213.compute-1.amazonaws.com port 80: Connection refused

```

**Comment by bermudezmt** [comment]
User error - still need to make that section of the tutorial a bit clearer.

**Comment by simanacci** [comment]
The error occurs when you fail to add this line.

> user_data=user_data, # <-- ADD THIS LINE
