### ISSUE TITLE
Clarify the information about api.pulumi.com vs. app.pulumi.com and what each is for

### ISSUE THREAD

**Issue by praneetloke** [pulumi/docs#1718]
File: [docs/reference/cli/pulumi_login.md](https://www.pulumi.com/docs/reference/cli/pulumi_login/)

The page says `By default, this will log into app.pulumi.com ...`, however, it isn't made clear to the user that what that means is that the CLI will use the backend at `api.pulumi.com`, which is basically the user account at `app.pulumi.com`, since `app` is the Console UI for `api`.

**Comment by lukehoban** [comment]
FWIW - we have now standardized on calling this the "Pulumi service backend".  I suspect we should use that terminology in the CLI docs too.  Note also that this needs to be fixed in `pulumi/pulumi` - the CLI docs are autogenerated from CLI help text.
