### ISSUE TITLE
Reduce the versions listed on the Available Versions page

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#1724]
We currently list a ton of releases on https://www.pulumi.com/docs/get-started/install/versions/ going back to 0.12.2.

Let's reconsider the list now that we've released 1.0. Should we pair it down? Only list 1.0 and above? Or ...?

@joeduffy, @lukehoban, any thoughts?

<img width="513" alt="Screen Shot 2019-09-11 at 4 03 49 PM" src="https://user-images.githubusercontent.com/710598/64741526-c02b3a80-d4ad-11e9-9d2c-83d4d122cf5d.png">

**Comment by lukehoban** [comment]
Honestly - it's kinda nice that we list all the old version here - to give the project a substantial sense of history.  Even a year on - this page doesn't feel particularly "overwhleming".  I'd be fine leaving this as is for the foreseeable future. Going to close for now - and I'm sure we'll reopen a discussion on this in the future if/when we consider removing old versions from public download access.
