### ISSUE TITLE
Formatting broken on Slackbot tutorial

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1757]
https://www.pulumi.com/docs/tutorials/aws/aws-ts-slackbot/

![image](https://user-images.githubusercontent.com/293763/65110879-b793a200-d98e-11e9-9edf-ad436d6829e2.png)

**Comment by justinvp** [comment]
Hugo's markdown renderer is super finicky (with code blocks within lists especially). When I was porting the site from Jekyll to Hugo, I had to massage some of our content to get it to render correctly.
