### ISSUE TITLE
Documentation should include "Basic" as a valid SKU for Azure Search Service

### ISSUE THREAD

**Issue by xtellurian** [pulumi/docs#1773]
File: [docs/reference/pkg/nodejs/pulumi/azure/search/_index.md](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azure/search/)

## Azure Search Docs

Current docs say:

> Valid values are free and standard

However, ['basic' is also valid. ](https://docs.microsoft.com/en-au/azure/search/search-sku-tier) The functionality already exists, but the documentation needs to be updated.

**Comment by stack72** [comment]
Hi @xtellurian 

You are indeed correct here - I have just pushed a PR to the upstream terraform provider which we use to generate our documentation

Once that PR has been merged, this will make it's way to our site

Paul

https://github.com/terraform-providers/terraform-provider-azurerm/pull/4406
