### ISSUE TITLE
Team Page Update Request - Add Sophia Parafina

### ISSUE THREAD

**Issue by freddy-hernandez** [pulumi/docs#1797]
Please add Sophia Parafina to our team page.
Technical Marketing Manager

https://www.linkedin.com/in/sophiaparafina/
https://github.com/spara
https://twitter.com/spara?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
![Sophia Parafina Headshot](https://user-images.githubusercontent.com/49878263/65905067-b130fd00-e374-11e9-8934-a8643bc87240.jpeg)

**Comment by justinvp** [comment]
Fixed by #1798
