### ISSUE TITLE
Deliver KtPW, KX and Cloud Query Tools

### ISSUE THREAD

**Issue by metral** [pulumi/docs#1827]
### Problem description

This is an issue for actively tracking the work streams on KtPW, KX, and the Cloud Query Tooling.

Expect the lists to evolve and for separate issues to stem from each list to properly track them in milestones.

- KtPW repo: https://github.com/pulumi/docs
- KX repo: https://github.com/pulumi/kx
- Ops: Defer to @hausdorff 

Outline 

(The anchor links don't seem to work in GH issues.)

- [1) KtPW](#1-ktpw)
  * [Code:](#code)
    + [General](#general)
    + [Cloud / IaaS Stacks](#cloud--iaas-stacks)
      - [Identity](#identity)
      - [Networking](#networking)
      - [Storage](#storage)
    + [Kubernetes Stacks](#kubernetes-stacks)
      - [Cluster Configuration](#cluster-configuration)
      - [Cluster Services](#cluster-services)
      - [App Services](#app-services)
      - [Slack Bot App](#slack-bot-app)
  * [Docs:](#docs)
    + [Introduction](#introduction)
    + [Cloud / IaaS Stacks](#cloud--iaas-stacks-1)
      - [Identity](#identity-1)
      - [Networking](#networking-1)
      - [Storage](#storage-1)
    + [Kubernetes Stacks](#kubernetes-stacks-1)
      - [Cluster Configuration](#cluster-configuration-1)
      - [Cluster Services](#cluster-services-1)
      - [App Services](#app-services-1)
      - [Slack Bot App](#slack-bot-app-1)
- [2) KX](#2-kx)
- [3) Cloud Query Tooling](#3-cloud-query-tooling)

---

# 1) KtPW

### General

- [x] Move the [KtPW repo](https://github.com/pulumi/kubernetes-the-prod-way) into this `pulumi/docs` repo. @metral 
- [ ] [Re-enable broken links for the ktpw in `pulumi/docs`](https://github.com/pulumi/docs/issues/1827#issuecomment-539746176)

#### Identity

AWS
- [ ] Integrate [KtPW: AWS Identity](https://github.com/pulumi/kubernetes-the-prod-way/blob/master/docs/02-identity.md) code into the stacks below. @metral
- [ ] Create Pulumi unit tests / gated deployments for **AWS.Identity** @lblackstone 

GCP
- [ ] Create Pulumi code for **GCP.Identity** (TBD by time available)
- [ ] Create Pulumi unit tests / gated deployments for **GCP.Identity** (TBD by time available)

Azure
- [ ] Create Pulumi code for **Azure.Identity** (TBD by time available)
- [ ] Create Pulumi unit tests / gated deployments for **Identity.Azure** (TBD by time available)

#### Networking

AWS
- [ ] Create Pulumi code provisioning networking for **AWS.Networking** @metral
- [ ] Create Pulumi unit tests / gated deployments for **AWS.Networking** @lblackstone

GCP
- [ ] Create Pulumi code for **GCP.Networking** (TBD by time available)
- [ ] Create Pulumi unit tests / gated deployments for **GCP.Networking** (TBD by time available)

Azure
- [ ] Create Pulumi code for **Azure.Networking** (TBD by time available)
- [ ] Create Pulumi unit tests / gated deployments for **Azure.Networking** (TBD by time available)

#### Storage

AWS
- [ ] Create Pulumi code provisioning storage for **AWS.Storage**: Aurora DBaaS @metral @lblackstone
- [ ] Create Pulumi unit tests / gated deployments for **AWS.Storage** Storage @lblackstone

GCP
- [ ] Create Pulumi code provisioning storage for **GCP.Storage**: Cloud SQL @metral @lblackstone (TBD by time available)
- [ ] Create Pulumi unit tests / gated deployments for **GCP.Storage** Storage (TBD by time available)

Azure
- [ ] Create Pulumi unit tests / gated deployments for **Azure.Storage** (TBD by time available)
- [ ] Create Pulumi code provisioning storage for **Azure.Storage**: CosmosDB @metral @lblackstone (TBD by time available)

Existing work:

-  [AWS RDS (Aurora or Postgres)](https://github.com/pulumi/examples/blob/master/aws-ts-airflow/index.ts#L30-L45)
- [Azure Cosmos DB](https://github.com/pulumi/examples/blob/master/azure-ts-cosmosapp-component/cosmosApp.ts)

#### Cluster Configuration

Code focused on show casing production settings and configuration for k8s cluster-based services.

  - [ ] Merge best of EKS cluster stacks in KtPW ([KtPW: Provisioning Environments](https://github.com/pulumi/kubernetes-the-prod-way/blob/master/docs/03-infrastructure.md)) and KX examples ([KX: Multi-stack architecture](https://github.com/pulumi/kx/tree/master/examples)). @metral 
- [ ] Create stack using Private Networking @metral
- [ ] Create stack using Private Control Plane / Endpoint @metral
- [ ] Create stack using proper Cluster Configuration @metral
- [ ] Create stack using NodeGroups @metral
- [ ] Create stack using RBAC @metral
- [ ] Create stack using Namespaces @metral
- [ ] Create stack using Default Namespace Quotas (TBD by time available) @metral
- [ ] Create stack using Default PodSecurityPolicies (TBD by time available) @metral

#### Cluster Services

Code focused on show casing production settings and configuration for k8s cluster-based services.

- [ ] Logs: `fluentd-cloudwatch`
  - Existing work: Mike has a native Pulumi port in a downstream repo that is better than the current Helm implementation in KX.
- [ ] Pod RBAC: [`kube2iam`](https://github.com/jtblin/kube2iam)
  - Existing work: Mike has a native Pulumi port in a downstream repo that is better than the current Helm implementation in KX.

#### App Services

Code focused on show casing production settings and configuration for k8s app-based services.

- [ ] Ingress Controller: nginx-ingress-controller @metral
  - [Existing work](https://github.com/pulumi/examples/blob/master/aws-ts-eks-migrate-nodegroups/nginx.ts)
- [ ] DNS: external-dns @metral
  - [Existing work](https://github.com/pulumi/kx/tree/master/nodejs/kx/apps/external-dns)
- [ ] TLS Certificates: cert-manager @metral

#### Slack Bot App

Code focused on show casing production settings and configuration for k8s resources to compose the Slack Bot App.

- [ ] Create SlackBot Example App @lblackstone @hausdorff (alexbot code?)
  - Uses k8s resources: Deployment, Service, ConfigMaps, Secrets, Ingress
- [ ] Create / Use **[KX.ServiceDeployment](https://github.com/pulumi/examples/blob/master/kubernetes-ts-guestbook/components/k8sjs.ts)**
- [ ] Create / Use **[KX.DockerSecret](https://github.com/pulumi/kx/blob/master/nodejs/kx/docker-secret.ts)** for private registry container image

## Docs:

Crosswalk for Kubernetes - Running Kubernetes in Production in the style of [Crosswalk for AWS](https://www.pulumi.com/docs/guides/crosswalk/aws/).

This work **requires** that the KtPW consolidation work above in [KtPW.General](#General) is completed before merging PRs, as to get the location of code & docs situated first.

### Introduction

- [ ] Review content and narrative in KtPW [README](https://github.com/pulumi/kubernetes-the-prod-way/blob/master/README.md) @spara @hausdorff 
- [ ] Review content and narrative in KtPW [Architecture](https://github.com/pulumi/kubernetes-the-prod-way/blob/master/docs/01-architecture.md) @metral 

#### Identity

Content focused on creating new IAM or using existing IAM.

- [ ] Review content and narrative in **Identity** README @spara @hausdorff 
- [ ] Review content and narrative in **AWS.Identity** README @spara @hausdorff
- [ ] Create **GCP.Identity** README @spara @hausdorff  (TBD by time available)
- [ ] Create **Azure.Identity** README @spara @hausdorff (TBD by time available)

#### Networking

Content focused on creating new VPC/Subnets etc. or using existing VPC/Subnets etc.

- [ ] Create **Networking** README @spara @hausdorff 
- [ ] Create **AWS.Networking** README@spara @hausdorff  
- [ ] Create **GCP.Networking** README @spara @hausdorff  (TBD by time available)
- [ ] Create **Azure.Networking** README @spara @hausdorff (TBD by time available)

Existing work to leverage:
- [AWS Networking](https://github.com/pulumi/pulumi-eks/blob/metral/prod-k8s-guides/docs/vpc.md) (Outdated but a start nevertheless)

#### Storage

Content focused on how to set up a DBaaS in each provider.

- [ ] Create **Storage** README @spara @hausdorff 
- [ ] Create **AWS.Storage** README @spara @hausdorff  
- [ ] Create **GCP.Storage** README @spara @hausdorff  (TBD by time available)
- [ ] Create **Azure.Storage** README @spara @hausdorff (TBD by time available)

#### Cluster Configuration

Content focused on show casing production settings and configuration for k8s clusters.

- [ ] Create **Cluster Configuration** README @spara @hausdorff 
- [ ] Create **Cluster_Configuration.AWS** README @spara @hausdorff  
- [ ] Create **Cluster_Configuration.GCP** README @spara @hausdorff (TBD by time available)
- [ ] Create **Cluster_Configuration.Azure** README @spara @hausdorff (TBD by time available)

Config used:

- Private Networking
- Private Control Plane / Endpoint
- NodeGroups
- RBAC
- Namespaces
- Default Namespace Quotas (TBD)
- Default PodSecurityPolicies (TBD)

#### Cluster Services

Content focused on show casing production settings and configuration for k8s cluster-based services.

Cluster Services Used:
- [fluentd-cloudwatch for API and Worker Node Logs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs.html)
- [kube2iam for fluent-cloudwatch Pod IAM](https://github.com/jtblin/kube2iam)

- [ ] Create **Cluster Services** README @spara @hausdorff 

#### App Services

Content focused on show casing production settings and configuration for k8s app-based services.

Cluster Services Used:
- [nginx-ingress-controller for Ingress management](https://github.com/kubernetes/ingress-nginx)
- [external-dns for DNS managment](https://github.com/kubernetes-incubator/external-dns)
- [cert-manager for LetsEncrypt TLS certificates](https://github.com/jetstack/cert-manager)

- [ ] Create **App Services** README @spara @hausdorff 

#### Slack Bot App

Content focused on show casing production settings and configuration for k8s and KX resources used to compose the Slack Bot App.

- [ ] SlackBot Example App @lblackstone @hausdorff (alexbot code)
  - Kubernetes resources used: Deployment, Service, ConfigMaps, Secrets, Ingress
- [ ] KX objects used e.g. **KX.ServiceDeployment**, **KX.DockerSecret**)

---

# 2) KX

Code to house a small, experimental library of helper functions and abstractions extracted and used in KtPW.

- [ ] Remove recent [stack examples](https://github.com/pulumi/kx/tree/master/examples) out of the KX repo, and place into proper stacks above in KtPW's new home in `pulumi/docs`. @metral 
- [ ] Consider removing the `PodBuilder` code out of the SDK as we have not quite landed on a consensus of what this should look like, and given the shortened timeline over the next few weeks.

Helpers To Consider Building

- [ ] [`DockerSecret`](https://github.com/pulumi/kx/blob/master/nodejs/kx/docker-secret.ts)
- [ ] [`ServiceDeployment`](https://github.com/pulumi/examples/blob/master/kubernetes-ts-guestbook/components/k8sjs.ts)
- [ ] [`PodBuilder`](https://github.com/pulumi/kx/blob/master/nodejs/kx/pod-builder.ts) or `DeploymentBuilder` (TBD)
Recent thoughts and feedback suggest PodBuilder may be too low of an atomic unit, and we should consider facilitating and optimizing resources directly such as a DeploymentBuilder.

---

# 3) Cloud Query Tooling

Code & docs on ops tools to query cloud & k8s for debugging, insight, and auditing.

- [ ]

**Comment by metral** [comment]
cc @lukehoban @joeduffy @hausdorff @lblackstone @spara

**Comment by joeduffy** [comment]
Thanks!

I assume the Kx work will happen in another repo?

Same for the query tools?

**Comment by metral** [comment]
> I assume the Kx work will happen in another repo?

https://github.com/pulumi/kx

> Same for the query tools?

cc @hausdorff ^

**Comment by justinvp** [comment]
@metral, do you want to add a task to re-enable checking for broken links to https://github.com/pulumi/kubernetes-the-prod-way/? Follow-up to #1833

**Comment by metral** [comment]
Will do @justinvp. Thank you!

**Comment by metral** [comment]
Closing this issue in favor of separate tracking issues for the 3 work streams: Crosswalk guides, KX, CloudQuery tools.

- Crosswalk guides: https://github.com/pulumi/docs/issues/1835
- KX: In progress
- CloudQuery: In progress
