### ISSUE TITLE
Document about how to implement own plugins

### ISSUE THREAD

**Issue by Aya-Yang** [pulumi/docs#1846]
I read the docs, but I can't find the tutorials to implement a custom plugin, such as Resource Provider.

**Comment by leezen** [comment]
Thanks for the feedback. You may find this blog post helpful depending on what you're trying to do: https://www.pulumi.com/blog/dynamic-providers/

**Comment by lukehoban** [comment]
Closing as dupe of https://github.com/pulumi/docs/issues/595.
