### ISSUE TITLE
Recommend LTS version of Node

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1848]
Our docs say we support Node 8 and above, but we should _recommend_ users use the latest LTS version of Node. 

At https://www.pulumi.com/docs/intro/languages/javascript/:
![image](https://user-images.githubusercontent.com/293763/66673913-7fdaeb80-ec16-11e9-958f-68c3e7bb6a57.png)

At https://github.com/pulumi/pulumi/blob/master/README.md:
![image](https://user-images.githubusercontent.com/293763/66674031-c4668700-ec16-11e9-84f7-1b98fb269d71.png)

**Comment by rosnovsky** [comment]
Hi @clstokes! I noticed that aside from these two mentions, there multiple tutorials mentioning supported Node versions. Some tutorials explicitly naming a version to use, for example, [here](https://github.com/pulumi/examples/tree/master/kubernetes-ts-multicloud), some of them mention really old versions as is the case [here](https://github.com/pulumi/examples/tree/master/gcp-ts-gke-hello-world), and some don't have a version mentioned at all, [here](https://github.com/pulumi/examples/tree/master/aws-ts-s3-lambda-copyzip), for instance.

Do you mind if I unify these? It is probably a good idea to not mention or recommend using Node earlier than Node 8, and with Node 8 EOL this December, it's probably a good idea to only recommend Node 10 and above, while supporting older versions as well. If it's ok with you guys, I'd go ahead and update the docs, tutorials and README to reflect this: `Pulumi supports JavaScript programs running Node.js version 8 and later. With Node 8 reaching End-Of-Life, we recommend using Node 10 LTS and above.` or something along these lines. In tutorials, I'd just unify Node requirements as something like `Install Node 8+ (Node 10 LTS and later recommended)`, matching contest.

**Comment by clstokes** [comment]
Hi @rosnovsky, thanks for identifying the different places we mention this and offering to update them! I think it would be great to unify these. 

@lukehoban given Node 12 will be LTS next week (I think that was the timeline I saw?), how would you recommend we update these?

**Comment by clstokes** [comment]
Related https://github.com/pulumi/pulumi-aws/issues/774.

**Comment by gitfool** [comment]
Indeed, Node 12 is now Active LTS and is the [recommended download](https://nodejs.org/en/download/) as the Latest LTS.

**Comment by rosnovsky** [comment]
Yeah, so the question is what is what, technically, is Pulumi going to support when it comes to Node. Will it still support Node 8 apps, or will Node 10/12 be a requirement moving forward, or something in between.

**Comment by lukehoban** [comment]
We do now advertise this as:

> Pulumi supports JavaScript programs running on Node.js using any of the Current, Active and Maintenance LTS versions.
