### ISSUE TITLE
Clarify full list of supported cloud providers

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#1879]
### Problem description

The [Cloud Providers](https://www.pulumi.com/docs/intro/cloud-providers/) page only lists a subset of the full list of providers that Pulumi supports - e.g. it lists AWS, Azure, Google Cloud, Kubernetes, OpenStack. The full list of providers that pulumi supports is at [API Reference](https://www.pulumi.com/docs/reference/pkg/) - e.g. AWS, Azure, and many more. This can lead to end users thinking Pulumi doesn't support their providers or services when in fact it does.

### Suggestions for a fix

The [Cloud Providers](https://www.pulumi.com/docs/intro/cloud-providers/) page should contain the full list of providers that Pulumi supports.

**Comment by stack72** [comment]
@clstokes OMG that's funny - yesterday I talked to someone at DevOpsDays about vSphere support and they didn't see it was supported as it wasn't listed on that page :) Nice to see someone else pick this up too

**Comment by stack72** [comment]
@clstokes I just spoke to @lukehoban about this - I will drive this forward and make sure we get the page updated with what we support

**Comment by clstokes** [comment]
@stack72 we should include F5, Vault, etc. on this page too, not just _cloud_ providers.

**Comment by stack72** [comment]
@clstokes my thoughts are that we have cloud providers, networking providers etc.

**Comment by clstokes** [comment]
@stack72 yea, **_all_** providers.

**Comment by stack72** [comment]
Oh @clstokes i mean in different sections - if you think they should all be listed here then I’m fine with that

**Comment by clstokes** [comment]
@stack72 sure, I'm fine with different sections. I just want all of them listed on the page.

**Comment by danfhernandez** [comment]
+1 here, I ran into this when trying to show all the providers we have during demo for MS... I would think it should include the list here: https://www.pulumi.com/docs/reference/pkg/

**Comment by lukehoban** [comment]
What's still remaining here?  

We may want to hand this over to @spara or someone else who could help "spruce up" this page (logos, etc.).

**Comment by stack72** [comment]
Closed via #2298
