### ISSUE TITLE
Consider making "On This Page" always visible

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#1900]
When reading longer pages like https://www.pulumi.com/docs/intro/concepts/programming-model/, it's easy to lose track of where you are on the page.

To help, we should consider "anchoring" the right-nav "ON THIS PAGE" so it's always visible (similar to the [Tailwind CSS docs](https://tailwindcss.com/docs/installation)) and bold the current section of the page (similar to [Docker's docs](https://docs.docker.com)).

**Comment by joeduffy** [comment]
@justinvp Ironically, I was just about to file this same issue... for the programming model page. This seems like a pretty minor change that would have a potentially large improvement to UX. Should we try to tackle this soon?

Note that we may want to consider the same for the left-hand nav, though it's probably less urgent.

**Comment by justinvp** [comment]
> Note that we may want to consider the same for the left-hand nav, though it's probably less urgent.

I kind of like how the Tailwind docs handle this: The left nav is scrollable and the right nav is sticky and scrollable. If that sounds good:

- [ ] Right-nav sticky
- [ ] Right-nav vertically scrollable
- [ ] Right-nav current section bolded as you scroll through the page
- [ ] Left-nav vertically scrollable

@cnunciato, here's one worth considering this milestone.
