### ISSUE TITLE
Typo - ConfgurationSet and ConfigurationSet both shown on the ses page

### ISSUE THREAD

**Issue by ledburyb** [pulumi/docs#1915]
File: [docs/reference/pkg/nodejs/pulumi/aws/ses/_index.md](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/ses/)

**Comment by pgavlin** [comment]
IIRC we do actually define both of these types due to a typo in earlier versions of this package. We retain the old, misspelled name for back-compat, which is why it shows up here. I believe it should be marked as deprecated. cc @justinvp

**Comment by justinvp** [comment]
@stack72, I see that we've renamed the misspelled resource with an alias here:

https://github.com/pulumi/pulumi-aws/blob/56a7214fa94e6637b3950fe0bf06ad74cadd4fcf/resources.go#L2351-L2353

But shouldn't the old name be marked as deprecated?

**Comment by stack72** [comment]
Linked to https://github.com/pulumi/pulumi-terraform-bridge/issues/133
