### ISSUE TITLE
Make Getting Started more Windows-friendly

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#1921]
We have several issues with our Getting Started flow on Windows. Someone should go through this end-to-end, and make sure it is as smooth as on other platforms, like macOS.

For example, see:

* https://github.com/pulumi/docs/issues/1764
* https://github.com/pulumi/pulumi/issues/3398

This includes (please update as needed)

- [x] PowerShell commands for Python activation
- [x] Verifying all steps work on a clean Windows installation
- [x] All terminal commands represented in PowerShell

**Comment by spara** [comment]
resolved with https://github.com/pulumi/docs/issues/1764
