### ISSUE TITLE
Move User Guides nav to the top level

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#1927]
I find that the way we list the User Guides today buries a lot of our most important content:

![image](https://user-images.githubusercontent.com/3953235/68170493-d7722b80-ff24-11e9-91dd-40aa94653842.png)

It's not until you expand the nav that you see the interesting things underneath:

![image](https://user-images.githubusercontent.com/3953235/68170499-e0fb9380-ff24-11e9-87dc-44893236ee99.png)

My proposal is that we rearrange this, so that it is:

* GUIDES AND TUTORIALS
     - Continuous Delivery
     - SAML Single Sign-on (SSO)
     - Crosswalk for AWS
     - Crosswalk for Kubernetes
     + Tutorials
         - AWS
         - Azure
         - GCP
         - Kubernetes

**Comment by cnunciato** [comment]
@joeduffy What do you think? 

http://content-bucket-1085c8f.s3-website-us-east-1.amazonaws.com/docs/

I'm not sure the self-hosted item really belongs at the top level, though. 🤔  Is this what you had in mind otherwise?
