### ISSUE TITLE
Example on launching Fargate task via lambda is out of date

### ISSUE THREAD

**Issue by 0xCMP** [pulumi/docs#1928]
### Problem description

Trying to run the code at https://www.pulumi.com/docs/guides/crosswalk/aws/ecs/#running-fire-and-forget-tasks leads to errors. I believe things have been moved.

I'm getting a type error trying to create a route like that because it does not return anything. The type error usually refers to "string" not being a valid "awsx.apigateway.Method", but the issue is actually the lack of a proper return.

There is also no clear way to invoke that or links to further docs from there to the api gateway.

### Affected product version(s)

Latest

- pulumi cli 1.4.1
- @pulumi/aws 0.18.27
- @pulumi/awsx 0.18.13
  - @pulumi/aws 1.7.0
- @pulumi/pulumi 1.4.1

**Comment by justinvp** [comment]
Sorry about that, @0xCMP. Thanks for letting us know about the issue! I've opened #2144 to fix it.
