### ISSUE TITLE
SCSS chooser jumps around page on lengthy pages when the choice is clicked

### ISSUE THREAD

**Issue by metral** [pulumi/docs#1961]
### Problem description

We have a k8s-language chooser done in the same fashion as our lang chooser, but for the choices of yaml vs TS vs TS-kx (kubernetesx).

I’ve noticed when i use many shortcodes in a single page across differing sections, each with their own `{{< k8s-language noyaml }}` header (for example), clicks on a language choice can cause the page to jump around. The very first k8s-langauge shortcode works fine and keeps the page in-place as expected, but any proceeding k8s-language sections will be thrown around the page on clicks.

- Example in crosswalk guides: https://raw.githubusercontent.com/pulumi/docs/c76b1b93fd3e822a8abcfbc13c04207d16679853/content/docs/guides/crosswalk/kubernetes/apps.md
- Example in the programming model: https://www.pulumi.com/docs/intro/concepts/programming-model/

**Comment by cnunciato** [comment]
This appears to be happening because of reflows resulting from changes to the content above the tab that was clicked. Looking into options.

**Comment by cnunciato** [comment]
Got a candidate fix -- will test across browsers and PR if it looks good.
