### ISSUE TITLE
Change the Crosswalk for Kubernetes landing page

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#2001]
Right now, the Crosswalk for Kubernetes landing page "jumps right in" to the content. I'd prefer if it set a little more context. It also misses discussion of Kx and Kq, which are essential to the story.

My suggestion is to change the current landing page to be very simply:

* A quick overview of Crosswalk for Kubernetes, aligned with how we are describing it
* A brief section about the Playbooks (and link to essentially what's the current landing page)
* A brief section about the KubernetesX library (and link to pages with deeper details)
* A brief section about the Kubernetes Query capabilities (and link to pages with deeper details)
* Links to other supporting material, like CI/CD integrations

**Comment by metral** [comment]
@joeduffy PR is in flight to address this issue: https://github.com/pulumi/docs/pull/1988

PTAL and review.
