### ISSUE TITLE
State and backends docs fail to mention environment variables for logging in to azure blob storage

### ISSUE THREAD

**Issue by wmeints** [pulumi/docs#2007]
### Problem description

The document states that you can use 

```
pulumi login azblob://somecontainer
```

It fails to mention the fact that you need to set two environment variables for this to work:

- AZURE_STORAGE_ACCOUNT
- AZURE_STORAGE_KEY

Both need to be set, otherwise you'll get an error stating the account name is missing.

- I saw a product documentation issue on the following URL: https://www.pulumi.com/docs/intro/concepts/state/#self-managed-backend

### Affected product version(s)

All

### Suggestions for a fix

Include instructions for setting the environment variables and where to find the information needed to fill them.

**Comment by leezen** [comment]
Thanks for pointing this out! We'll include this in an upcoming doc update.
