### ISSUE TITLE
Incorrect link formatting

### ISSUE THREAD

**Issue by jenstroeger** [pulumi/docs#2010]
File: [docs/reference/pkg/nodejs/pulumi/aws/lambda/_index.md](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/lambda/#Function-runtime) contains
```
See [Runtimes][6] for valid values.
```
which is probably a Markdown typo. Looking around that page, though, I see a few more issues, like `[Runtimes][2]` or `[AWS Lambda Layers][1]` or `[License Info][3]` …

**Comment by leezen** [comment]
Thanks for pointing this out -- we'll look into it.

**Comment by praneetloke** [comment]
Should be fixed by https://github.com/pulumi/pulumi-terraform-bridge/pull/166 when the tfgen version is taken-in by the providers.

**Comment by praneetloke** [comment]
This is now fixed with the latest docs release. I'll close this. Thank you for opening this issue, @jenstroeger.
