### ISSUE TITLE
Intended service reference text incorrectly omitted from rendered text description 

### ISSUE THREAD

**Issue by danvanderboom** [pulumi/docs#2036]
### Problem description

- I saw a product documentation issue on the following URL:
https://www.pulumi.com/blog/managing-secrets-with-pulumi/

“This means when storing state with , we use a key managed by the service, specific to your stack”

The missing text, in two places, is a reference to the Pulumi backend service. It appears correctly in the github.com view, but not as rendered by Safari on iOS (at least). 

### Suggestions for a fix

Format the service url differently. Test in Safari on iOS.

**Comment by leezen** [comment]
Thanks for pointing this out! I've submitted a PR to address this.
