### ISSUE TITLE
Mention Proper Auth for GCP

### ISSUE THREAD

**Issue by elucidsoft** [pulumi/docs#2054]
File: [docs/get-started/gcp/configure.md](https://www.pulumi.com/docs/get-started/gcp/configure/)

Pulumi does not use the standard credentials for GCloud SDK, instead you need to initialize using `gcloud auth application-default login` otherwise you will get RPC errors as Pulumi will be unable to find the default credentials from the normal `gcloud auth login` if they followed the Google Documentation on setting up GCP this would typically never be done.  

Where this really gets problematic is if you decide to use a different user for your Pulumi setup on your dev machine. No matter how many times you re-initialize `gcloud init` or re-reun `gcloud auth login` Pulumi will still use old credentials from application-default.  It's very confusing and there is very little documentation on this issue.

**Comment by pgavlin** [comment]
Thanks for the report. @jen20 @stack72 can you take a look?
