### ISSUE TITLE
API ref. for `kubernetesx`/`kx`

### ISSUE THREAD

**Issue by Dominik-K** [pulumi/docs#2083]
File: [docs/reference/pkg/_index.md](https://www.pulumi.com/docs/reference/pkg/)

It would be nice to already have an API overview of https://github.com/pulumi/pulumi-kubernetesx in the usual API reference. Best with a hint that this package is in experimental state, yet.

**Comment by lblackstone** [comment]
The API reference has been updated, and https://github.com/pulumi/pulumi-kubernetesx/issues/42 was opened to track documentation of the classes/methods.
