### ISSUE TITLE
Adopt Pulumify approach to S3 for production deploys

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#2107]
Right now Pulumify only works for pull request previews.

It would be easy to extend it with the notion of "permanent" branches, which would come with long-lived stacks, CDNs, and HTTPS.

At this point we could use Pulumify for production deployments too.

It would be a whole lot faster than our current approach to deployments, because it bulk-syncs all the S3 content at a time. I suspect it would cut average deployments from ~10m to ~2m.

**Comment by susanev** [comment]
@joeduffy is this still something we should do?

**Comment by cnunciato** [comment]
This is no longer applicable, as we no longer use Pulumify. I'll close -- but it'd be good to come back to a Pulumify V2 at some point!
