### ISSUE TITLE
Docs don't show optional types as they exist in code

### ISSUE THREAD

**Issue by metral** [pulumi/docs#2108]
### Problem description

Optional types don't have a `?` after the var name in the docs.

For example in 
https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/eks/#ManagedNodeGroupOptions

![image](https://user-images.githubusercontent.com/1112768/70268984-5a6de800-1756-11ea-8f2d-8b4d0918ab11.png)

And the actual code has `?`:

https://github.com/pulumi/pulumi-eks/blob/c904c9e63eff99fa819df46b9631c20be9b66dcb/nodejs/eks/nodegroup.ts#L638-L672

**Comment by justinvp** [comment]
Fix available at https://github.com/pulumi/docs/commit/d01f32f22c66c38867c24af2ce07f7c15625c89a on top of #2114. Once #2114 is merged, I'll rebase and open a PR with the fix.
