### ISSUE TITLE
Link Missing 

### ISSUE THREAD

**Issue by nickpulumi** [pulumi/docs#2152]
### Problem description

at the end of this section is says 

> Just see this quickstart video recorded by our CTO, Luke Hoban. You, too, can get started with Pulumi very quickly.

There is no link 

- I saw a product documentation issue on the following URL: <https://www.pulumi.com/docs/guides/self-hosted/#quickstart>

### Suggestions for a fix

Find the appropriate video or remove the offending line

**Comment by justinvp** [comment]
@praneetloke, this is referring to the following in https://github.com/pulumi/docs/blob/master/content/docs/guides/self-hosted/_index.md

```
<!--INSERT YOUTUBE LINK-->
```

Do you recall the video you were planning to include?

**Comment by praneetloke** [comment]
Ooh yeah. Let me remove it.
