### ISSUE TITLE
Mistake in code example in AWS Elastic Kubernetes Service (EKS)?

### ISSUE THREAD

**Issue by bdiringer** [pulumi/docs#2182]
File: [docs/guides/crosswalk/aws/eks.md](https://www.pulumi.com/docs/guides/crosswalk/aws/eks/)

In the code example in the Configuring Your EKS Cluster’s Networking section, on line 10:
`vpcId: vpc.vpcId,`
Should this actually be the following?
`vpcId: vpc.id,`

When I try the example as written, I get this error:

```
error: Running program '/eks' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    index.ts(12,16): error TS2339: Property 'vpcId' does not exist on type 'Vpc'.
```

**Comment by stack72** [comment]
Hi @bdiringer 

Thanks so much for reporting this - I have opened a PR in #2186 that fixes this up

Paul
