### ISSUE TITLE
Provide way for readers to provide feedback/suggestions

### ISSUE THREAD

**Issue by chrsmith** [pulumi/docs#2223]
Something we've heard from Pulumi users/customers is that our documentation is very important for their success, and at times isn't quite what is needed. (In addition to the "Edit on GitHub" link.)

We should provide a way for readers to push feedback to us to highlight any content issues and/or provide suggestions for how to improve various pages.

Looking at Kubernetes.io, you can see a "Feedback" widget at the bottoms of pages. This looks like it just sends data to Google Tags Manager.
- https://kubernetes.io/docs/reference/kubectl/overview/
- [Hugo template](https://github.com/kubernetes/website/blob/master/layouts/partials/feedback.html)
- [Hugo template continued](https://github.com/kubernetes/website/blob/88d0f7825190694ed21be2229839cef9e75f14cf/i18n/en.toml#L107)

@zchase could you look into what the best tool for this sort of thing is? e.g. is Google Tags Manager the right tool here? Is there a capability of HubSpot/Segment that we can use to track 👍 / 👎  ratings? Do we need to roll our own?

Once we have an idea for how to go about this, I'm happy to do the work.

**Comment by zchase** [comment]
@chrsmith Yup, we would use Segment and Google Analytics to track this. All we need to do is fire an event when the button is clicked, with the code looking something like this:
```
window.analytics.track(
    category: "User Documentation | Helpful",
    label: "Yes",
);
```

Then in Google Analytics we can bucket the events by page and see how many people clicked each of the button. The `category` above can be named whatever we want, as long as we can identify these events are for user feedback from the docs.

**Comment by justinvp** [comment]
@zchase, @chrsmith Is it possible to include an optional form field so users can type in a message on why they're clicking thumbs up or down?

**Comment by zchase** [comment]
@justinvp Yes and no. We can but we will have to rethink how we will store the feedback. We won't be able to store longer feedback in Google Analytics, it would be incredibly difficult to maintain this data in HubSpot, so I think we would have to store it in a table.

**Comment by justinvp** [comment]
@zchase, ok, I was just curious. I don't think we need the form field... We could just do something similar to the Kubernetes site that Chris linked to. When I click "No" it provides links to report a problem or suggest an improvement (by filing GitHub issues). A similar approach should work for us.

<img width="716" alt="Screen Shot 2020-01-09 at 9 30 14 AM" src="https://user-images.githubusercontent.com/710598/72076049-e7124580-32c2-11ea-8811-5a28a54ab79f.png">

**Comment by chrsmith** [comment]
I don't want to be a pain, but I would suggest that whatever feedback reporting mechanism we use doesn't requiring filing a GitHub issue. (Since that requires signing in with a GitHub account, associating that bug report with your public profile, etc.)

Having a user enter some text in a form anonymously, and optionally have an "(optional) please enter your email address if you would like us to follow up with you." field seems like a better approach. That would dramatically lower the barrier for users submitting feedback, which I think is the main goal here.

... is that something that makes sense in the GA world? For the "post anonymous form data", I assume we'd have to have our own small infrastructure app or something?

**Comment by zchase** [comment]
@chrsmith @justinvp The GA world won't be good for accepting long-form feedback so, I've been doing some research into different products around feedback collection. There are two products I think we should take a look at before we decide to roll our own solution. These products don't provide a `Yes/No` option at the end of the doc, but rather a floating feedback button on the side of the page. They both record the page the feedback was given on.

- Usabilla: https://usabilla.com/request-a-personal-demo/
- Appzi: https://www.appzi.com/

Usabilla is cool because they provide a way for the user to pick the specific part of the page they want to comment on. Let me know what y'all think.

**Comment by zchase** [comment]
@chrsmith @justinvp After some email discussion and short discussion offline with @lukehoban and myself, Luke pointed out that any event pushed into Segment will be pushed into our Redshift data warehouse and into queryable via Metabase. So we don't need to build any custom backend to consume and store the data. Metabase should handle our needs for now.

So the path forward here is to build out the UI for collecting feedback and then pushing the data into Segment via a `window.analytics.track` call. Will update the issue with a PR when it is ready.

**Comment by zchase** [comment]
PR here: https://github.com/pulumi/docs/pull/2284

**Comment by zchase** [comment]
PR has been merged in and the feedback feature is live on pulumi.com. The next step is to create a dashboard in Metabase for consuming the data.

**Comment by zchase** [comment]
The UI is live and the dashboards have been created.

Overview: https://metabase.corp.pulumi.com/dashboard/24
Per Page: https://metabase.corp.pulumi.com/dashboard/26

Closing.
