### ISSUE TITLE
None of the "sha256" hashes in the integrity attribute match the content of the subresource

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#2256]
Scripts aren't being loaded causing pages not to work as expected, e.g. the following was reported by a user:

> there's nothing in the "Install Pulumi" section and clicking "Windows" does nothing

Mikhail hit this and captured this screenshot:

<img width="1451" alt="Screenshot 2020-01-15 at 22 33 48" src="https://user-images.githubusercontent.com/710598/72532746-f0129200-3841-11ea-8edb-f07eefae7af8.png">

Clearing the browser cache resolved it.

Due to having an old HTML cached which points to scripts that aren't available in the new version of the site?

If we didn’t have the integrity check, would it have worked? Or would it still not have worked due to the old script not being available on the new version of the site (and not present in the browser cache)?

**Comment by justinvp** [comment]
Interestingly, I ran into a similar issue today with Safari. I was viewing the Get Started - Install Pulumi page, and the OS chooser tabs didn't work and the content below was empty. I opened the console and it showed an error that the script file had a 404 response. Refreshing the page fixed the issue. I think this is another case of "cached HTML which points to scripts that aren't available in the new version of the site". (Note that there were no integrity errors, perhaps Safari doesn't show those if the resource is 404).

I wonder if we need to be keeping old scripts around in S3 for some period of time somehow?

**Comment by justinvp** [comment]
@cnunciato, this is another issue worth considering for M31, if you have the bandwidth. This feels similar or potentially related to #1687. #1687 is about ensuring the site works during a deployment and this issue is about ensuring it continues to work after new deployments.

**Comment by justinvp** [comment]
Another thought: Do we need to make any changes to our cache headers? 🤔

**Comment by cnunciato** [comment]
@justinvp It doesn't look like we're setting any `Cache-Control` headers currently (so not directing browsers to do any caching, which leaves that up to their default behavior, in combination with user preferences). Our HTMLs are set to be cached at the CloudFront endpoint for 10 minutes, and our CSS and JS files for one week. 

So assuming the fix I submitted with #2290 doesn't address this (e.g., the user has a browser-cached HTML file that refers to a CSS or JS file that's expired from the CF cache and no longer exists on S3, or I guess if the requested HTML file had expired and was re-cached by CF less than 10 minutes before its corresponding asset files were set to expire themselves), you could end up in a place where the HTML file's asking for a bundle that's no longer on S3, yeah.

Theoretically the window for this should be no longer than either 10 minutes or the browser's settings, which I believe are unpredictable without an `max-age` header. If we want to be sure this never happens, though, we probably need to store up these bundles for a longer period of time. Does that jive with your understanding as well?

**Comment by cnunciato** [comment]
... and I think the reason we see that particular message is because the `content-type` for a non-existent CSS file, for example, is `text/html` (and the response actually does contain HTML content -- clouds and beams):

```
$ curl -I https://www.pulumi.com/css/styles.NOPE.css
HTTP/2 404
content-type: text/html
content-length: 1696
```

**Comment by justinvp** [comment]
> If we want to be sure this never happens, though, we probably need to store up these bundles for a longer period of time. Does that jive with your understanding as well?

Yep.

> the reason we see that particular message is because the `content-type` for a non-existent CSS file, for example, is `text/html`

And, yep. :)
