### ISSUE TITLE
Prototype resource-oriented doc gen from Pulumi resource model schema

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#2263]
Move to resource-oriented API docs, generated from the Pulumi resource model schema.

- One page per resource/datasource (similar to tf docs)
- Language chooser on each page to change format of examples/definitions on page

**Comment by dstine** [comment]
This would be a big usability improvement!

**Comment by justinvp** [comment]
This is in-progress and will continue into early next week.

**Comment by joeduffy** [comment]
@justinvp @cnunciato Do we have any mock-ups of what this will look like?

**Comment by justinvp** [comment]
> Do we have any mock-ups of what this will look like?

No, but I have some work-in-progress stuff I can show off (w/ stand-in data in some places) that demonstrates what I'm aiming for here. Sort of a "working" mockup. Will get that into shape and send around tomorrow. Then I'll sync with @cnunciato to get his feedback on how to make it look even more awesome :)

**Comment by justinvp** [comment]
I am going to close this issue as we have a rough initial prototype of schema-based API doc gen here: 

- https://github.com/pulumi/pulumi/tree/justin/docs_api
- https://github.com/pulumi/pulumi-terraform-bridge/tree/justin/docs_api
- https://github.com/pulumi/pulumi-aws/tree/justin/docs_api

This demonstrates an approach to generating docs similar to the codegen of other languages. Generated resource pages are still a WIP. These need to be cleaned up to better present creation of the resource, list nested types, and provide linking within declarations. We also likely want to show how to read an existing resource (i.e. via static `get` function) and/or importing the resource at the bottom of the page.

Similar treatment is needed for data sources.

Some other open items:

 - Examples from `tf2pulumi` need to be added to the schema (for each supported language).
 - Signatures and appropriate symbol names needs to be generated for each supported language.

For those following along, we are actively working on productizing this, which is largely tracked by https://github.com/pulumi/docs/issues/2265, though we will want to break this down into a more granular list of remaining tasks.

There are also several related issues:

- [#2265](https://github.com/pulumi/docs/issues/2265) - Create redirects from old API docs to new resource-oriented pages
- [#2137](https://github.com/pulumi/docs/issues/2137) - API docs for .NET SDK
- [#113](https://github.com/pulumi/pulumi-terraform-bridge/issues/113) - Doc generation meta-issue
- [#136](https://github.com/pulumi/tf2pulumi/issues/136) - tf2pulumi should support tf 0.12 syntax
- [#98](https://github.com/pulumi/tf2pulumi/issues/98) - Python Backend Bringup Meta-Issue
- [#140](https://github.com/pulumi/tf2pulumi/issues/140) - Add C# support
- [#148](https://github.com/pulumi/tf2pulumi/issues/148) - Add Go support
