### ISSUE TITLE
Create redirects from old API docs to new resource-oriented pages

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#2265]
Implement redirects from old pages (including anchors) to the new structure. For example: `/docs/reference/pkg/nodejs/pulumi/aws/s3/#Bucket` => `/docs/reference/pkg/pulumi/aws/s3/Bucket/` (or whatever structure we end up with.

**Comment by praneetloke** [comment]
We don't need to do this anymore since we will link to these docs from the new cloud resource reference page.
