### ISSUE TITLE
There are a number of formatting issues on the Python StackReference examples page

### ISSUE THREAD

**Issue by leezen** [pulumi/docs#2380]
File: [docs/tutorials/aws/aws-py-stackreference.md](https://www.pulumi.com/docs/tutorials/aws/aws-py-stackreference/)

**Comment by clstokes** [comment]
https://www.pulumi.com/docs/tutorials/gcp/gcp-py-instance-nginx/ has similar issues so this does not seem limited to a single page.

**Comment by leezen** [comment]
Yeah, it's more #1091 that's the issue here than anything
