### ISSUE TITLE
Gitlab <> Pulumi suggestion

### ISSUE THREAD

**Issue by daviddaskell** [pulumi/docs#2403]
File: [docs/guides/continuous-delivery/gitlab-ci.md](https://www.pulumi.com/docs/guides/continuous-delivery/gitlab-ci/)

In the `run-pulumi.sh` script, should it not be `pulumi up --yes` on the last line?

**Comment by stack72** [comment]
@davidkell I believe you are correct - I just opened a PR that should fix this

**Comment by lukehoban** [comment]
This was fixed.
