### ISSUE TITLE
Auto generate "Pulumi Examples" landing page

### ISSUE THREAD

**Issue by chrsmith** [pulumi/docs#2449]
I blindly went to https://www.pulumi.com/examples instead of https://github.com/pulumi/examples and got a 404. This is 100% working as intended... but maybe it isn't? Seems like having a top-level landing page for "Pulumi Examples" would be a pretty useful thing. (Especially if we can just have it auto generated from all of the examples we have in GitHub.)

**Comment by lukehoban** [comment]
FWIW - this is effectively what https://www.pulumi.com/docs/tutorials/ is.

**Comment by lukehoban** [comment]
Going to close this out as the content is there.  I thought about adding a redirect from `/examples`, but not sure that's needed right now.  We need to clean up overall how we have a single place for this content that is easily discoverable, but that's a longer term thing.
