### ISSUE TITLE
Which theme is shown on the home page of pulumi? 😅

### ISSUE THREAD

**Issue by RichieRunner** [pulumi/docs#2451]
Hello, I'm wondering which theme is being shown here on the home page of pulumi?

https://www.pulumi.com/

![image](https://user-images.githubusercontent.com/20289967/74690518-42720600-5194-11ea-9b8c-0fe60cf13854.png)

**Comment by cnunciato** [comment]
It's not actually a real theme -- it's just hard-coded markup, made with our [color palette](https://codepen.io/cnunciato/pen/XLQyYG). I took the VS Code Dark+ theme (which I think is the default) as a starting point, then applied our colors to that, just to make it look a little more in harmony with everything else.

I've written a couple of VS Code extensions, but never a theme, so I figured I'd take a look, and of course, [making a real theme](https://code.visualstudio.com/api/references/theme-color) would involve way more than I have time for today. 😄 But if you start with the Dark+ theme, then apply these customizations in your settings.json:

```
{
    ....
    "workbench.colorCustomizations": {
        "titleBar.activeBackground": "#CBD5E0",
        "editorGroupHeader.tabsBackground": "#000000",
        "editorWidget.background": "#2D3748",
        "editorWidget.border": "#718096",
        "editorWidget.foreground": "#ffffff",
        "tab.activeBackground": "#1A202C",
        "tab.inactiveBackground": "#000000",
        "editor.background": "#1A202C",
        "sideBar.background": "#1A202C",
        "sideBar.foreground": "#A0AEC0",
        "sideBarSectionHeader.background": "#2D3748",
        "sideBarSectionHeader.foreground": "#CBD5E0",
        "sideBarTitle.foreground": "#CBD5E0",
        "statusBar.background": "#365881",
        "list.activeSelectionBackground": "#4A5568",
        "list.inactiveSelectionBackground": "#2D3748",
        "activityBar.background": "#2D3748",
        "activityBarBadge.foreground": "#F5FBFF",
        "activityBarBadge.background": "#4387C7"
    },
    ...
}
``` 

... you'll at least be part of the way there:

![image](https://user-images.githubusercontent.com/274700/74890168-1abba300-5338-11ea-82ec-9350990b6484.png)

**Comment by cnunciato** [comment]
Closing for now, since there's nothing specifically to be done for this. Note that a member of the community is [working on a proper VS Code theme](https://pulumi-community.slack.com/archives/C84L4E3N1/p1582519271042500) with these colors, though; I'll post back here once that's publicly available.
