### ISSUE TITLE
Some of the Go sample code in docs is wrong

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#2490]
We didn't update all of the docs after rolling out the new Go SDK changes. For instance, the various [programming model examples](https://www.pulumi.com/docs/intro/concepts/programming-model/#import) seem incorrect. I know we're doing a pass over some of these, but didn't see an issue tracking this aspect of the docs specifically, so wanted to file and ensure we didn't miss it.

**Comment by lukehoban** [comment]
Part of https://github.com/pulumi/docs/issues/2311.

**Comment by EvanBoyle** [comment]
closing in favor of https://github.com/pulumi/docs/issues/2311
