### ISSUE TITLE
Python instructions don't tell you to install virtualenv

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#2491]
I have a new machine and, after running `pulumi new`, I get:

```
Your new project is ready to go! ✨

To perform an initial deployment, run the following commands:

   1. virtualenv -p python3 venv
   2. source venv/bin/activate
   3. pip3 install -r requirements.txt

Then, run 'pulumi up'
```

Unfortunately, `virtualenv` doesn't appear to be installed by default, and (unless I missed it), none of our instructions tell you to install it. (Neither the [Getting Started guide](https://www.pulumi.com/docs/get-started/aws/install-language-runtime/) nor [the Python docs](https://www.pulumi.com/docs/intro/languages/python/).)

It seems we should be explicit about what to do here, especially as it wasn't obvious how to get it on your `PATH`. For reference, I had to do this on my Mac:

```bash
$ pip3 install virtualenv
$ sudo /usr/bin/easy_install virtualenv
```

**Comment by lukehoban** [comment]
This is effectively https://github.com/pulumi/docs/issues/1764 which is being worked on in https://github.com/pulumi/docs/pull/2184.

**Comment by joeduffy** [comment]
Resolving as a dupe of #1764.
