### ISSUE TITLE
It's not clear that Awaitable objects should be transformed via Output.from_input

### ISSUE THREAD

**Issue by leezen** [pulumi/docs#2499]
File: [docs/intro/concepts/programming-model.md](https://www.pulumi.com/docs/intro/concepts/programming-model/)

**Comment by lukehoban** [comment]
There’s not many common reasons why you should have to turn an Awaitable into an Output. What was the case where this ended up being needed?

**Comment by leezen** [comment]
I’m realizing now it’s a mistake on my part in not understanding the model
— I didn’t realize I could directly reference the underlying attributes of
the Awaitable and that they’d resolve. I assumed I had to have it be an
Output. I’m going to close this issue.




On February 20, 2020 at 5:53:25 PM, Luke Hoban (notifications@github.com)
wrote:

There’s not many common reasons why you should have to turn an Awaitable
into an Output. What was the case where this ended up being needed?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/pulumi/docs/issues/2499?email_source=notifications&email_token=AAFQABA3ILJEJA4FV2NQ7MDRD4XZHA5CNFSM4KYZE5YKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMRHJUA#issuecomment-589460688>,
or unsubscribe
