### ISSUE TITLE
Documented parameter confusion for API Gateway deployment restApi

### ISSUE THREAD

**Issue by austinbutler** [pulumi/docs#2511]
The comment suggests you pass the restApi ID, but the type given is the actual restApi input.

https://github.com/pulumi/pulumi-aws/blob/23de947dd89d01224804e4c8b665c0d441d36415/sdk/nodejs/apigateway/deployment.ts#L212

https://github.com/pulumi/pulumi-aws/blob/23de947dd89d01224804e4c8b665c0d441d36415/sdk/nodejs/apigateway/deployment.ts#L214

**Comment by lukehoban** [comment]
The underlying API now accepts either a string or a RestAPI, and refers to this more generally as " REST API identifier" which is correct.

https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/apigateway/deployment.ts#L273-L276
