### ISSUE TITLE
LogSubscriptionFilter logGroup parameter expects LogGroup and not string

### ISSUE THREAD

**Issue by leezen** [pulumi/docs#2512]
> [The documentation ](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/cloudwatch/#example-usage-10) insinuates that the property `logGroup` can be a `string`. Currently the only supported type is `pulumi.Input<aws.cloudwatch.LogGroup>`. This makes it a little awkward to setup as I first have to `aws.cloudwatch.LogGroup.get` the resource before I can use it even if the log group name is predictable e.g `/aws/lambda/lambdaFunctionName`.

From https://github.com/pulumi/pulumi-aws/issues/869

**Comment by lukehoban** [comment]
This was fixed in the AWS provider in https://github.com/pulumi/pulumi-aws/commit/0249d45fa33b013041aba3de230a1e41091620be.
