### ISSUE TITLE
"Copy to clipboard" button doesn't work on multi-line command with backslash

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#2517]
### Problem description

If a snippet in our docs contains a backslash (`\`) (or the line ends with one?), only the first line is copied, not the full snippet.

For the snippet at https://www.pulumi.com/docs/intro/concepts/config/#aws-key-management-service-kms:
```
$ pulumi stack init my-stack \
    --secrets-provider="awskms://1234abcd-12ab-34cd-56ef-1234567890ab?region=us-east-1"
```

This is what gets copied:
```
pulumi stack init my-stack \
```

I'm not 100% sure the backslash is the issue, but I've only noticed the issue on multi-line commands when a backslash is used.

### Examples

- https://www.pulumi.com/docs/intro/concepts/config/#aws-key-management-service-kms
- https://www.pulumi.com/docs/intro/concepts/config/#azure-key-vault
- https://www.pulumi.com/docs/intro/concepts/config/#google-cloud-key-management-service-kms
- https://www.pulumi.com/docs/intro/concepts/config/#hashicorp-vault-transit-secrets-engine

### Suggestions for a fix

Copy the whole snippet.

**Comment by joeduffy** [comment]
Ahh, just hit this one too:

```
$ mkdir yaml
$pushd yaml
$ curl -L --remote-name \
    https://raw.githubusercontent.com/kubernetes/examples/master/guestbook/{frontend-deployment,frontend-service,redis-master-deployment,redis-master-service,redis-slave-deployment,redis-slave-service}.yaml
$ popd yaml
```

This gets copied as:

`mkdir yaml && pushd yaml && curl -L --remote-name \`
