### ISSUE TITLE
pulumi.com/dotnet redirecting to go language page

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/docs#2519]
https://pulumi.com/dotnet redirects to https://www.pulumi.com/docs/intro/languages/go/

The link appears in this blog post https://devblogs.microsoft.com/dotnet/building-modern-cloud-applications-using-pulumi-and-net-core/ and the issue is called out by a user in the comments.

**Comment by mikhailshilkov** [comment]
Whoa, I use this link in my slides and it used to work, I'll try to fix it
