### ISSUE TITLE
[bug] doc block links invalid

### ISSUE THREAD

**Issue by brandonkal** [pulumi/docs#2531]
This is probably a bug in other repos as well.

An example: randomPet contains a link to
https://github.com/terraform-providers/terraform-provider-random/blob/master/website/docs/r/pet.html.markdown
When it should point to
https://github.com/terraform-providers/terraform-provider-random/blob/master/website/docs/r/pet.html.md

It appears the extension is ignored in the generated comment.

**Comment by leezen** [comment]
Thanks for reporting! Moved issue to docs repo

**Comment by stack72** [comment]
This is fixed via https://github.com/pulumi/pulumi-terraform-bridge/pull/111 and will be rolled out across all the providers this week!
