### ISSUE TITLE
Improve description of env vars for the API and Console containers in the self-hosted guide

### ISSUE THREAD

**Issue by praneetloke** [pulumi/docs#2549]
### Problem description

Although the self-hosted [guide](https://www.pulumi.com/docs/guides/self-hosted/api/) has a TOC of the env vars used by each container image, some env vars could use additional information on how they are used. For example, `PULUMI_API_DOMAIN` and `PULUMI_CONSOLE_DOMAIN` in the API container.

### Affected product version(s)

N/A

### Suggestions for a fix

N/A

**Comment by clstokes** [comment]
Please include details about `MYSQL_ROOT_USERNAME`, `MYSQL_ROOT_PASSWORD`, and `MYSQL_ALLOW_EMPTY_PASSWORD` for the migration container too.
