### ISSUE TITLE
Update Prerequisites that Helm needs to be installed. 

### ISSUE THREAD

**Issue by sfmskywalker** [pulumi/docs#2564]
Perhaps obvious to experienced users, but for me it wasn;t immediately obvious why the `Chart` object was causing a "resource not found" exception when doing `pulumi up`. After installing Helm, the error went away.

File: [docs/guides/crosswalk/kubernetes/app-services.md](https://www.pulumi.com/docs/guides/crosswalk/kubernetes/app-services/)

**Comment by lukehoban** [comment]
The Helm v3 support in Pulumi no longer has this dependency, so best solution is likely to move examples forward to use that.
