### ISSUE TITLE
Layout improvements for the new auto-generated resource-level doc

### ISSUE THREAD

**Issue by praneetloke** [pulumi/docs#2587]
Some early thoughts that were discussed for this were:

* [ ] Sticky breadcrumbs
* [x] Improving the side-nav
* [ ] Reducing the repetition of the language chooser
* [ ] Fill in appropriate front matter on each generated page
  * The `header.tmpl` that is injected into every page contains just the `title` in the front-matter right now.

Note that the templates that generate the markdown files are in the `pulumi/pulumi` repo under `pkg/codegen/docs`.

**Comment by cnunciato** [comment]
Closing this in favor of what's captured in https://github.com/pulumi/docs/issues/2816.
