### ISSUE TITLE
fix kafka provider example 

### ISSUE THREAD

**Issue by mattnidz** [pulumi/docs#2588]
File: [docs/intro/cloud-providers/kafka/_index.md](https://www.pulumi.com/docs/intro/cloud-providers/kafka/)

This example should say kafka.Topic and not rabbitmq.Topic

topic = rabbitmq.Topic("topic",
  name="sample-topic",
  replication_factor=1,
  partitions=4,
)

**Comment by stack72** [comment]
My apologies here @mattnidz 

I’ll get this fixed up shortly and shipped out

**Comment by stack72** [comment]
Closed via #2590
