### ISSUE TITLE
minor typo with description of EventSubscription resource

### ISSUE THREAD

**Issue by jdj333** [pulumi/docs#2589]
File: [docs/reference/pkg/nodejs/pulumi/aws/lambda/_index.md](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/lambda/)

Base type for all subscription types. An event subscription represents a connection between some AWS resource **an** -> **and** an AWS lambda that will be triggered when something happens to that resource.

**Comment by stack72** [comment]
@leezen sorry, I didn't see you had assigned this to yourself, I wrote this down last night as something I can fix easily :/

Once https://github.com/pulumi/pulumi-aws/pull/891 is merged, we can regenerate the SDK docs and this will be fixed

**Comment by leezen** [comment]
Great! Thanks. I'll assign it to you in this case :)
