### ISSUE TITLE
Analyze how we're doing docs-wise (e.g. manual review of a few pages to look for imperfections)

### ISSUE THREAD

**Issue by leezen** [pulumi/docs#2611]

**Comment by praneetloke** [comment]
@cnunciato has agreed to take this on. Thank you, Christian!

**Comment by cnunciato** [comment]
See also https://github.com/pulumi/home/issues/720, which captures a bunch of resource docs-related feedback.

**Comment by cnunciato** [comment]
Created this follow-up issue for resource-related follow-ups:
https://github.com/pulumi/docs/issues/2816

**Comment by cnunciato** [comment]
I'm going to close this as I think we've identified a good number of issues to work on at this point.

**Comment by leezen** [comment]
👍
