### ISSUE TITLE
Document Advanced Use Cases for Apply instead of just string transformations

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/docs#2638]
### Problem description

As I was developing I needed to access Output/Input variables to be used in other .NET code such as templating a file. Currently the documentation only talks about using Tuple/Apply for changing/accessing variables to then convert to another simple string. My use case required me to run more complex logic inside the Apply method that would read a file, template it using Input/Outputs, then return this new "file" as a new Output string to be used when VM is created. I was finally able to figure this out after talking to people on Slack but it would be really helpful to add to the documentation more about this use case of logic needing to be inside the apply wrapper to access variables. It would also be beneficial to go more into detail on why you have to put logic inside these wrappers and cannot use regular variables in the language, where the reasons are they are not created yet at preview, or just not available yet, etc. It took me a bit to wrap my head around the Input/Output variables and why I couldn't just ToString them to it's raw form.

Here is an example code that I used which shows I needed to pass in outputs using the tuple and running the logic inside the apply

```c#
// Template Userdata file using Input/Output Pulumi Variables
var userDatafileGzipBase64 = Output.Tuple(args.Name.ToOutput(), args.DomainName.ToOutput(), tlsPrivateKey.PublicKeyOpenssh).Apply(x =>
{
    var (hostName, domainName, sshPubKey) = x;
    // Using liquid template engine to render file
    var renderedTemplate = Template.Parse(userDataFileRaw).Render(Hash.FromAnonymousObject(new
    {
        vmHostName = hostName,
        vmDomainName = domainName,
        vmSshPubKey = sshPubKey,
    }));
    return StringHelper.EncodeStringToGzipBase64(renderedTemplate);
});
```

**Comment by lukehoban** [comment]
Great point @mitchellmaler - I think we could definitely add another more complex example like the one you share above to https://www.pulumi.com/docs/intro/concepts/programming-model/#all.
