### ISSUE TITLE
Help page for get-started/azure/deploy-stack should include 'Azure CLI' as prerequisite

### ISSUE THREAD

**Issue by StefH** [pulumi/docs#2656]
File: [docs/get-started/azure/deploy-stack.md](https://www.pulumi.com/docs/get-started/azure/deploy-stack/)

> error: Error building AzureRM Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed

**Comment by leezen** [comment]
In https://www.pulumi.com/docs/get-started/azure/configure/ there's an instruction to "Configure Azure" which includes configuring the Azure CLI. Let me know if you feel like it isn't in a clear enough spot. Did you arrive at the `deploy-stack` page without going through the earlier steps somehow and if so how? We'd ideally only have people navigating through the step-by-step flow.

**Comment by StefH** [comment]
You are correct, I missed that step.

Maybe rename `Configure` to `Configure Azure`. Or just `Install and Configure Azure CLI` ?

**Comment by leezen** [comment]
Thanks for the suggestion!
