### ISSUE TITLE
"Social Previews" of documentation links have a lot of formatting and not a lot of preview

### ISSUE THREAD

**Issue by leezen** [pulumi/docs#2669]

**Comment by leezen** [comment]
![image](https://user-images.githubusercontent.com/720900/76980146-1615ea80-68f6-11ea-8240-a05b0aa615ef.png)

**Comment by cnunciato** [comment]
This is fixed as of #2856:

![image](https://user-images.githubusercontent.com/274700/80008370-83301900-847c-11ea-9586-510fd210556f.png)
