### ISSUE TITLE
SEO: get the word "Provider" into our different provider's page listing

### ISSUE THREAD

**Issue by zchase** [pulumi/docs#2673]
As suggested by 97thFloor we should have the word provider in the page titles of our provider doc pages. To do this we will have to add "display titles" to the front matter of our provider content pages.

**Comment by lukehoban** [comment]
Is this still something we want to do?  What exactly is the suggestion?

**Comment by zchase** [comment]
@lukehoban The suggestion from 97th floor is the get the word "Provider" into the page titles of the provider docs landing pages. For example, the page title for the OpenStack provider is `OpenStack | Pulumi` and the suggestion is that it should be `OpenStack Provider | Pulumi`. This issue at hand is that we use the `title` value from the front matter in multiple places, i.e. we define the text value for the page title and the text that appears on the right-hand nav from the same field. To just update the page title we need to add an additional field to the front matter so that the page title and the text displayed on the page can diverge. Hopefully, that makes sense, otherwise, we can jump on a quick call and I can show you what I'm talking about.

**Comment by lukehoban** [comment]
> For example, the page title for the OpenStack provider is OpenStack | Pulumi and the suggestion is that it should be OpenStack Provider | Pulumi. 

Got it.  That seems fine then. I assume there is some relatively easy way to make that happen.
