### ISSUE TITLE
Pricing Page

### ISSUE THREAD

**Issue by nick-graham** [pulumi/docs#2678]
### Problem description

- We only mention this is an annual price once, 2/3rds of the way down the page. This feels like we are burying pertinent information out of line with the SaaS model our users are used to.
-This is causing confusion with users and puts us on the back foot in a discussion. It is counter productive to the goal of self service sign ups for all Starter/Pro accounts

### Suggestions for a fix - 
Update to make our pricing options clearer - Some kind of toggle at the top of the page that displays annual vs. monthly pricing eg
[https://toggl.com/pricing/](url)
[https://travis-ci.com/plans](url)

Or we need to say annual or billed annually after every price eg- 
[https://slack.com/pricing](url) 
[https://about.gitlab.com/pricing/](url)
[https://www.jetbrains.com/space/buy/](url)

**Comment by nickpulumi** [comment]
@FinnPark

**Comment by FinnPark** [comment]
I would second this. We're getting some messages from users asking to move to the reduced monthly price so it's causing some confusion.
