### ISSUE TITLE
Travis CRON jobs are failing often

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#2709]
Many Travis CRON jobs have recently started failing due to `hugo server` OOMing:

https://travis-ci.com/github/pulumi/docs/builds/154411399

```
371make validate
372make[1]: Entering directory '/home/travis/build/pulumi/docs'
373hugo server \
374    --buildDrafts --disableBrowserError --disableLiveReload \
375    &>/dev/null &
376while ! nc -z localhost 1313; do sleep 0.1; done
377Building sites … fatal error: runtime: out of memory
```

Since we’re no longer running the broken link checker against PRs, should we consider making it so that the CRON job checks for broken links against the actual deployed www.pulumi.com itself, rather than using Hugo's built-in webserver?

Or are there any other knobs to `hugo server` we could add to help prevent it from OOMing?

Another option would be to explore upgrading Hugo to a more recent version, which might not OOM as much?

Or can we get more memory to use during Travis jobs?

@cnunciato, do you have any cycles to look into this?

**Comment by cnunciato** [comment]
@justinvp Sure, having a look now.

**Comment by cnunciato** [comment]
It looks like we're already running a build as part of the Make task, so seems like we can just run the checker against the locally built copy. I'll try that.

**Comment by justinvp** [comment]
> It looks like we're already running a build as part of the Make task, so seems like we can just run the checker against the locally built copy. I'll try that.

I think the current broken link checker needs to run against a site served over HTTP, rather than just looking at files. But maybe there's an option to do that?

As an aside, I've wanted to explore moving over to using https://github.com/wjdp/htmltest for some of these checks (which, if it's fast enough, might even allow us to run these against PRs again).

**Comment by cnunciato** [comment]
> I think the current broken link checker needs to run against a site served over HTTP, rather than just looking at files. But maybe there's an option to do that?

That's right -- I'll just add a little HTTP server that'll serve whatever's in `public`.
