### ISSUE TITLE
JavaScript error on the Kubernetes Control Plane docs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#2735]
[This page](https://www.pulumi.com/docs/guides/crosswalk/kubernetes/control-plane/) triggers a JavaScript error:
 
![image](https://user-images.githubusercontent.com/3953235/77433436-9cba4400-6d9c-11ea-9194-a81f8998c5da.png)

I'm not sure if it shows up anywhere else, as it's not clear what specifically about this page is wrong.

**Comment by cnunciato** [comment]
Reproduced in Chrome. This is happening because a component is receiving an event notification earlier than expected. Have fix, will submit this AM.
