### ISSUE TITLE
Wrong Link to Pulumi Terraform Bridge in Terraform vs. Pulumi

### ISSUE THREAD

**Issue by pbstrein** [pulumi/docs#2756]
### Problem description
https://www.pulumi.com/docs/intro/vs/terraform/- The link "Pulumi Terraform bridge repo" points to the wrong repo. 

### Suggestions for a fix

Replace https://github.com/pulumi/pulumi-terraform with https://github.com/pulumi/pulumi-terraform-bridge

**Comment by stack72** [comment]
Oh my apologies for that - we changed it and I didn't realise that was outstanding. I will fix those docs now

**Comment by stack72** [comment]
Closed via #2758
