### ISSUE TITLE
Wrong Link to "TF Provider Integration" in pulumi/terraform page

### ISSUE THREAD

**Issue by pbstrein** [pulumi/docs#2759]
### Problem description

On https://www.pulumi.com/terraform/, the link for TF Provider Integration leads to, https://github.com/pulumi/pulumi-terraform, instead of https://github.com/pulumi/pulumi-terraform-bridge

### Suggestions for a fix

Change link from https://github.com/pulumi/pulumi-terraform -> https://github.com/pulumi/pulumi-terraform-bridge

Related to #2756, just a different page.

**Comment by stack72** [comment]
Thanks for finding these broken links @pbstrein
