### ISSUE TITLE
Improvements to the events and webinars pages

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#2771]
A few things worth considering

* Link to /webinars from /events, especially since most of our activity is online now
* Add dates to the /webinars page -- hard to tell which ones apply and when to me at a glance (they tend to be in the slides preview, but now always, and it's hard to read)
* Let's start being more upfront about the time zone these are best for (e.g., several of them are intentionally for "EUROPE" -- maybe we should color them differently or have an icon?)
* Consider making these more prominent, AFAIK they don't show up in the top-level nav anywhere -- is it time to have a "LEARN" tab and have events, webinars, community slack, etc underneath?

**Comment by lukehoban** [comment]
@zchase I think most of these are done or have changed enough that they aren't relevant.  I almost closed out, but I think the last bullet above remains an important piece to address, as I don't believe `/resources` is linked from anywhere prominent in the site.  I'll leave this open to track that item unless you are already tracking somewhere?

**Comment by lukehoban** [comment]
Actually - I see https://github.com/pulumi/docs/issues/2971 is tracking that last bullet with more details.  So will close this out and can track there.
