### ISSUE TITLE
Links to InvokeOptions don't go anywhere

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#2782]
Many of our function signatures (e.g., [here](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/sfn/#getActivity)) offer links to the definition of `InvokeOptions` that lead to the docs for `pulumi/pulumi`, but don't anchor anywhere. We should fix these.

**Comment by susanev** [comment]
@cnunciato i cant quite tell what ur referring to, since this moved to registry. is this still an issue?

**Comment by cnunciato** [comment]
The link is a bit outdated, but it's still an issue for the Node.js SDK, yeah. (The other languages appear to be doing the right thing, though.) See here, where clicking `InvokeOptions` brings you to the `pulumi/pulumi` docs, but doesn't anchor you to  anything related with `pulumi.InvokeOptions` (and indeed that interface seems to be missing from the page):

https://www.pulumi.com/registry/packages/aws/api-docs/sfn/getactivity/

![image](https://user-images.githubusercontent.com/274700/155403957-3513b663-2e91-4509-8861-ab515bd45a43.png)
