### ISSUE TITLE
Generate resource docs for remaining providers

### ISSUE THREAD

**Issue by praneetloke** [pulumi/docs#2785]
Related to #2555.

The following are ready to be generated
* [x] Aiven
* [x] Docker
* [x] GitLab
* [x] Kong
* [x] Mailgun
* [x] Random
------
* [x] Kubernetes (~~blocked by pulumi/pulumi#4269~~ docs PR https://github.com/pulumi/docs/pull/2890)

**Comment by praneetloke** [comment]
Yesterday (4/7/2020), we merged a PR with resource docs for most providers.

**Comment by praneetloke** [comment]
GitLab docs were added today with https://github.com/pulumi/docs/pull/2902.

**Comment by justinvp** [comment]
I added Random and Docker to the task list in the issue description above.

**Comment by praneetloke** [comment]
Thanks @justinvp. `random` and `docker` are actually ready to have resource docs generated for them. They have the `generate_schema` `make` target already. I have updated the task list above.

**Comment by justinvp** [comment]
> They have the `generate_schema` `make` target already.

Ah, got it. 👍

**Comment by praneetloke** [comment]
`random` and `docker` were included with https://github.com/pulumi/docs/pull/3044.
