### ISSUE TITLE
Fix broken link to ResourceGroupArgs page

### ISSUE THREAD

**Issue by zakaluka** [pulumi/docs#2811]
File: [docs/reference/pkg/azure/core/resourcegroup.md](https://www.pulumi.com/docs/reference/pkg/azure/core/resourcegroup/)

Link currently points to https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi.Azure/Pulumi.Azure.Core.Inputs.ResourceGroupArgs.html.  If it is only supposed to go to the section on Resource Group Arguments further down on the page, then it should be changed to an intra-document link.

**Comment by praneetloke** [comment]
Thanks for opening this issue! This will be fixed by #2820.

**Comment by praneetloke** [comment]
This is now fixed. The link for `ResourceGroupArgs` in the constructor will take you to the .NET docs page if you have the C# language chosen. I will go ahead and close this out now.
