### ISSUE TITLE
How to handle overlay schematization

### ISSUE THREAD

**Issue by lblackstone** [pulumi/docs#2831]
### Problem description

Upcoming documentation will be based on schemas, which don't include information about overlays (e.g., Helm + YAML support in the k8s provider).

@pgavlin mentioned that the schema is only intended to encode information about codegen types/resources, so we need to figure out where to put overlay information so that we can generate appropriate docs.

/cc @cnunciato @praneetloke

**Comment by praneetloke** [comment]
Related to pulumi/pulumi#4269.

**Comment by lukehoban** [comment]
We did add support for this and have used it a couple places - so closing for now.
