### ISSUE TITLE
Document policy package versioning

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#2843]
I would suggest we add a section on how to version your policy packages.

For example, if I try to publish the same version, I get an error: `error: Publish policy pack failed: [400] Bad Request: Policy Pack: aws-tags-policies, Version Tag: 0.0.2 already exists`. The version is taken from `package.json` (in my case, it's an NPM package), so all I need to do is `npm version patch` (or `... minor`, etc, based on my scenario), and then republish.

Also, if I remove a policy pack using `pulumi policy rm ...`, and then attempt to republish, it still prevents me from doing so. I assume this is intentional because we don't want to enable replacement of old versions. This is a subtle point, however, and probably warrants explicitly mentioning (e.g., something like [what NPM says about why this isn't allowed](https://docs.npmjs.com/cli/unpublish)).

Neither of these points may be obvious to folks -- especially those new to NPM, etc -- so it would be great to have a section in the docs, and maybe even refer to this page from the error message.

**Comment by justinvp** [comment]
@ekrengel, do you have cycles to work on this one next week?

**Comment by ekrengel** [comment]
Yup I’ll take it on
