### ISSUE TITLE
Change default card to summary

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#2850]
At the moment, we use a summary card with a large image as the default, with a giant purple Pulumi logo.

At least when referring to our documentation, this comes across as overly salesy in my opinion. For example, see this Tweet: https://twitter.com/MikhailShilkov/status/1247151947456679936?s=19.

I propose we instead use the smaller summary card when there isn't an explicit meta image (see here for the difference: https://sproutsocial.com/insights/twitter-cards).

**Comment by joeduffy** [comment]
@cnunciato thoughts?

**Comment by cnunciato** [comment]
I agree, makes sense, like it. Those are my only thoughts! 👍😄
