### ISSUE TITLE
Add tooltips to resource docs

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#2855]
- [x] Create a new `pulumi-tooltip` component
- [x] Use the tooltip for the "required" asterisks in the resource docs
- [ ] Use the tooltip on list pages (e.g., /pkg/aws) for individual modules, if possible

**Comment by joeduffy** [comment]
FWIW, I recently made a CSS style derived from the code copy button, for use on the slightly revised pricing page. Not sure if that's helpful here: 
![image](https://user-images.githubusercontent.com/3953235/78618586-db85da80-782f-11ea-9317-ceaa297c5907.png)

**Comment by cnunciato** [comment]
Absolutely is! I noticed that as well and was planning have a look at it. Thanks!

**Comment by cnunciato** [comment]
Little update on this: It looks like this is being complicated by the way Hugo and Autoprefixer are conspiring to do their respective minifications, so it's a bit more painful than it should be. 😕 Working on it, though.

**Comment by cnunciato** [comment]
Looking more closely at the data we have for the modules (which is pretty much just the module name), there isn't much value to be added with tooltips yet, and it'd also be rather annoying if they were dropped into the lists we have today:

![tooltip-mania mov](https://user-images.githubusercontent.com/274700/83310521-26352a80-a1c1-11ea-87a6-3a4d6e6c4d6e.gif)

So I'm going to forgo checking that last box for now. We've talked about rethinking these lists pages a bit, so when we do that, we can revisit whether tooltips might add value in that context.
