### ISSUE TITLE
Group required properties at the top of property tables

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#2870]
Currently, we list properties alphabetically, which can make it harder to see the required ones -- for example:

https://www.pulumi.com/docs/reference/pkg/aws/cognito/userpool/#userpoolschema

![image](https://user-images.githubusercontent.com/274700/78699734-33b4ef00-78b9-11ea-8c51-65e748e85f16.png)

We should group all required properties together at the top of property tables, and keep them sorted alphabetically within their groups.

**Comment by praneetloke** [comment]
@sean1588 can this be closed now?

**Comment by sean1588** [comment]
> @sean1588 can this be closed now?

yes we can close.
