### ISSUE TITLE
StackReference tutorial: formatting broken

### ISSUE THREAD

**Issue by Dominik-K** [pulumi/docs#2883]
File: [docs/tutorials/aws/aws-ts-stackreference.md](https://www.pulumi.com/docs/tutorials/aws/aws-ts-stackreference/)

[Source in the `examples` repo](https://github.com/pulumi/examples/blob/master/aws-ts-stackreference/README.md).

**Comment by stack72** [comment]
Hi @Dominik-K 

What do you mean broken? Does the code not work or is there some other issue you are running into?

I can fix up the issue

Paul

**Comment by stack72** [comment]
@Dominik-K yes I see the formatting issues :) I will fix those up! Thanks for pointing them out

**Comment by lukehoban** [comment]
This and several other tutorial formatting issues are due to https://github.com/pulumi/docs/issues/1091.  Closing this one to track there.
