### ISSUE TITLE
In API docs, make 'package details' section match that of the new 'package details' section in the resource docs

### ISSUE THREAD

**Issue by leezen** [pulumi/docs#2886]
This will require backporting changes to existing code generators from the schema-based code generator to have a provider section

**Comment by sean1588** [comment]
@leezen is this still an issue? Not sure I see what you are referring to....  Which page exactly did you see an example of this, because everywhere I see package details it appears to look the same to me.

**Comment by lukehoban** [comment]
I believe this is about the old Node.js and Python docs. 

I honestly don’t think this one is as important to prioritize.

**Comment by leezen** [comment]
@sean1588 @lukehoban yes -- this is about the old nodejs/python docs and having it match

**Comment by sean1588** [comment]
ahh ok. gotcha. thanks. ok, I will prioritize other issues then.
