### ISSUE TITLE
Scrub existing content (blogs, tutorials, etc.) for links to API docs and change to resource docs where possible

### ISSUE THREAD

**Issue by leezen** [pulumi/docs#2887]
We should grep through the `docs` repo itself along with `examples` for anywhere we might be linking to language-specific docs and link to resource docs if possible.

**Comment by jkisk** [comment]
This is complete with a few exceptions where the docs have not yet been generated for a provider (eg: docker, datadog, aiven, mailgun, random).

**Comment by leezen** [comment]
I think that's good for now, so I'll close this issue out.
