### ISSUE TITLE
Shorten "Continuous Delivery for Cloud Resources" ToC

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#2912]
This seems excessively lengthy for the ToC:

![image](https://user-images.githubusercontent.com/3953235/79032755-da211e80-7b5d-11ea-814e-bdc9017db603.png)

I realize we probably made this change to improve SEO in https://github.com/pulumi/docs/commit/488af5b6e8df9fabbeb312f574938293f19b8f46, however, we can make that change to the H1 without impacting the ToC nav title, which I think we want to be short, sweet, and consistent with other topics in the ToC.

**Comment by justinvp** [comment]
When generating the ToC, we could check the length of the string that will be used and [fail the build](https://gohugo.io/functions/errorf/) to prevent such accidental changes in the future. Something to consider.

**Comment by joeduffy** [comment]
What was the intention of this change? The change from "Continuous Delivery" to "Continuous Delivery for Cloud Resources" has four specific changes:

1. H1
2. Page title
3. Left nav bar
4. Breadcrumbs

If we only wanted the page title, for instance, we could make this change:

```diff
diff --git a/content/docs/guides/continuous-delivery/_index.md b/content/docs/guides/continuous-delivery/_index.md
index 601a1f8a5..7d5d5d15c 100644
--- a/content/docs/guides/continuous-delivery/_index.md
+++ b/content/docs/guides/continuous-delivery/_index.md
@@ -1,8 +1,10 @@
 ---
 title: Continuous Delivery for Cloud Resources
+h1: Continuous Delivery
 meta_desc: Pulumi's approach to infrastructure as code is great for CI/CD because it uses source code to model cloud resources and integrates into any CI/CD system.
 menu:
     userguides:
+        name: Continuous Delivery
         identifier: cont_delivery
         weight: 3
```

But that still leads to somewhat silly looking breadcrumbs:

![image](https://user-images.githubusercontent.com/3953235/79048613-2e1a1a80-7bd3-11ea-86d2-f4e06473de6c.png)

Especially when you drill into a specific provider, when it almost runs off the page:

![image](https://user-images.githubusercontent.com/3953235/79048645-56a21480-7bd3-11ea-99b3-0bab05d746df.png)

**Comment by justinvp** [comment]
Can’t remember off the top of my head, and on my phone, so not positive, but I think you can use `linktitle` to control the breadcrumb.
