### ISSUE TITLE
change url gcp service account

### ISSUE THREAD

**Issue by krystian-kulgawczuk-pr** [pulumi/docs#2916]
File: [docs/reference/pkg/gcp/serviceAccount/_index.md](https://www.pulumi.com/docs/reference/pkg/gcp/serviceaccount/)

https://www.pulumi.com/docs/reference/pkg/gcp/serviceAccount/ -> https://www.pulumi.com/docs/reference/pkg/gcp/serviceaccount/

**Comment by stack72** [comment]
Hi @krystian-kulgawczuk-pr 

Thanks so much for raising the issue here - we are tracking this issue in #2837 

So I am going to close this as a duplicate of that issue and we will look at fixing it there

Paul
