### ISSUE TITLE
Update pulumi config set --path to include how to escape periods

### ISSUE THREAD

**Issue by danfhernandez** [pulumi/docs#2917]
Is there a way to run `pulumi config set --path "top.level.lower.level" "value"` and receive the following result:

```
config:
  top.level:
    lower.level: value
```
The answer is yes!  You can update the command above to `pulumi config set --path '["top.level"].["lower.level"]' "value"` 

Would be great to document this here: https://www.pulumi.com/docs/reference/cli/pulumi_config_set/

**Comment by danfhernandez** [comment]
Make change here: https://github.com/pulumi/pulumi/blob/7382de6b5fea0525bb890117cd033c87c30970b0/pkg/cmd/pulumi/config.go#L256-L263

**Comment by lukehoban** [comment]
This was fixed awhile ago.
