### ISSUE TITLE
Incorrect property comment on ec2/Instance

### ISSUE THREAD

**Issue by praneetloke** [pulumi/docs#2919]
### Problem description

The property comment for the `iamInstanceProfile` also has the comment for `ipv6AddressCount `.

![Screenshot_2020-04-13 Instance](https://user-images.githubusercontent.com/1466314/79145310-46299f80-7d75-11ea-834e-d9898dbe1c8d.png)

### Affected product version(s)

N/A

### Suggestions for a fix

N/A

**Comment by praneetloke** [comment]
Here's the API doc link for the TS API showing the same problem: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/ec2/#Instance-iamInstanceProfile.

**Comment by ekrengel** [comment]
This is happening bc the markdown doesnt have a space where is normally does
