### ISSUE TITLE
Don't link constructor `args` to the API docs 

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#2962]
Today, in the resource docs, we link the `args` type in constructors to their respective API docs:

![image](https://user-images.githubusercontent.com/274700/79383206-a5281980-7f19-11ea-9f89-95819e0f3732.png)

This is both confusing and unnecessary, however, because the same properties are already right in front of you:

![image](https://user-images.githubusercontent.com/274700/79383281-ca1c8c80-7f19-11ea-95a7-3e192f6a3bf0.png)

We should not link off to the API docs in this case, because the user who clicks that link will likely wonder how it differs from what they're already looking at.  Instead, we should just anchor to the Input Properties table, and provide a link to the API docs from there or from somewhere else on the page.

**Comment by cnunciato** [comment]
cc @lukehoban @justinvp who may have thoughts on this, too.

**Comment by justinvp** [comment]
I'm torn on this. I agree that it is confusing to link away in this case when the resource args are right below (that we could just anchor link to). But all the other types in the constructor signature is linking away to the API docs. It'd be equally confusing to me that some of those links go to the API docs and others link within page.

As an alternative, what if we removed the links on parameters altogether? We could keep a single link in the signature, on the type itself (in this case `Bucket`), which would take you to the API docs for the type (and then you can navigate to related types within the API docs from there).

**Comment by cnunciato** [comment]
> But all the other types in the constructor signature is linking away to the API docs. It'd be equally confusing to me that some of those links go to the API docs and others link within page.

I do see that point, yeah. 🤔

**Comment by cnunciato** [comment]
I've been thinking about this and I think I'll close it this issue for now, as I agree it's probably more consistent to have them point to the same general place, and having the other links in the signature is helpful as well.
