### ISSUE TITLE
Clarify Inputs and Outputs in the resource docs

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#2963]
In the resource docs today, Input properties are accessible only via the Create a new [Resource Name] navigation item, while Output Properties get their own section in the on-page navigation:

![image](https://user-images.githubusercontent.com/274700/79384603-0f41be00-7f1c-11ea-8617-0dd8caee367a.png)

Since it's useful to be able to find and refer to Inputs independently of the context of creating a new resource, and because Inputs and Outputs are related so closely (e.g., we explain both under a section called [Inputs and Outputs](http://www.pulumi.com/docs/intro/concepts/programming-model/#outputs) in the Programming Model docs), it'd probably make sense to show them as siblings in the overall page hierarchy as well -- like this, maybe:

![image](https://user-images.githubusercontent.com/274700/79385279-27fea380-7f1d-11ea-902a-ad489295d454.png)

This seems both clearer and more usable to me. 

It's also been mentioned that these sections could also use a link to the Programming Model docs, for those who may be new to inputs and outputs. So in addition to the hierarchical/navigational changes noted above, we could add some descriptive text under the new Resource Properties heading, providing [a link to Inputs and Outputs in the docs](http://www.pulumi.com/docs/intro/concepts/programming-model/#outputs), and brief descriptions underneath the Inputs and Outputs sections as well -- e.g.:

![image](https://user-images.githubusercontent.com/274700/79386286-c50e0c00-7f1e-11ea-93ce-f0254d89d383.png)

![image](https://user-images.githubusercontent.com/274700/79388092-98a7bf00-7f21-11ea-8f37-3771cd5b9a4d.png)

And when no additional Output properties are available, that same message would instead read:

![image](https://user-images.githubusercontent.com/274700/79390761-289b3800-7f25-11ea-8cd1-27c4a0b5b6d9.png)

**Comment by justinvp** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/4408
