### ISSUE TITLE
Support API examples in other languages

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#3026]
Right now all of our API examples are in JavaScript/TypeScript. We need to add other languages:

For 2.0 launch:

- [x] Python 

Afterwards:

- [x] Go
- [x] C#

**Comment by stack72** [comment]
@joeduffy / @lukehoban I believe we can close this out now that https://github.com/pulumi/docs/issues/3528 is in place?

**Comment by joeduffy** [comment]
@stack72 Thanks for the ping. Yep, we've landed all languages 🎉 so fine to close this out.
