### ISSUE TITLE
Multiple missing links on AWS lambda Function resource

### ISSUE THREAD

**Issue by JamesHageman** [pulumi/docs#3052]
Hello! There are multiple broken links on the AWS lambda function resource page, which all look like this:
- "[What is AWS Lambda?][1]"
- "[entrypoint][3]"
- "[Lambda Permission Model][4]"
- "[Runtimes][6]"
- and more ...

File: [docs/reference/pkg/aws/lambda/function.md](https://www.pulumi.com/docs/reference/pkg/aws/lambda/function/)

**Comment by praneetloke** [comment]
Thanks for opening the issue! @ekrengel if I am not wrong your recent [PR](https://github.com/pulumi/pulumi-terraform-bridge/pull/166) fixes this, correct?

**Comment by ekrengel** [comment]
Yes I fixed this in the bridge. Not sure when those changes will get rolled out via a docs update?

**Comment by praneetloke** [comment]
Yeah once the providers are updated with the latest `tfgen` the fixes should automatically flow to the docs.

**Comment by stack72** [comment]
@praneetloke I believe we are due an update to *all* providers to fix a codegen issue in the next day or so

**Comment by praneetloke** [comment]
Closing this issue since the links are now properly hyperlinked.
