### ISSUE TITLE
Property inline code block is wrong / invalid

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#3064]
### Problem description

For resource property descriptions that have inline code blocks, the rendered code block is wrong / meaningless.

Example: https://www.pulumi.com/docs/reference/pkg/gcp/logging/projectsink/#inputs

![image](https://user-images.githubusercontent.com/293763/79938295-0f0c5b80-8411-11ea-8154-b408bc57843d.png)

This is true in the API-style documentation too - https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/logging/#ProjectSink-destination.

![image](https://user-images.githubusercontent.com/293763/79938461-86da8600-8411-11ea-81d1-63214e6bd36d.png)

**Comment by lukehoban** [comment]
I can no longer repro this - I believe it has been fixed.
