### ISSUE TITLE
Go and .NET missing from Tutorials

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#3067]
Go and C# missing from the Tutorials lang chooser. These are automatically pulled in from https://github.com/pulumi/examples which do have examples in these languages.

For example:

- https://www.pulumi.com/docs/tutorials/aws/
- https://www.pulumi.com/docs/tutorials/azure/
- https://www.pulumi.com/docs/tutorials/gcp/

---

<img width="609" alt="Screen Shot 2020-04-22 at 11 35 49 AM" src="https://user-images.githubusercontent.com/710598/80020350-bcbd5000-848d-11ea-92a0-80fd6dc53b7f.png">

**Comment by lukehoban** [comment]
Fixed with https://github.com/pulumi/docs/pull/3260.
