### ISSUE TITLE
Fix order of provider listing in left nav

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#3072]
### Problem description

The Provider listing in the API Reference in the left nav isn't in alphabetical order.

Is it being sorted case-sensitively? I don't think this is how humans expect it.

From https://www.pulumi.com/docs/reference/pkg/:
![image](https://user-images.githubusercontent.com/293763/80037375-5265d900-84a8-11ea-8774-a2053f4e8212.png)

### Suggestions for a fix

Alphabetize the list regardless of case.

**Comment by joeduffy** [comment]
I don't know when, but this seems to have been fixed.
![image](https://user-images.githubusercontent.com/3953235/122652095-bf4b2200-d0f1-11eb-94c8-41d37a353c98.png)
