### ISSUE TITLE
Consider using "Google Cloud" rather than "GCP" or "Google Cloud Platform"

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#3073]
Yes, our package is named "gcp," but consider using simply "Google Cloud," which is the brand that Google uses these days.

For example, in the API Reference listing:

<img width="952" alt="Screen Shot 2020-04-22 at 2 59 05 PM" src="https://user-images.githubusercontent.com/710598/80038298-38c59100-84aa-11ea-823f-f2c7581f6bc8.png">

Cloud Providers listing:

<img width="926" alt="Screen Shot 2020-04-22 at 3 09 02 PM" src="https://user-images.githubusercontent.com/710598/80038858-4deeef80-84ab-11ea-8a42-4332030f7700.png">

**Comment by susanev** [comment]
this is referred to as google cloud platform in the registry now
