### ISSUE TITLE
Windows installation page references using bash shell command

### ISSUE THREAD

**Issue by glennsarti** [pulumi/docs#3078]
File: [docs/get-started/install/_index.md](https://www.pulumi.com/docs/get-started/install/)

On the installing Pulumi page I click on the Windows tab (which is great)

![image](https://user-images.githubusercontent.com/5819622/80064289-4e9a8b00-856a-11ea-8493-bc202645a51c.png)

However the New Version Warning section down the bottom references using `curl`  and `sh` instead of PowerShell

![image](https://user-images.githubusercontent.com/5819622/80064349-6e31b380-856a-11ea-9094-3d0d52ec691f.png)

This could be very confusing for people as this is probably only applicable for MacOS and Linux style installs (excluding WSL and WSL2 here.)

**Comment by praneetloke** [comment]
@glennsarti thank you for creating an issue! As the sentence above the statement reads, it is just an example warning. 

> If a new version of Pulumi is available, the CLI produces the following _example_ warning when running any of the available commands:

When you do actually see the warning on your machine (or in CI), the warning does show the appropriate command for that platform. This section is merely meant to highlight that a user may see a warning if there is a new version, and is not meant to highlight any specific commands to perform an upgrade. Does that help clarify things?

**Comment by glennsarti** [comment]
@praneetloke While I can see  that _technically_, yes, it's an example but it's still confusing to see bash/curl when I've select Windows above.  Why not just get rid of the bash/curl command all together to make it cross platform as it's just an example?

Also I get the following on Windows, which redirects back to the page which has the confusing upgrade message.

```
C:\Source> pulumi version
v2.2.0
warning: A new version of Pulumi is available. To upgrade from version '2.2.0' to '2.6.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
C:\Source>
```

**Comment by praneetloke** [comment]
> Also I get the following on Windows, which redirects back to the page which has the confusing upgrade message.

Hmm I see the correct upgrade message on Windows. How did you first install the CLI?

(Note: I took this screenshot on my Windows machine a while back. The current CLI version is 2.8.2 at the time of this writing.)

![Annotation 2020-08-01 064532](https://user-images.githubusercontent.com/1466314/89103817-9468ba00-d3c9-11ea-94c4-9ad56dcec2b5.png)
