### ISSUE TITLE
Typo in `mangedsslcertificate` => links don't work

### ISSUE THREAD

**Issue by Dominik-K** [pulumi/docs#3086]
File: [docs/reference/pkg/gcp/compute/mangedsslcertificate.md](https://www.pulumi.com/docs/reference/pkg/gcp/compute/mangedsslcertificate/)

**Comment by Dominik-K** [comment]
Got that link from the overview: https://www.pulumi.com/docs/reference/pkg/gcp/compute/

There's also the correct one: https://www.pulumi.com/docs/reference/pkg/gcp/compute/managedsslcertificate/

**Comment by leezen** [comment]
Thanks for reporting this. It should be fixed as part of https://github.com/pulumi/pulumi-terraform-bridge/pull/171 when that change is part of future docs regeneration.
