### ISSUE TITLE
Unintended content in resource docs after examples

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#3096]
https://www.pulumi.com/docs/reference/pkg/aws/emr/cluster/#multiple-node-master-instance-group

After the last example, it looks like there is content from the TF markdown that's incorrectly being included:

<img width="834" alt="Screen Shot 2020-04-24 at 1 03 10 PM" src="https://user-images.githubusercontent.com/710598/80252335-f5932b80-862b-11ea-983d-80863240d836.png">

**Comment by lukehoban** [comment]
Same as https://github.com/pulumi/pulumi-terraform-bridge/issues/159 (which was just resolved)?

**Comment by lukehoban** [comment]
And also https://github.com/pulumi/docs/issues/3025?

**Comment by justinvp** [comment]
Yep, closing as dupe.
