### ISSUE TITLE
Improve State Management documentation

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#3104]
We need to make it much clearer that

* You can use alternative state backends if you want
* If you use the Pulumi Service,
    - It never sees your code
    - It never sees your cloud credentials

I get asked about these frequently and it's clear we don't do a great job explaining this.

**Comment by lukehoban** [comment]
The changes in #4869 addressed all of the core points noted here.  We still need to address https://github.com/pulumi/pulumi/issues/3152, and doing that may include a desire to add more to the backends page to references from the CLI, but I think we can close this specific issue for now.
