### ISSUE TITLE
Document Pulumi Cloud Console features

### ISSUE THREAD

**Issue by lindydonna** [pulumi/docs#316]
_Updated July 2019_

---

- [ ] Pulumi Service Overview
    - [ ] Accounts and Organizations
        - [x] Adding 3rd party Identities
        - [ ] Access token management
        - [x] Organization Kinds
        - [x] Product Editions
    - [ ] Features
        - [ ] Stack History
        - [ ] Encryption and Secrets
        - [x] Webhooks
        - [x] SAML SSO
            - [x] Guide for setting up Okta with Pulumi
            - [x] Guide for setting up AAD with Pulumi
        - [x] Pulumi GitHub Application
    - [x] Collaboration
        - [x] Creating Templates ("Deploy with Pulumi" buttons)
        - [x] Teams
        - [x] Organization Roles
        - [x] Stack Permissions
    - [ ] Continuous Delivery
        - [ ] Credential Management
        - [x] Integration Guides
            - [x] CircleCI
            - [x] Codefresh
            - [x] GitHub Actions
            - [x] GitLab CI
            - [x] Google Cloud Build
            - [x] Travis CI
            - [ ] Jenkins

**Comment by chrsmith** [comment]
Moving back into M0.17. There is a lot of stuff to cover, as well as always documenting newer features. So we'll just track this as an ongoing core of sorts to continue to chip away at providing docs for the service.

**Comment by joeduffy** [comment]
For this sprint, it would be good to cover this question specifically:

![image](https://user-images.githubusercontent.com/3953235/44926273-bc46d300-ad05-11e8-9857-dc4a4de7b044.png)

**Comment by ericrudder** [comment]
Ideally, we would also (eventually?) enable a workflow similar to when you
have a G doc on "My Drive" that you move to a "Team Drive" ...

**Comment by chrsmith** [comment]
Linked PR takes care of this for M0.17.

**Comment by chrsmith** [comment]
For M0.18 https://github.com/pulumi/docs/pull/624

**Comment by chrsmith** [comment]
No new service features of notes for M0.19, but we did add docs for more CI/CD integrations.

**Comment by chrsmith** [comment]
I won't have time to get to this for the current milestone.

**Comment by lukehoban** [comment]
Can we enumerate the gap from whats available to what needed?  And then move this to M26 to fill in that gap?

**Comment by chrsmith** [comment]
The linked PR adds the most critical missing pages (e.g. a section for user accounts, mentioning the relationship between identities and organization access.)

Moving this issue too M0.26 to track the few remaining pages we'll want to add. Specifically:

- [ ] Security - A page detailing Pulumi user access tokens, and how secrets are managed in the service. (Linking to how to encrypt data client-side so the Pulumi Cloud Console doesn't have access to sensitive information.)
