### ISSUE TITLE
Revise the Crosswalk docs and marketing material

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#3171]
There are three things we want to do here:

1) Make it clearer that Crosswalk is more of a "reference architecture", and that you are free to fork and build your own architectures

2) Ensure even coverage across all languages

3) Support the new Architecture superpowers -- the architecture link goes to "Architecture & Concepts" right now, which isn't quite right

**Comment by susanev** [comment]
@joeduffy i see there were a few prs associated with this issue, is there still more work to do here?

**Comment by joeduffy** [comment]
Actually not entirely sure. I don't think we successfully got even language coverage. There's a project now to get AWSX up across all languages, so perhaps this should fold into that workstream? @lukehoban ?

**Comment by lukehoban** [comment]
That’s right. Accomplishing (2) is one of the key outputs of https://github.com/pulumi/pulumi-awsx/issues/308 which is a significant effort underway now. 

I’m less clear on precisely what (1) and (3) are tracking. 

We could either leave this open as a work item as part of that larger epic, or close this out as a dupe. 

Cc @stack72.

**Comment by stack72** [comment]
I think we will close this out as a dupe as this will form part of our EPIC
