### ISSUE TITLE
Content in vSphere API docs

### ISSUE THREAD

**Issue by retgits** [pulumi/docs#3182]
### Problem description

There are a few pages in the vSphere API docs that have double dots between vSphere and the name of the function (like `vsphere..ContentLibrary`). That results in links going to a 404 page. Examples:

* https://www.pulumi.com/docs/reference/pkg/vsphere/getcontentlibrary/
* https://www.pulumi.com/docs/reference/pkg/vsphere/getcontentlibraryitem/

On some pages, the name of the function doesn't match the example given in Go (the other languages seem to be okay, though). As an example, [this](https://www.pulumi.com/docs/reference/pkg/vsphere/getcontentlibraryitem/#using) page is called `GetContentLibraryItem` but the Go example lists `LookupContentLibraryItem` (the other languages have the correct form).

On the main page for the [vSphere provider](https://www.pulumi.com/docs/intro/cloud-providers/vsphere/), might I suggest the Go example to be slightly different? I'd suggest

```go
package main

import (
	vsphere "github.com/pulumi/pulumi-vsphere/sdk/v2/go/vsphere"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		dc, _ := vsphere.NewDatacenter(ctx, "test", &vsphere.DatacenterArgs{
			Name: "Production-DataCenter"
		})

		return nil
	})
}
``` 
I think this would help devs that want to get started with a complete working sample.

### Affected product version(s)

Pulumi Docs

**Comment by leezen** [comment]
Regarding Get vs. Lookup, please see https://github.com/pulumi/docs/issues/3075

**Comment by leezen** [comment]
Sorry if I missed it, but I wasn't sure which links you're referring to that 404? The double `..` is indeed odd, but I didn't see a broken link there?

**Comment by retgits** [comment]
There are a few pages where the double dot seems to result in a broken link. For example https://www.pulumi.com/docs/reference/pkg/vsphere/distributedportgroup/ has a link for `vsphere..DistributedVirtualSwitch` where the target is `https://www.pulumi.com/docs/providers/vsphere/r/distributed_virtual_switch.html`. The latter page doesn't exist. The issue also exists on https://www.pulumi.com/docs/reference/pkg/vsphere/getdatastorecluster/ where there are links for `vsphere..NasDatastore`, `vsphere..VmfsDatastore` and `vsphere..VirtualMachine`. These links all result in 404 pages.

**Comment by retgits** [comment]
Thanks for pointing me to #3075 (which does seem to be closed?) for the Get vs Lookup. I agree with @justinvp that adding a note would be helpful for Go devs, especially since both functions exist (as mentioned here https://github.com/pulumi/pulumi-gcp/issues/330 as well).

**Comment by lukehoban** [comment]
I opened #4598 to track the third point which is broader than vSphere.  I don't see any instances of `..`.  Going to close this one out for now.
