### ISSUE TITLE
VirtualNetworkSubnet -> ID | Wrong tsdoc description

### ISSUE THREAD

**Issue by ValkyrieUK** [pulumi/docs#3188]
### Problem description

ID Property description for `VirtualNetworkSubnet` is incorrect. ID property has tsdoc of `The Resource ID of DDoS Protection Plan.` Seems to be a copy paste error.

### Affected product version(s)
v 2.0.0

### Suggestions for a fix

Description should change to something like `The ID of the vnet Subnet` or just something more accurate.

**Comment by lukehoban** [comment]
I can't tell exactly what page this was referring to - but we fixed a large class of this style of issue a few months back, so I expect it is no longer a problem.  Please do reopen with a link to the page if you still see isssues.
