### ISSUE TITLE
Please provide a proper example of getting existing vpc by name or id

### ISSUE THREAD

**Issue by naveenreddyin** [pulumi/docs#3202]
File: [docs/reference/pkg/aws/ec2/vpc.md](https://www.pulumi.com/docs/reference/pkg/aws/ec2/vpc/)

**Comment by leezen** [comment]
The resource docs are split into the resources themselves and functions for looking up resources: https://www.pulumi.com/docs/reference/pkg/aws/ec2/#functions

In this case, you'll want `GetVpc`
