### ISSUE TITLE
Docs: Receive a 404 when navigating to ConfigFileArgs class

### ISSUE THREAD

**Issue by uptownbrown** [pulumi/docs#3219]
- On the following page: https://www.pulumi.com/docs/reference/pkg/kubernetes/yaml/configfile/
- The ConfigFileArgs class links to: https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi.Kubernetes/Pulumi.Kubernetes.ConfigFile.html 
- Results in a 404

**Comment by stack72** [comment]
@mikhailshilkov / @metral / @lblackstone looks like there are no DotNet docs generated for pulumi-kubernetes

https://www.pulumi.com/docs/reference/pkg/dotnet

**Comment by praneetloke** [comment]
Actually, there is, or at least I think there are .NET docs available already. For example, clicking the constructor for `ConfigFile` does take you to the right page: https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi.Kubernetes/Pulumi.Kubernetes.Yaml.ConfigFile.html.

The link for `ConfigFileArgs` should go to https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi.Kubernetes/Pulumi.Kubernetes.Yaml.ConfigFileArgs.html, which is incorrect.

**Comment by stack72** [comment]
Oh I stand corrected - you are 100% right!
