### ISSUE TITLE
Add bottom padding for last item in a bulleted list

### ISSUE THREAD

**Issue by lindydonna** [pulumi/docs#324]
1. In quickstart/aws-extract-thumbnail.html, there is is a bulleted list within a numbered item. The next numbered item is too close to the last bullet.

![image](https://user-images.githubusercontent.com/4260261/40566581-3ddeb95a-6026-11e8-906a-a883dcd39b82.png)

2. Consider using filled-in bullets, rather than outline ones, to make them stand out more.

**Comment by justinvp** [comment]
I believe this has been addressed with the new styling.

<img width="937" alt="screen shot 2018-06-20 at 8 57 06 am" src="https://user-images.githubusercontent.com/710598/41669988-f5dd32c0-7467-11e8-9dd2-bb459b46d407.png">
