### ISSUE TITLE
Change AWS Getting Started example with S3 static website

### ISSUE THREAD

**Issue by zchase** [pulumi/docs#3243]
Currently, the AWS Getting Started flow has the user deploy an S3 Bucket and then add a KMS key to that bucket. We would like to test whether changing the content of the flow has any effect on user drop off. The suggested content change is for the user to deploy a static website to S3 and make a change to that site.

To perform an A/B test we will need to create a second AWS flow and then control the routing to each flow via Google Optimize.

**Comment by lukehoban** [comment]
This was done some time ago.
