### ISSUE TITLE
Update to Component Resource Docs

### ISSUE THREAD

**Issue by danfhernandez** [pulumi/docs#3248]
Improve current Component Resource section in the Programming Model page to be more digestible, clear and focused. 

Here's a link to the draft: https://docs.google.com/document/d/13XqwkMfyrL2vIWEmBPC24R7hhLLlI6Sc5uZdBxrBaDA/edit?usp=sharing

Todo: 
- [ ] create examples in all languages
- [ ] finish up draft for review
- [ ] incorporate draft into Programming Model docs

**Comment by leezen** [comment]
Closing outdated issue as the architecture/programming model pages have been reorganized.
