### ISSUE TITLE
Come up with a plan for tutorials

### ISSUE THREAD

**Issue by leezen** [pulumi/docs#3256]
Decide if we should regenerate or trim some (and have a plan for the ones we cull) or something else

Two parts
1. Stop the bleeding
2. How do we get to a "good situation"

This issues focuses on (1)

For (2), there's a separate overarching topic covered by another issue

**Comment by lukehoban** [comment]
I've re-generated the tutorials from current `examples` repo in https://github.com/pulumi/docs/pull/3260 which addresses the immediate need here.

I'll open new issues on (a) automating this process and (b) deciding what we want to do about examples/tutorials content overall.

**Comment by lukehoban** [comment]
https://github.com/pulumi/docs/issues/1671 actually already tracks keeping content for tutorials up to date.
