### ISSUE TITLE
Update _config.yml to make builds faster

### ISSUE THREAD

**Issue by lindydonna** [pulumi/docs#332]
Since we're no longer directly using the typedoc generated HTML, we should be able to remove this line:

```
include:
  - _*
```

This might make the docs builds faster.

**Comment by lindydonna** [comment]
@justinvp Since you've been looking at `_config.yaml` more recently, do you mind taking this?  We can push to M16 if necessary.

**Comment by justinvp** [comment]
Already fixed as part of #386 :smile:
