### ISSUE TITLE
Inputs & Outputs docs for Go aren't finished

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/docs#3363]
### Problem description

The language chooser on the "Programming Model" page still isn't quite complete. If you look at the "working with strings" section, the Go example doesn't show a complete `apply`:

https://www.pulumi.com/docs/intro/concepts/programming-model/#outputs-and-strings

```
var hostname pulumi.StringOutput
var port pulumi.NumberOutput

url := // ?
```

In addition to this, the accessing properties of an output section is also not complete:

https://www.pulumi.com/docs/intro/concepts/programming-model/#lifting

```
// Helpers for accessing properties are not yet available in Go.
```

**Comment by EvanBoyle** [comment]
The first one is just the setup for the below examples. Python and others are similar:

![Screen Shot 2020-05-20 at 8 21 31 AM](https://user-images.githubusercontent.com/2553171/82464553-1146f180-9a73-11ea-8754-c966b845aa9f.png)

For the second one, this is accurate as we don't currently support property lifting in Go and have no plans to do so as far as I'm aware. I guess we have the `Index()` functions on Map and Array outputs, that could be documented here, but I'm not sure this is a 1:1 mapping of the lifting feature.

**Comment by lukehoban** [comment]
I think the former is the same across all languages. It’s part of the narrative way of introducing the concept. No doubt a little awkward - but I believe not Go-specific.

For the latter - we could show off the accessor methods that are conventional on strongly typed Output structs here. They aren’t quite the same - but could make sense to highlight in this context.

**Comment by leezen** [comment]
Relatedly, this came up again in the case of `Index` on output types in Go for `ArrayOutput`s and not having great documentation for that.
