### ISSUE TITLE
Incorrect flag

### ISSUE THREAD

**Issue by thrixton** [pulumi/docs#3372]
File: [docs/reference/cli/pulumi_state_delete.md](https://www.pulumi.com/docs/reference/cli/pulumi_state_delete/)

Incorrect flag
(use ‘pulumi stack –show-urns’ to get it).

Should be
(use ‘pulumi stack **-**-show-urns’ to get it).
e.g. -- instead of -

**Comment by thrixton** [comment]
Maybe `pulumi stack --show-urns`

**Comment by leezen** [comment]
Thanks for reporting this
