### ISSUE TITLE
Skip regenerating the schema for providers during resource docs generation

### ISSUE THREAD

**Issue by praneetloke** [pulumi/docs#3378]
Now that we are starting to check-in the schema to each provider repo, we can simply reuse that schema for docs generation, and still keep the current code to generate schema but IFF the schema is not found (as a fallback.)

This is in the `scripts/gen_resource_docs.sh` script.

**Comment by stack72** [comment]
Hi @praneetloke 

I am going to reopen this - it doesn't seem like the path to the schema file is correct - I am looking at the latest AWS provider docs build

https://travis-ci.com/github/pulumi/pulumi-signalfx/jobs/343547892#L1557
