### ISSUE TITLE
infrastructureEncryptionEnabled seems to be set to false by default

### ISSUE THREAD

**Issue by robertwe** [pulumi/docs#3379]
If you would like to create a Postgres instance on Azure you can specify flag called `infrastructureEncryptionEnabled`. I have tried already few times to use it but looks like it simply does not work. Provided documentation says it can be set to `true`. 
What is interesting Terraform Azure provider (azurerm) got it well documented. 
https://www.terraform.io/docs/providers/azurerm/r/postgresql_server.html#infrastructure_encryption_enabled so this is experimental feature and it does not work at this moment. 

I think we should do the same in the Pulumi documentation - set this flag to `false` whenever it appears plus add same warning as on terrafrom azurerm provider doc page. 
It can generate a lot of frustration.  

File: [docs/reference/pkg/azure/postgresql/server.md](https://www.pulumi.com/docs/reference/pkg/azure/postgresql/server/)

**Comment by cnunciato** [comment]
Closing as the provider seems to honor setting this property to `true` now:

```typescript
const exampleServer = new azure.postgresql.Server("exampleserver", {
    // ...
    infrastructureEncryptionEnabled: true,
});
```

![image](https://github.com/pulumi/docs/assets/274700/0dcbcb5d-76bf-41ea-8cbf-bcd95ccb0711)
