### ISSUE TITLE
Update CLI docs to include --show-secrets flag for pulumi stack export

### ISSUE THREAD

**Issue by danfhernandez** [pulumi/docs#3398]
https://github.com/pulumi/pulumi/pull/4046 was released and the CLI shows the update but the website still needs to be updated to reflect this new functionality here: https://www.pulumi.com/docs/reference/cli/pulumi_stack_export/

**Comment by stack72** [comment]
This will be taken care of in today's v2.3.0 release

**Comment by stack72** [comment]
Closed via https://github.com/pulumi/pulumi/issues/4713
