### ISSUE TITLE
Add Gartner Press Release to https://www.pulumi.com/about/#newsroom

### ISSUE THREAD

**Issue by isaac-pulumi** [pulumi/docs#3418]
### Problem description

Press release published on Hubspot:
https://info.pulumi.com/press-release/gartner-cool-vendor-5_28_2020

**Comment by susanev** [comment]
@isaac-pulumi is this done?

**Comment by susanev** [comment]
im going to close this as its been sitting for a while and i received no response to my question. pls reopen if there's more to do here.
