### ISSUE TITLE
Strange rendering of examples in AWS Lambda Function docs

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#3428]
See https://www.pulumi.com/docs/reference/pkg/aws/lambda/function/.

* Some examples are outside of language choosers and are included inline in multiple languages. 
* Examples are overall strangely organized
* "Basic Example" is missing

**Comment by stack72** [comment]
Points 1 and 2 have been completed!

I am not sure why we lose the "Basic Example" now - it's part of the SDK https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/lambda/function.ts#L18

@praneetloke thoughts here?

**Comment by pgavlin** [comment]
Related: https://github.com/pulumi/pulumi-terraform-bridge/pull/211

**Comment by lukehoban** [comment]
This is fixed now.
