### ISSUE TITLE
Running the docs site locally should be easier

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#3494]
It's currently too resource-intensive for many users to run `make serve` locally, which is less than ideal for many reasons. We need to make it easy to run the website locally, ideally having it start up within some small number of seconds, be stable, and not need to consume many gigs of RAM.

**Comment by danfhernandez** [comment]
Yes this would be awesome and very helpful!

**Comment by davidwrede** [comment]
I think with the new pulumi-hugo module work that @cnunciato did, running a local site is much easier and faster.
