### ISSUE TITLE
Eliminate hyperlinks to TF docs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#3499]
It looks like we are emitting hyperlinks to TF docs. For instance, see [this page](https://www.pulumi.com/docs/reference/pkg/docker/getregistryimage/):

![image](https://user-images.githubusercontent.com/3953235/83781405-59553f00-a643-11ea-926a-0387af6c0ea1.png)

The `docker_image` hyperlink goes to https://www.terraform.io/docs/providers/docker/r/image.html. Shouldn't it link to https://www.pulumi.com/docs/reference/pkg/docker/remoteimage/?

Interestingly, [that resource page](https://www.pulumi.com/docs/reference/pkg/docker/remoteimage/) also links to TF docs!

**Comment by stack72** [comment]
@joeduffy I am working through this right now - I have managed this on a few resources so far - there is an issue in the home repo tracking this - ping me for more information if you need it

**Comment by joeduffy** [comment]
Ah got it, I'll close this as a dupe -- didn't know there was an existing issue.
