### ISSUE TITLE
Add package installation instructions to resource package pages

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#3513]
In the API docs, we had clear package installation instructions at the top of the page (for Node.js, at least). I find this helpful otherwise it's not exactly clear the recommended way to install a dependency on the package. Should we add something like this near the top of the page?

![image](https://user-images.githubusercontent.com/3953235/83954074-bcd59d00-a7fa-11ea-8bce-136d7bf6367d.png)

My understanding is the commands would look something like this:

* JS/TS: `npm install @pulumi/abc`
* Python: `pip install pulumi_abc`
* Go: `go get github.com/pulumi/pulumi-abc/sdk/v2`
* C#: `dotnet add package Pulumi.Abc`

**Comment by lukehoban** [comment]
This has a lot of overlap with the question of if/how we should unify the “cloud provider” docs (https://www.pulumi.com/docs/intro/cloud-providers/ ) with the “resource” docs (https://www.pulumi.com/docs/reference/pkg/). 

The cloud provider docs do include effectively this same information (not in exactly the same format - but with the same goal) - along with a lot of other information that is similarly critical to use the provider:
* what config parameters are available
* a short example
* pointers to tutorials and other content
* instructions on configuring access to the provider (even beyond just the config options)

It feels in principle these should be further unified (or at the very least cross linked back to).

**Comment by susanev** [comment]
closing this as complete since we have the install+config pages now, pls reopen if ive misunderstood and this is not complete yet.
