### ISSUE TITLE
As a docs editor, I want a WYSIWYG way of editing content

### ISSUE THREAD

**Issue by leezen** [pulumi/docs#3538]
Some potential options:
* https://www.netlifycms.org/
* https://www.datocms.com/
* https://forestry.io/

**Comment by susanev** [comment]
im going to close this out, if a team starts working on this they can reopen or open up a new issue.

**Comment by cnunciato** [comment]
This is actually something I would like to do at some point in the near future — mind if I reopen and put it on the Content Engineering board?

**Comment by susanev** [comment]
fine with me, i didnt know this was in the works for this year.

**Comment by susanev** [comment]
@cnunciato mind if i close this, def support something like this in marketing but not sure about docs. want me to transfer to the marketing repo?

**Comment by cnunciato** [comment]
We can close, yeah -- we have no concrete plans to do this yet, so no sense keeping this open any longer.
