### ISSUE TITLE
docs/guides/continuous-delivery/github-app.md Request: Troubleshooting section

### ISSUE THREAD

**Issue by jonsherrard** [pulumi/docs#3580]
File: [docs/guides/continuous-delivery/github-app.md](https://www.pulumi.com/docs/guides/continuous-delivery/github-app/)

I've tried installing / re-installing / re-generating `PULUMI_ACCESS_TOKEN`s, but I cannot get the App to work. If there's any knowledge floating around on how to get it working, I'd appreciate it!

**Comment by praneetloke** [comment]
@jonsherrard are you using GitHub Actions as your CI?

**Comment by jonsherrard** [comment]
Ah yes sorry should've mentioned!

**Comment by praneetloke** [comment]
Yes there is an [issue](https://github.com/pulumi/pulumi/issues/4613) specifically with GitHub Actions and the GitHub App. I am looking into it.
