### ISSUE TITLE
Markdown code block mis-rendering from template

### ISSUE THREAD

**Issue by stevenfollis** [pulumi/docs#3593]
File: [docs/tutorials/azure/azure-py-webserver-component.md](https://www.pulumi.com/docs/tutorials/azure/azure-py-webserver-component/)

Code blocks in the `azure-py-webserver.md` appear to be rendering incorrectly on Steps 5 & 8:

![image](https://user-images.githubusercontent.com/5393923/84570451-8f897180-ad5b-11ea-8ff2-4f214615ad4d.png)

![image](https://user-images.githubusercontent.com/5393923/84570458-9912d980-ad5b-11ea-904c-1a99677a5627.png)

[Original example code](https://github.com/pulumi/examples/tree/master/azure-py-webserver-component) _looks_ correct at first glance and renders properly in GH, so may be an issue in the Hugo templating?

**Comment by stevenfollis** [comment]
Also impacting other `Azure` -> `Python` Tutorials -

- [Azure Virtual Data Center (VDC)
](https://www.pulumi.com/docs/tutorials/azure/azure-py-virtual-data-center/)

![image](https://user-images.githubusercontent.com/5393923/84571164-94e8bb00-ad5f-11ea-863d-1fdaed4571e1.png)

- [Multiple Azure Kubernetes Service (AKS) Clusters](https://www.pulumi.com/docs/tutorials/azure/azure-py-aks-multicluster/)

![image](https://user-images.githubusercontent.com/5393923/84571182-9fa35000-ad5f-11ea-891a-5b5b675878b3.png)

- [Web Server Using Azure Virtual Machine](https://www.pulumi.com/docs/tutorials/azure/azure-py-webserver/)

![image](https://user-images.githubusercontent.com/5393923/84571190-a762f480-ad5f-11ea-9e4f-88a82edc3ab9.png)

(not exhaustive but capturing other similar locations where issue is visible)

**Comment by leezen** [comment]
Thanks for pointing this out. I believe this should be fixed when https://github.com/pulumi/docs/issues/1091 gets taken care of
