### ISSUE TITLE
outputs not working...

### ISSUE THREAD

**Issue by snolangps** [pulumi/docs#3607]
File: [docs/reference/pkg/aws/sns/gettopic.md](https://www.pulumi.com/docs/reference/pkg/aws/sns/gettopic/)

I'm using the following:
`const example = pulumi.output(aws.sns.getTopic({
	name: 'deviceConfigUpdates-3ce3de0'
}, { async: true }))
console.log('example', example.arn)
`

but i receive the following:
`example OutputImpl {
      __pulumiOutput: true,
      isKnown: Promise { <pending> },
      isSecret: Promise { <pending> },
      resources: [Function],
      allResources: [Function],
      promise: [Function],
      toString: [Function],
      toJSON: [Function] }
`

am i missing something, or should this be returning the `arn` as a string as expected by the docs and the code.

**GetTopicResult** shows:
`
export interface GetTopicResult {
    /**
     * Set to the ARN of the found topic, suitable for referencing in other resources that support SNS topics.
     */
    readonly arn: string;
    readonly name: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
`
but I'm not seeing that being returned...

**Comment by EvanBoyle** [comment]
pulumi.output is an asynchronous future, similar to a promise. You'll need execute your log from within an apply callback to get the raw value. You can read about this more in the programming model documentation for apply:

https://www.pulumi.com/docs/intro/concepts/programming-model/#apply
