### ISSUE TITLE
Integration Test Example has Invalid Import

### ISSUE THREAD

**Issue by carterwilliamson** [pulumi/docs#3619]
File: [docs/guides/testing/integration.md](https://www.pulumi.com/docs/guides/testing/integration/)

In the example, the package referenced is `"github.com/pulumi/pulumi/pkg/v2/testing/integration"`

From what I can tell, this package no longer exists and the correct package is `"github.com/pulumi/pulumi/pkg/testing/integration"`

**Comment by EvanBoyle** [comment]
The  `v2` form is the correct package. We version our modules with the major branch strategy outlined here: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

So even though the source path doesn't include the v2, the declaration in the go.mod does:

https://github.com/pulumi/pulumi/blob/master/pkg/go.mod#L1

Are you having problems being able to consume it?

**Comment by carterwilliamson** [comment]
Thanks for the quick reply - Good to know. I am having issues getting the package.
I have the v1 package installed. Not sure if that's causing the issues or not. I tried removing it but got a similar result.

My go version is `1.14.4`

I have tried the following - 
`go get github.com/pulumi/pulumi/pkg/v2/testing/integration` and `github.com/pulumi/pulumi/pkg/v2`

Both give me the same result:

```
package github.com/pulumi/pulumi/pkg/v2/testing/integration: cannot find package "github.com/pulumi/pulumi/pkg/v2/testing/integration" in any of:
        /usr/local/go/src/github.com/pulumi/pulumi/pkg/v2/testing/integration (from $GOROOT)
        /Users/<user>/go/src/github.com/pulumi/pulumi/pkg/v2/testing/integration (from $GOPATH)
```

**Comment by EvanBoyle** [comment]
Are you using go modules? If so, can you share your go.mod file? 

Using this one from the examples repo would be a good starting point: https://github.com/pulumi/examples/blob/master/testing-integration/go.mod

**Comment by carterwilliamson** [comment]
Aha! That did the trick. 

IMO this would be useful to add to this doc page. Seeing as Pulumi supports a variety of languages, you can expect non-go users to need integration tests (like me). :)

I appreciate the help. I'll close this out.
