### ISSUE TITLE
Add Interns to https://www.pulumi.com/about/#team

### ISSUE THREAD

**Issue by freddy-hernandez** [pulumi/docs#3668]
Sashu Shankar
![Sashu Shankar Headshot](https://user-images.githubusercontent.com/49878263/85631747-f4ca4600-b62a-11ea-8df5-3b6a10c041b0.jpeg)

Albert Zhong
![Albert Zhong Headshot](https://user-images.githubusercontent.com/49878263/85631768-fd228100-b62a-11ea-8469-7afb487ce2b1.jpeg)

Zephyr Zhou
![Zephyr Zhou Headshot](https://user-images.githubusercontent.com/49878263/85631765-fac02700-b62a-11ea-9f2f-dbd31a3b9bcb.jpeg)

**Comment by leezen** [comment]
We actually want them to do this themselves. It's part of the engineering onboarding to make a PR for it. I believe @albert-zhong has already done so. @sashu-shankar @zephyrz73 in case they missed this step in the new hire onboarding docs.
