### ISSUE TITLE
CLI doc for `pulumi new` has formatting issues

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#3669]
[These docs](https://www.pulumi.com/docs/reference/cli/pulumi_new/) currently look like this:

![image](https://user-images.githubusercontent.com/274700/85633897-13324080-b62f-11ea-8c88-5e63b5a17c70.png)

**Comment by lukehoban** [comment]
This appears to be fixed - possibly by https://github.com/pulumi/docs/pull/5418.
