### ISSUE TITLE
Move the PAC getting-started docs into User Guides > PAC

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#3694]
In order to keep the content int he Getting Started section focused on getting started with Pulumi, we should move the PAC-related docs into a subsection of User Guides > PAC.

![image](https://user-images.githubusercontent.com/274700/86055140-36ceff80-ba10-11ea-986d-174e4ecb31fb.png)

Part of #3693.

**Comment by susanev** [comment]
this is no longer in get started, so closing.
