### ISSUE TITLE
[Documentation] Missing the GCP ServiceAccount documentation for Python

### ISSUE THREAD

**Issue by alexsavio** [pulumi/docs#3717]
I found this missing part:

https://www.pulumi.com/docs/reference/pkg/python/pulumi_gcp/serviceaccount/

This is a broken link found in the docs, here: https://www.pulumi.com/docs/reference/pkg/gcp/serviceaccount/

In reality the listing here: https://www.pulumi.com/docs/reference/pkg/gcp/ 
should show 'service_account' and the target should be:
https://www.pulumi.com/docs/reference/pkg/python/pulumi_gcp/service_account/

**Comment by lukehoban** [comment]
We’ve previously fixed this for Node.js docs and Reference docs - but looks like we need to also fix for Python. 

https://github.com/pulumi/docs/issues/2837

**Comment by komalali** [comment]
This should no longer be an issue once https://github.com/pulumi/docs/issues/4071 is complete.

**Comment by davidwrede** [comment]
The broken link is fixed now per the work done for #4071.
