### ISSUE TITLE
StateMachine output - arn

### ISSUE THREAD

**Issue by dror-g** [pulumi/docs#3724]
File: [docs/reference/pkg/aws/sfn/statemachine.md](https://www.pulumi.com/docs/reference/pkg/aws/sfn/statemachine/)

Might be worth mentioning in the docs that the ARN for the created resource is the `.id` output.
Alternatively, perhaps an `.arn` output should be added, which is more in-line with other AWS resources.
Cheers.

**Comment by stack72** [comment]
Hi @dror-g 

There is now an ARN included as part of the output - I hope this helps - sorry that you ran into this issue

https://www.pulumi.com/docs/reference/pkg/aws/sfn/statemachine/#outputs

paul

**Comment by dror-g** [comment]
Awesome! no worries @stack72 , that's what we're here for :)
