### ISSUE TITLE
"see also" for every command in the reference has an artifact?

### ISSUE THREAD

**Issue by ericrudder** [pulumi/docs#374]
at the end of every page, there's now a 

see also

pulumi -

we can either drop the dash or add the description (which possibly is coming from the empty "Synopsis" field?  since if you look at the pulumi page the synopsis is blank) ... if needed, can make the synopsis "Pulumi command line" or something like that

**Comment by lindydonna** [comment]
@joeduffy Given that the fix is in the CLI generation code, should the owner be someone else?
