### ISSUE TITLE
Destroy the pulumi/staging stack

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#3770]
This stack hasn't been updated for about a year, and none of our CI is using it anymore (it's effectively been replaced by Pulumify), so we should destroy it, `rm` the stack, and delete `infrastructure/Pulumi.staging.yaml`.

https://app.pulumi.com/pulumi/www.pulumi.com/staging

**Comment by susanev** [comment]
@cnunciato do you know if this is still a thing we need to do?

**Comment by cnunciato** [comment]
Yep, it is -- I'll put it on my list.

**Comment by susanev** [comment]
we are planning to use this staging stack again, so closing
