### ISSUE TITLE
Include import ID information in the resources documentation

### ISSUE THREAD

**Issue by komalali** [pulumi/docs#3773]
### Problem description

We don't include the import ID information in our resource docs currently. We should add a section that includes this information. Specifically, four pieces of work needed:

- [x] Ensure Import details are made part of the schema resource description
- [x] Ensure import details + example is available in the code generated SDK comment
- [x] Ensure import section is included in the Resource docs
- [x] Ensure styling is applicable for the Import section

**Comment by clstokes** [comment]
I opened https://github.com/pulumi/docs/issues/4077 for a similar need for documenting the ID expected in `.get()` lookups. 

Is the `.get()` ID format the same that's used for `import`? If so, can we solve for `.get()` at the same time?

**Comment by stack72** [comment]
PRs open:

* https://github.com/pulumi/pulumi/pull/5667
* https://github.com/pulumi/pulumi-terraform-bridge/pull/291

**Comment by stack72** [comment]
Waiting for styling changes now! http://pulumi-docs-origin-pr-4556-3d839e5d.s3-website.us-west-2.amazonaws.com/docs/reference/pkg/azuread/application/

**Comment by lukehoban** [comment]
> Is the .get() ID format the same that's used for import? If so, can we solve for .get() at the same time?

The format is the same - so ideally we would address #4077  as part of this (possibly just with a note in the `get` section linking down to the import id section).
