### ISSUE TITLE
Malformed markup

### ISSUE THREAD

**Issue by benmccann** [pulumi/docs#3779]
File: [docs/tutorials/aws/aws-ts-hello-fargate.md](https://www.pulumi.com/docs/tutorials/aws/aws-ts-hello-fargate/)

See the section that says:

>Updating (dev):

It's malformed when rendered on the web. It looks okay at https://github.com/pulumi/docs/blob/master/content/docs/tutorials/aws/aws-ts-hello-fargate.md though

**Comment by leezen** [comment]
Likely another symptom of https://github.com/pulumi/docs/issues/3779

**Comment by benmccann** [comment]
@leezen you just linked to this issue. I think you meant to link to another one?

**Comment by leezen** [comment]
@benmccann Yes, silly me -- fixed.
