### ISSUE TITLE
sdk defn, version

### ISSUE THREAD

**Issue by ericrudder** [pulumi/docs#378]
i think it might be nice if we actually "defined" what the SDK was somewhere in the doc.  (if we do this, i'm sorry i missed it in my last pass.)

i also wonder if we should try to remove "hard coded" refs to the SDK version, and instead replace with a link to "latest" (or SDK releases or something) ... every once in a while i see text that has something like 12.2 and i just think to myself, maybe this should just say latest SDK.

**Comment by lindydonna** [comment]
@ericrudder Could you clarify the original intent of the issue?

**Comment by ericrudder** [comment]
Our docs introduce SDK without defining what is is ... we blur the CLI
distro with the traditional meaning of an SDK because of how we
package/deliver.

**Comment by lukehoban** [comment]
I think https://pulumi.io/reference/pkg/index.html is sufficient here for now.  Our "SDK" is really only `@pulumi/pulumi`, and isn't by itself a major component we need to define in docs.  Our ecosystem of packages more broadly is the primary thing users interact with - and is generally documented there.

That said - PRs for inclusions of additional prose to that page welcome.
