### ISSUE TITLE
Crosswalk syntax error

### ISSUE THREAD

**Issue by ericrudder** [pulumi/docs#3781]
### Problem description

- I saw a product documentation issue on the following URL: <URL>

 https://www.pulumi.com/docs/guides/crosswalk/aws/ecs/#using-an-existing-ecs-cluster with relevant information

- Other: <DETAILS>

Code doesn't compile at:
// Fetch an existing cluster.
const cluster = new awsx.ecs.Cluster("custom", {
    cluster: aws.ecs.Cluster.get("existing_cluster_id"),
});

Reported by:  Vladimir Makayev

**Comment by leezen** [comment]
It's not 100% clear to me what the compilation error was. I can only assume it was the missing import for `@pulumi/aws`? I'll leave this open to see if the original reporter might shed more light on this and fix the missing import in the meantime.

**Comment by leezen** [comment]
Closing this as we never heard back and hopefully the above PR addressed the original issue.
