### ISSUE TITLE
from / to address inconsistency

### ISSUE THREAD

**Issue by benmccann** [pulumi/docs#3784]
### Problem description

- I saw a documentation issue on the following URL: https://www.pulumi.com/docs/guides/crosswalk/aws/vpc/

The comment says "from" but the `description` says "to"

```
// 1) inbound SSH traffic on port 22 from a specific IP address
sg.createIngressRule("ssh-access", {
    location: { cidrBlocks: [ "203.0.113.25/32" ] },
    ports: new awsx.ec2.TcpPorts(22),
    description: "allow SSH access to 203.0.113.25",
});
```

### Suggestions for a fix

I think "to" should be changed to "from" ?

**Comment by leezen** [comment]
Thanks for catching that! https://github.com/pulumi/docs/pull/3785
