### ISSUE TITLE
Minor render bug

### ISSUE THREAD

**Issue by satya-waylit** [pulumi/docs#3798]
File: [docs/guides/crosswalk/kubernetes/control-plane.md](https://www.pulumi.com/docs/guides/crosswalk/kubernetes/control-plane/)

The second code snippet in the "Storage" section is interpreting the `*` as Markdown instead of code. As a result it's removed from the snippet and part of the code is rendered in italic. Perhaps a bug in the renderer. May be possible to work around using extra newline.

**Comment by susanev** [comment]
this no longer seems to be an issue, so closing.
