### ISSUE TITLE
ClusterAddonsConfigDnsCacheConfig description is wrong

### ISSUE THREAD

**Issue by runlevel5** [pulumi/docs#3887]
File: [docs/reference/pkg/gcp/container/cluster.md](https://www.pulumi.com/docs/reference/pkg/gcp/container/cluster/#clusteraddonsconfigdnscacheconfig)

### Expected:

description of NodeLocal DNS Cache controller

### Actual

description of PodSecurityPolicy

**Comment by lukehoban** [comment]
I see https://github.com/pulumi/docs/issues/3895 was opened just now as well - possibly based on the same feedback in another channel.  That issue has a little more detail and screenshots, and captures the general problems - so I'll close this one as a duplicate and track improving this page in https://github.com/pulumi/docs/issues/3895.
