### ISSUE TITLE
Docs recommend that ec2 instance creation uses a deprecated parameter. 

### ISSUE THREAD

**Issue by twk** [pulumi/docs#3904]
File: [docs/tutorials/aws/ec2-webserver.md](https://www.pulumi.com/docs/tutorials/aws/ec2-webserver/)

```
const server = new aws.ec2.Instance("webserver-www", {
    instanceType: size,
    securityGroups: [ group.name ], // reference the security group resource above
    ami: ami.id,
});
```

In your docs, you say that usage of `securityGroups` is [discouraged](https://www.pulumi.com/docs/reference/pkg/aws/ec2/instance/#securitygroups_nodejs).

**Comment by lukehoban** [comment]
Thanks - yes - we should update this tutorial and the examples it is based on in pulumi/examples.

**Comment by stack72** [comment]
@lukehoban *part* of this tutorial was already updated... it's the manually created tutorial. I just opened https://github.com/pulumi/docs/pull/3917 that fixes this
