### ISSUE TITLE
Tour of Pulumi uses `var` where the `aws-javascript` template uses `const`

### ISSUE THREAD

**Issue by pgavlin** [pulumi/docs#392]
Here's the template:
```
"use strict";
const pulumi = require("@pulumi/pulumi");
const aws = require("@pulumi/aws");

// Create an AWS resource (S3 Bucket)
const bucket = new aws.s3.Bucket("my-bucket");

// Export the DNS name of the bucket
exports.bucketName = bucket.bucketDomainName;
```

Here's an example from https://docs.pulumi.com/tour/basics-updating.html:
```
var bucket = new aws.s3.Bucket("my-bucket", { acl: "public-read" });
```

We may want to update the tour to use `const`.

**Comment by lukehoban** [comment]
Unfortunately JS has made life hard here - and there is no great answer.  We'll just want to pick a standard and use it consistently.

The two easiest places to land are:
1. Use `var` everywhere, and generally avoid ES6+ features.
2. Assume ES6 generally (it's been supported since Node 4) and use `const` where possible and `let` where necessary.

I don't love either option - but I'd suggest that (2) will be easier to be consistent about.  It's also closest to where our examples and templates are today.

**Comment by pgavlin** [comment]
> We'll just want to pick a standard and use it consistently.

This is really why I filed this. Not so much about `var` vs. `const`, much more about being consistent.

**Comment by ericrudder** [comment]
I agree we can assume ES6; in part because we're (mostly) dealing with new
code ...

**Comment by joeduffy** [comment]
My approach has been to stick to "classic" JavaScript for our JS examples, and newer ES6+ advanced functionality for our TS examples.  IMHO, this covers the broadest range of skillsets and meets people closer to where they are.  So, that's my vote.

**Comment by joeduffy** [comment]
(It also avoids issues if you try to run our stuff on downlevel Node.js versions, which is common.)

**Comment by lindydonna** [comment]
> My approach has been to stick to "classic" JavaScript for our JS examples, and newer ES6+ advanced functionality for our TS examples. IMHO, this covers the broadest range of skillsets and meets people closer to where they are. So, that's my vote.

It sounds like we're talking about features above Node 4, which is actually EOL. My vote is to just be compatible with 6.10.x.

**Comment by lindydonna** [comment]
Here's a handy table that shows language features and Node versions: https://node.green/

**Comment by lukehoban** [comment]
Yeah - it's not so much a question of whether or not it's supported in Node (these features have all been available in Node for many years).

It's a question of whether we want to default to using "new"-style syntax of "old"-style syntax.

Unfortunately, it's generally hard to pick a consistent model for sticking with "old"-style syntax - we would need to tell folks not to use dozens of little features that we use all the time (for..of loops, template strings, etc.) So either we would make up some semirandom set of rules about what is okay to use and try to enforce them, or we go with "use ES6 features" (e.g. everything supported on Node 6 and beyond).

As I said, on this particular point of `var` vs. `let` vs. `const` I just think the ECMAScript committee did the world a disservice by forcing the choice (yes, I was part of said committee at the time - but I swear I did everything I could to try to stop this :smile:) - and I wish we didn't have to think about this.  But consistency will be more important for our sanity than any other aspect here - and I'm not sure there's a good consistent option other than "const where possible let necessary" as part of a more general "use ES6".
