### ISSUE TITLE
Code snippet testing

### ISSUE THREAD

**Issue by leezen** [pulumi/docs#3939]
There's currently no testing of code snippets for correctness (or that they even compile). This might not be possible since in some cases, snippets will refer to non-existent variables/code. But, where possible, it'd be nice to have unit tests to verify correctness for things like https://github.com/pulumi/docs/pull/3932

**Comment by cnunciato** [comment]
Closing this as completed with the work that went into https://github.com/pulumi/docs/issues/10230.
