### ISSUE TITLE
Cloud Providers page should mirror the pkg page

### ISSUE THREAD

**Issue by nickpulumi** [pulumi/docs#3950]
### Problem description

- Other: <https://www.pulumi.com/docs/intro/cloud-providers/ should have the same information as this page https://www.pulumi.com/docs/reference/pkg/ 

### Suggestions for a fix

Can we just mirror the pages or redirect intro/cloud-providers/ to the reference/pkg

**Comment by lukehoban** [comment]
Agreed - I would love to unify these pages into one. Both one index and one page per provider that has both the reference docs and the details on how to use it so that there is a great “canonical link” for each provider.

**Comment by susanev** [comment]
im going to close this as fixed with registry.
pls reopen if you believe it is still an issue.
