### ISSUE TITLE
Rancher package missing API examples

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#3954]
The Rancher package seems to be missing most/all of its API examples. There are eight examples missing from the `Cluster` resource type, for example: https://www.pulumi.com/docs/reference/pkg/rancher2/cluster/.

**Comment by stack72** [comment]
This is because the docs files are non-standard and need overrides on each of them

**Comment by stack72** [comment]
Closing this out as we now have examples in place for this provider!
