### ISSUE TITLE
Changing only the Content-Type of a resource requires a CloudFront invalidation to take effect

### ISSUE THREAD

**Issue by ellismg** [pulumi/docs#397]
This is very likely not a bug here, but I'm capturing it here because this is where I discovered it.

> I submitted https://github.com/pulumi/docs/pull/387 and the corresponding update here https://app.pulumi.com/pulumi/docs/pulumi.io/pulumi.io-staging/updates/20 did update the property.  I then confirmed with the AWS CLI that the property was updated, but CF is not serving it.

Using the aws-cli to do an invalidation got things working again.  My current working theory is that since the content did not change, the etag in S3 did not change and so CF did not believe that the item had been updated in the origin, so it continued to serve the cached version, even after refreshing.

We'll need to do some directed testing here at some point, but for now the manual invalidation is a fine workaround.

**Comment by lukehoban** [comment]
Closing as this does not appear to be something that is still an issue.
