### ISSUE TITLE
Strip out all TODOs into GitHub issues

### ISSUE THREAD

**Issue by swgillespie** [pulumi/docs#403]
Per https://github.com/pulumi/docs/pull/401#discussion_r195840628

**Comment by lindydonna** [comment]
These are the main pending docs:
https://github.com/pulumi/docs/issues/429
https://github.com/pulumi/docs/issues/272
https://github.com/pulumi/docs/issues/271
https://github.com/pulumi/docs/issues/270
https://github.com/pulumi/docs/issues/120

If folks see anything else that's missing, please file a new issue.
