### ISSUE TITLE
Incorrect attribute in example

### ISSUE THREAD

**Issue by gh-lbaldwin** [pulumi/docs#4052]
File: [docs/reference/pkg/python/pulumi_aws/elasticsearch/_index.md](https://www.pulumi.com/docs/reference/pkg/python/pulumi_aws/elasticsearch/)

argument: cluster_config 
should have attribute Instance_type not cluster_config

Bad:
example = aws.elasticsearch.Domain("example",
    cluster_config={
        "cluster_config": "r4.large.elasticsearch",
    },

Good:
example = aws.elasticsearch.Domain("example",
    cluster_config={
        "instance_type": "r4.large.elasticsearch",
    },

Reference:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain

**Comment by komalali** [comment]
This should no longer be an issue once https://github.com/pulumi/docs/issues/4071 is complete.
