### ISSUE TITLE
make self-hosted service free

### ISSUE THREAD

**Issue by arash-bizcover** [pulumi/docs#4063]
Or let me save state to my local instead of Pulumi SAAS.

**Comment by stack72** [comment]
Hi @arash-bizcover 

We have a number of open source backends you can already use to save your state with Pulumi

You would 'pulumi logout' of the SaaS and then 'Pulumi login' to one of the other backends like in this doc

https://www.pulumi.com/docs/reference/cli/pulumi_login/

Paul

**Comment by arash-bizcover** [comment]
@stack72 thanks man 👍 👍 .

Since last year, whenever I searched Pulumi self managed I was seeing [only enterprise version](https://www.pulumi.com/docs/guides/self-hosted/) and was going back to my Terraform disappointed.

Now I can ditch Terraform harder than brick loops for good old js 😁.
