### ISSUE TITLE
Remove and redirect language-specific provider API docs

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#4071]
This issue tracks removing our language-specific **provider** API docs and redirecting them to their associated resource docs, which now have representation for all supported languages.

- [x] Python
- [x] .NET 
- [x] Node.js

This doesn't include our own API docs, of course (e.g., @pulumi/pulumi, @pulumi/policy, etc.) -- only those SDK docs that have corresponding entries at https://www.pulumi.com/docs/reference/pkg/.

**Comment by justinvp** [comment]
We'll need to disable linking to the API docs from the resource docs. I already implemented support for this in #5421, but it's currently [hard coded for the `azure-nextgen` package only](https://github.com/pulumi/pulumi/blob/83f2aa613bf70ec07773e47775e61b32033ffd11/pkg/codegen/docs/gen.go#L1883) (since we decided not to emit API docs for that package), so part of this would be disabling the linking for all packages.

**Comment by lukehoban** [comment]
> We'll need to disable linking to the API docs from the resource docs. I

One thought - should we link directly into GitHub source code?  That might be a way to still give folks a way to see the raw language-specific API details if they need them.

**Comment by clstokes** [comment]
Can we address https://github.com/pulumi/docs/issues/3641 before removing the language docs? `config` is a pretty commonly used and I don't want to remove the docs for it.

**Comment by cnunciato** [comment]
@lukehoban @leezen What do y'all think about @clstokes's question above, about provider config modules? Should #3641 that block this work? I'm working on this issue now and I'm not sure there's a clean way to keep just the config docs but drop everything else for a given provider.

**Comment by leezen** [comment]
While this is true, I think that the `Provider` resource for each provider adequately covers what's in `config`, so I'd personally still be comfortable proceeding.

**Comment by lukehoban** [comment]
Yeah - I think we don't have to block this work on #3641, but should try to address it soon.
