### ISSUE TITLE
Tushar Shah needs to be added to the teams page

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/docs#4090]
### Tushar Shah needs to be added to teams page ###

Tushar Shah's Title:          Senior Customer Engineer
Tushar Shah's Linkedin:    https://www.linkedin.com/in/tusharrshah
Tushar Shah's git:              https://github.com/tusharshahrs
![Tushar_Shah_Picture](https://user-images.githubusercontent.com/5281839/91494169-6d958a80-e886-11ea-8f8c-ed533c5af37c.jpeg)

**Comment by leezen** [comment]
@tusharshahrs Did you want to submit a PR for this yourself?

**Comment by tusharshahrs** [comment]
Updated picture provided as per Christian
![Tushar Shah Pulumi](https://user-images.githubusercontent.com/5281839/91720054-68755b80-eb64-11ea-89fb-3bbf523dd647.jpg)

**Comment by clstokes** [comment]
@tusharshahrs You can add yourself to the team page. See https://github.com/pulumi/docs/pull/3828 for a previous pull request that shows how.
