### ISSUE TITLE
Publish a roadmap

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#417]
As part of post-launch planning, let's make sure we emerge with an open source roadmap to share with the community.  This should include things like fleshing our AWS Serverless, Azure and GCP serverless capabilities, and more.  @lukehoban and I have been discussing how "far out" to go here -- we want to make sure we are reliable in delivering open source goodies on time -- and I think the [TypeScript Roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap) is a wonderful example for us to follow.

**Comment by lukehoban** [comment]
Created a first cut of the roadmap here: https://github.com/pulumi/pulumi/wiki/Roadmap.

Once this is reviewed, I'll add links to it from pulumi/pulumi README and from the docs site.
