### ISSUE TITLE
Review grunt hygiene issue in docs/install/index

### ISSUE THREAD

**Issue by ericrudder** [pulumi/docs#426]

**Comment by chrsmith** [comment]
Edited content, see email.

**Comment by ellismg** [comment]
@justinvp Per the discussion in https://github.com/pulumi/docs/commit/7b827d0e02560ff59873f7347ba33cba37961911, I'm giving this one to you, since you'll be adding back grunt and addressing the warning at the same time.

**Comment by justinvp** [comment]
#471 removes the need for grunt, so no need to add it back.

**Comment by lukehoban** [comment]
Is there any work being tracked by this issue?

**Comment by justinvp** [comment]
#471 removes the need to add back grunt.
