### ISSUE TITLE
Flesh out reference/gcp.html

### ISSUE THREAD

**Issue by lindydonna** [pulumi/docs#429]
https://pulumi.io/reference/gcp.html

**Comment by lindydonna** [comment]
@joeduffy @lukehoban This needs an owner.

**Comment by joeduffy** [comment]
@lindydonna Do you want to take an initial cut at this? It would be great to have more Google Cloud experts here on the team 😄

**Comment by lindydonna** [comment]
Sure thing. I can't promise M15.1 though, due to 2 conference talks next week.
