### ISSUE TITLE
Azure Next Generation Documentation hard to find easily

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/docs#4295]
### Azure Next Generation is hard to find.

 If you start from here:  https://www.pulumi.com/docs/ one would have no idea about azure next gen.
   The Get Started-> Azure References are all "@pulumi/azure"
   The examples are old azure.
    The easy way to currently get to azure next gen is 
    [Mikhails' Blog](via https://www.pulumi.com/blog/announcing-nextgen-azure-provider/)

https://www.pulumi.com/docs/ Next to AWS, put azure next gen, and move azure to the end of the list.  
The getting started link on the left side of the page, the azure next gen needs to be above azure.  
The examples need to be the ones that are in the blog, not the current one.

**Comment by lblackstone** [comment]
Dave is planning to work on the getting started guide for Azure NG, so assigning this to him to avoid duplicating effort here.

**Comment by lblackstone** [comment]
Getting started now defaults to native azure
