### ISSUE TITLE
Use friendlier clouds page for 404s (and address the logo, font, etc.)

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#433]
Currently:

![screen shot 2018-06-18 at 3 44 46 pm](https://user-images.githubusercontent.com/710598/41566066-9483efbe-730e-11e8-8395-35b880f83aa1.png)

**Comment by chrsmith** [comment]
It should just be a matter of replacing `denied-cloud` and `denied-beam` with `welcome-cloud` and `welcome-beam`.

**Comment by justinvp** [comment]
@chrsmith, can we delete `/welcome.html` from this repo? If so, I'll take care of it as part of this issue.
