### ISSUE TITLE
Typo Certifiate -> Certificate

### ISSUE THREAD

**Issue by shahiddev** [pulumi/docs#4340]
File: [docs/reference/pkg/azure/keyvault/certifiate.md](https://www.pulumi.com/docs/reference/pkg/azure/keyvault/certifiate/)

**Comment by stack72** [comment]
Hey @shahiddev 

Thanks for opening the issue here - this is a notice on those docs as follows:

> Deprecated: azure.keyvault.Certifiate has been deprecated in favor of azure.keyvault.Certificate

We picked up the typo but can't deprecate the class until the next major version

Paul

**Comment by shahiddev** [comment]
Apologies, didn't see that. 
I wonder if that deprecated warning should be at the top of the page?

**Comment by stack72** [comment]
yes you are correct - that should be right at the top

@cnunciato is this something we can do easily? Move the depreciations above the examples?
