### ISSUE TITLE
Stack names may be partially qualified

### ISSUE THREAD

**Issue by jamesianberry** [pulumi/docs#4365]
File: [docs/intro/concepts/programming-model.md](https://www.pulumi.com/docs/intro/concepts/programming-model/)

Stack names may be partially qualified, including organization, project, and stack name components, with valid formats including:
`//<stack>` (current organization and project assumed)
`/<project>/<stack>` (current organization assumed)
`<organization>/<project>/<stack>`

See the following working examples of this:
https://github.com/pulumi/examples/tree/master/azure-py-virtual-data-center
https://github.com/pulumi/examples/tree/master/azure-nextgen-py-virtual-data-center

**Comment by stack72** [comment]
Hi @jamesianberry 

Yeah I would agree here that we need to do some work as they can indeed be partially qualified to allow non-SaaS backends to use them

Paul
