### ISSUE TITLE
Remove Cloud Engineering Summit "SAVE YOUR SPOT" banner from https://www.pulumi.com/docs/

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#4366]
https://www.pulumi.com/docs/

<img width="1281" alt="Screen Shot 2020-10-11 at 12 11 58 PM" src="https://user-images.githubusercontent.com/710598/95687852-18ee6a80-0bbb-11eb-9301-f163435f22e9.png">

**Comment by davidwrede** [comment]
Banner was removed a while ago. Closing out this issue.
