### ISSUE TITLE
New Kubernetes Tutorial Request

### ISSUE THREAD

**Issue by pawanku2** [pulumi/docs#4375]
### Problem description

- I saw a product documentation issue on the following URL: <URL>

- I saw an issue on the following blog post: <URL>

- I had trouble finding the information that I needed: <URL>

- Other: <DETAILS>

**Comment by leezen** [comment]
Could you please clarify what kind of tutorial and content you're looking for?

**Comment by susanev** [comment]
@pawanku2 im going to close this out, but pls let us know if ya end up having more details to add and we can reopen this.
