### ISSUE TITLE
Code samples for S3 bucket notifications to SQS Queue do not work

### ISSUE THREAD

**Issue by smcoll** [pulumi/docs#4400]
File: [docs/reference/pkg/aws/s3/bucketnotification.md](https://www.pulumi.com/docs/reference/pkg/aws/s3/bucketnotification/)

When i run the "Add notification configuration to SQS Queue" and "Add multiple notification configurations to SQS Queue" Python code samples, i get the following error:

```
Updating (dev):
     Type                          Name                Status                  Info
     pulumi:pulumi:Stack           my-dev     **failed**              1 error
 +   ├─ aws:s3:Bucket              bucket              created                 
 +   ├─ aws:sqs:Queue              queue               created                 
 +   └─ aws:s3:BucketNotification  bucketNotification  **creating failed**     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (my-dev):
    error: update failed  aws:s3:BucketNotification (bucketNotification):
    error: 1 error occurred:
        * Error putting S3 notification configuration: InvalidArgument: Unable to validate the following destination configurations
        status code: 400, request id: AAA5A7D3EF2C8EEA, host id: uiodwz2bxuMpvMh29OFnC7GTt/066ddP49++qFYQIP812RD8gSzbl56KuDmkAMQawsi2yyURgbQ=
```
i'm suspecting that this is a dependency issue.  The article at https://aws.amazon.com/premiumsupport/knowledge-center/unable-validate-destination-s3/ (which pertains to CloudFormation, and SNS rather than SQS) seems to indicate that the SQS queue must exist before the bucket, because and the bucket before the policy.  Their solution is to specify a value for the bucket name before spinning up everything in that order.  

i'm hoping that doesn't have to be the case for Pulumi because i prefer the unique AWS resource suffixes.  But in any case, the code samples don't seem to work.

v2.12.0

**Comment by leezen** [comment]
I think the issue here is that the example references a hard-coded arn (in this case `s3-event-notification-queue`) as the example. You'll either want to control the name of the queue directly (so that you can do this kind of hardcoding) or if you're using autonaming, then you'll want to apply the queue policy after creating the queue so that you can reference its ARN as part of creating the policy like so:

```python
import pulumi
import pulumi_aws as aws

bucket = aws.s3.Bucket("bucket")
queue = aws.sqs.Queue("queue")
policy = aws.sqs.queue_policy.QueuePolicy("queue_policy", queue_url=queue.id,
    policy=pulumi.Output.all(bucket.arn, queue.arn).apply(lambda args: f"""{{
        "Version": "2012-10-17",
        "Statement": [
            {{
            "Effect": "Allow",
            "Principal": "*",
            "Action": "sqs:SendMessage",
            "Resource": "{args[1]}",
            "Condition": {{
                "ArnEquals": {{ "aws:SourceArn": "{args[0]}" }}
            }}
            }}
        ]
        }}
        """
    ))
bucket_notification = aws.s3.BucketNotification("bucketNotification",
    bucket=bucket.id,
    queues=[aws.s3.BucketNotificationQueueArgs(
        queue_arn=queue.arn,
        events=["s3:ObjectCreated:*"],
        filter_suffix=".log",
    )])
```

**Comment by smcoll** [comment]
Yes, that's it- thanks for explaining.
