### ISSUE TITLE
AWS App Mesh documentation does not include docs for VirtualGateway and GatewayRoute

### ISSUE THREAD

**Issue by tyronedougherty** [pulumi/docs#4428]
File: [docs/reference/pkg/aws/appmesh/_index.md](https://www.pulumi.com/docs/reference/pkg/aws/appmesh/)

The docs are missing documentation for the `VirtualGateway` and `GatewayRoute` Resources.

Would be awesome if we could get those added. I'd do it myself but I don't feel confident enough with Go/CSharp to add an accurate code sample.

Cheers!

**Comment by stack72** [comment]
Hi @tyronedougherty 

Apologies for this - I just merged a PR that fixes this up! It should be published within the next 30 minutes

Paul

**Comment by stack72** [comment]
https://github.com/pulumi/docs/pull/4450

**Comment by tyronedougherty** [comment]
Awesome!! Thanks so much :)
