### ISSUE TITLE
Confusion around the definition of Security Groups in docs

### ISSUE THREAD

**Issue by qasimalbaqali** [pulumi/docs#4504]
File: [docs/guides/crosswalk/aws/vpc.md](https://www.pulumi.com/docs/guides/crosswalk/aws/vpc/)

I could be wrong about this due to my limited knowledge in AWS, but the following statement is a bit confusing maybe for new comers like myself 

> All traffic in and out of a VPC is controlled by Security Groups, which act as virtual firewalls that limit inbound traffic to and outbound traffic from your VPC. [SOURCE](https://www.pulumi.com/docs/guides/crosswalk/aws/vpc/#configuring-security-groups-for-a-vpc)

Isn't a security group is connected to an instance **of** a VPC and acts as a firewall for an EC2 instance but not the VPC as a whole? The following defintion is taken from AWS documentation

> A security group acts as a virtual firewall for your instance to control inbound and outbound traffic. When you launch an instance in a VPC, you can assign up to five security groups to the instance. Security groups act at the instance level, not the subnet level. Therefore, each instance in a subnet in your VPC can be assigned to a different set of security groups. [SOURCE](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html)

If you guys agree, I could create a PR to update the definition.

**Comment by stack72** [comment]
Hi @qasimalbaqali 

You are correct - the details used here are not correct. If you would be happy to shape this up, according to the AWS docs you quotes, I'd be happy to see that PR

Paul

**Comment by qasimalbaqali** [comment]
Thanks for the reply @stack72. I have created a PR accordingly #4505

**Comment by stack72** [comment]
Closed via #4505
