### ISSUE TITLE
Please mention to install aws plugin

### ISSUE THREAD

**Issue by henninge** [pulumi/docs#4506]
File: [docs/get-started/aws/create-project.md](https://www.pulumi.com/docs/get-started/aws/create-project/)

When doing `pulumi up` two pages later, I ran in to this:

    Diagnostics:
      pulumi:providers:aws (default_3_11_0):
        error: no resource plugin 'aws-v3.11.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource aws v3.11.0`

I did as requested and it worked. I guess the guide should either mention the command here or `pulumi new aws-python` should do it for me.

Thanks.

**Comment by stack72** [comment]
Hi @henninge 

This should already automatically be handled for you as part of installing the Python Pulumi-aws package

Did you receive any errors when you used the aws-Python template?

**Comment by henninge** [comment]
Hi @stack72 !

Thanks for responding. I re-tried it to see what happened and found out that plugins get cached during `pulumi up`. I guess this did not happen for me because I first encountered this bug: #3981 when running `pulumi up`. With the workaround for the bug in place, the caching happens as expected. I am not sure if the but is actually in the caching code?

**Comment by henninge** [comment]
A fix has been merged for #3981 which I see as being responsible for my problem here. So this ticket can be closed.
