### ISSUE TITLE
Missing resources in GCP API documentation

### ISSUE THREAD

**Issue by cloudcalvin** [pulumi/docs#4514]
File: [docs/reference/pkg/gcp/cloudfunctions/_index.md](https://www.pulumi.com/docs/reference/pkg/gcp/cloudfunctions/)

It seems like some of the Resources are not listed on the page, such as CallbackFunction and HttpCallbackFunction for example.

**Comment by komalali** [comment]
Dupe of https://github.com/pulumi/pulumi/issues/4785, tracking there
