### ISSUE TITLE
Make Automation API more easily navigable from the docs

### ISSUE THREAD

**Issue by danfhernandez** [pulumi/docs#4522]
It's currently not very intuitive or easy to find the automation api docs when navigating in the docs site. 

You have to know what you're looking for and spelunk around the pulumi sdk docs.  

It would be great to have a user guide on Automation API similar to the blog post at https://www.pulumi.com/blog/automation-api/ or have an additional link in the list of packages that links directly to the API docs.

**Comment by clstokes** [comment]
These docs are now available at https://www.pulumi.com/docs/guides/automation-api/ and linked in the sidebar.
