### ISSUE TITLE
Pulumi Website: Dark Mode

### ISSUE THREAD

**Issue by rafaribe** [pulumi/docs#4526]
Many of us programmers prefer the Dark. 
This has nothing to do with some of us being coding vampires 😂, but in all seriousness it would be cool if the Pulumi website, which many of us use daily to look at the API references could have a toggled option that would allow us to choose freely between the current light design vs dark.

**Comment by susanev** [comment]
im going to close this out as a duplicate, but we are working on this, and hope to have something out in the coming months!

**Comment by wommy** [comment]
@smithrobs  404
