### ISSUE TITLE
Import CLI command not showing on left-hand nav-bar

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#4532]
I initially thought `import` wasn't getting documented in the usual CLI reference ways, but [it is](https://www.pulumi.com/docs/reference/cli/pulumi_import/). It's simply missing from the left hand nav-bar.

![image](https://user-images.githubusercontent.com/3953235/98390062-c2cde500-2009-11eb-8fc6-9de1fe5ca0c6.png)

Maybe adding new commands to the nav-bar is a manual process. In addition to adding `import`, it's worth double checking that nothing else is missing.

**Comment by stack72** [comment]
I missed that this was a manual command - I will send a PR for this today and look for the missing pieces
