### ISSUE TITLE
Document import command

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#4533]
We should document how to use the new `import` command on the [Adopting Pulumi guide's "Importing Infrastructure" page](https://www.pulumi.com/docs/guides/adopting/import/).

**Comment by stack72** [comment]
I will ensure this is part of the current import docs work

**Comment by joeduffy** [comment]
@stack72 I am curious, was this scoped as part of delivering the import feature?

@davidwrede Good to think about overall process for documenting feature launches. I will observe we often blog and then move on without the corresponding product docs. I love blogging, but always prefer to link end users to the official docs.

**Comment by stack72** [comment]
Posting here a quick update I gave to @joeduffy on this. This was not forgotten, just a couple of time sensitive items needed to happen first

https://github.com/pulumi/docs/pull/4726

That PR should update the guide

@joeduffy / @davidwrede I'd love your thoughts on that please

**Comment by davidwrede** [comment]
@joeduffy Yup, I agree that it's good to have blog posts that help raise awareness of new features, but we should always strive to have corresponding docs available for users at launch. Of course, being able to do that is highly dependent on available resources and time. 

Happy to help contribute to time estimation for upcoming feature doc work as we do future quarterly and milestone planning.
