### ISSUE TITLE
@pulumi/cloud docs seems to be missing API types

### ISSUE THREAD

**Issue by pgavlin** [pulumi/docs#455]
<img width="1680" alt="pulumi-cloud-docs" src="https://user-images.githubusercontent.com/1224093/41931111-f1e0acc8-7931-11e8-9c6b-0459b2624672.png">

I would have expected to see the definitions for `cloud.ServiceArguments`, `cloud.Container`, etc.

**Comment by joeduffy** [comment]
Assigning to @lukehoban , not sure who he wants to own issues like this.

**Comment by swgillespie** [comment]
This is probably a dupe of this: https://github.com/pulumi/docs/issues/400

**Comment by lukehoban** [comment]
Closing as dupe.
