### ISSUE TITLE
/docs UX Improvements

### ISSUE THREAD

**Issue by isaac-pulumi** [pulumi/docs#4579]

**Comment by isaac-pulumi** [comment]
## Problem
High bounce/high traffic page with little user help (blended score = 7182).
Paths below /docs have similar names (get-started, intro, tutorials, guides) - each area is poorly defined.

## Proposed Fix
- [ ] UX help for navigating/understanding /docs sections would be nice (cards with descriptions?)

**Comment by susanev** [comment]
gonna close this out, as we have related planned work this year.
