### ISSUE TITLE
Address high bounce rate on /docs/get-started/azure/

### ISSUE THREAD

**Issue by isaac-pulumi** [pulumi/docs#4581]
## Problem
/docs/get-started/azure/ has a blended score of 4647 (3rd highest for negative feedback, traffic and bounce).

## Proposed Solution
UX Design help needed. This is a very barebones page. We should have some additional, helpful info/links such as:

- [ ] We should tease tutorials here because 'get started' could mean 'try something' if the user is already set up. 

- [ ] Add a quick guide / or checklist (e.g. install pre-reqs, deploy your first project, tutorials, examples)

- [ ] Highlight azure-nextgen as an option (via CTA?)

**Comment by susanev** [comment]
we made some changes here, and are planning for a redesign of these guides in the future. closing this one out.
