### ISSUE TITLE
Address high bounce rate on /docs/get-started

### ISSUE THREAD

**Issue by isaac-pulumi** [pulumi/docs#4582]
## Problem
/docs/get-started has the 4th-highest blended score (4152) for bounce/traffic/negative feedback.

## Proposed Solution

- [ ] Make 'cloud providers for other clouds' more discoverable with a CTA button instead of a link.

- [ ] Add better intro text "Ready to get started using Pulumi on your preferred cloud using your favorite languages? Pick a cloud below for step-by-step instructions and you'll be up and running in no time."

**Comment by davidwrede** [comment]
Intro text has been updated to be more descriptive. See https://www.pulumi.com/docs/get-started/. 

The other cloud providers link has remain unchanged (i.e. not a CTA button). Updating the getting started experience for additional cloud providers will be based on usage, customer feedback, and page view information.
