### ISSUE TITLE
Address user feedback on /docs/intro/concepts/state

### ISSUE THREAD

**Issue by isaac-pulumi** [pulumi/docs#4583]
## Problem
This page has a high blended score (3803) for traffic, bounce, and negative feedback. There are two pieces of user feedback that appear actionable.

NOTE: Unclear how far we should go down the path of making self-hosting state 'easy' but we can address inaccuracies or gaps.

## Proposed Solution

- [ ] One commenter requests more info about state clean-up in this doc.

- [ ] Azure-specific feedback (e.g. replace 'bucket' with 'container') in the Azure example.

**Comment by susanev** [comment]
these pages were redone since this issue was opened, so closing
