### ISSUE TITLE
Add multi-lang examples to /docs/tutorials/aws/ecs-fargate/

### ISSUE THREAD

**Issue by isaac-pulumi** [pulumi/docs#4584]
## Problem
This page has a high blended score (2989) for traffic, bounce and negative feedback. One primary issue is that it is TypeScript-only.

## Proposed Solution

- [ ] Write examples for C#, Golang, Python 

- [ ] Add language picker

- [ ] Add a short intro to the page describing why ECS and Fargate are useful.

**Comment by davidwrede** [comment]
Tracking the parity work in #5010.

**Comment by susanev** [comment]
looks like Dave fixed this, pls reopen if there are still issues.
