### ISSUE TITLE
Add multi-lang examples to /docs/reference/pkg/aws/ec2/securitygroup/

### ISSUE THREAD

**Issue by isaac-pulumi** [pulumi/docs#4591]
## Problem
Language picker is missing from the first 4 example code snippets.

## Proposed solution

- [ ] Add multi-lang examples and code-picker to the first 4 examples on the page.

**Comment by stack72** [comment]
@isaac-pulumi im going to close this as a dupe of https://github.com/pulumi/docs/issues/4573
