### ISSUE TITLE
Upcloud as a cloud provider

### ISSUE THREAD

**Issue by bkmgit** [pulumi/docs#4601]
### Problem description

It would be nice to have [Upcloud](https://upcloud.com) as a provider

**Comment by mikhailshilkov** [comment]
Probably belongs to https://github/pulumi/pulumi but I can't seem to move it there...

**Comment by bkmgit** [comment]
Thanks created new issue [https://github.com/pulumi/pulumi/issues/5772](https://github.com/pulumi/pulumi/issues/5772)
