### ISSUE TITLE
Formatting issue on resource `merge` docs

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#4607]
### Problem description

The Python docs for the `merge` function have formatting issues with the ordered list - e.g. https://www.pulumi.com/docs/reference/pkg/python/pulumi/#pulumi.ResourceOptions.merge.

![image](https://user-images.githubusercontent.com/293763/99412651-d438ac00-28a9-11eb-8396-5fb9a527499b.png)

**Comment by komalali** [comment]
I think this can probably be corrected in the source code with some tweaking.
