### ISSUE TITLE
BucketObjects are re-deployed with no changes

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#465]
We seem to re-deploy BucketObjects even if they don't contain changes, stretching out the update time in this repo from what would have otherwise likely been seconds, to 10s of minutes.

I thought we had a bug tracking this elsewhere, but couldn't find it handy.  Feel free to dupe it if we have a bug.  However, if it's elsewhere (like the AWS repo), let's keep this bug open to track the resolution of the CI time in this repo specifically.  Let's aim to fix this in M16.

**Comment by joeduffy** [comment]
Note that, strangely, it's not *all* content that gets updated.  Do we just have some timestamps or something for a subset of the contents that trigger the updates?  If we committed the `_site` directory rather than regenerating it in CI, would that help?

```
<snip>
~  aws:s3:BucketObject quickstart/aws-s3-website.html updated changes: ~ source
 ~  aws:s3:BucketObject quickstart/index.html updating.. changes: ~ source
 ~  aws:s3:BucketObject quickstart/index.html updated changes: ~ source
 *  aws:s3:BucketObject quickstart/part1.html unchanged 
 *  aws:s3:BucketObject quickstart/part2.html unchanged 
 *  aws:s3:BucketObject redirects.json unchanged 
 ~  aws:s3:BucketObject reference/aws.html updating changes: ~ source
 ~  aws:s3:BucketObject reference/aws.html updated changes: ~ source
 ~  aws:s3:BucketObject reference/azure.html updating changes: ~ source
 ~  aws:s3:BucketObject reference/azure.html updated changes: ~ source
 ~  aws:s3:BucketObject reference/cd-travis.html updating.. changes: ~ source
 ~  aws:s3:BucketObject reference/cd-travis.html updated changes: ~ source
 ~  aws:s3:BucketObject reference/cd.html updating.. changes: ~ source
 ~  aws:s3:BucketObject reference/cd.html updated changes: ~ source
 *  aws:s3:BucketObject reference/cli/README.txt unchanged 
 ~  aws:s3:BucketObject reference/cli/pulumi.html updating changes: ~ source
 ~  aws:s3:BucketObject reference/cli/pulumi.html updated changes: ~ source
 ~  aws:s3:BucketObject reference/cli/pulumi_cancel.html updating changes: ~ source
 ~  aws:s3:BucketObject reference/cli/pulumi_cancel.html updated changes: ~ source
<snip>
```

**Comment by justinvp** [comment]
I believe the reason so many pages needed to be re-deployed is because #464 included a change to [`_includes/head.html`](https://github.com/pulumi/docs/blob/master/_includes/head.html) (to add the anchor script), which affects pretty much every page.

**Comment by joeduffy** [comment]
Ah okay, that makes sense. Every time I look at a job it seems to be deploying too much, but I agree in this case it seems exactly right. Perhaps we just change templates more than I thought.

Parallelism can't come soon enough!
