### ISSUE TITLE
Prune the Kubernetes types

### ISSUE THREAD

**Issue by hausdorff** [pulumi/docs#468]
In Kubernetes, we distinguish between "top-level" API objects (_i.e._, standalone types that can be submitted to the API server, like `apps/v1/Deployment`), and non-top-level API objects types (_i.e._, the nominal types that top-level types are made up from).

Currently we list in the Kubernetes docs index _every_ nominal type in the spec, but really we only need the index to show these "top-level" types.

We should filter the indexes down to contain only these types. Note that every top-level type will contain members `kind` and `apiVersion`, so this is fairly easy to do distinguish.

**Comment by hausdorff** [comment]
cc @joeduffy

**Comment by lukehoban** [comment]
I'm not sure we want to remove these types from the docs if they are really there.

Should we perhaps embed those support types in submodules or somehow distinguish them more explicitly in the API itself?

Notably - even the Kubernetes API docs themselves haven't "solved" this problem - they present all the types/objects: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/

**Comment by hausdorff** [comment]
I don't think we should remove them from the docs, I'm just saying we should remove them from the index. In other words, where the index now is a list of stuff like `core.v1.PodTemplateSpec`, it should be pruned to, _e.g._, `core.v1.Pod`, which _references_ the `PodTemplateSpec`. This is how the kube docs work, too, which is one of the reasons I think it's useful to do.

**Comment by lukehoban** [comment]
We don't really have a unified index - we have per-module pages.  So is your suggestion that we'd remove types listed at the top of pages like https://pulumi.io/reference/pkg/nodejs/@pulumi/kubernetes/apps/v1/?  I feel like that would be rather confusing in isolation.

Perhaps the suggestion is sort of the opposite - to include an additional overall index of the top-level API objects on https://pulumi.io/reference/pkg/nodejs/@pulumi/kubernetes/index.html (possibly even manually curated as part of a general mechanism to inject a top-level doc comment block as a package/module-scope block of text?)

**Comment by hausdorff** [comment]
Talking with @lukehoban offline I think we agree on the need to build a "consumable" interface to the docs, so rather than continuing this discussion in terms of what the docs for various Pulumi modules should look like, it seems like it probably makes sense to talk about what "consumable" docs look like.

I understand Luke's proposal to basically to have a godocs-style package-level overview that provides a somewhat curated view of the interface, coupled with perhaps some even-higher-level docs aimed at helping people get started. Missing anything @lukehoban?

**Comment by joeduffy** [comment]
We've made a ton of progress since this issue was filed. Closing out. If there are still concrete suggestions here, please reopen with details or file a new, detailed issue.
