### ISSUE TITLE
Pulumi vs Other under Intro

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/docs#4689]
### Problem description
  On https://www.pulumi.com/docs/
The left side under `INTRO` has `Pulumi vs. Other`.
https://share.getcloudapp.com/7Kub2pEr

Does it need to be `Pulumi vs. Others` or `Pulumi Other Software`

**Comment by clstokes** [comment]
@tusharshahrs do you mean `Pulumi vs. Other Software` as your suggestion?
