### ISSUE TITLE
Datadog-Dashboard page has rendering issue

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/docs#4703]
### Problem description

- I saw a product documentation issue on the following URL: https://www.pulumi.com/docs/reference/pkg/datadog/dashboard/

The page renders slowly and strangely where the left panel disappears and then appears and then examples disappear for a bit and the finally the page settles down.

I would not consider this a major issue, but it is disorienting the first time it is encountered to the point where I felt it was necessary to refresh the page (which just started the cycle again).

[internal recording](https://pulumi.slack.com/archives/C85BS3LJZ/p1606921015159200)

**Comment by cnunciato** [comment]
Closing as no longer reproducible.
