### ISSUE TITLE
add converters to left nav of docs

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/docs#4710]
## design details
- [x] add a section named `Converters` in the left nav of the docs above reference
- [x] link to each converter in that section by name (e.g., arm2pulumi), ordered alphabetically by name

### Problem description
 Can all the pulumi converters be located on one page?  
Here are the current links.  You have to know the name of each one to find it, you can't see them all on one page.

[arm2pulumi](https://www.pulumi.com/arm2pulumi/)
[crd2pulumi](https://github.com/pulumi/crd2pulumi)
[kube2pulumi](https://www.pulumi.com/kube2pulumi/)
[tf2pulumi](https://www.pulumi.com/tf2pulumi/)

### Suggestions for a fix

Link all the converter tools on one page.
https://www.pulumi.com/docs/converters/arm2pulumi
https://www.pulumi.com/docs/converters/kube2pulumi
https://www.pulumi.com/docs/converters/crd2pulumi
https://www.pulumi.com/docs/converters/tf2pulumi
or
https://www.pulumi.com/converters/arm2pulumi and so on...

**Comment by susanev** [comment]
yaah these are only discoverable from the blog posts if I understand correctly, we may want to consider putting something in the left nav that groups these together if we don't want to do a landing page
cc/ @davidwrede would love ur thoughts

**Comment by lukehoban** [comment]
We do also link them all from the bottom of https://www.pulumi.com/docs/guides/adopting/, but it's not as prominent as it should be relative to the value of the tools.

**Comment by davidwrede** [comment]
Yeah, they're pretty undiscoverable. I think a "Tools" left nav category (above Reference) would be a good place to put usage documentation on the converters and the Pulumi CLI.

**Comment by susanev** [comment]
ive updated the issue description with the design details of this work
