### ISSUE TITLE
Document how to ignore changes to desiredSize of managed node group

### ISSUE THREAD

**Issue by abatilo** [pulumi/docs#4721]
Based on looking at:
https://www.pulumi.com/docs/reference/pkg/aws/eks/nodegroup/

There is a section for https://www.pulumi.com/docs/reference/pkg/aws/eks/nodegroup/#ignoring-changes-to-desired-size that doesn't seem to actually demonstrate how to make this work.

If you have something running in the EKS cluster like `cluster-autoscaler`, the `desiredSize` will be changed for you and be marked as a diff.

**Comment by leezen** [comment]
Thanks for pointing the error in the example out. In case you didn't find this in the documentation, the way to do this is use the `ignoreChanges` resource option: https://www.pulumi.com/docs/intro/concepts/programming-model/#ignorechanges

**Comment by benjaminran** [comment]
The previous link has gone stale. Here's a new one: https://www.pulumi.com/docs/intro/concepts/resources/options/ignorechanges/

**Comment by cnunciato** [comment]
Closing this as documented at https://www.pulumi.com/docs/intro/concepts/resources/options/ignorechanges/, but if there's still something to be done here, feel free to reopen with details. Thanks!
