### ISSUE TITLE
Add a "How to use" section to crosswalk VPC page

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#4765]
### Problem description

Using the public and private subnets from AWSX isn't always obvious to users (specifically `pulumi.output(vpc.publicSubnetIds)[0]`), so let's add a "How to use your VPC and Security Group" section and Ec2 instance example to the page at https://www.pulumi.com/docs/guides/crosswalk/aws/vpc/.

![image](https://user-images.githubusercontent.com/293763/101681450-035cbc00-3a17-11eb-85f0-77bf4bbdc4a2.png)

**Comment by tusharshahrs** [comment]
Code changes [here](https://github.com/pulumi/docs/pull/4766)

**Comment by clstokes** [comment]
Fixed in https://github.com/pulumi/docs/pull/4766.
