### ISSUE TITLE
Suggestion: Provide examples or a reference for importing non-AWS resources

### ISSUE THREAD

**Issue by haacked** [pulumi/docs#4789]
Hi, I'd like to manage some of my existing resources in Azure using Pulumi. Reading the docs, it seems like the `import` cli command is the right tool for the job. The docs show some AWS examples such as:

> pulumi import aws:s3/bucket:Bucket infra-logs company-infra-logs

But the docs aren't clear on what these terms mean. It'd be nice if there was a breakdown with links. For example, how do I reference an Azure App Service?

File: [docs/guides/adopting/import.md](https://www.pulumi.com/docs/guides/adopting/import/)

**Comment by haacked** [comment]
Also, is there a way for me to simply specify an Azure resource group and have pulumi manage everything in that resource group?

**Comment by lukehoban** [comment]
Hey @haacked - great to see you here! 👋 

Glad you did ultimately find the docs you needed. Not that if you are looking for the ID format to use for these lookups - it's available at e.g. https://www.pulumi.com/docs/reference/pkg/azure/core/resourcegroup/#import. 

Great point on cross-linking here from the import docs.

**Comment by haacked** [comment]
@lukehoban 👋🏼 I'm still trying to wrap my head around things, but so far it's pretty cool! I have a lot of questions about importing resources. Is there a discussion forum or should I just log issues?

BTW, GitHub just released a [Discussions feature for repositories](https://github.com/github/roadmap/issues/104) if you don't have your own discussion place. :smile:

**Comment by lukehoban** [comment]
> Is there a discussion forum or should I just log issues?

The Pulumi Community Slack is a great place for discussion: https://slack.pulumi.com

> BTW, GitHub just released a Discussions feature for repositories if you don't have your own discussion place. 😄

Yeah - we've been thinking about adding this to the mix recently as well!

**Comment by thoward** [comment]
This doc got a lot of updating over the past ~4yrs. Specifically, [PR #3992](https://github.com/pulumi/pulumi-hugo/pull/3992) by @jkodroff covered the main focus of what this issue was filed about. Closing as `fixed`.
