### ISSUE TITLE
Improve page meta descriptions for Resource Docs pages

### ISSUE THREAD

**Issue by zchase** [pulumi/docs#4799]
Currently, Google is not displaying our defined meta descriptions on many of our resource docs pages. This is probably because Google is flagging our descriptions as "too badly written" or "inappropriate" when compared to the content of the page. For example, the resource page for `aws.lambda.Permission` has the description:

```
Explore the Permission resource of the lambda module, including examples, input properties, output properties, lookup functions, and supporting types. Gives an external source (like a CloudWatch Event Rule, SNS, or S3) permission to access the Lambda function.
```

Suggested change to make the description more relevant to the page title and content:

```
Documentation for the aws.lambda.Permission resource with examples, input properties, output properties, lookup functions, and supporting types.
```

The suggested change adds the page title into the description as well as shortens the descriptions. Google will only display ~160 characters of a meta description, so anything beyond that limit is likely to get cut off. Appending the resource description to the base description is not very helpful because it will get cut off when displayed in the search results.

![Screen Shot 2020-12-15 at 11 49 47 AM](https://user-images.githubusercontent.com/15146337/102277345-fb9c8c00-3edc-11eb-9019-37e3618b7dca.png)

Meta Description Display Issues: https://www.sistrix.com/ask-sistrix/onpage-optimisation/meta-element-meta-tag/my-own-meta-description-is-not-being-displayed-in-the-search-results-why/

**Comment by davidwrede** [comment]
Proposed change looks good. 

Do we also need "Pulumi" as a keyword in the meta description (like "...aws.lambda.permission Pulumi resource...")?
