### ISSUE TITLE
AWS Getting Started doesn't work in PowerShell

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#4823]
The "Modify the Program" step for AWS's getting started guide assumes you are running in CMD.EXE. I think many Windows users will default to PowerShell these days.

The step says to copy and paste this:

```
(
@echo.^<html^>
@echo.  ^<body^>
@echo.      ^<h1^>Hello, Pulumi!^</h1^>
@echo.  ^</body^>
@echo.^</html^>
)site/index.html
```

This yields these errors in PowerShell:

![image](https://user-images.githubusercontent.com/3953235/102700691-9ca08500-4204-11eb-94d0-59f5db39b441.png)

Maybe we should have separate WINDOWS (CMD) and WINDOWS (PS) options?

**Comment by lukehoban** [comment]
Related: https://github.com/pulumi/docs/pull/4678#discussion_r532931955
