### ISSUE TITLE
Broken link in awsx.apigateway reference docs

### ISSUE THREAD

**Issue by tenwit** [pulumi/docs#4856]
### Problem description

The section https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/apigateway/#static-route has a link to https://github.com/pulumi/pulumi-awsx/blob/master/nodejs/awsx/examples/api/index.ts but the code has moved. The example is now at https://github.com/pulumi/pulumi-awsx/blob/master/nodejs/examples/api/index.ts.

### Suggestions for a fix

PR following soon.

**Comment by stack72** [comment]
Hi @tenwit 

the change for this will need to propagate through the awsx library as we generate the docs based on that

Paul

**Comment by tenwit** [comment]
+:+1:
