### ISSUE TITLE
tscdocgen produces invalid output for package names with hyphens

### ISSUE THREAD

**Issue by chrsmith** [pulumi/docs#488]
The tool we use to generate documentation from our TypeScript-based Pulumi packages produces incorrect output for package names that contain invalid characters. e.g. we generate local variable names `pulumi-aws` when we should instead be using `pulumiAws`.

I believe the change needs to be made somewhere in:
https://github.com/pulumi/docs/tree/master/tools/tscdocgen

See PR https://github.com/pulumi/docs/pull/487 for an example of this causing problem in the resulting Markdown files.

**Comment by Tirke** [comment]
Will try to fix.
