### ISSUE TITLE
Update integration docs to talk about Automation API

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#4902]
Our [integration test page](https://www.pulumi.com/docs/guides/testing/integration/) talks only about our Go-based `testing/integration` package. This is, unfortunately, Go-specific. The new [Automation API](https://www.pulumi.com/blog/automation-api/) provides everything necessary to do integration testing that drives the CLI from all other supported languages, and we expect to build minimal test helpers on top of that in the future (bridging the gap between the Go package and raw Automation API). In the meantime, however, 80%+ of what an end user needs to do Automation API-based integration testing from any language is already there. We should update our docs to describe how to do this.

**Comment by susanev** [comment]
i see automation api docs on that page now? can we close this? or is more work needed?

**Comment by joeduffy** [comment]
Yep, looks like someone took care of this at some point! 🎉
