### ISSUE TITLE
Improve doc generator

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#492]
Bugs:
- [ ] Some code blocks don't render correctly
- [x] Stop embedding local paths in generated files: `let apiShape: "/Users/luke/go/src/github.com/pulumi/pulumi-cloud/aws/node_modules/@pulumi/cloud/types" =  undefined as any;`

Features:
- [ ] Experiment with expanding types w/ properties (a la [Godoc](https://golang.org/pkg/os/exec/#Cmd))
- [x] Scrub short package names to be legal identifiers
- [x] Print literal types (rather than `{ ... }`)
- [x] Perform intra-package linking
- [x] Perform inter-package linking (where possible)
- [x] Consider restyling the file list somehow (e.g., add a "Module Files" header)
- [x] Make Index, et. al collapsable
- [ ] Add fancy logos to spruce up the clouds packages page

**Comment by joeduffy** [comment]
Others

- [ ] Add ability for index "overview" sections (package, module, etc)

**Comment by joeduffy** [comment]
Made good progress this sprint, will try to chip away more next sprint.

**Comment by justinvp** [comment]
Some others:
 - [ ] We're not pulling in docs for nested structures
 - [ ] We often pick the wrong name
 - [ ] Larger issue: We don't have a named type for the options (it's just an anonymous type), so we don't have a place to hang-off docs for the properties

**Comment by justinvp** [comment]
All the work we're planning to do this milestone related to this is tracked in individual issues, so I am moving this issue out.

**Comment by justinvp** [comment]
Everything I'm planning for this milestone is already tracked as its own issue.

**Comment by lukehoban** [comment]
We've completed a large overhaul of work in this area.  All remaining work should be tracked in other issues now.
