### ISSUE TITLE
github actionsorganizationsecret visibility attribute missing information

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/docs#4976]
### Problem description
The gihub documentation here https://www.pulumi.com/docs/reference/pkg/github/actionsorganizationsecret/ for the [visibility](https://www.pulumi.com/docs/reference/pkg/github/actionsorganizationsecret/#state_visibility_nodejs) attrribute, doesn't show any info( This is for all the languages).  

It should inform about the possible values based on [this](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_organization_secret#visiblity):  

### Affected product version(s)

typescript, go, c#, python

### Suggestions for a fix

visibility (string):   needs to have one of the following values:  

(Required) Configures the access that repositories have to the organization secret. Must be one of `all`, `private`, `selected`. `selected_repository_ids` is required if set to `selected`

**Comment by stack72** [comment]
@davidwrede the issue here is that the attribute `visibility` in the upstream TF provider docs was spelled incorrectly...
