### ISSUE TITLE
New Kubernetes Tutorial Request

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [pulumi/docs#5012]
### Problem description

- I had trouble finding the information that I needed: The closest references that I found were : 
  - https://www.pulumi.com/docs/tutorials/kubernetes/kubernetes-ts-configmap-rollout/
  - https://www.pulumi.com/docs/tutorials/kubernetes/kubernetes-ts-s3-rollout/
 

- Other: 

Never the less, none of the two above mentioned examples match a simple, I believe extremely natural case to work on, which the following : 
* I develop a software, and I package it as a docker container, so I build a docker image : `quay.io/mysupercompany/myawesomeapp:0.0.1`
* to deploy my awesome software, I created a Helm Chart
* I use `pulumi` to, in a row, provision a Kubernetes Cluster, and execute my Helm Chart, with a `value` setting the docker image tag of my software, for my helm release, from the pulumi config. Great. SO I start with tag `0.0.1`
* Ok now I want to jsut deploy new versions of my app, cahnging just one thing, the docker image of My app. There two scenarios : 
  * After I pushed the `0.0.1` version of my image, I ideitified a bug in my source code, SO I fixed the bug, and duilt again the docker image with image tag :  How Do I deploy that with Pulumi ? 
  * I fixed a bug or added a new feature, and I publish a new version of my docker image (so a new image tag) : How do I do that with Pulumi and my embedded Helm Chart

Finally wanna add, that I googled to try and find  : 
* How to I execute `Helm upgrade` with pulumi ?
* How do I execute a Kubernetes Rolling update , with pulumi ?

All questions that I think many teams  of course fall on very quickly : it would very valuable, I believe, that such questions are answered, and proper fully fledged tutorial on the matter. Pulumi is awesome, let's make it even more accessible to more teams.

Finally, I am devops architect at https://github.com/gravitee-io ( see also https://gravitee.io ), and since I am working on the subject right now: 
* I will be glad to share the result of my work with Pulumi 's great team 
* and author the tutorial on the subject, (my work will include writing afull article anyway, for internal devops portal, formated with gohugo.io )

I will watch this issue everyday for answers, will be glad to take any tech tip to push up the subject as quickly as possible, and will also answer asap on any of your questions / requests

Kind Regards, 

jean-baptiste.lasselle@graviteesource.com

**Comment by stack72** [comment]
Hi @Jean-Baptiste-Lasselle 

I'm sorry we took so long to get back to you here. Thanks for opening the issue, this isn't something we plan on adding to our docs right now but we would gladly accept a pull request to our github.com/pulumi/examples repo to cover this scenario please let us know if you have any questions - a good place to find information is in our [community slack](https://slack.pulumi.com/)

Thanks

Paul
