### ISSUE TITLE
The sample code does not compile

### ISSUE THREAD

**Issue by jfjcn** [pulumi/docs#5022]
There is an issue on the RoutingRules->RoutingRulesArgs->RouteConfiguration value.

File: [docs/reference/pkg/azure-nextgen/network/frontdoor.md](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/network/frontdoor/)

**Comment by susanev** [comment]
also tracked here: https://github.com/pulumi/pulumi-azure-nextgen/issues/210

**Comment by mikhailshilkov** [comment]
Dupe of https://github.com/pulumi/pulumi-azure-nextgen/issues/210
