### ISSUE TITLE
Broken anchor tags in python SDK docs

### ISSUE THREAD

**Issue by komalali** [pulumi/docs#5047]
### Problem description

The python SDK doc's anchor tags don't work. For example, automation API:

The link from the anchor icon is https://www.pulumi.com/docs/reference/pkg/python/pulumi/#automation-api-1 - which doesn't work.

However, linking https://www.pulumi.com/docs/reference/pkg/python/pulumi/#module-pulumi.x.automation actually gets you to the correct spot.

This issue is probably due to how we dump sphinx-generated html into markdown and then Hugo does its thing to the markdown to generate into Pulumi format.

Related to: https://github.com/pulumi/docs/issues/4615

**Comment by justinvp** [comment]
This may require changing the styles we have in https://github.com/pulumi/docs/blob/master/assets/sass/_api-python.scss
