### ISSUE TITLE
Update link checker to report if we link to terraform docs 

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/docs#5083]
### Problem description

We link to terraform docs on [acm.Certificate](https://www.pulumi.com/docs/reference/pkg/aws/acm/certificate/#certificate) page.

### Suggestions for a fix

Update link checker to create report on docs pages where we link to terraform website.

**Comment by cnunciato** [comment]
@pierskarsenbarg Is this issue still relevant? It looks like we only link to the TF docs at the foot of the page, which I believe we still want to do, so I'm assuming there were at some point other links in the content that are no longer there. If that's the case, can you close?

**Comment by thoward** [comment]
closing as `fixed`, as whatever this was originally filed about 3.75yrs ago seems to no longer be an issue.
