### ISSUE TITLE
Missing some info in AWS ECS resource docs

### ISSUE THREAD

**Issue by davidwrede** [pulumi/docs#5199]
Looks like we are cutting off an important part of the example code block here: https://www.pulumi.com/docs/reference/pkg/aws/ecs/service/#ignoring-changes-to-desired-count 

Specifically, the following is not being pulled into the example block:

```
lifecycle {
    ignore_changes = [desired_count]
}
```

Also, we're missing a description for `waitForSteadyState` (in all languages).

Originally reported in https://pulumi-community.slack.com/team/U01400Z5N9Z

**Comment by lukehoban** [comment]
The first issue is https://github.com/pulumi/tf2pulumi/issues/229.  The second issue is something that should be reconciled in pulumi-aws.
