### ISSUE TITLE
doc images breaking out of container

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#5205]
## Problem description

noticed the access tokens doc images breaks out of its container before it hits the page breakpoint

<img width="918" alt="access-tokens-img" src="https://user-images.githubusercontent.com/5489125/107682261-f6498c80-6c54-11eb-9372-af3f16ea33a0.png">

**Comment by davidwrede** [comment]
@susanev Do you happen to know what res you're running in when you hit that?

**Comment by susanev** [comment]
1440x900

**Comment by davidwrede** [comment]
@cnunciato Would love to get your thoughts on this. On my machine, I can repro this when scaling the browser window from max size down to a more mobile-like resolution.
