### ISSUE TITLE
Update Branding from Packet to Equinix Metal

### ISSUE THREAD

**Issue by etrosa** [pulumi/docs#5214]
File: [docs/reference/pkg/packet/_index.md](https://www.pulumi.com/docs/reference/pkg/packet/)

Please update the branding on the page/menu to represent the Packet.net branding change to Equinix Metal. Thank you!

**Comment by stack72** [comment]
Hi @etrosa 

This page will continue to exist for the users of the packet.net deprecated provider while we allow them to cut over

Each page has a deprecation message across the top pointing to the new Equinix Metal provider

After a period of time we will flat out redirect these pages. The 2 providers exist at this time but we've made it clear the old one has been deprecated so we need to keep these docs around a little longer

I hope this is ok

Thanks

Paul
