### ISSUE TITLE
Please add Equinix Metal to Cloud Providers List

### ISSUE THREAD

**Issue by etrosa** [pulumi/docs#5215]
File: [docs/intro/cloud-providers/_index.md](https://www.pulumi.com/docs/intro/cloud-providers/)

Please add Equinix Metal to Cloud providers list. As well as update the menu item from Packet.net to Equinix Metal

**Comment by stack72** [comment]
Hi @etrosa 

Equinix Metal already exists in this menu listing and packet.net has been removed

We will redirect the packet.net page to the Equinix Metal page this week

Paul

**Comment by etrosa** [comment]
Awesome, Thank you Paul!
