### ISSUE TITLE
What are some valid values for the Property `Kind` 

### ISSUE THREAD

**Issue by StevenTCramer** [pulumi/docs#5229]
File: [docs/reference/pkg/azure-nextgen/web/webappconnectionstrings.md](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/web/webappconnectionstrings/)

I'm trying to set a ConnectionString to a secret in a KeyVault and avoid the circular dependency using WebApConnectionStrings.  

The documentation indicates a property called Kind which is a "kind of resource"  but I have no idea what a valid value would look like. 

`Kind = "WebApp" ????

![image](https://user-images.githubusercontent.com/357219/107857261-f8336b80-6e5f-11eb-87b1-0166932bd448.png)

**Comment by mikhailshilkov** [comment]
We generate these docs from Open API specs of Microsoft... that's how this property is defined there. From what I know, you should leave this property out (it's optional).

**Comment by StevenTCramer** [comment]
@mikhailshilkov You Rock!  The fastest response times ever.  Thank you!
