### ISSUE TITLE
move docs search

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#5250]
### Problem description

with the improvements to docs search, it be cool to also consider moving search to a more prominent location so its super clear to everyone that we have docs search; im including a few explorations, super open to feedback or other ideas

#### top-level
across the top above all the content, we could even go full width; would be nice to keep this sticky at the top if possible
![top-level](https://user-images.githubusercontent.com/5489125/108083016-8279fc00-7027-11eb-8653-43cd511ba664.png)

#### top of left-nav instead of right-aside
this is another location which wouldn't require us to make it sticky, but wed still have the width issue; also a nit the left nav should really be in a nav element instead of an aside element
![docs-left-nav](https://user-images.githubusercontent.com/5489125/108083167-a6d5d880-7027-11eb-9ad3-30f40939323c.png)

**Comment by susanev** [comment]
@davidwrede @cnunciato thoughts?

**Comment by davidwrede** [comment]
@susanev I like the second option where the input text box sits at the top of the left nav. Btw, would one option be better than the other for mobile users?

**Comment by cnunciato** [comment]
I agree, top-left seems better -- although it'd be a bit of a bummer to have to lose yet more visible TOC content to make room for this, especially since the right-hand side is so underutilized. (I do prefer it on the left, though. But yeah -- it'd come at a cost, at least given our current TOC size, structure, and behavior.)

**Comment by susanev** [comment]
@davidwrede no real difference between these two. ideally the nav goes to a hamburger menu and the search appears on screen at the top.

@davidwrede @cnunciato okay lets go with above the left-nav for now. i do think there's value in a wide search at the top but we can revisit that later after this redesign.  do yall think it would be reasonable to merge this when we also merge the improved search? i think there's value in it happening at the same time so folks have a hint that search is better.
