### ISSUE TITLE
Please make better documentation

### ISSUE THREAD

**Issue by jamesnunn** [pulumi/docs#5302]
File: [docs/reference/pkg/python/pulumi/_index.md](https://www.pulumi.com/docs/reference/pkg/python/pulumi/)

The documentation is lacking a navigation panel showing the various sections and the reference material is overcrowded, especially with the unused scrollbars wrapping code blocks

**Comment by leezen** [comment]
Fixed in https://github.com/pulumi/pulumi-hugo/pull/352 and supposedly merged in https://github.com/pulumi/docs/pull/6157 but currently don't see this being the case on the site.

**Comment by leezen** [comment]
Fixed with https://github.com/pulumi/pulumi-hugo/pull/363
