### ISSUE TITLE
GHA to generate and refresh all provider docs

### ISSUE THREAD

**Issue by davidwrede** [pulumi/docs#5330]
### Problem statement

Right now we automate the generation (and merging) of provider docs per provider through a GitHub Action (https://github.com/pulumi/docs/pull/5314); however, whenever we rollout global changes to our docgen strings upstream, the best tool we have right now to refresh all of our provider docs is `scripts/gen_all_resource_docs.sh`. This script contains a manually updated list of providers, which is problematic. It also isn't hooked into the new auto-merge GHA action.

### Proposed solution

It would be great to have a GHA that rebuilds all of the provider docs automagically to pick up global doc changes and then auto merges them in like #5314.

**Comment by cnunciato** [comment]
I believe this is no longer relevant as all docs are now built on every merge to the master branch of this repo. Therefore closing, but feel free to reopen if I'm misunderstanding.
