### ISSUE TITLE
Improve API reference provider docs for .NET users

### ISSUE THREAD

**Issue by davidwrede** [pulumi/docs#5340]
After #5133 was merged, there was some usability feedback that the experience reading and using API reference documentation was worse for .NET users compared to the previous solution of using the docFx output and serving that up for users.

Here are some areas for improvement:

- Resource provider docs have horizontal scrolling problems with example blocks
- Top-right side of old DocFX-generated documentation was useful because it references the base platform docs 
- Resource provider API docs have wasted space in left nav and right nav
  - More screen real estate should be devoted to the main topic pane
- It would be great to have links to all resources available in one place (like on the left nav) without having to go back and forth through breadcrumbs or using the back button

A potential option is to bring back the .NET resource and core SDK docs as they were (via docfx) until we can make the resource and core SDK docs more accommodating for .NET folks, but that's a fairly large work item and should only be explored if the usability gap is large and our timeframe for improving the resource provider docs are several iterations away.

**Comment by davidwrede** [comment]
Core .NET SDK docs have been added back in. You can find them at https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi/Pulumi.html.

**Comment by cnunciato** [comment]
Closing as these docs now exist. We are considering the larger issue of SDK docs in general so will open language-specific issues as needed.
