### ISSUE TITLE
Horizontal scroll is very difficult to use for Python API docs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#5365]
We generate Python `def`s as one long line, which makes horizontal scrolling quite extreme.

For instance, go to https://www.pulumi.com/docs/reference/pkg/openstack/compute/instance/, and check out the "Create an Instance Resource" signature for Python:

![image](https://user-images.githubusercontent.com/3953235/109187637-f06ca480-7746-11eb-91b1-5b522d7fe25f.png)

It just keeps going...

![image](https://user-images.githubusercontent.com/3953235/109187839-1f831600-7747-11eb-810f-089fa1661632.png)

...and going...

![image](https://user-images.githubusercontent.com/3953235/109187868-27db5100-7747-11eb-9ffa-ba79b13d7827.png)

... and going...

![image](https://user-images.githubusercontent.com/3953235/109187942-3e81a800-7747-11eb-9d0f-4c2f1ecffdd9.png)

... and going ....................

It feels like some linebreaks and whitespace would go a long way to improving the usability here.

**Comment by justinvp** [comment]
We'll address this by adding linebreaks/whitespace for the args, as well as showing the new ResourceArgs overload.
