### ISSUE TITLE
The async style of import doesn't work in the unit testing guide

### ISSUE THREAD

**Issue by leezen** [pulumi/docs#5370]
I'm able to do 
```typescript

pulumi.runtime.setMocks(

...

import * as infra from "./index";

...

describe(...

```

But if I attempt the style shown in the guide:

```typescript
let infra: typeof import('../index');

before(async function() {
    // It's important to import the program _after_ the mocks are defined.
    infra = await import('../index');
})
```

I end up with undefined properties hanging off `infra`

File: [docs/guides/testing/unit.md](https://www.pulumi.com/docs/guides/testing/unit/)

**Comment by leezen** [comment]
@mikhailshilkov Do you know if something changed in Node that might cause the async style to no longer work? Is there a way to make it work or should we update the guide to simply import inline?

**Comment by mikhailshilkov** [comment]
We changed that in https://github.com/pulumi/docs/pull/3176

I'm sure I ran it at the time of that change but I'm not sure what could change since then.

@SimenB any chance you know what's going on here?

**Comment by SimenB** [comment]
Nothing should be `undefined`, sounds very odd. Without a complete reproduction it's hard to tell, though.

**Comment by mikhailshilkov** [comment]
@leezen https://github.com/pulumi/docs/pull/3176#discussion_r587490203 could this be your problem?

**Comment by leezen** [comment]
@SimenB @mikhailshilkov That was indeed the problem. Attempting to get the value from w/in the `describe` was causing the value to be `undefined`. When I fully reference `infra.foo...` within a test, it works as expected.
