### ISSUE TITLE
Markdown Code block misformatted

### ISSUE THREAD

**Issue by oktocat** [pulumi/docs#5377]
Hi folks,

The MD code block formatting is broken on https://www.pulumi.com/docs/tutorials/aws/aws-ts-stackreference/

@pierskarsenbarg asked me to cut an issue: https://pulumi-community.slack.com/archives/C84L4E3N1/p1614616965367000

Thanks!

**Comment by leezen** [comment]
Thanks for pointing this out. Closing as a duplicate of https://github.com/pulumi/docs/issues/3593
