### ISSUE TITLE
Core .NET SDK docs are missing 

### ISSUE THREAD

**Issue by davidwrede** [pulumi/docs#5378]
After #5133 was merged, the core .NET SDK API ref documentation was also removed. To keep parity with the other languages we support, we should regenerate the Pulumi .NET SDK docs. 

To keep with the look and feel of our other API ref docs, we should use our current API ref theme and layout; however, that may require a fair amount of engineering work. An interim short-term solution would be to bring back the DocFX-generated version (using a scaled down `docfx.json` file) and host it on our site as we did previously.

**Comment by stack72** [comment]
Closed via:

* https://github.com/pulumi/pulumi-hugo/pull/52
* https://github.com/pulumi/docs/pull/5751
