### ISSUE TITLE
The article does not state clearly what language the code examples are in

### ISSUE THREAD

**Issue by dekobon** [pulumi/docs#5487]
File: [docs/guides/crosswalk/aws/eks.md](https://www.pulumi.com/docs/guides/crosswalk/aws/eks/)

It would make the article clearer if the language of the examples was called out more explicitly.

**Comment by viveklak** [comment]
The language here is typescript but we do have support for it now in other languages. @davidwrede not sure if you are already tracking something to update docs/blogs for multilang support?

**Comment by davidwrede** [comment]
@viveklak Thanks for the reminder. Yeah, I'll include the update work for this topic as part of that other set of items.

**Comment by susanev** [comment]
@dekobon im not sure what the state of things was when you opened this issue, but would you mind taking another look? is the language still unclear to you?

**Comment by dekobon** [comment]
Yes, this is much clearer now.
