### ISSUE TITLE
Make /reference/terraform.html more useful

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#549]
This website's #2 search term is "pulumi vs terraform"

![image](https://user-images.githubusercontent.com/3953235/44310240-f8db0c00-a3a0-11e8-83e9-ff270bc0a17c.png)

which apparently ends up landing folks on the /reference/terraform.html page

![image](https://user-images.githubusercontent.com/3953235/44310245-07c1be80-a3a1-11e8-9f94-a354516fd2ce.png)

which is not terribly helpful. We should improve this page.

**Comment by justinvp** [comment]
Fixed by #566
