### ISSUE TITLE
Add code snippets for tutorials

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#550]
Our quickstart tutorials are a little awkward to use. We often tell you to "copy this code and replace the contents of `index.js` with it," but the size of code snippets can be quite large in some cases.

We should add a notion of real code snippets, similar to the kubernetes.io website:

![image](https://user-images.githubusercontent.com/3953235/44310522-c8e23780-a3a5-11e8-8393-da36bfbd3f1e.png)

Notice that there is a header complete with the name of the file and a handy little "copy to clipboard" shortcut, which makes pasting to `index.js` slightly less awkward.

I also think we should create a template for each quickstart and tell folks to use that flow instead, e.g. `pulumi new https://github.com/pulumi/...`. That way they don't even need to do the copy and paste dance. I find it cumbersome enough personally that I wouldn't be surprised if it results in dropoff.

**Comment by justinvp** [comment]
Looking at the remaining work on my plate this week, it's going to be difficult to get this wrapped up by EOD Friday. Proactively moving out. Would love to spend a little time on this and some of the other pulumi.io improvements assigned to me the next milestone.

**Comment by joeduffy** [comment]
Now that https://github.com/pulumi/docs/issues/1023 has taken over the "copy to clipboard" aspect of this, I think the only remaining thing to do is add a title bar for the code snippets.

@justinvp does that sound about right?

**Comment by bermudezmt** [comment]
We've addressed via #1363
