### ISSUE TITLE
Pulumi Workshops are hard to find

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/docs#5502]
### Problem description
 Pulumi scheduled workshops and workshops that have been completed are hard to find for customers. 
Currently to get there:
  1. Navigate to pulumi.com
  2. Scroll to the very bottom of page.
  3. Click on the link called `Resources`. [Screen Shot](https://share.getcloudapp.com/7Kup7bKp)

- Trouble finding the information that is needed
    - Upcoming Workshops:  https://www.pulumi.com/resources/#upcoming
    -  Completed Workshops to view:  https://www.pulumi.com/resources/#all

### Suggestions for a fix
Create a link on the very top that has workshops.  [Example Screen Shot](https://share.getcloudapp.com/qGuX9X0n)

**Comment by davidwrede** [comment]
We now have the intro workshops linked to from the root [Getting Started page](https://www.pulumi.com/docs/get-started/#additional-resources) and they are now available under the **Learn** menu item in the top nav.

Please re-open if customers still have a hard time finding the workshops.
