### ISSUE TITLE
Pulumi release artifacts are different depending on where you download them from

### ISSUE THREAD

**Issue by bls** [pulumi/docs#5507]
### Problem description

I downloaded: https://get.pulumi.com/releases/sdk/pulumi-v2.23.1-linux-x64.tar.gz but seem to get different artifacts depending on whether I was coming from a USA or Australian location.  Should I expect this?

When I add a remote artifact reference to an automated process, I usually lock in the hash I observe at development time to avoid unexpected substitution. Sometimes I don't have a good way to verify what the hash is really supposed to be (this is true for Pulumi) but TOFU (trust on first use) is better than nothing if the automated process will be long running.  I do this because I've been hassled a few times in security review for doing random file downloads from the Internet without checking them at all. It's a compliance issue blah blah blah.

But the checksums of the files I got varied by location which broke CI for me.

```
% ls -l *.tar.gz && shasum -a 256 *.tar.gz
-rw-r--r--  1 nobody  staff  63890137 20 Mar 17:39 aus-pulumi-v2.23.1-linux-x64.tar.gz
-rw-r--r--  1 nobody  staff  63890127 20 Mar 17:46 usa-pulumi-v2.23.1-linux-x64.tar.gz
b31b129d0a7fce8dc52ce30cce962e0b9a7e433365958a45a1731905ec10a53b  aus-pulumi-v2.23.1-linux-x64.tar.gz
63aefbb7b2083e602560f923e2c971f0914acf691e439acab6cb787eb75eb954  usa-pulumi-v2.23.1-linux-x64.tar.gz
```

### Affected product version(s)

I have only tested `pulumi-v2.23.1-linux-x64.tar.gz`

### Suggestions for a fix

It would be nice if downloads (from anywhere) always gave the same artifact.  I found the download behaviour surprising.

It would also be nice if checksums (or even GPG signed checksums for extra tinfoil hat) could be published so I could have a better idea what to expect, but I see that idea was already rejected in another issue.

**Comment by stack72** [comment]
Hi @bls 

This is 100% a bug! We should never be serving different release artifacts - we actually do publish the checksums - http://get.pulumi.com/releases/sdk/pulumi-2.23.1-checksums.txt

Notice the version in there - but it doesn't start with the "v"

I have checked this and this is not the case anymore - I am not sure why this is the case but I will ensure we don't have these issues in the future

Thank you for bringing this to our attention

Paul

**Comment by bls** [comment]
Thank you! I looked all over the download pages but couldn't find the link for the checksums.

I now realise they're linked from the github release page 🤦

**Comment by stack72** [comment]
ok, that does indeed help! thank you :) Sorry for this... this should not be happening to you. I am going to put a couple of download tests on my side to ensure this looks correct and will alert going forward

**Comment by t0yv0** [comment]
Hitting the same problem as a nix user. It happens that nix insists on checksums.

Currently I have this SHA256 returned:

```
$ nix-prefetch-url https://get.pulumi.com/releases/sdk/pulumi-v2.23.1-linux-x64.tar.gz
path is '/nix/store/a80n26nx02skxqbyzq4r2kbvzcsw2xcr-pulumi-v2.23.1-linux-x64.tar.gz'
0fx523n0a6bkl52qm5b56d1px6hb5sbcw3735k2qvkkz1afi46xk
```

Previously I had it return this:

  sha256 = "0m5rbsvpwy6bnv59lhqyd77lm4ghf74y48zrc0jn0gh8navzpbk3";

As you can see in my nixpkgs fork:

https://github.com/t0yv0/nixpkgs/commit/ced2354b58ab871e9a4669a26fb571819e2895e6#diff-d9b63dcc6184dc89efde113bfb02629fbf83a22c58c30cc51447ac69ec2fbec8R9

My problem now is that nix detects checksum change.

**Comment by stack72** [comment]
Hi @bls 

thanks again for helping us track down a potential bug here - as you can see, I linked https://github.com/pulumi/pulumi/issues/6634 which was a potential error condition that would cause this problem

AFAICT, this has actually only caused us pain once.... but I am going to close that hole out to make sure that there is no more pain here

Thanks again

Paul

**Comment by stack72** [comment]
Hi @bls 

I am going to close this out as we are tracking this in a pulumi/pulumi issue - I assure you this will be fixed!

Paul
