### ISSUE TITLE
Add Helm AKS examples that use native Azure provider 

### ISSUE THREAD

**Issue by t0yv0** [pulumi/docs#5518]
### Problem description

We recently completed an example that provisions a Helm chart on AKS in Azure, in four languages:

- https://github.com/pulumi/examples/tree/master/azure-py-aks-helm
- https://github.com/pulumi/examples/tree/master/azure-ts-aks-helm
- https://github.com/pulumi/examples/tree/master/azure-cs-aks-helm
- https://github.com/pulumi/examples/tree/master/azure-go-aks-helm

The idea is to add these examples to the docs site to feature them.

CC @mikhailshilkov

**Comment by mikhailshilkov** [comment]
@t0yv0 Will you have time to complete this before 4/20?

**Comment by t0yv0** [comment]
Yes! Taking a note.

**Comment by t0yv0** [comment]
@mikhailshilkov can you spec out where on the site the changes should land?

Guessing:

(1) https://www.pulumi.com/docs/get-started/azure/next-steps/ - add link to GitHub source for new examples

(2) https://www.pulumi.com/docs/tutorials/azure/azure-ts-webserver/ - add new examples as new tutorials under /docs/tutorials/azure/$ex

(3) https://www.pulumi.com/docs/intro/cloud-providers/azure/#getting-started - add link to GitHub source for new examples

**Comment by mikhailshilkov** [comment]
@t0yv0 Just here: https://www.pulumi.com/docs/tutorials/azure/

In the list at the bottom + I would replace the AKS example with AKS+Helm

**Comment by t0yv0** [comment]
Ok awesome. Thanks.

**Comment by t0yv0** [comment]
WIP https://github.com/pulumi/pulumi-hugo/pull/63
