### ISSUE TITLE
Update/Provide alternative tutorial using Azure native

### ISSUE THREAD

**Issue by Slaiyer** [pulumi/docs#5593]
File: [docs/tutorials/kubernetes/aks.md](https://www.pulumi.com/docs/tutorials/kubernetes/aks/)

Examples for AKS using azure-native in pulumi/examples are rather barebones compared to this.

**Comment by mikhailshilkov** [comment]
Thank you @Slaiyer, this is already tracked in https://github.com/pulumi/docs/issues/5188
