### ISSUE TITLE
Add AKS, EKS, GKE, manual cluster landing pages

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#562]

**Comment by joeduffy** [comment]
@hausdorff As part of M20 work, let's add pages specific to the various kinds of Kubernetes clusters one might want to set up, and show how to do it with Pulumi.

For bonus points, let's consider creating a `KubernetesCluster` abstraction that can internally deploy itself to either of these targets, and let's have a tutorial showing how to use it.

**Comment by lblackstone** [comment]
https://github.com/pulumi/docs/pull/688 is related

**Comment by hausdorff** [comment]
Per conversations with @joeduffy and @lukehoban we're going to push this out in favor of the Kubernetes the Prod Way workstream.

**Comment by lukehoban** [comment]
I *think* at this point this is tracking tutorial pages for each of GKE, EKS and AKS. The first two are available now. On AKS there is an examples PR that could be the foundation of this? https://github.com/pulumi/examples/pull/237

I think we should add the AKS tutorial to the docs and ensure we cross link to all of these from both AWS/Azure/GCP docs as well as Kubernetes docs.

**Comment by metral** [comment]
With https://github.com/pulumi/examples/pull/237 now merged, we're good to close this out.
