### ISSUE TITLE
Typo in BucketObject kwarg

### ISSUE THREAD

**Issue by lostineverland** [pulumi/docs#5647]
File: [docs/get-started/aws/deploy-changes.md](https://www.pulumi.com/docs/get-started/aws/deploy-changes/)

`content` keyword should be `source` at the end.

```
bucketObject = s3.BucketObject(
    'index.html',
    acl='public-read',
    content_type='text/html',
    bucket=bucket,
    content=pulumi.FileAsset('index.html'),
)
```

**Comment by davidwrede** [comment]
Fixed in https://github.com/pulumi/pulumi-hugo/pull/26
