### ISSUE TITLE
Pulumi vs. CloudFormation content

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#565]
We have https://www.pulumi.com/cloudformation/, but having a more detailed and technical page on the pulumi.io site with code for code examples would be useful.

Something along the lines of https://www.terraform.io/intro/vs/cloudformation.html

Related: #549

**Comment by joeduffy** [comment]
I'll be doing this as part of https://github.com/pulumi/docs/issues/549.

**Comment by justinvp** [comment]
Fixed by #566
