### ISSUE TITLE
Fix all broken links

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#568]
We currently have two categories of broken links remaining:

1) Our generated API docs have lots of broken links
2) Our changelog includes links to private repos

The former is a mixture of things, including Terraform doc links and doc generator bugs (leading to private desktop paths being included), and the latter is presumably easy to fix.

**Comment by lukehoban** [comment]
Note that we fixed (1) in the providers, we just haven’t updated docs since we haven’t yet released the version with the fixes.  This will be fixed as part of the released next week.
