### ISSUE TITLE
Get more actionable feedback through docs feedback flow

### ISSUE THREAD

**Issue by davidwrede** [pulumi/docs#5864]
### Problem description

In trying to address topics that get negative feedback, it's often hard to take action when someone simply marks it as "No" without further comments. Right now comments are optional. Thankfully, most of the comments we have received are actionable and speak to specific pain with the topic, which helps in prioritizing work and making effective updates to improve doc quality.

### Suggestions for a fix

When selecting "No" in our doc feedback flow, I propose requiring long form comments before you're allowed to click the submit button. Conversely, for any "Yes" votes, we can leave the long form comments as optional.

**Comment by susanev** [comment]
i am going to recommend against requiring long-form input to be able to accept this feedback. Internally, we can always exclude nos without long-form feedback for whatever questions we are trying to answer but id much rather still have the no data.

closing, if anyone else feels strongly that we must require long-form feedback pls reopen.
