### ISSUE TITLE
Sphinx Object Inventory would be awesome

### ISSUE THREAD

**Issue by cblegare** [pulumi/docs#5874]
### Problem description

While writing some documentation about a pulumi program, I was not able to find a `objects.inv` file anywhere in the documentation website.

These files are used by [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) for crossreferences to external documentation project. This is one of the things that makes Sphinx so awesome.

### Suggestions for a fix

Generate an objects.inv file and serve it under https://www.pulumi.com/docs/reference/pkg/python/objects.inv.  I think you use a wild combination of tools to pack all documentations from many projects in one place, you might need to artificially generate that inventory using [sphobinv](https://sphobjinv.readthedocs.io/en/stable/).

Also, btw, Sphinx is quite capable of extracting API docs from numerous languages:

- Python (built-in)
- Javascript/Typescript: [Sphinxjs by people at Mozilla](https://github.com/mozilla/sphinx-js)
- C/C++/C#/Java: through Doxygen and [Breathe](https://github.com/michaeljones/breathe)
- Go: possibly with [sphinx-autoapi](https://github.com/readthedocs/sphinx-autoapi)

**Comment by thoward** [comment]
Thanks for the report @cblegare ! Closing, as seems to have been fixed, originally in https://github.com/pulumi/docs/pull/8110 and in later modifications to the site generation systems. As of today, the referenced `objects.inv` file exists at the URL described in this issue.
