### ISSUE TITLE
VSCode theme in docs

### ISSUE THREAD

**Issue by sourcec0de** [pulumi/docs#588]
Hey guys, great job on Pulumi.

Does anyone know what theme this is?
Saw it here https://pulumi.io/reference/javascript.html
![image](https://user-images.githubusercontent.com/1580651/45496339-109c7a80-b72a-11e8-9742-c68f8c728d65.png)

**Comment by lukehoban** [comment]
I believe it is "Quiet Light".

![screen shot 2018-09-13 at 7 57 09 am](https://user-images.githubusercontent.com/223467/45496594-aafcbe00-b72a-11e8-8c55-5f4efdfa7c37.png)
