### ISSUE TITLE
aws codedeploy application shouldn't have tags input

### ISSUE THREAD

**Issue by dhanvi** [pulumi/docs#5899]
### Problem description

aws codedeploy doesn't support tags input but the below documentation says that it supports.

- I saw a product documentation issue on the following URL: https://www.pulumi.com/docs/reference/pkg/aws/codedeploy/application/#tags_nodejs

### Suggestions for a fix

Remove tags input from the source.

**Comment by justinvp** [comment]
@dhanvi, I'm not familiar with the specifics of the `aws.codedeploy.Application` resource, but it does support tags:

https://github.com/pulumi/pulumi-aws/blob/bf65178e74c16e330f4e76d94cea7b2ab0e93c35/sdk/nodejs/codedeploy/application.ts#L193

And the underlying TF provider:

https://github.com/hashicorp/terraform-provider-aws/blob/1eadd0c34c51d2436250f5eb35afd248b2bd7fd4/aws/resource_aws_codedeploy_app.go#L105

Can you clarify what you mean by "aws codedeploy doesn't support tags input"?

**Comment by dhanvi** [comment]
AWS doesn't support tagging for codedeploy https://docs.aws.amazon.com/ARG/latest/userguide/supported-resources.html#services-codedeploy

It must be a mistake on the TF provider side.

Should I be raising this issue in that repo?

**Comment by justinvp** [comment]
> It must be a mistake on the TF provider side.

If that's the case, yes, opening an issue in that repo makes sense, and then I can tag this issue as "awaiting-upstream".

**Comment by stack72** [comment]
Hi @dhanvi 

So, I looked into this and codedeploy application does support Tagging 

it's available via the CLI - https://docs.aws.amazon.com/cli/latest/reference/deploy/create-application.html

via the go sdk: https://github.com/aws/aws-sdk-go/blob/main/service/codedeploy/api.go#L6721

So I believe this functionality is correct

I am going to close this out as we are inline with the AWS code sdk we use here - I think this may be an AWS docs issue

Please let me know if there are other issues here

Paul
