### ISSUE TITLE
Eliminate @cloud from all AWS-specific Tutorials

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#592]
Now that we have advanced functionality in the AWS package itself, we should be able to convert all AWS-specific Tutorials so that they just use `@pulumi/aws`. The one I'm unsure about is the containers example, but I would love to see us make an attempt at that also (and perhaps that would inform the ongoing work we have at the AWS abstraction layer).

**Comment by CyrusNajmabadi** [comment]
Have updated the apigateway sample.  Containers will take more work, so moving out to next milestone.  We can see about coming up with a design for that in m19.
