### ISSUE TITLE
Add an Azure Tutorial

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#593]
Right now, we don't have any Azure Tutorials. Compare

![image](https://user-images.githubusercontent.com/3953235/45904032-8e066180-bda0-11e8-9cc0-333ea8b2061a.png)

with

![image](https://user-images.githubusercontent.com/3953235/45904034-92327f00-bda0-11e8-9196-68c2752505fb.png)

Let's add one for the virtual machine and perhaps one showing off Azure Functions support.

**Comment by CyrusNajmabadi** [comment]
I'm going to roll this into work next milestone to properly setup Azure development to be like what we've now turned aws development into.  Namely, moving things down into the pulumi/azure library, deprecating pulumi/azure-serverless.  Providing an appropriate http/api abstraction. etc. etc.
