### ISSUE TITLE
Document how to create a new provider

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#595]
We don't currently have docs on how to bring up a new provider. There are two approaches currently

1. Build it from scratch, like [our Kubernetes provider](https://github.com/pulumi/pulumi-kubernetes)
2. Use [pulumi/terraform](https://github.com/pulumi/pulumi-terraform) to adapt an existing TF provider, like [our AWS provider](https://github.com/pulumi/pulumi-aws)

We have a lot of examples, but no good end-to-end tutorials of how to go about this.

For example, [the initial Kubernetes repo commit](https://github.com/pulumi/pulumi-kubernetes/commit/e85e03360ab8b1657d47016b4d38365ebb30e077) demonstrates some essential ingredients for implementing [our provider gRPC interface](https://github.com/pulumi/pulumi/blob/master/sdk/proto/provider.proto), and [this README](https://github.com/pulumi/pulumi-terraform#adapting-a-new-terraform-provider) briefly describes how to create a new TF-based provider (and there are [simple providers](https://github.com/pulumi/pulumi-openstack)) to base this on.

We do have a [brief FAQ entry](https://pulumi.io/reference/faq.html#how-can-i-add-support-for-my-favorite-cloud), but it probably isn't complete enough to figure things out.

**Comment by eropple** [comment]
FWIW, I'm looking to do this right now in order to sell the use of Pulumi at my current employer. We have a cloud offering and a Terraform provider, open source but not part of the Terraform distribution, and I'd very much like to use Pulumi for it. At the same time, our VMware infrastructure uses not just `vsphere` but also `nsxt`, so I need to bolt something together for that, too. ;)

If there's any chance of some help from the Pulumi side of things I am more than happy to pay it forward by documenting it out to close out this ticket.

**Comment by tigerwings** [comment]
What is the status of this now? 
I think a good start is to create a minimal provider repo to show how to write a resource provider, and how the TS, python sdk communicating with it. The kubernetes-provider in the top comment is too complicated to understand the necessary codes for a provider.

**Comment by remorses** [comment]
I thing the first link meant to be github.com/pulumi/pulumi-terraform-bridge

**Comment by lukehoban** [comment]
We now have https://www.pulumi.com/docs/guides/pulumi-packages/ which is an initial page covering this topic.  That page and the various boilerplate repos it links to for each of the ways of building a Pulumi Package provide the core information needed to build a Pulumi Package and its associated provider.  There's a lot of "best practices" not yet captured there - so I'll leave https://github.com/pulumi/docs/issues/4825 open to track all the good concrete best practices topics tracked there that should ultimately be added to this guide.  But I think we can close this issue out, and open new issues on more specific additional content we want to include (possibly as part of 4825).
