### ISSUE TITLE
Larger reference docs seem to have slowed down significantly

### ISSUE THREAD

**Issue by viveklak** [pulumi/docs#5959]
### Problem description
Some of the larger reference docs pages seem to be taking on the order of 30+ secs to load.

Multiple traces seem to implicate a call initiated by insight.js:
https://px.ads.linkedin.com/collect?v=2&fmt=js&pid=<xxx>&time=<yyy>&url=https%3A%2F%2Fwww.pulumi.com%2Fdocs%2Freference%2Fpkg%2Fazure-native%2Fcontainerservice%2Fmanagedcluster%2F
My bandwidth generally is reasonable (100 mbps+).  Looking at the trace, the GET blocks for 30-90 seconds for me sometimes.
<img width="1785" alt="Screen Shot 2021-05-10 at 6 44 56 PM" src="https://user-images.githubusercontent.com/1094518/117746033-89e11980-b1c0-11eb-8b60-548878c0a59d.png">

Note - I can't claim this is happening consistently across all users/browsers at all times. Even for me, sometimes that specific call succeeds quickly only for other calls to slow down. Perhaps there is some unfortunate browser pipelining side-effects being seen? Regardless some deeper analysis of docs page load latency analysis would be worthwhile.
 

- I saw a product documentation issue on the following URL: https://www.pulumi.com/docs/reference/pkg/azure-native/containerservice/managedcluster/

**Comment by cnunciato** [comment]
@viveklak I just switched off several scripts (including the one you noted) that had been enabled but weren't being used, and @zchase is checking on one last one and will disable that one as well if we can. This appears to lighten the load somewhat in terms of network calls, but not dramatically so -- curious as to whether you see an improvement.

There are a few more things I can likely do here, but figured I'd get your feedback on this first bit.

**Comment by viveklak** [comment]
@cnunciato - sorry late to respond to this. It does seem to be a lot faster now.

**Comment by cnunciato** [comment]
Just a quick update: I'm starting to suspect the problem may actually be Sentry here. I was just able to reproduce a failure that triggered a bunch of Sentry rate-limiting errors and ultimately broke the page. May send up a PR that disables it for a while to gather some additional data.
