### ISSUE TITLE
More documentation for using Pulumi in CI

### ISSUE THREAD

**Issue by chrsmith** [pulumi/docs#598]
Add more docs for how to use Pulumi with CI systems, like Circle CI, Jenkins, Code Deploy, etc.

Bonus points for how the Pulumi GitHub app fits into them too. (i.e. what environment variables need to be set.)

**Comment by joeduffy** [comment]
In order:

- [ ] GitLab
- [ ] Jenkins
- [ ] Azure DevOps
- [ ] Circle CI

**Comment by joeduffy** [comment]
@praneetloke I think we made a good dent in this for M19. Moving out for now, feel free to opportunistically continue fleshing things out now and in M20, but great progress so far.

**Comment by praneetloke** [comment]
I just unchecked Jenkins from the above list. Not sure how it was checked-off, but I don't see a related doc for it on our site.

**Comment by chrsmith** [comment]
Added `P1` label since this is top of mind for the current milestone. @praneetloke , I'm happy to assist if you'd like some help.

**Comment by kostis-codefresh** [comment]
Hello. I work for Codefresh and I can easily prepare a CI/CD page on how Codefresh and Pulumi can work together. There is already an example on our docs https://codefresh.io/docs/docs/yaml-examples/examples/pulumi/

**Comment by praneetloke** [comment]
@kostis-codefresh that would be great! Please feel free to send us a PR.

**Comment by kostis-codefresh** [comment]
@praneetloke PR is here https://github.com/pulumi/docs/pull/1087 :-)

**Comment by chrsmith** [comment]
I believe we added some new docs here, but there's still more we can do. So keeping this open for the next milestone as well.

**Comment by chrsmith** [comment]
Moving over to @praneetloke for the current milestone. It looks like we have pretty solid coverage, and with our hooks / documentation for adding new CI/CD systems, I think we have all of our bases covered.

If we just added Jenkins this milestone I think we'd be in great shape. /cc https://github.com/pulumi/pulumi/issues/2106.

**Comment by joeduffy** [comment]
@praneetloke Do you have cycles to tackle Octopus and Spinnaker?

**Comment by praneetloke** [comment]
Moving to M28, but I have a doc for Octopus Deploy in-progress that I plan on completing today.

**Comment by stack72** [comment]
Closing this out - we can revisit this as more concrete items / use cases rather than a top level open goal
