### ISSUE TITLE
Auto-merge merges a PR without waiting for the build to complete

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/docs#5990]
`pulumi-bot` merges a PR in docs as soon as I approve it without waiting for the build to complete. Example: https://github.com/pulumi/docs/pull/5989

Two undesired effects:

- A potentially broken PR is merged
- Clean-up runs before the preview is ready, so the preview resources remain hanging

**Comment by susanev** [comment]
@mikhailshilkov is docs the right place for this issue? or should it be in home?

**Comment by mikhailshilkov** [comment]
I only saw it in docs but I'm not sure it doesn't happen elsewhere

**Comment by cnunciato** [comment]
I'll investigate whether this is still an issue.

**Comment by cnunciato** [comment]
Indeed, still an issue: https://github.com/pulumi/docs/pull/7438#issuecomment-1114319502

**Comment by thoward** [comment]
Closing this as fixed, because we changed how the system works and this is no longer an issue (per @sean1588).
