### ISSUE TITLE
Can't find docs for `aws.iam.assumeRolePolicyForPrincipal`

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/docs#5999]
### Problem description

We have a[ typescript method](https://github.com/pulumi/pulumi-aws/blob/303d169b68d5b2af9d245a18efda744365bf4ed4/sdk/nodejs/iam/documents.ts#L214) `aws.iam.assumeRolePolicyForPrincipal` but it's nowhere in our docs.

**Comment by t0yv0** [comment]
Input from @stack72 : the underlying issue here is this applies to mixing in awsx (TypeScript-only) that are currently not generating docs. These are not yet automated in the same way as regular resources.

**Comment by emiliza** [comment]
Closing issue - we're tracking the root of this in: https://github.com/pulumi/pulumi/issues/4785

**Comment by dirien** [comment]
Took me some time to find the source of this @pierskarsenbarg! I think in Golang it's not available?
