### ISSUE TITLE
Installation is too buried

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#601]
After the change to streamline the Getting Started workflow, we went from zero clicks to three clicks to find the installation instructions. This feels like a step backwards. Let's see if we can find a middle ground.

**Comment by lukehoban** [comment]
Related to this - I've noticed a couple other pieces of information related to installation are now harder (or impossible?) to find:
1. What is the version of the current release I will get if I follow the installation instructions (and generally - what is the current version).
2. The changelog with links to historical download version.
3. Details on manually installing from tarball.

**Comment by joeduffy** [comment]
For 2, it is under Reference at https://pulumi.io/reference/changelog.html. Perhaps too hard to find.

For 3, if you select "Manual Install" in the dropdown, you will see the manual install steps.
