### ISSUE TITLE
Create a Kubernetes StatefulSet tutorial

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#609]
Something along the lines of what's available here: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/. Probably https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/.

**Comment by lukehoban** [comment]
This is now covered in https://pulumi.io/quickstart/kubernetes/tutorial-wordpress-chart.html.

**Comment by elucidsoft** [comment]
That's a pretty poor excuse of a demonstration of how to setup a StatefulSet in Pulumi since that example is entirely based on Helm and literally shows no code.
