### ISSUE TITLE
git-lfs is still mentioned in .gitattributes

### ISSUE THREAD

**Issue by lindydonna** [pulumi/docs#62]
@ellismg and @chrsmith: the docs repo still has git LFS in [.gitattributes](https://github.com/pulumi/docs/blob/master/.gitattributes), which causes my Git clients to prompt to install LFS. Can we safely remove this?

**Comment by ellismg** [comment]
We removed it from .gitattributes in https://github.com/pulumi/docs/commit/2c008f984d02a98827f300dcf8b7d66f1d893214
