### ISSUE TITLE
PulumiTV video not allowed playback on site

### ISSUE THREAD

**Issue by spara** [pulumi/docs#6207]
<img width="1362" alt="Screen Shot 2021-07-07 at 3 13 06 PM" src="https://user-images.githubusercontent.com/638672/124822795-ff096a80-df35-11eb-81cb-2acbde178c0d.png">

**Comment by lukehoban** [comment]
Looks like this is on https://www.pulumi.com/cloudformation/.

**Comment by emiliza** [comment]
@leezen do you have ownership of the PulumiTV youtube account?

Whoever owns this just needs to go to the video details and "Allow Embedding" (supposedly)

**Comment by cnunciato** [comment]
Awesome, thanks @emiliza -- I was able to do that:

![image](https://user-images.githubusercontent.com/274700/125144244-1b420e80-e0d2-11eb-86b7-9de6027e2f93.png)

I see the video on the page now, so closing.
