### ISSUE TITLE
Add an example of using Pulumi with GitLab Pipelines

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#622]
We should add an example of how to configure and use Pulumi inside of a GitLab Pipeline, similar to how we have documentation for [GitHub Actions](https://pulumi.io/github). This is related to https://github.com/pulumi/docs/issues/598, but sufficiently distinct (and related to a customer ask), that I decided to file separately.

**Comment by praneetloke** [comment]
This was completed by #628.

**Comment by praneetloke** [comment]
I am closing this since there is now a doc on pulumi.io about how to use pulumi in a GitLab CI runner.

**Comment by joeduffy** [comment]
🎉
