### ISSUE TITLE
Remove approval step for automated PRs

### ISSUE THREAD

**Issue by emiliza** [pulumi/docs#6234]
As part of the pulumi/pulumi release we need to also manually approve the automated PRs here (eg: https://github.com/pulumi/docs/pull/6233) or the updates don't propagate to the CLI

Thoughts? @stack72

**Comment by stack72** [comment]
As all of the actual manual content has moved to pulumi-hugo, I agree with you on this and I've gone ahead and removed it

We can always add this back if we desire

P.
