### ISSUE TITLE
EKS SEO directs users to language specific pages

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/docs#6282]
### Problem description

Before we had multi language EKS, it was nodejs only. When I search for `pulumi eks` in Google, it takes me to this page: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/eks/

This only shows the nodejs docs, whereas the users should be landing here: https://www.pulumi.com/docs/reference/pkg/eks/cluster/

**Comment by cnunciato** [comment]
Most likely just need to remove this line: https://github.com/pulumi/docs/blob/586f635232b93678ffe9889fa51b7b7b824ced4b/infrastructure/cloudfrontLambdaAssociations.ts#L163

**Comment by susanev** [comment]
this appears to have been reopened by the pulumi-bot but then not closed. am closing, but pls reopen if there is more to do here.
