### ISSUE TITLE
Document CircleCI integration

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#631]
Similar to https://pulumi.io/reference/cd-travis.html and https://github.com/pulumi/docs/pull/628.

**Comment by joeduffy** [comment]
Note that this is already covered in https://github.com/pulumi/docs/issues/598. I'm fine breaking out into separate work items (preferred in fact so we can be more precise about ownership and timeline), 
 but we should probably do that for the full list (TeamCity, etc).

**Comment by chrsmith** [comment]
I'll take care of this one, since we'll want to cover our orbs.
