### ISSUE TITLE
Update Team Page

### ISSUE THREAD

**Issue by csnyde24** [pulumi/docs#6380]
Please remove Freddy Hernandez from the team page on the website. 

Please add Ian Wahbe to the page:

Title: Software Engineer
Headshot Image: https://media-exp1.licdn.com/dms/image/C5603AQGhvKd0zwyZWw/profile-displayphoto-shrink_800_800/0/1561455806402?e=1634774400&v=beta&t=76Tw472AN3_pmWiTjvfXFRgZrFt_syyhd25b3zNweL4
Linkedin: https://www.linkedin.com/in/iwahbe/
Twitter:@iwahbe

**Comment by iwahbe** [comment]
Fixed in https://github.com/pulumi/pulumi-hugo/pull/536
