### ISSUE TITLE
Webhooks page screenshot needs updating

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/docs#6522]
### Problem description

The screenshot on the [webhooks page](https://www.pulumi.com/docs/intro/console/webhooks/) shows an older version of the console 

![image.png](https://user-images.githubusercontent.com/109047/135165981-3a1d15c9-80f9-48a4-8c49-0858441f9483.png)

**Comment by susanev** [comment]
thix @pierskarsenbarg!

these kind of issues should be opened in pulumi-hugo
and also i already have this https://github.com/pulumi/pulumi-hugo/issues/347, would you mind adding a comment there instead?

ill try and do it this week

**Comment by pierskarsenbarg** [comment]
Got it. I'll add the comment now

**Comment by leezen** [comment]
Closing as a duplicate of pulumi/pulumi-hugo#347 per the earlier comment.
