### ISSUE TITLE
Add Google Verification code to `pulumi.com` domain as TXT record

### ISSUE THREAD

**Issue by zchase** [pulumi/docs#6523]
To connect our Google Search Console data with our Google Analytics data we need to add the Google Verification Code as TXT record to our `pulumi.com` domain.

[Google Documentation](https://support.google.com/webmasters/answer/9008080#domain_name_verification&zippy=%2Cdomain-name-provider)
[AWS Guide](https://freestonedigitalmedia.com/how-to-verify-google-search-console-on-aws-website)

**Comment by cnunciato** [comment]
I did something like this [a while back for an HR project ](https://github.com/pulumi/home/blob/master/infrastructure/people-ops/greenhouse.ts), if we wanted to write a program to do this, rather than manually.

**Comment by susanev** [comment]
@zchase @cnunciato is this something we still need to do?

**Comment by sean1588** [comment]
chatted with @zchase about this and this is something that we no longer need to do. going to close this out.
