### ISSUE TITLE
Merge rules for component resource empty

### ISSUE THREAD

**Issue by sam-cogan** [pulumi/docs#6558]
### Problem description

- I saw a product documentation issue on the following URL:  https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi/Pulumi.ComponentResourceOptions.html#Pulumi_ComponentResourceOptions_Merge_Pulumi_ComponentResourceOptions_Pulumi_ComponentResourceOptions_

- Other: <DETAILS>

### Suggestions for a fix

Looks like someone forgot to add content to the list of merge rules

**Comment by leezen** [comment]
Interestingly, the text _is_ there in the actual docstring (see https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/Pulumi/Resources/ComponentResourceOptions.cs/#L54) so there's either a problem in the markup or rendering of the markup.
