### ISSUE TITLE
(Auto)Convert the Examples repo to /examples pages

### ISSUE THREAD

**Issue by mehzer** [pulumi/docs#664]
Each page would be /example/<title> and contain:

* SEO friendly H1 and Opening Para
* Tagging/Sidebar representing Cloud/Language/Service as way of navigating lists/sets of examples
* Base the content on the README, a Diagram (where appropriate) and a walk of the files. 
* Links to the original GH example

Overall this would need a list page too

**Comment by lukehoban** [comment]
We did this in the /tutorials pages.
