### ISSUE TITLE
Language pivot on Getting Started

### ISSUE THREAD

**Issue by mehzer** [pulumi/docs#665]
We should have a Getting Started tutorial for Python (and Go), probably also specialize TS and JS (as TS is a great SEO opportunity).

Ideally, each cloud tutorial should be available in each language. (Perhaps through a smart language selector, multi language box).

**Comment by Lawouach** [comment]
Hi there,

I can't say how much I'd love that. I am struggling finding any good documentation on the Python support right now and it has killed the wow factor a bit :(

**Comment by joeduffy** [comment]
The new Getting Started flow has addressed this.
