### ISSUE TITLE
Move API Reference to top Nav

### ISSUE THREAD

**Issue by mehzer** [pulumi/docs#666]
API Reference is buried in Reference as 'Packages'. Should be a top level item, and called something more obvious (like API).

**Comment by clstokes** [comment]
@mehzer I think this is done now with Joe's recent changes.

![image](https://user-images.githubusercontent.com/293763/51768571-8aa81d00-2095-11e9-8897-fdf1554aa75d.png)

**Comment by joeduffy** [comment]
Ah, I totally missed this one; I agree, we can close out.
