### ISSUE TITLE
SEO Friendliness for Docs

### ISSUE THREAD

**Issue by mehzer** [pulumi/docs#668]
All Docs pages should have SEO friendly:
* URL structure
* H1 and H2
* Opening Para 
* Tagging (e.g. Cloud, Language, Service) (with links)

Additionally, all major concepts (/<language>, /<cloud>, /<service>) should have solid technical guidance landing page. 

- [x] Finish updating meta descriptions for blog posts

**Comment by lukehoban** [comment]
We've made progress.  We'll close out.
