### ISSUE TITLE
Add tests for redirect rules

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#6691]
We've moved a lot of content around over the years, and as such, we've begun to accumulate quite a few redirects and redirect rules. These rules come in various forms -- Hugo aliases, custom `redirect_to` frontmatter params,  Cloudfront/Lambda@Edge functions -- and we currently have no automated tests around any of them, which means you can't easily tell

* what a particular redirect rule is doing (e.g., a function with a regex that examines and/or alters only certain parts of a request URI)
* why the redirect rule was created
* whether changing it in a certain way is going to break something
* when it's okay to remove it

We should write some automated tests (and probably run them for pull-request and push jobs) that address all of these issues.

**Comment by thoward** [comment]
This is a great idea, but probably is not something we will prioritize soon. It has been in the backlog for 3 years. We will re-open if we decide to work on this.
