### ISSUE TITLE
Run code formatters against code examples

### ISSUE THREAD

**Issue by leezen** [pulumi/docs#6752]
We should run the relevant code formatter (prettier, autopep8, etc.) against code examples. Today, only  `gofmt` gets run as part of program codegen (https://github.com/pulumi/pulumi/blob/f21eda521f88860ed9b1891a361ec3ee29af035f/pkg/codegen/go/gen_program.go#L94)

**Comment by thoward** [comment]
Closing as fixed since we have implemented formatting during codegen for many (all?) of the languages we support.
