### ISSUE TITLE
Codegen for pluralized properties

### ISSUE THREAD

**Issue by leezen** [pulumi/docs#6855]
We appear to not have the correct codegen outcome for properties that are pluralized. TypeScript seems to be correct, but the other languages lop off the 's' (example being `excluded_rules` in the wafv2 ACL resource in `pulumi-aws`)

**Comment by pgavlin** [comment]
@leezen do you have a link to the bad codegen? I suspect that this is specific to `tf2pulumi`...

**Comment by leezen** [comment]
@pgavlin I don't -- I am mainly suspecting codegen given the fact that TS is correct while the remaining languages are incorrect.

**Comment by cnunciato** [comment]
Closing this as it's unclear what's to be done.
