### ISSUE TITLE
Link-check our READMEs also

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#6985]
We currently rely on people telling us when a link in a README stops working. We should run the link checker against our pulumi/* READMEs (maybe not all of them, but definitely some) so we can know about these sooner and fix them.

**Comment by cnunciato** [comment]
@leezen I've added this to the board I've started using for managing website-related engineering tasks, so you can remove it from the others if you like.

**Comment by susanev** [comment]
is it weird that we would be running this as part of docs? should it live in home instead?

**Comment by susanev** [comment]
or should the repos themselves handle this?

**Comment by cnunciato** [comment]
The link checking should probably live in one place, if only for overall ease of use and maintenance. Doesn't have to be the docs/website, though -- could be pulumi/home or somewhere else.

**Comment by thoward** [comment]
This is a great idea, but probably is not something we will prioritize soon. It has been in the backlog for 2.75 years. We will re-open if we decide to work on this.
