### ISSUE TITLE
Auto-update API documentation based on released versions

### ISSUE THREAD

**Issue by ellismg** [pulumi/docs#699]
Today, updating API documentation requires checking out each released version, generating API docs, and then pushing a pull request.

This entire process is tedious, error prone, and easy to forget to do.

We should make the following improvements:

- [ ] API documentation should be generated *per build* in *every repository*, so it can be published later. This will prevent someone from having to check out every repository at specific commits when we want to update documentation.
- [ ] When a new build is tagged with `latest` automation should update the documentation for the released packages to the latest version (ideally by directly submitting to master and then opening a PR to production
- [ ] The `latest-version` file should be updated in the same manner, as well as the table of released CLIs and the CLI documentation based on when a new version of the CLI is released.

There is probably more we can do, but this will be a substantial improvement over our current process.

**Comment by ellismg** [comment]
@lukehoban I think the above covers some the improvements we discussed two nights ago.  Please let me know if you think there is more low hanging fruit here.

**Comment by justinvp** [comment]
We now have automation in place that automatically opens a PR when new versions are released.
