### ISSUE TITLE
Scheduled jobs: Update Hugo modules is failing

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#7037]
https://github.com/pulumi/docs/runs/4910749034?check_suite_focus=true#step:8:37

**Comment by susanev** [comment]
@cnunciato do you know whats up with this?

**Comment by cnunciato** [comment]
From the log -- Yarn was temporarily unavailable: 

```
error An unexpected error occurred: "https://registry.yarnpkg.com/purgecss/-/purgecss-4.0.3.tgz: 
Request failed \"502 Bad Gateway\"".
```

Momentarily blip, happens sometimes. Looks like the next run passed and the site's currently deploying, so nothing to be done on our end.
