### ISSUE TITLE
Notify ourselves when build actions fail

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#7062]
We've had a couple of instances lately of failed docs builds that weren't known about until days later. We should probably add some messaging to notify ourselves (e.g., in the #builds channel) when a site build fails so we aren't relying on a human to notice something's gone wrong.

**Comment by susanev** [comment]
🙏 id prefer this get sent to #docs instead of #builds if possible, or to have a specific channel made for this if possible

**Comment by cnunciato** [comment]
We now have #website-notifications for this.

**Comment by susanev** [comment]
@sean1588 has fixed this, yay!
