### ISSUE TITLE
SQS triggered lambda

### ISSUE THREAD

**Issue by brunetto** [pulumi/docs#7069]
SDK language: Go
Provider: AWS

Hi, 
I can't find any doc about how to trigger a lambda function with a SQS queue.
Is there something to start from?

Thanks

**Comment by leezen** [comment]
At a high-level, you'll want to create a queue, function, and a mapping between the two. Please see https://www.pulumi.com/registry/packages/aws/api-docs/lambda/eventsourcemapping/#sqs for an example of creating that mapping and https://github.com/pulumi/examples/tree/master/aws-go-lambda for an example of setting up a Lambda function.

**Comment by leezen** [comment]
If you have additional questions/follow-up on getting this working, please open up a discussion topic in https://github.com/pulumi/pulumi/discussions

**Comment by brunetto** [comment]
Discussion started here https://github.com/pulumi/pulumi/discussions/8904
