### ISSUE TITLE
Add Go API documentation

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#722]

**Comment by swgillespie** [comment]
Go support is out of scope for M21.

**Comment by joeduffy** [comment]
For what it's worth, there are already Go docs published at e.g. https://godoc.org/github.com/pulumi/pulumi-aws/sdk/go/aws, since our repos are open source. We should just figure out where to add the appropriate links.

**Comment by leezen** [comment]
Closing as we have godoc and we have resource docs in Go on the site. Separately, we're tracking examples in Go via https://github.com/pulumi/pulumi/issues/4330, the first set of which came with https://github.com/pulumi/pulumi-terraform-bridge/issues/216
