### ISSUE TITLE
make build fails to build due to shortcode reference

### ISSUE THREAD

**Issue by tomweston** [pulumi/docs#7242]
### Problem description

`make build` fails to build due to shortcode reference

```
Error: Error building site: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/pulumi/pulumi-hugo/themes/default@v0.0.0-20220318004743-dbc39a077f17/content/blog/aws-eks-managed-nodes-fargate/index.md:36:1": failed to render shortcode "tweet": failed to process shortcode: template: _internal/shortcodes/tweet.html:6:82: executing "_internal/shortcodes/tweet.html" at <index .Params 0>: error calling index: value has type int; should be string
Total in 60070 ms
Makefile:44: recipe for target 'build' failed
make: *** [build] Error 255
```

### Affected product version(s)

master @ 09cef630a976fb68b838d7981620cc449056e816

**Comment by nimbinatus** [comment]
Hey @tomweston! Quick question: Which version of Hugo are you on? There was an update to the [Twitter API](https://github.com/gohugoio/hugo/pull/9106), and therefore an [update to the shortcode](https://github.com/gohugoio/hugo/releases/tag/v0.89.0), upstream. We adopted the update, which would leave the error message that you're finding there if you're on a Hugo version before 0.89.0. I bumped up to 0.92.0 and built cleanly.

**Comment by tomweston** [comment]
Thanks @nimbinatus I was using `hugo v0.86.0+extended linux/amd64` which was `>= 0.81` [as referenced in the README](https://github.com/pulumi/docs/blob/master/README.md?plain=1#L19). 

Updating Hugo to `0.92.0` fixed it. 

Ill raise a PR to change the [README ](https://github.com/pulumi/docs/blob/master/README.md?plain=1#L19)to the correct version

**Comment by nimbinatus** [comment]
Ah, thanks for catching that in the readme, and thanks for the PR!
