### ISSUE TITLE
Add a Cypress test for secondary button color on hover

### ISSUE THREAD

**Issue by kimberleyamackenzie** [pulumi/docs#7341]
See https://github.com/pulumi/pulumi-hugo/issues/1308 and specifically https://github.com/pulumi/pulumi-hugo/issues/1308#issuecomment-1092342561 for further details

**Comment by thoward** [comment]
This is a great idea, but probably is not something we will prioritize soon. It has been in the backlog for 2.5 years. We will re-open if we decide to work on this.
