### ISSUE TITLE
KTPW Lab2 doesn't document required config variables

### ISSUE THREAD

**Issue by lblackstone** [pulumi/docs#736]
Running `pulumi up` as specified in https://pulumi.io/quickstart/k8s-the-prod-way/infrastructure.html will result in errors if required config values are not set first. Document how to do this.

**Comment by hausdorff** [comment]
Hmm, this documentation actually _does_ tell you how to set the appropriate config values, @lblackstone? I'm not sure what's missing.

**Comment by lblackstone** [comment]
Yep, looks like it's there now. Not sure if it was added, or if I just missed it...
