### ISSUE TITLE
Document api.pulumi.com REST API

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#741]
The Pulumi service has a REST API served at http://api.pulumi.com which supports the `pulumi` CLI, webhooks registration, and other management scenarios.

We should begin to document and formalize this API for additional use cases and extensibility outside of the CLI.

This will also pave the way to supporting a Pulumi Service Pulumi Provider that could manage CRUD operations over Pulumi service resources including stacks, webhooks and more.

**Comment by imod** [comment]
@pierskarsenbarg posted this on Slack: 

> So we don't have any official documents on it but if you use chrome's dev tools in the console you'll see the calls to the API that your browser makes.
> There's also [this gist](https://gist.github.com/clstokes/9f7f64f59bea289ea92687b98748d5ae) which is fairly up to date.
> Please note that the API is subject to change (although the CLI also uses it so it's not going to change that often)

**Comment by lukehoban** [comment]
This is now available at https://www.pulumi.com/docs/reference/service-rest-api/.
