### ISSUE TITLE
Overhaul the ToC

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#744]
We'd like to overhaul the ToC for the website. This includes

- [x] Make the left hand nav collapsable
- [x] Add "mini ToCs" for complex pages
- [x] Rearrange the ToC
- [ ] Merge disparate sections and remove duplication (Tour/Reference)
- [ ] Turn the Quickstart into a more "hands on tutorial," with a Tour-like style

**Comment by clstokes** [comment]
Looks awesome! I noticed a small strange behavior. If you click the header of a sidebar menu item that's already open, the page kind of "jerks" a little bit and the menu doesn't collapse. Clicking the toggleButton icon works as expected.

<details>
  <summary>GIF</summary>

![screencast 2019-01-13 10-19-10](https://user-images.githubusercontent.com/293763/51089279-7cfea900-171f-11e9-88ac-6b91b48d3d07.gif)

</details>

**Comment by justinvp** [comment]
Should we close this in favor of https://github.com/pulumi/docs/issues/831?

**Comment by joeduffy** [comment]
Will look at this as we overhaul the current architecture next sprint.

**Comment by joeduffy** [comment]
https://github.com/pulumi/docs/issues/831
