### ISSUE TITLE
AWS YAML getting started seems broken

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#7508]
The AWS YAML getting started guide references `my-bucket`, yet `pulumi new aws-yaml` seems to give me a project with the bucket defined as `bucket` so subsequent steps in the getting started guide fail. That's odd because the template itself seems to [use `my-bucket`](https://github.com/pulumi/templates/blob/master/aws-yaml/Pulumi.yaml); there is, however, [this other `.append` template file along side it](https://github.com/pulumi/templates/blob/master/aws-yaml/Pulumi.yaml.append) which I don't understand but does still use the name `bucket`, so perhaps that's where this is stemming from?

I thought at first it was a caching issue, but my `~/.pulumi/templates/aws-yaml` contents match the template GitHub repo.

I haven't tried other clouds, but, assuming this is a real issue, it's worth an exhaustive double check.

**Comment by lukehoban** [comment]
Marking p1 since this is on the core getting started path.

**Comment by cnunciato** [comment]
>there is, however, [this other .append template file along side it](https://github.com/pulumi/templates/blob/master/aws-yaml/Pulumi.yaml.append) which I don't understand but does still use the name bucket, so perhaps that's where this is stemming from?

Yep, this is indeed what's going on -- the contents of the template file are being overwritten by the contents of the .append file, which is setting the name back to `bucket`. PR here to update the contents of the .append file as well: https://github.com/pulumi/templates/pull/284
