### ISSUE TITLE
language chooser is missing in this doc

### ISSUE THREAD

**Issue by Danielkiss9** [pulumi/docs#7511]
Hi,
Language chooser is missing from this doc page: 
https://www.pulumi.com/registry/packages/aws/api-docs/cloudwatch/eventtarget/

instead, all the languages are showing one after the other

**Comment by susanev** [comment]
hi @Danielkiss9 thank you for the report! we have a parent issue that's tracking this, ive added your report over there. will close this out as a duplicate.
