### ISSUE TITLE
make serve-static and make build dont work

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#7551]
make serve-static gives 404s
make build fails on the resourcedocsgen copying step

[internal slack convo](https://pulumi.slack.com/archives/C85BS3LJZ/p1653063721888749)

**Comment by cnunciato** [comment]
@susanev can you post some details on what happens with `make build`? [The README](https://github.com/pulumi/docs#makefile) does at least try to explain how this is supposed to work:

> `make build` generates the website and writes it to `./public`.
> `make serve` runs a local HTTP server that serves the contents of `./public`

.. so you'll definitely get a 404 if you haven't successfully run `make build` yet (as there's nothing there to be served).

**Comment by cnunciato** [comment]
Just used this, still seems to work, closing.

**Comment by susanev** [comment]
i could never build from the docs repo, might be worth having a new person try it fresh to see if they can get it to work
