### ISSUE TITLE
Reproducible build tooling

### ISSUE THREAD

**Issue by icepuma** [pulumi/docs#7610]
### Problem description

Hey folks,
I tried to build the docs on my local machine. I got all required tools installed, but it took more than 15 minutes to get all up and running. And especially with the different ecosystems (go, node, ...) installing is a bit tedious.

### Suggestions for a fix

The solution of this problem could be a Docker container containing all the necessary tools so that one can run `docker run ... make build` or something like this.

The build would be reproducible on all machines which support Docker. The container itself could then be the thing building the documentation in the CI.

Have a nice day!

**Comment by susanev** [comment]
hi @icepuma thx for opening the issue! i was curious, what are you working on contributing? want to make sure you are in the right place as most of our docs live over in https://github.com/pulumi/pulumi-hugo

**Comment by icepuma** [comment]
Hey,
someone on the `Rawkode Academy` - Discord posted the link to this repo. Out of curiosity I tried building the docs following the readme. Currently I have no real stake in the documentation but thought the tooling might be a bit better with that enhancement :)

**Comment by susanev** [comment]
appreciate you opening this up, but we wont be able to prioritize this anytime soon so im going to close this out. we do very much value community contributions to our docs so if i can help you get your environment setup in order to contribute pls reach out. thank you!!
