### ISSUE TITLE
TypeScript doc generator includes non-exported functions

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#772]
The EKS package includes a tightly controlled set of top-level exports https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/index.ts.

However, the docs generated for this include many non-exported functions - like `createStorageClass` which are imported from submodules but not re-exported as part of the top-level module.

I have noticed this in many other libraries - in particular `@pulumi/pulumi`.

**Comment by justinvp** [comment]
Note that, for the EKS package, `createStorageClass` _is_ actually exported from `index.ts`. `createCore` is an example of a function that shouldn't be included in the docs.

**Comment by justinvp** [comment]
https://github.com/TypeStrong/typedoc/issues/639

**Comment by ericrudder** [comment]
can we make our search page look more like this (columns) ... rather than
one "huge" column (try searching on index for fun)

**Comment by justinvp** [comment]
> can we make our search page look more like this (columns) ... rather than one "huge" column (try searching on index for fun)

@ericrudder, I'd very much like to improve the search results, particularly when searching for API symbols. @cnunciato is tracking some improvements at #1036 (last item).

**Comment by lukehoban** [comment]
We plan on replacing these docs with multi-language EKS provider resource docs, which will remove the need for this.  It's also not a particularly significant issue in the meantime, so happy to close this out for now.
