### ISSUE TITLE
Docs include inline HCL

### ISSUE THREAD

**Issue by pgavlin** [pulumi/docs#784]
See e.g. 
https://pulumi.io/reference/pkg/nodejs/@pulumi/aws/ec2/#PeeringConnectionOptions

These should be converted or omitted.

**Comment by joeduffy** [comment]
Ah, it doesn't look like this is a new issue. It seems these blocks appear in non-example sections, which we don't attempt to parse. Perhaps we should just try to parse _all_ code examples in the entirety of the text. E.g., https://www.terraform.io/docs/providers/aws/r/vpc_peering_options.html
