### ISSUE TITLE
Add introduction/description to main package pages

### ISSUE THREAD

**Issue by clstokes** [pulumi/docs#794]
We should add an introduction or description to our package pages - e.g. [@pulumi/aws](https://pulumi.io/reference/pkg/nodejs/@pulumi/aws/index.html), [@pulumi/eks](https://pulumi.io/reference/pkg/nodejs/@pulumi/eks/index.html), etc. We describe the packages at the bottom of https://pulumi.io/reference/pkg/, but this likely isn't found frequently.

**Comment by joeduffy** [comment]
I had actually tinkered a little with this. An issue I ran into is that JSDoc doesn't have the notion of a "module-level" description, as far as I can tell. It would be nice to be able to have these for all modules in addition to the package itself (e.g., the S3 module), although the package itself is a good start.

One idea is to have a private, unexported type in the package that we (ab)use for this. Another idea was to actually just use the `## Overview` section from our package `README.md`s, although that would help much for the modules (unless we actually add `README.md`s to those too).

**Comment by lukehoban** [comment]
> Another idea was to actually just use the ## Overview section from our package README.mds, although that would help much for the modules (unless we actually add README.mds to those too).

I think this is not a bad idea - it makes authoring much easier, and would double the benefit (we get nice GitHub content as well as docs).  @CyrusNajmabadi started doing this exact thing in https://github.com/pulumi/pulumi-aws-infra/blob/master/nodejs/aws-infra/ecs/README.md, which feels like a great model to follow.

**Comment by clstokes** [comment]
The `README.md -> ## Overview` idea is a great idea to make it easy to add docs where additional context is needed.

Could we make it work for all module depths - not just `nodejs/@pulumi/azure`, but also `nodejs/@pulumi/azure/search/` et al?

**Comment by joeduffy** [comment]
This capability has been added. Now we just need to do a pass over all the places we want to add READMEs -- both for packages themselves, and also for the sub-modules.

**Comment by justinvp** [comment]
@bermudezmt, as an example:

- https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/README.md is used at the top of https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/
- https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/acm/README.md is used at the top of https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/acm/
- etc.

**Comment by bermudezmt** [comment]
Based on the number of missing READMEs (both for packages and modules), I'm moving this to the next milestone. It looks like the READMEs have only been added to a few packages.

**Comment by joeduffy** [comment]
I just noticed an unintended consequence of this: all of the AWSX packages now have _gigantic_ READMEs at the top. For instance, https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/apigateway/#module-apigateway. Worse, these headers are largely duplicative with respect to other documentation, for example, https://www.pulumi.com/docs/reference/crosswalk/aws/api-gateway/.

I wonder if we should only be rendering the first section up to the initial H1 for the READMEs -- or simply crop the READMEs in the AWSX packages and link to the official documentation pages.

**Comment by justinvp** [comment]
Another consequence of this: https://github.com/pulumi/docs/issues/1519

**Comment by lukehoban** [comment]
Current plan is to do this for all package-level docs for now.  We should capture a list of all the packages we need to do this for (we could decide to only target Tier 1 packages for Pulumi/AWS/Azure/GCP/Kubernetes for now?).  And then we should create 1 or 2 "great" examples of this that we can use as a template for the rest.

**Comment by lukehoban** [comment]
I'm going to close this out - as we now do support this - and have a variety of issues tracking various follows up related to improving this.  Let's open specific issues on further follow ups.
