### ISSUE TITLE
`build-pulumi-cli-docs` GHA job not producing changes to the Node and Python SDK docs

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#8075]
The `build-pulumi-cli-docs` job ran successfully for the `3.40.2` release, but didn’t produce any changes to the Node or Python SDK docs. At the very least, I’d expect the Node SDK docs to change with references to the commit for `3.40.2`.

- https://github.com/pulumi/docs/actions/runs/3132374608/jobs/5084652963
- https://github.com/pulumi/docs/pull/8073

**Comment by cnunciato** [comment]
It looks like this is [running now](https://github.com/pulumi/docs/pull/9521) and has been for some time, so closing.
