### ISSUE TITLE
Document how to use links to Kubernetes resources

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#815]
In the Kubernetes setup/getting-started page we should add a note about using the links to Kube resources from the pulumi console - indicating;
1. They point to the Kubernetes Dashboard which you'll need to install for these links to work
2. That you'll need to run `kubectl proxy` to be able to proxy local access to the dashboard (which should be running inside the cluster not exposed directly to the internet)

**Comment by lblackstone** [comment]
Related: https://github.com/pulumi/pulumi-service/issues/3172
