### ISSUE TITLE
Automerge workflow doesn't always run

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#8207]
The [Automerge workflow](https://github.com/pulumi/docs/actions/workflows/automerge-workflow.yml) on this repo frequently fails to run, or runs, but doesn't actually do the merge. We should either fix this workflow or drop it and replace it with something more reliable.

**Comment by dixler** [comment]
left a temporary note on https://github.com/pulumi/home/wiki/Producing-the-Pulumi-CLI-and-SDKs

**Comment by zchase** [comment]
Should be fixed from bumping the retries: https://github.com/pulumi/docs/pull/8316

Will re-open if issue comes up again.
