### ISSUE TITLE
Bump version of AWSX classic docs to v0.40.1

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/docs#8216]
Currently docs for AWSX classic are on v0.32.0

Should be bumped to latest version (currently v0.40.1) 

PR for the last time this was done: #7077

**Comment by viveklak** [comment]
I can't seem to get the awsx 0.40.0 to build locally. I believe this should be a simple update PR to docs with `make generate`.

**Comment by susanev** [comment]
hi folks, i see @danielrbradley and @viveklak are assigned to this. can we drop the needs-triage tag?

**Comment by danielrbradley** [comment]
This has been updated for 1.0.0
