### ISSUE TITLE
hugo changes are not being pulled in any more

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#8220]

**Comment by nimbinatus** [comment]
Debugging log incoming here in a little bit; please hold.

**Comment by nimbinatus** [comment]
It appears that we've hit a size limit on the size of the pulumi-hugo build, as evidenced by the difference between the following logs:
- https://github.com/pulumi/docs/actions/runs/3421982071/jobs/5698824099#step:7:13 (build finished)
- https://github.com/pulumi/docs/actions/runs/3422407711/jobs/5699780011#step:7:13 (error appears)

We've narrowed it down to the appearance of multiple animated gifs in both blogs and the newest Pulumi Challenge.

Recommendations:
- @susanev opened the following PR to start addressing the problem: https://github.com/pulumi/pulumi-hugo/pull/2203
- We should consider converting all animations to SVG instead of GIF to save on space.
- We should consider what we might be able to remove from the site to make it more compact.

**Comment by susanev** [comment]
the problem with our gifs, is a lof of them use very large images so even if we convert them to svg they are still going to be large because the images get embedded into our svgs. we will more than likely want to consider some standards for gif and svg creation. or consider hosting of these things elsewhere.

**Comment by susanev** [comment]
some of these gifs should prolly be videos hosted on youtube to be honest.

**Comment by nimbinatus** [comment]
Are any of them terminal-based, @susanev? We could re-record those with asciinema, which can be hosted elsewhere. It might be worthwhile to consider a CDN that points to a separate storage system, to be honest, as the site gets bigger and needs to be more available (unless we're already doing that?).

**Comment by susanev** [comment]
reduces all the image sizes in @sean1588's list
https://github.com/pulumi/pulumi-hugo/pull/2204

**Comment by aureq** [comment]
So, as it turns out it should be straight forward to convert animated `.gif` into animated `.webp`.

Here is the command I used to
* convert to webp format
* reduced the image width to 900px

```bash
🌈✨ ❯ wget https://www.pulumi.com/blog/ill-just-update-my-bucket-object-what-could-go-wrong/atomic-deployment.gif
🌈✨ ❯ ffmpeg -i atomic-deployment.gif -vf "fps=10,scale=900:-1:flags=lanczos" -vcodec libwebp -lossless 0 -compression_level 6 -q:v 50 -loop 0 -preset picture -an -vsync 0 atomic-deployment.webp
🌈✨ ❯ ls -lh
total 50M
-rw-r--r-- 1 aureq users  45M Nov 10 08:47 atomic-deployment.gif
-rw-r--r-- 1 aureq users 4.7M Nov 10 17:09 atomic-deployment.webp
```
It took about 41 seconds to convert the 45M file.

@susanev I'll open a PR

**Comment by aureq** [comment]
Here is the script I created and used to convert the files in pulumi/pulumi-hugo#2211

```bash
#!/bin/bash

find ./default -type f -name "*.gif" -size +1M | while read SRC; do

    BASE_SRC="$(basename $SRC)"
    DST="$(echo $SRC | sed 's/\.gif/.webp/')"
    BASE_DST="$(basename $DST)"

    if [ ! -f "$DST" ]; then
        rm -f "$DST"
        ffmpeg -i "$SRC" -vf "fps=10,scale=min'(900,iw)':-2:flags=lanczos" -vcodec libwebp -lossless 0 -compression_level 6 -q:v 50 -loop 0 -final_delay 500 -preset picture -an -vsync drop "$DST" </dev/null >/dev/null 2>/dev/null
        if [ "$?" -ne 0 ]; then
            echo "ffmpeg failed. stopping at $SRC"
            exit 1
        fi
    else
        echo "$DST already exists. skipping."
    fi

    if [ -s "$SRC" -a -s "$DST" ]; then

        SRC_SIZE="$(ls -l "$SRC" | awk '{print $5}')"
        DST_SIZE="$(ls -l "$DST" | awk '{print $5}')"

        if [ "$SRC_SIZE" -gt "$DST_SIZE" ]; then
            # conversion and conversion were good enough so the new image
            # is smaller than the original. We can update our docs accordingly.

            # search for files that are referencing the original image
            # and replace all references.
            grep -rl "$BASE_SRC" ./default | while read DOC; do
                sed -i "s/$BASE_SRC/$BASE_DST/g" $DOC
                if [ "$?" -ne 0 ]; then
                    echo "failed to update $DOC"
                    exit 1
                else
                    git add "$DOC"
                fi
            done

            # remove original image file
            git rm "$SRC"
            git add "$DST"

        else
            # we keep the original file and just issue a notice.
            # we remove the new file since it's no use for us.
            rm -f "$DST"
            echo "$SRC cannot be optimized further"
        fi
    else
        echo "Can't find $SRC or $DST"
        echo "something went wrong"
        exit 1
    fi
done
```

**Comment by susanev** [comment]
considering this resolved, as @aureq reduced a large amount of the gif sizes. so we have a lot more room now.
