### ISSUE TITLE
Node.js docs have Python tab with "coming soon"

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#837]
When viewing the Node.js package docs, we have a tabs at the top for each language. If you choose Python, it says "Python API documentation is [coming soon](https://github.com/pulumi/docs/issues/630)." and the link is to a closed GitHub issue.

<img width="843" alt="screen shot 2019-02-01 at 11 29 43 am" src="https://user-images.githubusercontent.com/710598/52145022-be92bd80-2614-11e9-90b2-8a59d1ab6c03.png">

To start, we should fix the `pulumi`, `aws`, `azure`, and `gcp` Node.js packages to link to docs for the equivalent Python packages. For the other Node.js packages that don't (yet) have an equivalent Python package, should we just remove the Python tab?

Or alternatively, just delete the Python and Go tabs at the top of all the Node.js docs, as the tabs don't make sense with how we've _currently_ structured things as a separate set of API reference docs for Node.js and Python, instead of a unified view.

/cc @swgillespie

**Comment by justinvp** [comment]
Another option would be to leave the tabs as-is and just update all the Python tabs to link to https://pulumi.io/reference/pkg/python/index.html

**Comment by lukehoban** [comment]
> Another option would be to leave the tabs as-is and just update all the Python tabs to link to https://pulumi.io/reference/pkg/python/index.html

Yes - I think we should at least make that change so that at least the content is "correct".  I'd honestly just remove the tabs for now and add them back once we decide whether we're going to embed the multi-language docs under a single switcher like that.

**Comment by justinvp** [comment]
> I'd honestly just remove the tabs for now and add them back once we decide whether we're going to embed the multi-language docs under a single switcher like that.

Makes sense to me. Should we keep JS and TS tabs, or remove all 4?
