### ISSUE TITLE
Deprecated history command page shows up in docs search

### ISSUE THREAD

**Issue by mnlumi** [pulumi/docs#8441]
### Problem description

When using the search bar on the docs page, searching for 'history' will show an old result for the '[pulumi history](https://www.pulumi.com/docs/reference/cli/pulumi_history/)' command [which was moved ](https://github.com/pulumi/pulumi/pull/5158)to '[pulumi stack history](https://www.pulumi.com/docs/reference/cli/pulumi_stack_history/)' a while back.

![pulumi_history_search](https://user-images.githubusercontent.com/118926824/213015394-4e1b2b0b-078b-48e4-b7a0-c255c75fc483.png)

### Suggestions for a fix

Remove the old page or redirect to stack history command.

**Comment by susanev** [comment]
for seo reasons i believe we will want to redirect, so we maintain any seo weight we have built up on the pulumi history page
