### ISSUE TITLE
docs PRs being opened as `Regen docs pulumi@${PULUMI_VERSION}`

### ISSUE THREAD

**Issue by dixler** [pulumi/docs#8451]
### What happened?

Recently, regen docs dispatches are not correctly interpolating the `PULUMI_VERSION`
https://github.com/pulumi/docs/pulls?q=is%3Apr+is%3Aclosed+Regen+docs+pulumi+sort%3Acreated-desc+

Re-ran old CI jobs and they're also affected.
- https://github.com/pulumi/docs/actions/runs/3954185705
- https://github.com/pulumi/docs/actions/runs/3954184067

Probably some dependency being updated.

### Steps to reproduce

Cut a release.

### Expected Behavior

Opens docs PR like `Regen docs pulumi@3.52.0`

### Actual Behavior

Opens docs PR like `Regen docs pulumi@${PULUMI_VERSION}`.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@dixler, looks like this is still happening, e.g. https://github.com/pulumi/docs/pull/8455 which was opened after https://github.com/pulumi/docs/pull/8453

**Comment by dixler** [comment]
@justinvp I forgot to merge the PR before kicking of the release so it didn't use the new version.

**Comment by justinvp** [comment]
ahh, ok. sorry for the noise.
