### ISSUE TITLE
investigate transient test failures in docs build

### ISSUE THREAD

**Issue by sean1588** [pulumi/docs#8627]
We are continuing to get transient test failures when the cypress tests run as part of the docs build. We attempted to fix this by adding some retry logic to the tests, but it doesn't seem to be helping.  We should do a bit more investigation to see what is going on.

failed job:
https://github.com/pulumi/docs/actions/runs/4286641689/jobs/7466477522#step:9:1816

**Comment by cnunciato** [comment]
Actually, I'll close this as a wontfix for now, since we don't seem to have seen it for a while, and we now have automation in place to file new P1 on build failures.
