### ISSUE TITLE
docs build is broken on docker provider due to tfgen

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#8672]
more context in this [internal slack thread](https://pulumi.slack.com/archives/C04A7AKMGP4/p1678240052895449)

failure is here https://github.com/pulumi/docs/actions/runs/4360562491/jobs/7623592646
issue in tfgen is here: https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfgen/docs.go#L1093

**Comment by susanev** [comment]
my understanding on the path forward
- fix mistake in tfgen or adjust docker example to not hit the tfgen case
- release tfgen
- update docker
- release docker
- wait for registry release than docs release
- confirm

**Comment by AaronFriel** [comment]
Summary of resolution:

https://pulumi.slack.com/archives/C04A7AKMGP4/p1678265370577929?thread_ts=1678240052.895449&cid=C04A7AKMGP4

**Comment by jazzyfresh** [comment]
This issue has been resolved, docs are released
