### ISSUE TITLE
The pulumi stack tag ls and stack tag get commands don't seem to work

### ISSUE THREAD

**Issue by andrewlayman** [pulumi/docs#890]
The pulumi stack tag ls and stack tag get commands don't seem to work
```PS C:\users\Andrew\pulumi\webserver> pulumi stack init dev
Created stack 'dev'
PS C:\users\Andrew\pulumi\webserver> pulumi stack tag set fruit banana
PS C:\users\Andrew\pulumi\webserver> pulumi stack tag ls
NAME  VALUE
PS C:\users\Andrew\pulumi\webserver> pulumi stack tag get fruit
error: stack tag 'fruit' not found for stack 'dev```

**Comment by justinvp** [comment]
@andrewlayman, thanks for filing this!

I'm guessing you're using the [filesystem backend](https://pulumi.io/reference/state.html#to-the-filesystem-backend)? I realize it is not mentioned in the docs, but stack tags are currently only persisted when logged into the web backend. When using the filesystem backend (e.g. `pulumi login --local`), these commands are essentially no-ops.

Assigning to myself to update the docs to make this clear.

If you are using the web backend and still seeing this behavior, please let me know.

**Comment by joeduffy** [comment]
Shouldn't the local backend simply error out, i.e. `error: stack tags not supported in --local mode`?

**Comment by justinvp** [comment]
> Shouldn't the local backend simply error out, i.e. `error: stack tags not supported in --local mode`?

Yes, I agree, and was going to suggest doing that. This is a side-effect of punting on the programmatic access side of this feature area for now (until we sort out the larger story around config and some of the open issues we have there), and the local implementation got put on ice as part of that. Having the local backend return an error in the meantime would definitely be an improvement over silently doing nothing.
