### ISSUE TITLE
Add parent branding to practitioner navigation

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#8966]
## Overview

We're introducing sub-branding elements to the practitioner navigation (topmost black bar) in Docs & Registry. This parent "Documentation" branding will be a parent to all sub-categories of documentation in an effort to unify these experiences. 

## Figma preview

<img width="1712" alt="practitioner-nav-branding (2)" src="https://github.com/pulumi/docs/assets/97129308/cd1bda0d-ff7f-4f7c-a00a-ccf7b841cf6f">

### Style changes

- [ ] Add branding svg after the Pulumi logo

**Comment by susanev** [comment]
@anita-trimbur can you update this issue since this has changed a bit?

**Comment by susanev** [comment]
@anita-trimbur ive been putting this off because i still don't feel good about calling the parent `Documentation` since the label in the marketing nav and practitioner nav is `Docs`. i think we have two options..

1. go with `Docs` branding, even though its weird since part of docs is docs
2. do no branding at all

my preference is 1 because i really think it ties it together. but what do you think? and are there any additional options we should consider?

**Comment by anita-trimbur** [comment]
did we ever hear back from marketing if they had an opinion on the naming convention here? i do think docs in docs is strange, but i agree with you that have some label is going to make this structure feel a lot more straightforward. would we be adding this parent name to the breadcrumb? unless we went back to using the `<>` icon from the designs, that would give us a structure of `Docs / Docs / ...` if we can circumvent that, i support option 1.

**Comment by susanev** [comment]
@anita-trimbur this change wont affect any breadcrumbs, it will only b e adding the badge to the top bar; i think we should wait to add `<>` until the bigger decision is made. ill open a pr and me you and Sean can figure out if we want to do it from there.

i haven't heard anything from marketing. 🤷🏻

**Comment by thoward** [comment]
Our current site design seems to cover this intent though using a different look and feel. 

![Image](https://github.com/user-attachments/assets/473a0378-0147-48b0-984f-4d982d84c99f)


Regardless, I feel like we've moved far enough away from this design that closing this is appropriate.
