### ISSUE TITLE
Introduce documentation type tabular navigation

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#8969]
## Overview

We would like to introduce a new tabular navigation representing distinct types of documentation. For now, that includes our Docs and Registry properties. This change allows users to easily see where they are in our documentation ecosystem and what other types of documentation are available to them. We expect this structure to accommodate additional sub-types in the future (e.g. tutorials, examples, etc).

## Figma preview

<img width="1712" alt="docs-type-navigation" src="https://user-images.githubusercontent.com/97129308/234951958-485036a2-7a73-4b96-b6f1-2b7cd9020c00.png">

## Design features

- [ ] Appears directly underneath the practitioner navigation (topmost) bar
- [ ] Docs & Registry are accessible via tab - selecting a tab lands you in Docs or Registry home respectively
- [ ]  The appropriate tab appears selected on any child page in its type category (e.g. pulumi.com/registry/packages will show the "Registry" tab selected)
- [ ]  Tabs have unselected, hover, and selected states
- [ ] Search bar moves in line with the tab selection
- [ ] On screens under the 768 breakpoint, searc flexes above the bar

**Comment by susanev** [comment]
@anita-trimbur how do you feel about what shipped already? do you want any additional changes?

**Comment by anita-trimbur** [comment]
i think sean was able to address everything already! the only change that would have to happen is once the light practitioner nav is introduced i think this will need a top border. but we can probably close this out and make a note of that in the practitioner nav issue.

**Comment by susanev** [comment]
@anita-trimbur gonna close this, i added the border when we ship the practitioner nav
