### ISSUE TITLE
Make breadcrumbs consistent across Pulumi Developer + style changes

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#8978]
## Overview

We'd like to ensure that consistent breadcrumbs appear across the Pulumi Documentation context. We have also made style changes to ensure the breadcrumbs seat better in the page hierachy.

## Figma preview
<img width="1712" alt="breadcrumbs (1)" src="https://github.com/pulumi/docs/assets/97129308/d025a0f5-eb1b-4bb8-a85c-fed5398c3d3f">

### Style changes
- [ ] Font size decreased
- [ ] Font weight changes
- [ ] Text color changes

## Functionality changes
- [ ] Breadcrumbs appear in a consistent position on ALL Pulumi Documentation pages, including landing pages
- [ ] Wrap handling

**Comment by susanev** [comment]
@anita-trimbur can you update this issue with the changes?
