### ISSUE TITLE
Build Docs page layouts

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#8988]
## Overview
The new docs designs will standardize a page layout that can be used across our existing Docs & Registry pages. This issue also defines the behavior of those layouts at all our breakpoints. 

## Figma preview
<img width="1396" alt="Screen Shot 2023-04-28 at 11 46 31 AM" src="https://user-images.githubusercontent.com/97129308/235193891-fca7bbda-58be-4d3c-9471-4a9143f74ce2.png">

**Comment by susanev** [comment]
@anita-trimbur could i trouble you to update this issue since we arent calling it pulumi developer anymore?
