### ISSUE TITLE
consider a top-level documentation page

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#9010]
## Overview

We've had some ongoing discussion about creating a top-level landing page for our documentation in light of the new docs work. This would function similarly to Hashi's, "Developer" landing page, but purposed for multiple doc types rather than multiple products. We're not yet certain that the parent construct needs a landing page, or if we'd rather land folks in pulumi.com/docs as the common entry point. we'll want to keep an eye out for feedback relating to this as changes go into production.

**Comment by thoward** [comment]
This was implemented as part of https://github.com/pulumi/docs/pull/12693
