### ISSUE TITLE
Create single source of truth for page names & descriptions in Additional Resources sections

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#9022]
Currently we hard code "Additional Resources" sections. It makes it difficult when there are updates to headings or page content to manually maintain each instance. It would be really handy if there was a single source of truth that would propogate changes for every instance of a given page in this section.

![Screen Shot 2023-05-03 at 3 29 05 PM](https://user-images.githubusercontent.com/97129308/236035235-51402399-f0d2-4562-9585-4e816f74b82b.png)

**Comment by interurban** [comment]
Thanks Anita; we're going to close this issue. In the future there's plans to look at partials and shortcodes to make this more useable.
