### ISSUE TITLE
add left border to children's children in left nav 

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#9067]
small style follow-on from https://github.com/pulumi/pulumi-hugo/pull/2769.

child lists in the left nav have a left border to help visually group same-level pages. this style does not show for children's children, and we would like to apply that style consistently.

<img width="200" alt="Screen Shot 2023-05-15 at 1 38 57 PM" src="https://github.com/pulumi/pulumi-hugo/assets/97129308/1ba19212-8368-4d26-b486-23dcdd8d6837">

**Comment by susanev** [comment]
this is done
