### ISSUE TITLE
improve search ui

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#9069]
## Work items
This epic represents improvements to the search experience across docs & registry.

### References 📔

- [figma design reference](https://www.figma.com/file/CPxzPFMWrtbZOjZXy88418/pulumi-docs?type=design&node-id=1626%3A44663&t=rvSkh5lo657tSLre-1)

### Work Items ⚙️
- https://github.com/pulumi/docs/issues/9203

**Comment by cnunciato** [comment]
Completed with https://github.com/pulumi/pulumi-hugo/pull/2868. Will file any follow-ups as separate issues.
