### ISSUE TITLE
auto-generate the cli menu in docs

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#9107]
right now the cli menu in docs is controlled from this manually maintained file...
https://github.com/pulumi/docs/blob/master/config/_default/menus.yml

we instead want to do this over in
https://github.com/pulumi/pulumi/blob/master/pkg/cmd/pulumi/gen_markdown.go

so for every top-level command, directly under pulumi we would want to add this to its frontmatter

```
cli:
    weight: 2
    parent: commands
 ```

giving everything a weight of 2 will cause hugo to order them alphabetically

the pulumi command is a special case and we want it to h ave a weight of 1 so it always appears at the top

```
cli:
    weight: 1
    parent: commands
```

this should not be added for sub commands, e.g., https://www.pulumi.com/docs/cli/commands/pulumi_stack_select/

**Comment by interurban** [comment]
Thanks! This was fixed and we forgot to close down the issue.
