### ISSUE TITLE
restructure docs so that parent folders don't have associated pages

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#9174]
## overview

we would like to reconsider how we structure folders or groupings of docs. currently, every item in the docs nav - child or parent - has an associated page. some parent groups are forced to have pages that are not useful (e.g. just a list of child pages no different from the nav itself). example below:

<img width="700" alt="Screen Shot 2023-05-25 at 10 03 27 AM" src="https://github.com/pulumi/docs/assets/97129308/ce766bc4-44aa-4a7d-b233-f02c4e16aa37">

requiring these pages also makes it more difficult to interact with expanders in the left nav. users either must navigate to the parent page first, then a child inside, or be very precise in selecting the expander arrow beside the link text to see the child pages in the left nav.

we can alleviate these problems by using parent folders as logical groupings only without associated pages. any parent folders that do have important content should have that content moved to an "overview" type child page. [try out stripe's navigation](https://stripe.com/docs/payments) to see how this experience works in practice. you can easily click the arrow or the text of a nav item to explore without being bounced around to other pages. any info that would exist on the "parent page," exists in the topmost child "overview."

**Comment by thoward** [comment]
This is a good idea, however we are unlikely to implement this any time soon. For that reason, I'm closing this ticket for now. We can re-open if we decide to make additional investments into left nav usability.
