### ISSUE TITLE
create meta images for core docs pages

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#9197]
create meta images for core docs pages..

prolly start with...

- [x] docs landing
- [x] registry landing

and if time allows also create ones for...

- [ ] get started
- [ ] concepts
- [ ] adopting pulumi
- [ ] meta image template for language pages, like the cloud one
  - [ ] pulumi + typescript (node.js)
  - [ ] pulumi + python
  - [ ] pulumi + c# (.net)
  - [ ] pulumi + go
  - [ ] pulumi + java
  - [ ] pulumi + yaml

**Comment by thoward** [comment]
Closing as fixed since higher priority partial work was done and the remainder is not likely to get done.
