### ISSUE TITLE
Styling around certain docs pages makes sections hard to distinguish

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/docs#927]
This came up with a discussion with @lukehoban .  Many or our docs pages look like basically a long flat list which is hard to grok.  For example:

https://pulumi.io/reference/programming-model.html

If you go to the `Outputs` section: https://pulumi.io/reference/programming-model.html#outputs then you'll see it is composed out of 5 subsections: The main explanation, followed by `Apply`, `All`, `Convert Input to Output` and `Working with Outputs and strings`.

Problems here are:
1. It's really hard to tell that these subsections even belong to the general `Output` section.  It looks like these are all just top level concepts.
2. Even if you do get that these are subsections, it's really daunting.  You have a wall of text thrown at you.

@lukehoban and i discussed this and understood that this is basically a bikeshedding topic.  There are several things that could be tried out, but really, we'd need to see the results to get a good feel if it addresses the above.  Things that could help include, but are not necessarily limited to:

1. just changing the sizes of headings/subheadings
2. potentially indenting subsections.
3. including glyphs for top level headings.
4. including line-separators around large groups
5. underlining a heading.
6. making subsections easily collapsible (or starting them out collapsed).
7. breaking subsections into their own pages (though it feels like this has its own set of negatives).

Ideally, to me at least, someone coudl get to the `Outputs` section and read a quick blurb that helps give an intuition about them.  In fact, we already have a good blurb for `Outputs` in the opening paragraph.  At that point though, i think the rest of hte info should "get out of the way" until you need it.  So, for example, you could have this:

> Most of the time, when data needs to be passed from one Resource to another, it is sufficient to just pass the Output for that data 'as is'.  However, there may be cases where the data needs to be manipulated first.  There are many ways to go about doing this which you can read about below:

> <details><summary>Accessing simple properties of the Output</summary> yadda yadda</details>
> <details><summary>Combing data from multiple outputs</summary> yadda yadda</details>

That way things look less daunting, and you can expand and learn about this stuff at your own pace.

--

Note: as mentioned above, this is a bikeshedding topic.  Woudl love to work with someone html/css knowledgable to quickly knock out several options for us to compare/contrast.

**Comment by CyrusNajmabadi** [comment]
Tagging @justinvp for  ideas!

**Comment by cnunciato** [comment]
An "On This Page" menu could make this a lot better; it'd help with both orientation/wayfinding and for navigation, and would remain fixed on the desktop as you scroll -- e.g.: 

![](https://cl.ly/9fe89f235a4f/Screen%252520Recording%2525202019-07-15%252520at%25252002.00%252520PM.gif)

**Comment by bermudezmt** [comment]
This has been addressed via #1441 with the remaining follow-up work tracked at https://github.com/pulumi/docs/issues/1325.
