### ISSUE TITLE
hook up free-form docs responses to send to a slack channel

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#9311]
when folks vote on a docs page, they can also provide free-form comments.
if folks submit the free form comments we should make this more accessible to everyone at pulumi
lets hook them up to send to a slack channel, either #docs or a new channel

this could be potentially tie this in with https://github.com/pulumi/pulumi-hugo/issues/1213 when we do that work

**Comment by cnunciato** [comment]
Closing this for now as we've no plans to do this, but feel free to reopen if necessary.
