### ISSUE TITLE
NetworkArgs section get rendered in a weird way

### ISSUE THREAD

**Issue by d-nishi** [pulumi/docs#934]
Location: https://pulumi.io/reference/pkg/nodejs/@pulumi/awsx/index.html#NetworkArgs

This could be a problem when converting .md to https.

**Comment by justinvp** [comment]
I started investigating this and started implementing a fix before I went on my initial parental leave, but getting back to it now, it seems to have fixed itself. @d-nishi, please reopen if you're still seeing an issue.
