### ISSUE TITLE
Inconsistent Python version recommendation

### ISSUE THREAD

**Issue by aureq** [pulumi/docs#9435]
### Problem description

It appears Pulumi doesn't consistently recommend the same version of Python.

- The Pulumi Python SDK recommends Python 3.6 https://www.pulumi.com/docs/reference/pkg/python/pulumi/
- The Language and SDK page recommends Python 3.7 https://www.pulumi.com/docs/languages-sdks/python/

### Affected product version(s)

- docs

### Suggestions for a fix

1. It would be great to be consistent and show we support actively maintained Python versions
2. If we decide to support unmaintained Python version, we should state for how long we are planning to do so

For reference, Python 3.6 hasn't been maintained for 18 months. and Python 3.7 is just out of maintenance.

https://endoflife.date/python

**Comment by scottslowe** [comment]
https://github.com/pulumi/pulumi-hugo/pull/3249 removes the Python version reference from the Languages & SDKs page. All that is left is to remove the Python version from the Python SDK page. (Is that page auto-generated?)

**Comment by cnunciato** [comment]
@scottslowe Awesome thanks. These are generated, yeah, but this particular bit is almost surely hand-authored somewhere. I'm happy to take it from here to get the second part of this finished off.
