### ISSUE TITLE
Searchability Improvement: Delete a stack in Pulumi Cloud

### ISSUE THREAD

**Issue by toriancrane** [pulumi/docs#9512]
The documentation for [how to delete a stack in the Pulumi Cloud](https://www.pulumi.com/docs/pulumi-cloud/projects-and-stacks/#deleting-a-stack) is not easily searchable on the Pulumi docs website.

If I enter 'delete stack" into the search, the following results are shown:
![image](https://github.com/pulumi/docs/assets/19211559/2321f191-eedc-432e-a4d9-40d4b20940cb)

If I enter 'delete stack cloud', no results are shown.
![image](https://github.com/pulumi/docs/assets/19211559/66a105fb-1f18-4785-80d3-0bd6a8f402fb)

If I enter just 'delete', it is included in these results but much further down the list.
![image](https://github.com/pulumi/docs/assets/19211559/a2e49f10-e11e-4fec-940e-47591b6d4435)

If I enter "deleting a stack", it is the first option.
![image](https://github.com/pulumi/docs/assets/19211559/ed29d0d7-7636-4958-b080-48a989ad8c39)

**Comment by cnunciato** [comment]
Thank you for writing this up @toriancrane! This is great feedback.

**Comment by scottslowe** [comment]
@interurban Assigning to you, probably needs to go to the Docs board
