### ISSUE TITLE
link hover styles do not work in numbered lists

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#9529]
## overview
in-paragraph links use an animated hover style across docs & registry. these styles do not work for links that appear in numbered lists and instead default to an underline.

## screenshot
<img width="1006" alt="Screen Shot 2023-07-21 at 3 58 53 PM" src="https://github.com/pulumi/docs/assets/97129308/d214bd14-480a-490b-b194-091536fb5caa">

**Comment by thoward** [comment]
This has been fixed, as evidenced on this page: https://www.pulumi.com/docs/iac/adopting-pulumi/import/#two-ways-to-import-a-resource
