### ISSUE TITLE
breadcrumbs are rendered incorrectly on sdk docs pages

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#9536]
## overview
breadcrumbs are not rendered correctly on the sdk docs pages, presumably because of how we generate them.

<img width="1015" alt="Screen Shot 2023-07-21 at 1 17 50 PM" src="https://github.com/pulumi/docs/assets/97129308/6d18fabf-18af-400f-b11d-7719f001c0a9">

**Comment by thoward** [comment]
This seems to have been fixed at some point.
