### ISSUE TITLE
cli command docs skip h2s

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#9537]
## overview

cli command page headers go straight from h1s to h3s ([example](https://www.pulumi.com/docs/cli/commands/pulumi_config/)).  header tags should never be skipped - this is both a concern for seo and accessibility.

## screenshot
<img width="721" alt="Screen Shot 2023-07-21 at 4 50 05 PM" src="https://github.com/pulumi/docs/assets/97129308/e97a4afb-eeef-4201-816b-1e92ef0037c3">

**Comment by cnunciato** [comment]
For whoever takes this on, we generate these files [in the CLI Docs Build workflow](https://github.com/pulumi/docs/blob/a6bd2faf6de16d1812cf8276bc615cfbf90588b1/.github/workflows/pulumi-cli.yml#L88) of this repo (pulumi/docs) using the [gen-markdown subcommand](https://github.com/pulumi/pulumi/blob/master/pkg/cmd/pulumi/gen_markdown.go) of the Pulumi CLI.
