### ISSUE TITLE
Bad formatting of deprecation notices in resource docs

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#9541]
https://www.pulumi.com/registry/packages/azure/api-docs/containerservice/registrywebook/

![image](https://github.com/pulumi/docs/assets/274700/c41501e9-e441-45fd-ab38-cb59092fefa0)

Looks like this is malformed markup resulting from doc-gen templating:

![image](https://github.com/pulumi/docs/assets/274700/ab87fd5f-de6f-4132-abcf-14ff56208d0b)

**Comment by scottslowe** [comment]
@interurban Assigning to you, probably needs to go to the Docs board

**Comment by cnunciato** [comment]
Duplicate of https://github.com/pulumi/pulumi-hugo/issues/2832.
