### ISSUE TITLE
Better document the existence of `pulumi convert`

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#9563]
A Community Slack user asked:

>Hello - had a quick question. Has there been some prior work around converting an existing pulumi yaml to say, generate python code?

To find a good link, I went searching for "convert" in the docs, but all I was able to find were links to the command itself (which is only a reference) and the docs on converting third-party programs to Pulumi:

![image](https://github.com/pulumi/docs/assets/274700/b31da5db-f70b-400c-b7fc-0790ea470d02)

I actually don't think we have anything else in the docs right now that covers this feature; I believe the [Pulumi YAML blog post](https://www.pulumi.com/blog/pulumi-yaml-ga/) is the closest thing there is. We should add something that explains this excellent feature and how to use it.

**Comment by cnunciato** [comment]
Related: https://github.com/pulumi/pulumi/issues/12720

**Comment by jkodroff** [comment]
Related: https://github.com/pulumi/pulumi-hugo/issues/3888

**Comment by interurban** [comment]
Closing this, with the following fixes to to the converting page:
https://github.com/pulumi/pulumi-hugo/pull/3921
