### ISSUE TITLE
Use `pulumi new` consistently

### ISSUE THREAD

**Issue by ekrengel** [pulumi/docs#964]
Some docs suggest using `pulumi new` while others use `pulumi new typescript --dir gke-hello-world`. We want to scrub all docs to consistently use `pulumi new` to avoid confusion.

A proposed consistent approach by @lukehoban is:

```
$ mkdir gke-hello-world && cd gke-hello-world
$ pulumi new typescript
```

**Comment by justinvp** [comment]
Part of this will be scrubbing blog posts and examples in other repos.

**Comment by justinvp** [comment]
Updated all blog posts (except https://blog.pulumi.com/from-terraform-to-infrastructure-as-software, which would require a little more editing, and is fine as-is). Also did a search on GitHub and didn't find any other repos that needed updating.
