### ISSUE TITLE
Remove `$` from commands with no output

### ISSUE THREAD

**Issue by ekrengel** [pulumi/docs#965]
Some of the examples have $ at the beginning. These make it a bit harder to just copy & paste the snippet. Markdown linters suggest the `$` should only be present when the code snippet also includes output. We should update all docs to be consistent and only have `$` when output is included.

Nice to have: It would also be nice to have “Click to copy” buttons on example code.

**Comment by nesl247** [comment]
This seems like a duplicate of #1024
