### ISSUE TITLE
AWS Crosswalk Guides Page: Link to Getting Started Tutorial is Confusing

### ISSUE THREAD

**Issue by toriancrane** [pulumi/docs#9650]
### Problem description

On the Crosswalk for AWS Guides page, in the [Getting Started](https://www.pulumi.com/docs/clouds/aws/guides/#getting-started) section, the [try the Getting Started tutorial](https://www.pulumi.com/registry/packages/aws/how-to-guides/ecs-fargate/) part links to a How-To guide for ECS Fargate.

I was expecting to be sent to the equivalent of one of "Get Started" series (ex: [Get started with Pulumi & AWS](https://www.pulumi.com/docs/clouds/aws/get-started/)). I initially thought that I was redirected to an incorrect page altogether, but this How-To has a focus on deploying using Pulumi Crosswalk for AWS so I believe this was intentional.

### Suggestions for a fix
Reword the verbiage in this section to indicate that they can get started with AWSX by following the How-To.

**Comment by cnunciato** [comment]
This should probably just link directly to the actual [AWS getting-started guide](https://www.pulumi.com/docs/clouds/aws/get-started/).

**Comment by toriancrane** [comment]
> Yep, this should probably just link directly to the actual [AWS getting-started guide](https://www.pulumi.com/docs/clouds/aws/get-started/) as you suggest.

Well I think it is still important to have the link be specific to AWSX since it's not exactly the same as the AWS package. For example with AWSX the import statement is `import * as awsx from "@pulumi/awsx";` , and you would make calls using `awsx` and not `aws`.

I worry if linking to the AWS getting started guide would cause confusion?

**Comment by cnunciato** [comment]
Ah, yep, you're right -- I read this too quickly. Your suggestion to reword the text on the page definitely makes more sense. Sorry for the confusion!
