### ISSUE TITLE
Document GCP service account expected permissions

### ISSUE THREAD

**Issue by Lawouach** [pulumi/docs#967]
Hi all,

I was following the page to setup my GCP provider but realised it didn't make mention of the expected permissions/roles from the service account linked to those credentials.

https://pulumi.io/quickstart/gcp/setup.html

I'm reluctant to set something too-wide open. Could you please advice on what the required permissions?

Cheers,

**Comment by leezen** [comment]
This is entirely dependent on what GCP services you will use and consume from your Pulumi application, the same as configuring any other user or role to ensure that it can create/modify/delete the appropriate resources.
