### ISSUE TITLE
Update Terraform page - no longer open source 

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#9677]
This page incorrectly labels Terraform as open-source. We should revise and update any other relevant materials to make it clear that it is proprietary source-available software, including HCL. https://www.pulumi.com/docs/concepts/vs/terraform/

**Comment by interurban** [comment]
We've updated the page over the last couple of days, per https://github.com/pulumi/pulumi-hugo/pull/3286 forgot to tag this issue to auto close. thx Joe
