### ISSUE TITLE
Documentation for using the Python language is poor

### ISSUE THREAD

**Issue by Lawouach** [pulumi/docs#977]
Hey all,

I've been fighting with pulumi for the past few days because the docs are quite poor when it comes to the Python language. Things don't always translate straightforwardly from TS to Python and since examples are scarce with the Python language, it's really killing my effort right now. 

I can see the Python language is well supported so it's even more frustrating to fight simple things such as https://github.com/pulumi/pulumi/issues/2366

Any update on that front would go a long way :)

Thanks!

**Comment by Lawouach** [comment]
Let's note that that this one example doesn't lie in its name:

https://github.com/pulumi/pulumi-gcp/blob/master/examples/minimal-py/__main__.py

**Comment by Lawouach** [comment]
This one is more useful at least:
https://github.com/pulumi/examples/blob/master/gcp-py-gke/__main__.py

**Comment by lukehoban** [comment]
@Lawouach Anything in particular beyond pulumi/pulumi#2366 that you were looking for but couldn't find in Python?  If so - we would love to make sure we have issues tracking them.  Also - is there documentation you couldn't find related to Python - or was the issue examples/tutorials and some feature gaps?

**Comment by Lawouach** [comment]
Hi there,

Thank you for replying :)

I think, generally speaking, ensuring we have all the examples in all languages would help. While the API seems to be on par, it doesn't always work as-is.

For instance, in plenty of places, the docs says to call `pulumi.all` or pulumi.apply`  (same with interpolate or concat). But none of them exists on the Python `pulumi` module (like they seem to in TypeScript). Instead, you need to call the first two on `pulumi.Output`. As for interpolate and concat, I don't know where they are defined.

I'm actually very happy https://github.com/pulumi/examples/blob/master/gcp-py-gke/__main__.py was added because I couldn't make it work without it. At least, I wasn't too clear on what I was supposed to call. But it was added 4 days ago, after I started my quest :)

**Comment by Lawouach** [comment]
Linking to this one as well :) https://github.com/pulumi/docs/issues/968

**Comment by oliverxchen** [comment]
@lukehoban, I'll second @Lawouach's opinion: examples in all languages would be very helpful. 

The way, for example, GCP does their documentation for multiple languages is very convenient: https://cloud.google.com/bigquery/docs/reference/libraries.

You can choose the language and all the code blocks on the page will change. I'm not familiar with Jekyll and don't know if this can easily be implemented, but if you provided that functionality and even left the python code blocks as something like "coming soon" then I guess people would help you to fill them in (including me!).

**Comment by lukehoban** [comment]
@oliverxchen Absolutely - in many places we do already have language choosers to let you get JavaScript/Python/Go code (like https://pulumi.io/reference/programming-model.html).  For the API documentation, we do not yet have examples for Python, but this is in the works.

**Comment by lukehoban** [comment]
We made a lot of improvements to the availability of Python snippets in the programming model docs recently.

The examples in API docs is blocked on (and tracked by) https://github.com/pulumi/tf2pulumi/issues/98.

There are likely a handful of other places we include TypeScript snippets throughout the docs where we should include language choosers which we should fix up.

**Comment by ekrengel** [comment]
@lukehoban Should I close this issue? Or is there more you'd like to see here?

**Comment by lukehoban** [comment]
I'm going to close this out given all the progress recently.

I think the single biggest remaining thing is pulumi/tf2pulumi#98 which is required to have examples in API docs for Python.

If there are other specific things, let's open individual issues.
