### ISSUE TITLE
get-started video doesn't add value

### ISSUE THREAD

**Issue by desteves** [pulumi/docs#9844]
### Problem description

Under https://www.pulumi.com/docs/get-started/ the first link is “infrastructure as code” which contains a 7 minute video that doesn’t seem to add much to the text summary on the page. This seems to be adding more friction to getting started quickly. 

### Suggestions for a fix

Remove video

Thanks @aaijazi

**Comment by aaijazi** [comment]
btw I recently saw some other dev tool (can't remember which one), but the docs there explicitly called out that the video and text were just two different ways of getting the same information. It said something like "if you would prefer to have this information in video form instead, here a video that explains the same concepts". I really appreciated that, and I think that could be a good compromise to just removing the video.
