### ISSUE TITLE
get-started assumes brew is installed

### ISSUE THREAD

**Issue by desteves** [pulumi/docs#9845]
### Problem description

https://www.pulumi.com/docs/clouds/aws/get-started/begin/ assumes `brew` is installed by default. This is not reasonable to assume. 

### Suggestions for a fix

Include alternatives
Include steps or link for installing `brew`
Have the "More installation options" listed in the main page by default

All credits go to @aaijazi

**Comment by cnunciato** [comment]
@aaijazi We think most Mac users will either have Brew installed or know how to install it (and including instructions for installing Brew would be outside the scope of our docs), so we're closing this for now. But appreciate the feedback!

**Comment by cnunciato** [comment]
@aaijazi We think most Mac users will either have Brew installed or know how to install it (and including instructions for installing Brew would be outside the scope of our docs), so we're closing this for now. But appreciate the feedback!
