### ISSUE TITLE
Document dependsOn a Component resource

### ISSUE THREAD

**Issue by andrewlayman** [pulumi/docs#987]
Document dependsOn a Component resource.  (A new feature in 0.17.1). See [https://pulumi-community.slack.com/archives/C84L4E3N1/p1551945676230900](https://pulumi-community.slack.com/archives/C84L4E3N1/p1551945676230900).

**Comment by leezen** [comment]
Closing out stale issue. This is documented in https://www.pulumi.com/docs/intro/concepts/programming-model/
