### ISSUE TITLE
Investigate private CloudFront distribution for registry

### ISSUE THREAD

**Issue by sean1588** [pulumi/docs#9888]
Investigate if there is a way to have a private CloudFront distribution for the registry Cloudfront distribution (should we??) (i.e. make it only accessible from the cloudfront distribution managed in the docs repo).. This could possibly get us around the need to wrangle robots.txt files since it will not be publicly accessible.

**Comment by cnunciato** [comment]
We've decided this isn't worth taking on at this time, so closing.
