### ISSUE TITLE
User Guide: Testing Infrastructure

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#992]
There are multiple forms of testing you might want to do with Pulumi:

- I want to unit test code in my Pulumi app
- I want to test that my Pulumi app created resources as expected
- I want to test that Pulumi itself provisioned the resources correctly
- I want to test the runtime behavior of apps provisioned by my Pulumi app

We have answers for all of these, but we don't have a centralize, one stop shopping doc, about them.

Let's write one.

**Comment by joeduffy** [comment]
This went out as a blog: https://blog.pulumi.com/testing-your-infrastructure-as-code-with-pulumi. I do think we ought to create conceptual docs someday, so I'll keep this open as a reminder.

**Comment by joeduffy** [comment]
This is required for https://github.com/pulumi/pulumi/issues/3045.

**Comment by boillodmanuel** [comment]
Hello,

I read the blog post mentioned above https://blog.pulumi.com/testing-your-infrastructure-as-code-with-pulumi, but didn't find a way to test my use cases.

The tests described in the blog post are part of the pulumi lifecycle.

In my usecase, I want to test a cloud policy, so I would do something like that:

- setup test : 
  - create the cloud policy
- do tests :
  - scenario 1 : try to create an allowed resource and check that it's possible
  - scenario 2 : try to create a not allowed resource and check that it's not possible
- tear down test :
  - delete the cloud policy

Let me know if I created this issue in the right place :)
