### ISSUE TITLE
Appsync Schema and Resolver not documented

### ISSUE THREAD

**Issue by woeps** [pulumi/docs#993]
Appsync Schema and Resolver were added to pulumi-aws in v0.18.1, but it's not reflected in the [docs](https://pulumi.io/reference/pkg/nodejs/@pulumi/aws/appsync/). Although the comments in the code are pretty readable, it would be convinient, to be able to find the information on the pulumi docs website.

**Comment by jen20** [comment]
This was fixed by pulumi/docs#1047, which is deploying now. Thanks for the heads-up, @woeps!
