### ISSUE TITLE
AWSX API Gateway not showing up in docs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#996]

**Comment by joeduffy** [comment]
@CyrusNajmabadi any idea why these are missing altogether from https://pulumi.io/reference/pkg/nodejs/@pulumi/awsx/index.html?

**Comment by CyrusNajmabadi** [comment]
I do.  Not sure why these docs aren't there.  I honestly don't really know how our docs pipeline works.  Going to try to learn a bit about it.

**Comment by CyrusNajmabadi** [comment]
Looks like typedoc is failing on our code:

```
Using TypeScript 3.1.6 from /mnt/c/go/src/github.com/pulumi/docs/node_modules/typedoc/node_modules/typescript/lib
Error: /mnt/c/go/src/github.com/pulumi/pulumi-awsx/nodejs/awsx/apigateway/api.ts(617)
 Argument of type '{ [securityDefinitionName: string]: SecurityDefinition; } | undefined' is not assignable to parameter of type '{}'.
  Type 'undefined' is not assignable to type '{}'.
Error: /mnt/c/go/src/github.com/pulumi/pulumi-awsx/nodejs/awsx/apigateway/api.ts(630)
 Object is possibly 'undefined'.
```

Looking to try to upgrade the version we use so it can actually understand the modern TS code we use.
