### ISSUE TITLE
Getting started flow though docs should be clear and complete

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#997]
We have a core flow through the docs site currently:
1. Home page
2. Getting started
3. Install
4. Choose cloud
5. Tutorials for a cloud

Through these steps, we frequently miss key things - like the need to install node, the need to run `Pulumi new` to create a project/stack, etc. 

We also don’t carry users clearly through this flow, it is too easy to fall out of this flow or fall into it part way through without clarity on pre-requisites. 

We’ve had users send targeted PRs to fix some of these things, but we likely need a more robust review and improvements to every path through this flow to make sure it is clear and complete.

**Comment by lukehoban** [comment]
@justinvp Curious - is there anything here that is *not* planned to be addressed as part of https://github.com/pulumi/docs/issues/1033? Should we unify these two tracking issues into one to make sure we tackle all of these as part of the reworking of the getting started flow?

**Comment by justinvp** [comment]
Let's unify on #1033.
